== IPsec profile uses insecure authentication algorithms on Palo Alto Networks devices

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a9ed2462-ec77-43dd-88db-7e777729ea70

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/ansible/checks/graph_checks/PanosIPsecAuthenticationAlgorithms.yaml[CKV_PAN_12]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Ansible

|=== 

=== Description

This policy detects whether IPsec profiles in Palo Alto Networks devices use insecure authentication algorithms. Specifically, the policy checks that IPsec profiles do not use 'none', 'md5', or 'sha1' for ESP (Encapsulating Security Payload) authentication, as these algorithms are considered weak and vulnerable to attacks. Strong authentication algorithms are crucial for ensuring the confidentiality and integrity of IPsec VPN connections.


=== Fix - Buildtime

*Palo Alto Networks*

* *Resource:* panos_ipsec_profile
* *Attribute:* esp_authentication

To mitigate risks, configure your panos_ipsec_profile resources to use stronger algorithms like 'sha256' or 'sha512' to ensure robust authentication. Avoid using weak algorithms such as 'none', 'md5', or 'sha1' as the ESP authentication algorithm.


Secure Code Example:


[source,yaml]
----
- name: Example
  ...
  tasks:
    - name: ipsec
      paloaltonetworks.panos.panos_ipsec_profile:
        ...
-        esp_authentication: ['md5'] # Unacceptable authentication algorithm
+        esp_authentication: ['sha256'] # Acceptable
----

In this example, configuring `esp_authentication` with secure algorithms such as 'sha256' or 'sha512' enhances the security of IPsec VPN connections by using robust authentication methods.