== Supported Assets

The Prisma Cloud Data Security Posture Management (DSPM) solution, previously known as Dig Security platform, helps you discover, classify, protect, and govern your data across multi-cloud environments. With Prisma Cloud DSPM, you can reduce data misuse, achieve compliance, and prevent ransomware attacks and data breaches.

Prisma Cloud offers data classification for the following assets and services.

* *AWS*
** Storage: Simple Storage Service (S3), and Elastic File System (EFS)
** Databases: Aurora, RDS (MySQL, MariaDB, PostgreSQL), OpenSearch (Serverless), DynamoDB, and Unmanaged Database instances (database running on AWS EC2)
//deleted: DynamoDB Accelerator, Elasticache Cluster, Elasticache Replication Group, Elasticache for Memcache, MemoryDB for Redis
** Analytics: Redshift
//deleted: EMR and OpenSearch

* *Azure*
** Storage: Blob Storage and NetApp Files
** Databases: SQL Server, Azure SQL, CosmosDB (NoSQL and MongoDB), and Unmanaged SQL instances
//deleted: Cache for Redis, Database for MariaDB, Database for MySQL, Database for PostgreSQL, SQL Database, SQL Managed instances, Unmanaged Database instances
//deleted: ** Analytics: Synapse Analytics

* *GCP*
** Storage: Cloud Storage and Filestore
** Databases: Cloud BigTable, Cloud SQL (MySQL, PostgreSQL, SQL Server), and Unmanaged Database instances
//deleted: Cloud Spanner, Memorystore for Redis, Memorystore for Memcache
** Analytics: BigQuery

* *DBaaS*
** Snowflake

* *SaaS*
** Microsoft Office 365 (OneDrive and Sharepoint Sites)

* *Unmanaged Databases* (hosted on VMs)
** PostgreSQL
** MongoDB
** MySQL
** MariaDB
** MSSQL

Prisma Cloud DSPM metering depends on the type of data assets being secured:

* For IaaS and PaaS assets, DSPM requires 1 credit per data asset.
* For DBaaS assets, DSPM requires 1 credit per TB of data volume (i.e. size of the data asset).
* For SaaS assets, DSPM requires 0.1 credit per user in supported SaaS applications.

NOTE: While the above list refers to only data classification, Prisma Cloud discovers and monitors all cloud assets and services for usage and misconfigurations.


//* *SaaS*
//** Microsoft Office 365: OneDrive and Sharepoint Sites

//* *On-Premises*
//** Storage: NFS
//** Windows FileShare
//** NetApp FileShare
