== New Relic APM license key detected in code


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
|950ebe76-7e17-417b-8c38-d0960b3ff90b

|Checkov Check ID
|CKV_SECRET_240

|Severity
|MEDIUM

|Subtype
|build

|Frameworks
|Git

|===


=== Description

A New Relic APM license key is a sensitive credential that grants access to your New Relic account and data. If this key is exposed, unauthorized individuals could potentially access sensitive performance data, manipulate your monitoring settings, or even incur additional charges on your account. 

=== Fix - Buildtime

*New Relic*

To protect your New Relic APM license key, follow these steps:

1. Log in to your New Relic account with admin or owner permissions.
2. Navigate to Account Settings, API keys or License keys section of the UI.
3. Regenerate the License Key.
4. Replace the old license key in your application configurations with the new one to avoid any interruptions.

Ensure all your applications are using the new license key. If the old key is still in use, those applications will lose connectivity to New Relic's monitoring services.
