== Docker APT is used


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e2c80d46-7f1f-4ef8-af47-0a60a23a8624

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/dockerfile/checks/RunUsingAPT.py[CKV_DOCKER_9]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description

This policy detects whether the `apt`` (Advanced Package Tool) command is used within Dockerfile RUN instructions. Using `apt`` within Dockerfiles is generally discouraged due to potential instability and security vulnerabilities.



=== Fix - Buildtime

*Dockerfile*

To enhance security and reliability, replace `apt` with `apt-get` for package management within Dockerfiles. `apt-get` offers greater stability and control for package management, reducing potential errors and security risks.

In the example below, `apt`` is replaced with `apt-get` to ensures a more reliable and secure package installation process.

[source,dockerfile]
----
# Bad example
RUN apt update && apt install -y nginx

# Good example
RUN apt-get update && apt-get install -y nginx
----
