== Healthcheck instructions have not been added to container images


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2457c548-1ac6-4f6e-a6e5-d6a1ad318720

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/dockerfile/checks/HealthcheckExists.py[CKV_DOCKER_2]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


This policy ensures that HEALTHCHECK instructions have been added to Docker container images. Adding HEALTHCHECK instructions to your Dockerfiles helps to follow best practices for Docker container health management. These instructions provide a way to check the health of the running container, ensuring that issues are detected and handled promptly, thus improving the reliability and stability of your containerized applications.

=== Fix - Buildtime


*Docker* 

To mitigate this issue, add HEALTHCHECK instructions to your Dockerfile. Define a command that will be used to check the health of the container and specify the interval, timeout, and retries for how often the check should be performed.

Example:

[source,dockerfile]
----
+ HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD curl -f http://localhost/health || exit 1
----
