== Docker WORKDIR values are not absolute paths


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3b5a51c0-9b3d-4cc2-be84-18e6ac4aba1b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/dockerfile/checks/WorkdirIsAbsolute.py[CKV_DOCKER_10]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


This policy ensures that all WORKDIR values specified in Dockerfiles are absolute paths. For clarity and reliability, you should always use absolute paths for your WORKDIR instruction in Dockerfiles. Absolute paths prevent ambiguity and ensure the Docker instructions correctly navigate the intended directory structure. Using absolute paths makes Dockerfile more explicit and understandable, contributing to consistent and predictable behavior during image build and runtime.

=== Fix - Buildtime


*Docker* 

To mitigate this issue, ensure that all WORKDIR instructions in your Dockerfile use absolute paths instead of relative paths.

Example:

[source,dockerfile]
----
- WORKDIR relative/path
+ WORKDIR /absolute/path
----
