== Scan GitHub Configurations

Checkov supports the evaluation of policies on your GitHub organization and repositories settings. When using Checkov with GitHub token, it can collect your current organization settings and validate it complies with GitHub security best practices such as having 2FA defined, having SSO and more. 

The full list of GitHub organization and repository settings related checks can be found here.
//TODO add a ref link to GitHub policies

=== GitHub Scanning Configuration

[cols="1,1,2"]
|===
|Environment Variable |Default Value |Description

|*CKV_GITHUB_CONFIG_FETCH_DATA* |"True" |checkov will try to fetch GitHub configuration from API by default (unless no access token provided)

|*CKV_GITHUB_CONF_DIR_NAME* |"github_conf" |checkov will create a new directory named "github_conf" under current working directory

|*GITHUB_API_URL* |"https://api.github.com/" | 

|*GITHUB_TOKEN* | |GitHub personal access token to be used to fetch GitHub configuration

|*GITHUB_REF* |refs/heads/master |GitHub branch for which to fetch branch protection rules configuration

|*GITHUB_ORG* | |GitHub organization

|*GITHUB_REPOSITORY* | |GitHub repository for which to fetch repository configuration info

|*GITHUB_REPO_OWNER* | |The owner of the repository. This could be either GitHub repository owner username or the organization name, in which the user is the owner.
|===

=== Example Organization Security Configuration

[source,json]
----
{
    "data": {
        "organization": {
            "name": "Prisma",
            "login": "prismaio",
            "description": "Secure public cloud infrastructure",
            "ipAllowListEnabledSetting": "ENABLED",
            "ipAllowListForInstalledAppsEnabledSetting": "ENABLED",
            "requiresTwoFactorAuthentication": false,
            "samlIdentityProvider": {
                "ssoUrl": "https://prisma.okta.com/app/githubcloud/foo/sso/saml"
            }
        }
    }
}
----

=== Example Policy

[source,py]
----
from checkov.github.base_github_org_security import OrgSecurity


class Github2FA(OrgSecurity):
    def __init__(self):
        name = "Ensure GitHub organization security settings require 2FA"
        id = "CKV_GITHUB_1"
        super().__init__(
            name=name,
            id=id
        )

    def get_evaluated_keys(self):
        return ['data/organization/requiresTwoFactorAuthentication']



check = Github2FA()
----

=== Run in CLI

[source,bash]
----
#configure github personal access token
export GITHUB_TOKEN="ghp_abc"
#configure vpn (optional)
export REQUESTS_CA_BUNDLE="/usr/local/etc/openssl/cert.pem"
export BC_CA_BUNDLE="globalprotect_certifi.txt"

checkov -d . --framework github_configuration
----

=== Example Output

[source,yaml]
----
___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By Prisma Cloud | version: 2.0.707 

github_configuration scan results:

Passed checks: 2, Failed checks: 1, Skipped checks: 0

Check: CKV_GITHUB_3: "Ensure GitHub organization security settings has IP allow list enabled"
	PASSED for resource: _conf/org_security.json
	File: /github_conf/org_security.json:2-15

Check: CKV_GITHUB_2: "Ensure GitHub organization security settings require SSO"
	PASSED for resource: _conf/org_security.json
	File: /github_conf/org_security.json:2-15

Check: CKV_GITHUB_1: "Ensure GitHub organization security settings require 2FA"
	FAILED for resource: _conf/org_security.json
	File: /github_conf/org_security.json:2-15

		2  |     "data": {
		3  |         "organization": {
		4  |             "name": "Prisma",
		5  |             "login": "prismaio",
		6  |             "description": "Secure public cloud infrastructure",
		7  |             "ipAllowListEnabledSetting": "ENABLED",
		8  |             "ipAllowListForInstalledAppsEnabledSetting": "ENABLED",
		9  |             "requiresTwoFactorAuthentication": false,
		10 |             "samlIdentityProvider": {
		11 |                                 "ssoUrl": "https://prisma.okta.com/app/githubcloud/foo/sso/saml"
		12 |             }
		13 |         }
		14 |     }
		15 | }
----

