== Azure Data Explorer without SLA misconfiguration detected in code
// Ensure that data explorer uses Sku with an SLA

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_180
|Category |Storage - Backups
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Azure Data Explorer is a fast, fully managed data analytics service for real-time analysis on large volumes of data streaming from applications, websites, IoT devices, and more. Service Level Agreements (SLA) ensure that services are up and running. Using SKUs without an SLA may introduce risks in terms of availability.

This rule checks that the Azure Data Explorer cluster does not use a SKU which lacks an SLA.

=== How to Fix

*Terraform*

*Resource:* 
- azurerm_kusto_cluster

*Argument:* 
- sku/[0]/name

[source,terraform]
----
resource "azurerm_kusto_cluster" "example" {
  name                = "example-cluster"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  # ... other configurations ...

- sku {
-   name     = "Dev(No SLA)_Standard_D11_v2"  // Not recommended
-   capacity = 2
- }

+ sku {
+   name     = "Standard_D13_v2"  // Use a SKU with an SLA
+   capacity = 2
+ }

}

----

