== App Configuration Without Purge Protection Enabled misconfiguration detected in code
// Ensure App configuration purge protection is enabled.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_187
|Category - Subcategory |Storage - Backups
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Purge protection safeguards configuration stores from the irrecoverable, accidental purge of a deleted key. When enabled, a deleted key can't be permanently deleted until the protection is disabled. 

This rule ensures that Azure App Configuration has purge protection enabled to prevent accidental loss of important configuration keys.

=== How to Fix

*Terraform*

*Resource:* 
- azurerm_app_configuration

*Arguments:* 
- purge_protection_enabled

[source,terraform]
----
resource "azurerm_app_configuration" "example" {
  name                = "example-app-configuration"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  # ... other configurations ...

+ purge_protection_enabled = true  // Enable purge protection
}
----

