
== Standard Replication is not enabled

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_230
|Category |Storage - Replication
|Provider |Azure
|Severity |HIGH
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This policy checks if Standard Replication is enabled. Standard Replication refers to the mechanism of storing multiple copies of data across regions to ensure their durability and availability. If this is not enabled, it can potentially lead to data loss in case of regional failures, compromising important business information and processes. Therefore, enabling Standard Replication is important for robust data recovery and backup strategies.

=== How to Fix

*Terraform*

* *Resource:* azurerm_redis_cache
* *Arguments:* sku_name

To fix this issue, you need to set the `sku_name` attribute of the `azurerm_redis_cache` resource to `Standard` or `Premium`.

[source,hcl]
----
resource "azurerm_redis_cache" "example" {
  name                = "example"
  ...
  sku_name                 = "Standard"
}
----

