== AWS MSK cluster encryption in transit is not enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_81
|Category |Storage - Encryption
|Provider |AWS
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, CloudFormation
|Mapped CSPM/KSPM Rule |18d55f5a-c4de-4fc1-9346-c95b523f58d0
|===


=== Impact
This policy identifies AWS Managed Streaming for Apache Kafka clusters having in-transit encryption in a disabled state.

In-transit encryption secures data while it's being transferred between brokers. Without it, there's a risk of data interception during transit.

It is recommended to enable in-transit encryption among brokers within the cluster. This ensures that all data exchanged within the cluster is encrypted, effectively protecting it from potential eavesdropping and unauthorized access.


=== Fix - Buildtime


*Terraform* 


To fix this issue, ensure that the `encryption_info` property in the `aws_msk_cluster` resource includes `encryption_in_transit` settings with `client_broker` set to `TLS` and `in_cluster` set to `true`.


[source,go]
----
resource "aws_msk_cluster" "example" {
  cluster_name           = "example"
  ...
    + encryption_info {
  +    encryption_at_rest_kms_key_arn = aws_kms_key.kms.arn
  +   
    +    encryption_in_transit {
    +        client_broker = "TLS"
    +        in_cluster    = true 
  +     }
  + }
  ...
}
----

*CloudFormation*

To fix this issue, ensure that the `EncryptionInfo` property in the `AWS::MSK::Cluster` resource includes `EncryptionInTransit` settings with `ClientBroker` set to `TLS` and `InCluster` set to `true`.

Example:

[source,yaml]
----
Resources:
  MyMSKCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: example-cluster
      KafkaVersion: 2.8.0
      NumberOfBrokerNodes: 3
      BrokerNodeGroupInfo:
        ...
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: arn:aws:kms:us-west-2:123456789012:key/example-key-arn
        EncryptionInTransit:
          ClientBroker: TLS
          InCluster: true
      ...
----
