== Azure Key Vault Keys does not have expiration date

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_40
|Category |Storage - Alerting
|Provider |Azure
|Severity |HIGH
|Framework |ARM, Bicep, Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_40
|Category |Storage - Alerting
|Provider |Azure
|Severity |HIGH
|Framework |ARM, Bicep, Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
The Azure Key Vault enables users to store and use cryptographic keys within the Microsoft Azure environment.
The exp (expiration time) attribute identifies the expiration time on or after which the key *must not* be used for a cryptographic operation.
Keys are not set to expire by default.
We recommend you rotate keys in the key vault and set an explicit expiration time for all keys in the Azure Key Vault.
This ensures that the keys cannot be used beyond their assigned lifetimes.
=== How to Fix


*Terraform* 


* *Resource:* azurerm_key_vault_key
* *Arguments:* expiration_date


[source,go]
----
resource "azurerm_key_vault_key" "generated" {
    ...
+   expiration_date = "2020-12-30T20:00:00Z"
}
----
