== Dynamodb point in time recovery is not enabled for global tables


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_165
|Category |STORAGE - BACKUPS
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


Enabling point-in-time recovery (PITR) for Amazon DynamoDB global tables can help to protect against data loss due to accidental write or delete operations, or due to data corruption.
With PITR enabled, you can restore a global table to any point in time within the specified recovery window (typically up to 35 days).
This can be helpful if you need to undo unintended changes or recover from data corruption.

=== Fix - Buildtime


*CloudFormation* 


* *Resource:*  AWS::DynamoDB::GlobalTable
* *Arguments:* Properties.DistributionConfig.Logging/Bucket


[source,yaml]
----
Resources:
  MyCloudFrontDistribution:
    Type: AWS::DynamoDB::GlobalTable
    Properties: 
            ...
      Replicas: 
+       - PointInTimeRecoverySpecification: 
+           - PointInTimeRecoveryEnabled
----
