== MariaDB server does not enable geo-redundant backups
// MariaDB server geo-redundant backups not enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_129
|Category |Storage - Backups
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Ensure that your Microsoft Azure MariaDB database servers have geo-redundant backups enabled, to allow you to restore your MariaDB servers to a different Azure region in the event of a regional outage or a disaster.
Geo-restore is the default recovery option when your MariaDB database server is unavailable because of a large-scale incident, such as a natural disaster, occurs in the region where the database server is hosted.

.During geo-restore, the MariaDB server configuration can be changed.
These configuration changes include compute generation, vCore, backup retention period and backup redundancy options.
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_mariadb_server
* *Arguments:* geo_redundant_backup_enabled


[source,go]
----
resource "azurerm_mariadb_server" "example" {
            ...
+           geo_redundant_backup_enabled  = true
        }
----
