== Alibaba Cloud OSS bucket has versioning disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7e6a6a80-42b4-4609-b23c-101f0de481bc

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/OSSBucketVersioning.py[CKV_ALI_10]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that versioning is enabled for Alibaba Cloud OSS (Object Storage Service) buckets. Versioning helps protect against accidental deletion or overwriting of objects by maintaining multiple versions of an object. Enabling versioning is a best practice for data protection and recovery in case of user errors or malicious actions.

Failing to enable versioning could lead to irreversible data loss if objects are deleted or modified unintentionally.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_oss_bucket
* *Arguments:* versioning.status

To mitigate this issue, ensure the `versioning.status` attribute in the `alicloud_oss_bucket` resource is set to `Enabled`.

Example:

[source,go]
----
resource "alicloud_oss_bucket" "example" {
  ...

  versioning {
+    status = "Enabled"
  }
}
----
