== Azure Batch account does not use key vault to encrypt data


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_76
|Category |STORAGE-ENCRYPTION
|Provider |AZURE
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


Use customer-managed keys to manage the encryption at rest of your Batch account data.
By default, customer data is encrypted with service-managed keys, but customer-managed keys are commonly required to meet regulatory compliance standards.
Customer-managed keys enable the data to be encrypted with an Azure Key Vault key created and owned by you.
You have full control and responsibility for the key lifecycle, including rotation and management.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_batch_account
* *Arguments:* key_vault_reference


[source,go]
----
resource "azurerm_batch_account" "example" {
                            ...
+             key_vault_reference {
                id = "test"
                url = "https://test.com"
              }
            }
----
