== AWS EMR cluster is not configured with security configuration

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_AWS_55
|Category |Storage - Permissions
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |d1fae1fd-5d39-48c4-9583-e08b1d80244d
|===


=== Description

This policy detects if an AWS EMR cluster is not configured with a security configuration. The security configuration of an EMR cluster determines things like encryption settings and security group rules. If such a configuration is not set, the cluster may be vulnerable to attacks or data breaches. 

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_emr_cluster
* *Arguments:* security_configuration

To fix the issue, name a valid security configuration in the `security_configuration` argument of the `aws_emr_cluster` resource. 

Secure code example:

[source,go]
----
resource "aws_emr_cluster" "example" {
  ...
  security_configuration = aws_emr_security_configuration.example.name
  ...
}
----

The above code is secure because it names a valid security configuration for the AWS EMR cluster, reducing its vulnerability to attacks or data breaches.