== AWS ElastiCache Redis cluster with encryption for data at rest disabled misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_29
|Category |Storage - Encryption
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |f22216ac-8065-43fc-81d4-18ea427af666
|===
 



=== Impact
ElastiCache for Redis offers default encryption at rest as a service, as well as the ability to use your own symmetric customer-managed customer master keys in AWS Key Management Service (KMS).

ElastiCache for Redis at-rest encryption encrypts the following aspects:

* Disk during sync, backup and swap operations
* Backups stored in Amazon S3


=== How to Fix


*Terraform* 


* *Resource:* aws_elasticache_replication_group
* *Arguments:* at_rest_encryption_enabled - (Optional) Whether to enable encryption at rest.


[source,go]
----
resource "aws_elasticache_replication_group" "default"{
  ...
  replication_group_id          = "default-1"
+ at_rest_encryption_enabled    = true
  ...
}
----


*CloudFormation* 


* *Resource:* AWS::ElastiCache::ReplicationGroup
* *Arguments:* AtRestEncryptionEnabled


[source,yaml]
----
Resources:
    ReplicationGroup:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      ...
+     AtRestEncryptionEnabled: True
----
