== AWS Secrets Manager secret not encrypted by Customer Managed Key (CMK)


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8d4c6ccf-d558-49ff-ab7f-6db986b065f5

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py[CKV_AWS_149]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Impact
This policy ensures that AWS Secrets Manager secrets are encrypted using a customer-managed key (CMK) in AWS Key Management Service (KMS). Using a CMK provides additional control over the encryption keys used to protect your secrets, allowing you to manage key policies, rotation, and usage. This policy checks whether the `KmsKeyId` property is set to a value that does not contain the prefix `aws/` which indicates the use of the default AWS-managed key.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_secretsmanager_secret
* *Arguments:*  kms_key_id


[source,go]
----
resource "aws_secretsmanager_secret" "enabled" {
   ...
 + kms_key_id = var.kms_key_id
}
----


*CloudFormation*

To fix this issue, ensure that the `KmsKeyId` property in the `AWS::SecretsManager::Secret` resource is set to a customer-managed KMS key ARN or ID.

Example:

[source,yaml]
----
Resources:
  MySecretManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: example-secret
      KmsKeyId: arn:aws:kms:us-west-2:123456789012:key/example-key-arn
      ...
----
