== PostgreSQL server enables geo-redundant backups
// PostgreSQL server geo-redundant backup disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_102
|Category |Storage - Backups
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Azure PostgreSQL allows you to choose between locally redundant or geo-redundant backup storage in the General Purpose and Memory Optimized tiers.
When the backups are stored in geo-redundant backup storage, they are not only stored within the region in which your server is hosted, but are also replicated to a paired data center.
This provides better protection and ability to restore your server in a different region in the event of a disaster.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_postgresql_server
* *Arguments:* geo_redundant_backup_enabled - (Optional) Turn Geo-redundant server backups on/off.


[source,go]
----
{
 "resource "azurerm_postgresql_server" "example" {
  ...
+ geo_redundant_backup_enabled = true
}

",
}
----
