== AWS Elasticsearch domain Encryption for data at rest is disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0a54c279-d08a-4443-a93b-6d109addd964

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/ElasticsearchEncryption.py[CKV_AWS_5]

|Severity
|LOW

|Subtype
|Build, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Impact
This policy identifies Elasticsearch domains for which encryption is disabled. Encryption of data at rest is required to prevent unauthorized users from accessing the sensitive information available on your Elasticsearch domains components. This may include all data of file systems, primary and replica indices, log files, memory swap files and automated snapshots. The Elasticsearch uses AWS KMS service to store and manage the encryption keys. It is highly recommended to implement encryption at rest when you are working with production data that have sensitive information, to protect from unauthorized access.

=== Fix - Buildtime


*Terraform*

* *Resource:* aws_elasticsearch_domain
* *Arguments:* encrypt_at_rest

To fix this issue, you should ensure that your Elasticsearch domain configuration has the `encrypt_at_rest` property enabled. Below is an example of how to set this property in a Terraform configuration:

[source,go]
----
resource "aws_elasticsearch_domain" "example" {
  domain_name = "example"
  
  encrypt_at_rest {
    enabled = true
  }
}
----


*CloudFormation* 


* *Resource:* AWS::Elasticsearch::Domain 
* *Argument:* Properties.EncryptionAtRestOptions.Enabled

To mitigate this issue, ensure that the `EncryptAtRestOptions` property in the `AWS::Elasticsearch::Domain` resource is properly configured to enable encryption at rest.

Example:

[source,json]
----
{
  "Resources": {
    "ExampleElasticsearchDomain": {
      "Type": "AWS::Elasticsearch::Domain",
      "Properties": {
        "DomainName": "example",
        "EncryptAtRestOptions": {
          "Enabled": true
        }
        ...
      }
    }
  }
}
----

[source,yaml]
----
Resources:
  ExampleElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: example
      EncryptAtRestOptions:
        Enabled: true
      ...
----
