== Workspace root volumes are not encrypted


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_156
|Category |Storage - Encryption
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Encrypting your Workspace root volumes helps protect your data from unauthorized access or tampering.
That way, you can ensure that only authorized users can access and modify the contents of your volumes.
Such action can help protect against external threats such as hackers or malware, as well as internal threats such as accidental or unauthorized access.

=== How to Fix


*Terraform* 


* *Resource:* aws_workspaces_workspace
* *Arguments:*  root_volume_encryption_enabled


[source,go]
----
resource "aws_workspaces_workspace" "pass" {
    ...
+ root_volume_encryption_enabled = true
    ...
}
----


*CloudFormation* 


* *Resource:* AWS::WorkSpaces::Workspace
* *Arguments:*  Properties.RootVolumeEncryptionEnabled


[source,yaml]
----
Type: AWS::WorkSpaces::Workspace
    ...
  Properties: 
    ...
+   RootVolumeEncryptionEnabled: true
----
