== Azure AKS cluster is not configured with disk encryption set
// Azure Kubernetes Service (AKS) does not use disk encryption set


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_117
|Category |Storage - Encryption
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |4b83a6a2-c481-4e62-bc78-b45aa8712816
|===


=== Impact
Disk encryption is a security measure that encrypts the data on a disk to protect it from unauthorized access or tampering.
When disk encryption is enabled for AKS, it encrypts the data on the disks that are used by the nodes in your cluster.
This can help to protect your data from being accessed or modified by unauthorized users, even if the disks are physically stolen or the data is accessed from an unauthorized location.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_kubernetes_cluster
* *Arguments:* disk_encryption_set_id


[source,go]
----
resource "azurerm_kubernetes_cluster" "example" {
              ...
 +            disk_encryption_set_id = "someId"
            }
----
