== Azure Key Vault secrets does not have expiration date misconfiguration detected in code
// Azure Key Vault secrets do not have expiration dates


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_41
|Category |Storage - Alerting
|Provider |Azure
|Severity |HIGH
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_41
|Category |Storage - Alerting
|Provider |Azure
|Severity |HIGH
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
The Azure Key Vault (AKV) enables users to store and keep secrets within the Microsoft Azure environment.
Secrets in the AKV are octet sequences with a maximum size of 25k bytes each.
The exp (expiration time) attribute identifies the expiration time on or after which the secret must not be used.
By default, secrets do not expire.
We recommend you rotate secrets in the key vault and set an explicit expiration time for all secrets.
This ensures that the secrets cannot be used beyond their assigned lifetimes.
*Terraform* 


* *Resource:* azurerm_key_vault_secret
* *Arguments:* expiration_date


[source,go]
----
resource "azurerm_key_vault_secret" "example" {
     ...
 +   expiration_date = "2020-12-30T20:00:00Z"
}
----

