== OCI Block Storage Block Volumes are not encrypted with a Customer Managed Key (CMK)


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_OCI_3
|Category |STORAGE-ENCRYPTION
|Provider |ORACLE
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


This policy identifies the OCI Block Storage Volumes that are not encrypted with a Customer Managed Key (CMK).
It is recommended that Block Storage Volumes should be encrypted with a Customer Managed Key (CMK), using  Customer Managed Key (CMK), provides an additional level of security on your data by allowing you to manage your own encryption key lifecycle management for the Block Storage Volume.

////
=== Fix - Runtime


* OCI Console* 



. Login to the OCI Console

. Type the resource reported in the alert into the Search box at the top of the Console.

. Click the resource reported in the alert from the Resources submenu

. Click Assign next to Encryption Key: Oracle managed key.

. Select a Vault from the appropriate compartment

. Select a Master Encryption Key

. Click Assign
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* oci_core_volum
* *Arguments:* kms_key_id


[source,go]
----
resource "oci_core_volume" "pass" {
  ...
+  kms_key_id           = oci_kms_key.test_key.id
  ...
}
----

