== AWS S3 Object Versioning is disabled


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_21
|Category |STORAGE-VERSIONING
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |8ec3f878-0f5e-4782-b4cd-98018b217be5
|===


=== Description 


This policy identifies the S3 buckets which have Object Versioning disabled. S3 Object Versioning is an important capability in protecting your data within a bucket. Once you enable Object Versioning, you cannot remove it; you can suspend Object Versioning at any time on a bucket if you do not wish for it to persist. It is recommended to enable Object Versioning on S3.

=== Fix - Buildtime


*Terraform* 


To fix this issue, ensure that `aws_s3_bucket` resources either has `versioning.enabled` set to `true` or is connected to an `aws_s3_bucket_versioning` block with `versioning_configuration.status` set to `Enabled`.

[source,go]
----
+ resource "aws_s3_bucket_versioning" "example" {
+   bucket = aws_s3_bucket.example.id
+ 
+   versioning_configuration {
+     status = "Enabled"
+   }
+ }
----


*CloudFormation*

To fix this issue, ensure that the `VersioningConfiguration` property in the `AWS::S3::Bucket` resource is configured with `Status` set to `Enabled`.

Example:

[source,yaml]
----
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: example-bucket
      VersioningConfiguration:
        Status: Enabled
      ...
----
