== Geo-Replicated Not Enabled for Azure Container Registry (ACR) misconfiguration detected in code
// Ensure geo-replicated container registries to match multi-region container deployments.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_165
|Category |Storage - Replication
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Geo-replication is an important feature for container registries that operate in a multi-region context. It allows for container images and artifacts to be available closer to where they are run, reducing latency and increasing reliability.

This rule ensures that if you're using a Premium SKU for your Azure Container Registry, geo-replication is enabled.

=== How to Fix

*Terraform*

* *Resource:* azurerm_container_registry
* *Arguments:* sku, georeplications

[source,terraform]
----
resource "azurerm_container_registry" "example" {
  name                     = "exampleContainerRegistry"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
+ sku                      = "Premium"
  admin_enabled            = false
  
+ georeplications {
+    location                = "East US"
+    zone_redundancy_enabled = true
+    tags                    = {}
+ }
}
----