== AWS S3 Bucket has an ACL defined which allows public WRITE access misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_57
|Category |Storage - Permissions
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_57
|Category |Storage - Permissions
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Unprotected S3 buckets are one of the major causes of data theft and intrusions.
An S3 bucket that allows *WRITE* access to everyone allows attackers to create, overwrite and delete objects within the bucket, which can lead to: S3 data loss, unintended changes to applications using that bucket, and unexpected charges.
The only S3 buckets that should be globally accessible for unauthenticated users or for *Any AWS Authenticate Users* are those used for hosting static websites.
Bucket ACL helps manage access to S3 bucket data.
We recommend AWS S3 buckets are not publicly accessible for *WRITE* actions to protect S3 data from unauthorized users and exposing sensitive data to public access.

=== How to Fix


*CloudFormation* 


* *Resource:* AWS::S3::Bucket
* *Arguments:* Properties.AccessControl


[source,yaml]
----
Type: AWS::S3::Bucket
    Properties:
        ...
-     AccessControl: PublicReadWrite
----

*Terraform* 


* *Resource:* aws_s3_bucket, aws_s3_bucket_acl
* *Arguments:* acl


[source,go]
----
resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.example.id
-  acl    = "public-read-write"
+  acl    = "private"
}
----
