== AWS ElastiCache Redis cluster is not configured with automatic backup misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_134
|Category |Storage - Backups
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |50fcfd4b-25fd-47e8-8ffa-917be4f8cfa3
|===


=== Impact
Amazon ElastiCache clusters running Redis can back up their data.
Using automated backup, you can restore a cluster or seed a new cluster.
The backup consists of the cluster's metadata, along with all of the data in the cluster.
You can enable or disable automatic backups on an existing Redis cluster or replication group by modifying it using the ElastiCache console, the AWS CLI, or the ElastiCache API.
For any Redis cluster, you can enable automatic backups.
When automatic backups are enabled, ElastiCache creates a backup of the cluster on a daily basis.
There is no impact on the cluster and the change is immediate.

=== How to Fix


*Terraform* 


* *Resource:* aws_elasticache_cluster
* *Arguments:* snapshot_retention_limit


[source,go]
----
resource "aws_elasticache_cluster" "example" {
  ...
+ snapshot_retention_limit = 5
}
----
