[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates to Secure the Infrastructure

Review any changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 24.5.2 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and it is not a cumulative list of all announcements.

[NOTE]
====
The details and functionality listed below are a preview and the actual release date is subject to change.
====

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|*Feature*
|*Description*

|*Alert Info API*
//RLP-134888

|The Alert Info https://pan.dev/prisma-cloud/api/cspm/get-alert/[GET alert/:id] response will include a new field `connectionDetails` in release 24.5.2.

|*API Rate Limits*
//RLP-129569, RLP-139236

|Prisma Cloud uses API https://pan.dev/prisma-cloud/api/cspm/rate-limits/[rate limits] at the endpoint level to protect the performance and availability of its services. Rate limits will be applied to additional APIs starting from the 24.6.1 release. Details of these rate limits will be made available in the supporting API documentation and Look Ahead Notices when these limits are introduced. 

---

*Resource Lists*

[cols="3,1,1"]
!===
! Endpoint ! Rate Limit ! Burst Rate

! Get Resource Lists -  https://pan.dev/prisma-cloud/api/cspm/get-all-resource-list-for-customer/[GET /v1/resource_list] !80 !80
! Get Resource List by ID - https://pan.dev/prisma-cloud/api/cspm/get-resource-list-by-id/[GET /v1/resource_list/#id] ! 4 ! 4
! Get Resource List Types - https://pan.dev/prisma-cloud/api/cspm/get-resource-list-types/[GET /v1/resource_list/types] !4 !  4
! Get Resource List Names -  GET /v1/resource_list/names ! 80 ! 80

!===

*Account Groups*
[cols="3,1,1"]
!===
! Endpoint ! Rate Limit ! Burst Rate

! List Account Groups - https://pan.dev/prisma-cloud/api/cspm/get-account-groups/[GET /cloud/group] ! 32 ! 32
! Account Group Info -  https://pan.dev/prisma-cloud/api/cspm/get-account-group/[GET /cloud/group/#id] ! 80 ! 80
! List Account Group Names - https://pan.dev/prisma-cloud/api/cspm/get-account-group-name/[GET /cloud/group/name] ! 32 ! 32
! List Account Group Names by Cloud Type - https://pan.dev/prisma-cloud/api/cspm/get-account-group-name-by-cloud-type/[GET cloud/group/name/#cloud_type] ! 4 ! 4

!===

*Collections*

[cols="3,1,1"]
!===

! Endpoint ! Rate Limit ! Burst Rate
! Get All Collections - https://pan.dev/prisma-cloud/api/cspm/get-all-collections/[GET /entitlement/api/v1/collection] ! 4 ! 4
! Get Collection by ID - https://pan.dev/prisma-cloud/api/cspm/get-collection-by-id/[GET /entitlement/api/v1/collection/#id] ! 8 ! 8

!===


|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-24.5.2.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.

[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

|*Azure Virtual Network subnet is not configured with a Network Security Group*
//RLP-137711

|*Changes*— The policy description and RQL will be updated.

*Severity*— Low

*Policy Type*— Config

*Current Description—* This policy identifies Azure Virtual Network (VNet) subnets that are not associated with a Network Security Group (NSG). While binding an NSG to a network interface of a Virtual Machine (VM) enables fine-grained control to the VM, associating a NSG to a subnet enables better control over network traffic to all resources within a subnet. As a best practice, associate an NSG with a subnet so that you can protect your VMs on a subnet-level.

For more information,
https://learn.microsoft.com/en-gb/archive/blogs/igorpag/azure-network-security-groups-nsg-best-practices-and-lessons-learned[Azure Network Security Groups (NSG) - Best Practices and Lessons Learned] 
https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview#limitations[What is a private endpoint? - Azure Private Link] 

Note: This policy will not report for subnets used by Azure Firewall, Gateway, NetApp File Share, RouteServerSubnet, Private endpoints and Private links as Azure recommends not to configure Network Security Group (NSG) for these services.

*Updated Description—* This policy identifies Azure Virtual Network (VNet) subnets that are not associated with a Network Security Group (NSG). 

While binding an NSG to a network interface of a Virtual Machine (VM) enables fine-grained control of the VM, associating an NSG to a subnet enables better control over network traffic to all resources within a subnet. 

It is recommended to associate an NSG with a subnet so that you can protect your VMs on a subnet-level.

For more information,
https://learn.microsoft.com/en-gb/archive/blogs/igorpag/azure-network-security-groups-nsg-best-practices-and-lessons-learned[Azure Network Security Groups (NSG) - Best Practices and Lessons Learned] 
https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview#limitations[What is a private endpoint? - Azure Private Link] 

Note: This policy will not report for subnets used by Azure Firewall Subnet, Azure Firewall Management Subnet, Gateway Subnet, NetApp File Share, Route Server Subnet, Private endpoints and Private links as Azure recommends not to configure Network Security Group (NSG) for these services.


*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-subnet-list' AND json.rule = networkSecurityGroupId does not exist and name does not equal ignore case "GatewaySubnet" and name does not equal ignore case "RouteServerSubnet" and name does not equal ignore case "AzureFirewallSubnet" and ['properties.delegations'][*].['properties.serviceName'] does not equal "Microsoft.Netapp/volumes"
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-subnet-list' AND json.rule = networkSecurityGroupId does not exist and name does not equal ignore case "GatewaySubnet" and name does not equal ignore case "RouteServerSubnet" and name does not equal ignore case "AzureFirewallSubnet" and name does not equal ignore case "AzureFirewallManagementSubnet" and ['properties.delegations'][*].['properties.serviceName'] does not equal "Microsoft.Netapp/volumes"
----

*Impact*— Low. Alert for Azure Virtual Network (VNet) subnets used by  `AzureFirewallManagementSubnet` will be resolved. 

|*Azure Storage account encryption key configured by access policy with privileged operations*
//RLP-139004

|*Changes*— The policy RQL will be updated to check if the key vault will use Role-Based Access Control (RBAC) for authorization of data actions or not.

*Severity*— Medium

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.encryption.keySource equal ignore case "Microsoft.Keyvault" as X; config from cloud.resource where api.name = 'azure-key-vault-list' and json.rule = properties.accessPolicies[*].permissions exists and (properties.accessPolicies[*].permissions.keys[*] intersects ('Decrypt', 'Encrypt', 'Release', 'Purge', 'all') or properties.accessPolicies[*].permissions.secrets[*] intersects ('Purge', 'all') or properties.accessPolicies[*].permissions.certificates[*] intersects ('Purge', 'all')) as Y; filter '$.Y.properties.vaultUri contains $.X.properties.encryption.keyvaultproperties.keyvaulturi'; show X;
----

*Updated RQL—*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.encryption.keySource equal ignore case "Microsoft.Keyvault" as X; config from cloud.resource where api.name = 'azure-key-vault-list' and json.rule = properties.enableRbacAuthorization is false and properties.accessPolicies[*].permissions exists and (properties.accessPolicies[*].permissions.keys[*] intersects ('Decrypt', 'Encrypt', 'Release', 'Purge', 'all') or properties.accessPolicies[*].permissions.secrets[*] intersects ('Purge', 'all') or properties.accessPolicies[*].permissions.certificates[*] intersects ('Purge', 'all')) as Y; filter '$.Y.properties.vaultUri contains $.X.properties.encryption.keyvaultproperties.keyvaulturi'; show X; 
----

*Impact*— Low.



|===

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*AWS Network Firewall*
//RLP-138830 

|*aws-network-firewall-logging-configuration*

Additional permissions required:

* `network-firewall:DescribeLoggingConfiguration`
* `network-firewall:ListFirewalls`

The Security Audit role includes the permissions.

|*AWS Migration Hub*
//RLP-138824 

|*aws-migration-hub-home-region-control*

Additional permission required:

* `mgh:DescribeHomeRegionControls`

You must manually add the permission to the CFT template to enable it.

|*Azure API Management Services*
//RLP-134921
|*azure-api-management-service-diagnostic-settings*

Additional permissions required:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions. 


|*Azure App Service*
//RLP-136675

|*azure-app-service-basic-publishing-credentials-policies*

Additional permissions required:

* `Microsoft.Web/sites/Read`
* `Microsoft.Web/sites/basicPublishingCredentialsPolicies/Read`

The Reader role includes the permissions. 

|*Azure App Service*
//RLP-132837

|*azure-app-service-environment-diagnostic-settings*

Additional permissions required:

* `Microsoft.Web/hostingEnvironments/Read`
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions. 


|*Azure Analysis Services*
//RLP-134923

|*azure-analysisservices-servers-diagnostic-settings*

Additional permissions required:

* `Microsoft.AnalysisServices/servers/read`
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions. 

|*Azure Machine Learning*
//RLP-129311

|*zure-machine-learning-compute*

Additional permissions required:

* `Microsoft.MachineLearningServices/workspaces/read`
* `Microsoft.MachineLearningServices/workspaces/computes/read`

The Reader role includes the permissions. 

|*Google Cloud Support*
//RLP-131425

|*gcloud-cloud-support-case*

Additional permission required:

* `cloudsupport.techCases.list`

The Viewer role includes the permission. 


|*Google Cloud VMware Engine*
//RLP-135383

|*gcloud-vmware-engine-external-address*

Additional permissions required:

* `vmwareengine.locations.list 
* `vmwareengine.privateClouds.list`
* `vmwareengine.externalAddresses.list`

The Viewer role includes the permissions. 

|*Google Vertex AI AIPlatform*
//RLP-135381
|*gcloud-vertex-ai-aiplatform-feature-online-store*

Additional permission required:

* `aiplatform.featureOnlineStores.list`

The Viewer role includes the permission.

|*Google Vertex AI AIPlatform*
//RLP-135380
|*gcloud-vertex-ai-aiplatform-feature-group*

Additional permission required:

* `aiplatform.featureGroups.list`

The Viewer role includes the permission.

|*Google Workspace*
//RLP-135384
|*gcloud-domain-user-last-login-time*

No additional permissions required for this API.




|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|*End of support for Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services*

//RLP-134902

|NA
|24.5.2
|The following APIs are planned for deprecation at the end of April 2024 because Azure has announced the retirement of Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services. Due to this, Prisma Cloud will no longer ingest metadata for the following APIs:

* azure-data-lake-analytics-account
* azure-data-lake-analytics-diagnostic-settings
* azure-data-lake-store-gen1-account
* azure-data-lake-store-gen1-diagnostic-settings

In RQL, the key will not available in the `api.name` attribute auto-completion.

*Impact—* If you have a saved search or custom policies based on this API, you must delete them manually. The policy alerts will be resolved as Policy_Deleted.

|tt:[*Resource Explorer API*]

//RLP-131482

* https://pan.dev/prisma-cloud/api/cspm/get-resource/[GET/resource]
* https://pan.dev/prisma-cloud/api/cspm/get-timeline-for-resource/[POST /resource/timeline]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-raw/[POST /resource/raw]

|23.9.2
|24.6.2
|* https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[POST /uai/v1/asset]


|tt:[*Change to Compliance Trendline and Deprecation of Compliance Filters*]
//RLP-126719, need to check if this notice can be moved to current features in 24.1.2
| - 
| - 
|To provide better performance, the *Compliance trendline* will start displaying data only from the past one year. Prisma Cloud will not retain the snapshots of data older than one year.
The Compliance-related filters (*Compliance Requirement, Compliance Standard, and Compliance Section*) will not be available on Asset Inventory (*Inventory > Assets*).

|The following endpoints are deprecated as the date filters—time object or time string in query parameters or the request body—used by these APIs will be removed in the updated API endpoints. The updated API endpoints will always return current data.

tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|24.6.1

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA


|===