== Look Ahead—Planned Updates to Secure the Runtime

//Currently, there are no previews or announcements for updates.

The following sections provide a preview of the planned updates for the `v34.00` release of Runtime Security. 

*NOTE*: 

The details and functionality listed below provide a preview of what is planned for the `v34.00` release. Both the updates and their actual release dates are subject to potential changes.


//*<<announcement>>
//*<<intelligence-stream-updates>>
//*<<enhancements>>
<<changes-in-existing-behavior>>
//* <<new-policies>>
//* <<policy-updates>>
//* <<iam-policy-update>>
//* <<new-compliance-benchmarks-and-updates>>
//* <<api-ingestions>>
//* <<deprecation-notices>>

=== Changes in Existing Behavior
//CWP-62948
A fix is being implemented in Prisma Cloud to remove outdated assets that are no longer protected by a Defender. These assets should have been automatically deleted previously, but were not. 

With this update, you might notice that certain stale assets are no longer present in your inventory. As a result, you might also see a drop in vulnerabilities and compliance findings due to their removal. 
