== Look Ahead—Planned Updates to Secure the Infrastructure

Here are the changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 26.2.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and is not a cumulative list of all announcements.

[NOTE]
====
The details and functionalities listed below are a preview and the actual release date is subject to change.
====

//* <<changes-in-existing-behavior>>
* <<new-policies>>
//* <<policy-updates>>
* <<policy-deletions>>
//* <<api-ingestions>>
* <<deprecation-notices>>

There are currently no API ingetions for the 2.1 release.


//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior 

//[cols="50%a,50%a"]

//|===




//|===


[#new-policies] 
=== New Policies

To learn about the upcoming new Prisma Cloud policies and updates to existing Prisma Cloud policies, you need access to the *private* Prisma Cloud policies repository on GitHub. The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. 

Contact your Prisma Cloud representative, who will let you know the information required to get access to the repository. Once you receive access to the Prisma Cloud policies repository:

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has a monthly release, the release naming convention in GitHub is PCS-<year>.<month>.<1>. For example, PCS-26.2.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="40%a,60%a"]
|===
|*Policy Updates*
|*Description*

|*Azure Storage account diagnostic setting for blob is disabled*
//RLP-157561

|*Changes–* The policy RQL is updated to exclude irrelevant resources, helping reduce false positives.

*Current RQL–*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded as X; config from cloud.resource where api.name = 'azure-storage-account-blob-diagnostic-settings' AND json.rule = (properties.logs[?(@.categoryGroup)] exists and properties.logs[*].enabled any true) or (properties.logs[?(@.category)] exists and properties.logs[*].enabled all true) as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'azure' and api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded and kind does not contain FileStorage as X; config from cloud.resource where api.name = 'azure-storage-account-blob-diagnostic-settings' AND json.rule = (properties.logs[?(@.categoryGroup)] exists and properties.logs[*].enabled any true) or (properties.logs[?(@.category)] exists and properties.logs[*].enabled all true) as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts will be resolved for storage accounts where diagnostic settings are not applicable.

|*Azure Storage account diagnostic setting for file is disabled*
//RLP-157560

|*Changes–* The policy RQL is updated to exclude irrelevant resources, helping reduce false positives.

*Current RQL–*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded as X; config from cloud.resource where api.name = 'azure-storage-account-file-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'azure' and api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded and not(kind equal ignore case BlockBlobStorage or (kind equal ignore case StorageV2 and sku.tier equal ignore case Premium)) as X; config from cloud.resource where api.name = 'azure-storage-account-file-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts will be resolved for storage accounts where diagnostic settings are not applicable.

|*Azure Storage account diagnostic setting for table is disabled*
//RLP-157559

|*Changes–* The policy RQL is updated to exclude irrelevant resources, helping reduce false positives.

*Current RQL–*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded as X; config from cloud.resource where api.name = 'azure-storage-account-table-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'azure' and api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded and not(sku.tier equal ignore case Premium or (kind equal ignore case FileStorage and sku.tier equal ignore case Standard)) as X; config from cloud.resource where api.name = 'azure-storage-account-table-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts will be resolved for storage accounts where diagnostic settings are not applicable.

|*Azure Storage account diagnostic setting for queue is disabled*
//RLP-157558

|*Changes–* The policy RQL is updated to exclude irrelevant resources, helping reduce false positives.

*Current RQL–*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded as X; config from cloud.resource where api.name = 'azure-storage-account-queue-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X; 
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'azure' and api.name = 'azure-storage-account-list' AND json.rule = properties.provisioningState equal ignore case Succeeded and not(sku.tier equal ignore case Premium or (kind equal ignore case FileStorage and sku.tier equal ignore case Standard)) as X; config from cloud.resource where api.name = 'azure-storage-account-queue-diagnostic-settings' AND json.rule = properties.logs[*].enabled all true as Y; filter 'not($.X.name equal ignore case $.Y.StorageAccountName)'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts will be resolved for storage accounts where diagnostic settings are not applicable.

|===


[#policy-deletions]
=== Policy Deletions

[cols="50%a,50%a"]

|===
|*Policy Updates*
|*Description*

|*Azure Policy Deletions*
//RLP-156921

|*Changes–* The following Azure policies will be removed from Prisma Cloud because the database services **Azure Database for MySQL - Single Server**, **Azure Database for PostgreSQL - Single Server**, and **Azure Database for MariaDB** have been retired by the cloud service provider (CSP).

**List of deleted policies:**

1. Azure Database for MySQL server not configured with private endpoint
2. Azure MySQL Database Server using insecure TLS version
3. Azure MySQL Database Server SSL connection is disabled
4. Azure PostgreSQL database server with log duration parameter disabled
5. Azure PostgreSQL database server with SSL connection disabled
6. Azure PostgreSQL database server with log checkpoints parameter disabled
7. Azure PostgreSQL Database Server 'Allow access to Azure services' enabled
8. Azure PostgreSQL database server with connection throttling parameter is disabled
9. Azure PostgreSQL servers not configured with private endpoint
10. Azure PostgreSQL database server log retention days is less than or equals to 3 days
11. Azure PostgreSQL database server Infrastructure double encryption is disabled
12. Azure PostgreSQL database server deny public network access setting is not set
13. Azure PostgreSQL Database Server Firewall rule allow access to all IPV4 address
14. Azure PostgreSQL database server with log disconnections parameter disabled
15. Azure PostgreSQL database server with log connections parameter disabled
16. Azure MariaDB database server not using latest TLS version
17. Azure Database for MariaDB not configured with private endpoint
18. Azure MariaDB database server with SSL connection disabled

*Impact–* Existing alerts will be resolved as `Policy_Deleted`.


|===

//[#api-ingestions]
//=== API Ingestions

//[cols="50%a,50%a"]
//|===
//|*Service*
//|*API Details*

//|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[*Asset Trendline and Compliance APIs*]
//PCS-4515, PCS-4556

It is recommended that you start using the Asset Inventory and Compliance Summary APIs once they're available since they provide the latest snapshot of data. The Asset Trendline and Compliance APIs listed have been deprecated. They will remain accessible until 25.9.1, ensuring you get ample time for a smooth transition to use the Asset Inventory and Compliance Summary APIs to get the latest state.

//new apis - still lga? - https://docs.prismacloud.io/en/enterprise-edition/assets/pdf/asset-inventory-compliance-api-documentation.pdf

*Asset Trendline*

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/

*Compliance*

* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/


|25.4.1

|25.9.1

|Will be provided in an upcoming release.

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823, Abinaya - They are not planning to sunset the APIs anytime soon and they want the sunset column to be left blank.

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|NA

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*Asset Explorer APIs*]
//RLP-139337
|24.8.1
|NA

|The `accountGroup` response parameter was introduced in error and is now deprecated for Get Asset - https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[GET - uai/v1/asset] API endpoint.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|===