== Look Ahead—Planned Updates to Secure the Infrastructure

Here are the changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 26.4.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and is not a cumulative list of all announcements.

[NOTE]
====
The details and functionalities listed below are a preview and the actual release date is subject to change.
====

//* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<policy-deletions>>
* <<api-ingestions>>
* <<deprecation-notices>>


There are currently no API ingestions planned for the 26.4.1 release.

//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior 

//[cols="50%a,50%a"]

//|===




//|===


[#new-policies] 
=== New Policies

To learn about the upcoming new Prisma Cloud policies and updates to existing Prisma Cloud policies, you need access to the *private* Prisma Cloud policies repository on GitHub. The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. 

Contact your Prisma Cloud representative, who will let you know the information required to get access to the repository. Once you receive access to the Prisma Cloud policies repository:

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has a monthly release, the release naming convention in GitHub is PCS-<year>.<month>.<1>. For example, PCS-26.4.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.

Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="40%a,60%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*GCP Dataproc Cluster on Compute Engine is using default network*
//RLP-156954

|*Changes–* The policy RQL will be updated to match GCP API.

*Current RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-dataproc-clusters-list' AND json.rule = status.state is member of ("SCHEDULED", "CREATING", "RUNNING") and ( environmentConfig.executionConfig.networkUri ends with "default" or environmentConfig.executionConfig.subnetworkUri ends with "default" or ( environmentConfig.executionConfig.networkUri does not exist and environmentConfig.executionConfig.subnetworkUri does not exist ) )
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-dataproc-clusters-list' AND json.rule = status.state is member of ("SCHEDULED", "CREATING", "RUNNING") and ( config.gceClusterConfig.networkUri ends with "default" or config.gceClusterConfig.subnetworkUri ends with "default" or ( config.gceClusterConfig.networkUri does not exist and config.gceClusterConfig.subnetworkUri does not exist ) )
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. New alerts will be generated as per the new RQL.

|*GCP Dataproc Cluster on Compute Engine is using default network*
//RLP-156961

|*Changes–* The policy RQL will be updated to cover Dataproc clusters using zonal GKE clusters.

*Current RQL–*
----
config from cloud.resource where api.name = 'gcloud-dataproc-clusters-list' AND json.rule = status.state is member of ("SCHEDULED", "CREATING", "RUNNING") as X; config from cloud.resource where api.name = 'gcloud-container-describe-clusters' AND json.rule = status equals RUNNING and ['network'] ends with "default" as Y; filter ' $.Y.selfLink contains $.X.virtualClusterConfig.kubernetesClusterConfig.gkeClusterConfig.gkeClusterTarget '; show X;
----

*Proposed RQL–*
----
config from cloud.resource where api.name = 'gcloud-dataproc-clusters-list' as X; config from cloud.resource where api.name = 'gcloud-container-describe-clusters' AND json.rule = status equals RUNNING and ['network'] ends with "default" as Y; filter ' $.X.virtualClusterConfig.kubernetesClusterConfig.gkeClusterConfig.gkeClusterTarget contains $.Y.location and $.X.virtualClusterConfig.kubernetesClusterConfig.gkeClusterConfig.gkeClusterTarget contains $.Y.name and $.Y.selfLink contains $.X.projectId '; show X;
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. New alerts will be generated as per the new RQL.

|*Azure VM OS disk is encrypted with the default encryption key instead of ADE/CMK*
//RLP-157779

|*Changes–* The policy RQL will be updated to remove the `encryptionSettings parameter` parameter.

*Current RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-disk-list' and json.rule = 'osType exists and managedBy exists and (encryptionSettings does not exist or encryptionSettings.enabled == false) and encryption.type is not member of ("EncryptionAtRestWithCustomerKey", "EncryptionAtRestWithPlatformAndCustomerKeys")' 
----

*Proposed RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-disk-list' and json.rule = 'osType exists and managedBy exists and encryption.type is not member of ("EncryptionAtRestWithCustomerKey", "EncryptionAtRestWithPlatformAndCustomerKeys")'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low




// 2+|*Policy Updates—Metadata*

|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*


|*AWS Service Quotas*
//RLP-157762

|*aws-servicequotas-service-quota*

Additional permissions required:

* `servicequotas:ListServiceQuotas`
* `servicequotas:ListTagsForResource`

The Security audit role includes the permissions.

|*Amazon Cognito*
//RLP-157834

|*aws-cognito-identity-provider*

Additional permissions required:

* `aws-cognito-identity-provider`

The Security audit role includes the permission.

|*AWS Database Migration Service*
//RLP-157837

|*aws-servicequotas-service-quota*

Additional permissions required:

* `dms:DescribeInstanceProfiles`
* `dms:ListTagsForResource`

The Security audit role includes the permissions.

|*AWS Database Migration Service*
//RLP-157838

|*aws-dms-replication-subnet-group*

Additional permissions required:

* `dms:DescribeReplicationSubnetGroups`
* `dms:ListTagsForResource`

The Security audit role includes the permissions.

|*Google Network Security*
//RLP-157648

|*gcloud-network-security-project-address-group*

Additional permission required:

* `networksecurity.addressGroups.list`

The Viewer role includes the permission.

|*Google Network Security*
//RLP-157647

|*gcloud-network-security-organization-address-group*

Additional permission required:

* `networksecurity.addressGroups.list`

The Viewer role includes the permission.

|*Amazon Route53 Resolver*
tt:[Update]
//RLP-157836

|*aws-route53resolver-resolver-endpoint*

Updated the existing API to ingest additional attribute `IpAddresses`. The following permission is required for this attribute to be ingested.


* `route53resolver:ListResolverEndpointIpAddresses`



|===

[#policy-deletions]
=== Policy Deletions

[cols="50%a,50%a"]

|===
|*Policy Updates*
|*Description*

|*AutoFocus Policy Deletions*
//RLP-157644

|*Changes–* Palo Alto Networks' AutoFocus product has reached its End of Life (EOL) date. As a result, the following AutoFocus Anomaly policies will be removed from Prisma Cloud. Learn more about https://live.paloaltonetworks.com/t5/community-blogs/autofocus-end-of-sale-faq-and-alternatives/ba-p/516051[AutoFocus EOL].

* Traffic to a suspicious IP address associated with Loader activity
* Traffic from a suspicious IP address associated with File Infector activity
* Traffic to a suspicious IP address associated with File Infector activity
* Traffic from a suspicious IP address associated with Dropper activity
* Traffic to a suspicious IP address associated with Ransomware activity
* Traffic to a suspicious IP address associated with Backdoor activity
* Traffic to a suspicious IP address associated with Cryptominer activity
* Traffic from a suspicious IP address associated with Botnet activity
* Traffic from a suspicious IP address associated with Cryptominer activity
* Traffic from a suspicious IP address associated with Ransomware activity
* Traffic to a suspicious IP address associated with Linux Malware activity
* Traffic to a suspicious IP address associated with Botnet activity
* Traffic from a suspicious IP address associated with Backdoor activity
* Traffic from a suspicious IP address associated with Linux Malware activity
* Traffic from a suspicious IP address associated with Remote Access Trojan activity
* Traffic to a suspicious IP address associated with Remote Access Trojan activity
* Traffic from a suspicious IP address associated with DDoS activity
* Traffic from a suspicious IP address associated with InfoStealer activity
* Traffic to a suspicious IP address associated with DDoS activity
* Traffic to a suspicious IP address associated with InfoStealer activity
* Traffic from a suspicious IP address associated with Wiper activity
* Traffic to a suspicious IP address associated with Wiper activity
* Traffic to a suspicious IP address associated with Dropper activity
* Traffic from a suspicious IP address associated with Loader activity
* Traffic from a suspicious IP address associated with Rootkit activity
* Traffic to a suspicious IP address associated with Webshell activity
* Traffic from a suspicious IP address associated with Webshell activity
* Traffic to a suspicious IP address associated with Rootkit activity
* Traffic to a suspicious IP address associated with Exploit Kit activity
* Traffic from a suspicious IP address associated with Exploit Kit activity
* Traffic to a suspicious IP address associated with Hacking Tool activity
* Traffic from a suspicious IP address associated with Hacking Tool activity
* Traffic from a suspicious IP address associated with Worm activity
* Traffic to a suspicious IP address associated with Worm activity
* Traffic from a suspicious IP address associated with Downloader activity
* Traffic to a suspicious IP address associated with Downloader activity

 
The following Attack path policies are also impacted:

* Potential malicious activity on Azure Virtual Machine affected by malware
* Potential unauthorized cryptomining activity on AWS EC2 instance affected by malware
* Potential unauthorized cryptomining activity on GCP VM instance affected by malware
* Potentially nefarious backdoor activity detected on a publicly exposed and vulnerable GCP VM instance
* Potentially nefarious downloader activity detected on Azure Virtual machine with public serial console access
* Potentially nefarious hacking tools activity detected on a publicly exposed and vulnerable AWS EC2 instance with risky privilege escalation permissions
* Potentially nefarious hacking tools activity detected on a publicly exposed and vulnerable Azure Virtual Machine with risky privilege escalation permissions
* Potentially nefarious hacking tools activity detected on a publicly exposed and vulnerable GCP VM instance with risky service account impersonation permissions
* Potentially nefarious malware activity detected on a publicly exposed and vulnerable Azure Virtual Machine
* Potentially nefarious malware activity detected on a publicly exposed and vulnerable GCP VM instance
* Secrets exfiltration risk due to malware in AWS EC2 instance containing secrets with traffic to/from suspicious IPs associated with malicious activity
* Secrets exfiltration risk due to malware in Azure Virtual Machine containing secrets with traffic to/from suspicious IPs associated with malicious activity
* Secrets exfiltration risk due to malware in GCP VM instance containing secrets with traffic to/from suspicious IPs associated with malicious activity
* Sensitive data leakage via "InfoStealer" malware activity detected on a publicly exposed and vulnerable AWS EC2 instance
* Sensitive data leakage via "InfoStealer" malware activity detected on a publicly exposed and vulnerable Azure Virtual Machine
* Potentially nefarious webshell activity detected on a publicly exposed and vulnerable Azure Virtual Machine with risky privilege escalation permissions
* Potential malicious activity on GCP VM instance affected by malware
* Potential unauthorized cryptomining activity on Azure Virtual Machine affected by malware
* Potentially unauthorized cryptomining activity detected on a publicly exposed and vulnerable AWS EC2 instance
* Potentially unauthorized cryptomining activity detected on a publicly exposed and vulnerable Azure Virtual Machine
* Potentially nefarious webshell activity detected on a publicly exposed and vulnerable GCP VM instance with risky service account impersonation permissions
* Potential malicious activity on AWS EC2 instance affected by malware
* Potentially nefarious backdoor activity detected on a publicly exposed and vulnerable Azure Virtual Machine
* Potentially nefarious webshell activity detected on a publicly exposed and vulnerable AWS EC2 instance with risky privilege escalation permissions
* Potentially nefarious malware activity detected on a publicly exposed and vulnerable AWS EC2 instance
* Potentially unauthorized cryptomining activity detected on a publicly exposed and vulnerable GCP VM instance
* Potentially nefarious ransomware activity detected on Azure Virtual machine with public serial console access
* Potentially nefarious hacking tools activity detected on Azure Virtual machine with public serial console access
* Potentially nefarious backdoor activity detected on a publicly exposed and vulnerable AWS EC2 instance


*Impact*– Keep in mind the following potential effects of this change: +
* Existing alerts will be resolved as `Policy_Deleted`. +
* All policies related to AutoFocus will be deprecated. +
* RQL support for AutoFocus suggestions will be removed. +
* The ability to add trusted IP addresses to AutoFocus anomaly polices will be deprecated. +
* Any custom policies that use AutoFocus attributes will also be impacted. 


|===

[#deprecation-notices]
=== Deprecation Notices

[cols="40%a,10%a,10%a,40%a"]
|===

|*Deprecated Endpoints*
|*Deprecated*
|*Sunset*
|*Replacement Endpoints*


|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823, Abinaya - They are not planning to sunset the APIs anytime soon and they want the sunset column to be left blank.

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|NA

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*Asset Explorer APIs*]
//RLP-139337
|24.8.1
|NA

|The `accountGroup` response parameter was introduced in error and is now deprecated for Get Asset - https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[GET - uai/v1/asset] API endpoint.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|===