[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates to Secure the Infrastructure

Review any changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 24.6.2 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and it is not a cumulative list of all announcements.

[NOTE]
====
The details and functionality listed below are a preview and the actual release date is subject to change.
====

* <<changes-in-existing-behavior>>
* <<new-policies>>
//* <<policy-updates>>
* <<api-ingestions>>
//* <<new-compliance-benchmarks-and-updates>>
* <<rest-api-updates>>
* <<deprecation-notices>>

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|*Feature*
|*Description*

// |*Tag-based Resource Lists*
//RLP-140177

// |Starting with the X release, the following limits will be enforced for Tag-based Resource Lists:

//* Tag-based Resource Lists will be limited to 10 key-value pairs
//* Up to 5 Tag-based Resource Lists may be associated with a Role

//*Impact*: These changes will affect Tag-based Resource Lists and Roles after the X release. Existing configurations will not be affected.
// Commenting out per feedback from AO 5/24

|*API Rate Limits — Update User Role API*
//RLP-141323

|To resolve a critical performance issue with the https://pan.dev/prisma-cloud/api/cspm/update-user-role/[Update User Role] API (PUT /user/role), a rate limit with the following parameters will be implemented effective 24.6.2.

`Limit=3, Burst=3` 

*Impact*—Requests exceeding these limits will result in an *HTTP 429* Too Many Requests response.

|*Role-Based Access Control for Compliance and Alert Reports*
//RLP-140182

|Implementing Role-Based Access Control (RBAC) enhances data security by streamlining report access for users with the same role, while also preventing unauthorized access.

*Impact*—Starting with the 24.8.1 release, user-generated Reports will only be visible to System Administrators and users with the same role.

|===

[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-24.6.2.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


=== New Policies

[cols="50%a,50%a"]
|===
|*Policies*
|*Description*

|*Azure Application Gateway WAF policy is not enabled in prevention mode*
//RLP-141038

|This policy identifies the Azure Application Gateway WAF policies that are not enabled in prevention mode.

Azure Application Gateway WAF policies support Prevention and Detection modes. Detection mode monitors and logs all threat alerts to a log file. Detection mode is useful for testing purposes and configures WAF initially but it does not provide protection. It logs the traffic, but it doesn't take any actions such as allow or deny. Where as, in Prevention mode, WAF analyzes incoming traffic to the application gateway and blocks any requests that are determined to be malicious based on a set of rules.

As a best security practice, it is recommended to enable Application Gateway WAF policies with Prevention mode to prevent malicious requests from reaching your application and potentially causing damage.

*Policy Severity—* Low

*Policy Type—* Config

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-application-gateway-waf-policy' AND json.rule = properties.applicationGateways[*].id size greater than 0 and properties.policySettings.state equal ignore case Enabled and properties.policySettings.mode does not equal ignore case Prevention
----

|*Azure Storage Account storing Cognitive service diagnostic logs is publicly accessible*
//RLP-141884

| This policy identifies Azure Storage Accounts storing Cognitive service diagnostic logs are publicly accessible. 

Azure Storage account stores Cognitive service diagnostic logs which might contain detailed information of platform logs, resource logs, trace logs and metrics. Diagnostic log data may contain sensitive data and helps in identifying potentially malicious activity. The attacker could exploit publicly accessible storage account to get cognitive diagnostic data logs and could breach in to the system by leveraging data exposed and propagate across your system.

As a best security practice, it is recommended to restrict storage account access to only to the services as per business requirement.

*Policy Severity—* Medium

*Policy Type—* Config

----
config from cloud.resource where api.name = 'azure-cognitive-services-account-diagnostic-settings' AND json.rule = (properties.logs[?any(enabled equal ignore case "true")] exists or properties.metrics[?any( enabled equal ignore case "true" )] exists) and properties.storageAccountId exists as X; config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = 'totalPublicContainers > 0 and (properties.allowBlobPublicAccess is true or properties.allowBlobPublicAccess does not exist)' as Y; filter '$.X.properties.storageAccountId contains $.Y.id'; show Y;
----

|*Azure Key vault used for machine learning workspace secrets storage is not enabled with audit logging*
//RLP-142008

|This policy identifies Azure Key vaults used for machine learning workspace secrets storage that are not enabled with audit logging.

Azure Key vaults are used to store machine learning workspace secrets and other sensitive information that is needed by the workspace. Enabling key vaults with audit logging will help in monitoring how and when machine learning workspace secrets are accessed, and by whom. This audit log data enhances visibility by providing valuable insights into the trail of interactions involving confidential information.

As a best practice,  it is recommended to enable audit event logging for key vaults used for machine learning workspace secrets storage.

*Policy Severity—* Informational

*Policy Type—* Config

----
config from cloud.resource where api.name = 'azure-machine-learning-workspace' AND json.rule = properties.keyVault exists as X; config from cloud.resource where api.name = 'azure-key-vault-list' AND json.rule =  "not (diagnosticSettings.value[*].properties.logs[*].enabled any equal true and diagnosticSettings.value[*].properties.logs[*].enabled size greater than 0)" as Y; filter '$.X.properties.keyVault contains $.Y.name'; show Y; 
----

|*OCI VCN subnet flow logging is disabled*
//RLP-61034

|This policy identifies Virtual Cloud Network (VCN) subnets that have flow logs disabled. 

Enabling VCN flow logs enables you to monitor traffic flowing within your virtual network and can be used to detect anomalous traffic. Without the flow logs turned on, it is not possible to get any visibility into network traffic. 

It is recommended to enable a VCN flow log on each of your VCN subnets

*Policy Severity—* Low

*Policy Type—* Config

----
config from cloud.resource where api.name = 'oci-networking-subnet' as X; config from cloud.resource where api.name = 'oci-logging-logs' AND json.rule = lifecycleState equals ACTIVE and isEnabled is true and configuration.source.service contains flowlogs as Y; filter 'not ($.X.id contains $.Y.configuration.source.resource)'; show X;
----

|===

[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*Config Policies related to Azure Function App*
//RLP-139004

|*Changes*— All Function app policies have been updated to not report for logic app and web apps as the scope of the policy is Azure function app only.

*Policy*— *Azure Function App doesn't have a Managed Service Identity*

*Severity*— Low

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case Running and kind contains functionapp and (identity.type does not exist or identity.principalId is empty) 
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND kind does not contain "workflowapp" AND kind does not equal "app" AND (identity.type does not exist or identity.principalId is empty)
----

*Policy*— *Azure Function app configured with public network access*

*Severity*— Medium

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with functionapp and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist)) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists' 
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind contains functionapp and kind does not contain workflowapp and kind does not equal app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist)) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy*— *Azure Function App doesn't use latest TLS version*

*Severity*— Low

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND config.minTlsVersion does not equal "1.2"
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND kind does not contain "workflowapp" AND kind does not equal "app" AND config.minTlsVersion does not equal "1.2"
----

*Policy*— *Azure Function App doesn't use HTTP 2.0*

*Severity*— Informational

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND config.http20Enabled is false
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND kind does not contain "workflowapp" AND kind does not equal "app" AND config.http20Enabled is false
----

*Policy*— *Azure Function App doesn't redirect HTTP to HTTPS*

*Severity*— Medium

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND properties.httpsOnly is false
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND kind does not contain "workflowapp" AND kind does not equal "app" AND properties.httpsOnly is false
----

*Policy*— *Azure Function App client certificate is disabled*

*Severity*— Informational

*Policy Type*— Config

*Current RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case Running and kind contains functionapp and properties.clientCertEnabled is false
----

*Updated RQL—*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = properties.state equal ignore case "Running" AND kind contains "functionapp" AND kind does not contain "workflowapp" AND kind does not equal "app" AND properties.clientCertEnabled is false
----

|===

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*AWS Service Catalog*
//RLP-141195

|*aws-servicecatalog-principals-for-portfolio*

Additional permissions required:

* `servicecatalog:ListPortfolios`
* `servicecatalog:ListPrincipalsForPortfolio`

The Security Audit role does not include the permissions. Create a new custom role for the permissions.

|*Amazon Comprehend*
//RLP-141193

|*aws-comprehend-pii-entities-detection-jobs*

Additional permissions required:

* `comprehend:ListPiiEntitiesDetectionJobs`
* `comprehend:ListTagsForResource`

The Security Audit role includes the permissions. 

|*Amazon Comprehend*
//RLP-141490

|*aws-comprehend-sentiment-detection-jobs*

Additional permissions required:

* `comprehend:ListSentimentDetectionJobs`
* `comprehend:ListTagsForResource`

The Security Audit role includes the permissions. 

|*Amazon Comprehend*
//RLP-141485

|*aws-comprehend-key-phrases-detection-jobs*

Additional permission required:

* `comprehend:ListKeyPhrasesDetectionJobs`
* `comprehend:ListTagsForResource`

The Security Audit role includes the permissions.

|*Azure Compute*
//RLP-141280

|*azure-compute-disk-encryption-sets*

Additional permission required:

* `Microsoft.Compute/diskEncryptionSets/read`

The Reader role includes the permission.


|*Azure Active Directory*
//RLP-141052

|*azure-active-directory-user-registration-details*

Additional permission required:

* `AuditLog.Read.All`

The Reader role includes the permission.


|*Azure Databricks*
//RLP-141045

|*azure-databricks-diagnostic-settings*

Additional permission required:

* `Microsoft.Databricks/workspaces/read
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions.


|*Azure App Service*
//RLP-141007

|*azure-app-service-web-apps-functions*

Additional permission required:

* `Microsoft.Web/sites/Read`
* `Microsoft.Web/sites/Functions/Read`

The Reader role includes the permissions.


|*Azure NetApp Files*
//RLP-141005

|*aws-comprehend-key-phrases-detection-jobs*

Additional permission required:

* `Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read`
* `Microsoft.NetApp/netAppAccounts/read`
* `Microsoft.NetApp/netAppAccounts/capacityPools/read`

The Reader role includes the permissions.

|*Azure App Service*
//RLP-138481

|*azure-app-service-plan*

Additional permission required:

* `Microsoft.Web/serverfarms/Read`

The Reader role includes the permission.


|*Google Vertex AI AIPlatform*
//RLP-141136

|*gcloud-vertex-ai-aiplatform-monitoring-job*

Additional permission required:

* `aiplatform.modelDeploymentMonitoringJobs.list`

The Viewer role includes the permission. 


|*Google Vertex AI AIPlatform*
//RLP-141135

|*gcloud-vertex-ai-aiplatform-persistent-resource*

Additional permission required:

* `aiplatform.persistentResources.list`

The Viewer role includes the permission. 

|*Google Vertex AI AIPlatform*
//RLP-141134

|*gcloud-vertex-ai-aiplatform-vizier-study*

Additional permission required:

* `aiplatform.studies.list`

The Viewer role includes the permission. 

|*Google Vertex AI AIPlatform*
//RLP-141133

|*gcloud-vertex-ai-aiplatform-tuning-job*

Additional permission required:

* `aiplatform.tuningJobs.list`

The Viewer role includes the permission. 

|*Google Vertex AI*
//RLP-129987

|*gcloud-vertex-ai-workbench-instance*

Additional permission required:

* `notebooks.instances.list`
* `notebooks.instances.getIamPolicy`

The Viewer role includes the permission. 

|tt:[Update] *Amazon Route53*
//RLP-141028

|*aws-route53-list-hosted-zones*

The following fields will be excluded from the resource JSON for this API:

* `resourceRecordSet[*].region`

* `resourceRecordSet[*].trafficPolicyInstanceId`

* `resourceRecordSet[*].ttl`

|tt:[Update] *AWS Trusted Advisor*
//RLP-141028

|*aws-trusted-advisor-check-result*

The `flaggedResources` field with the status `OK` will be excluded from the resource JSON for this API.


|===


[#rest-api-updates]
=== REST API Updates

[cols="37%a,63%a"]
|===
|*Change*
|*Description*

|*Update to Alerts APIs*

//RLP-128008

|The https://pan.dev/prisma-cloud/api/cspm/alert-policy-list/[POST /alert/v1/policy] and https://pan.dev/prisma-cloud/api/cspm/alert-aggregation/[POST /alert/v1/aggregate] APIs will have an additional `countDetails` parameter in the response that will include `totalAlerts` and `totalPolicies`. This parameter allows you to view the total number of alerts across the total number of policies on the *Alerts Overview* page.

|===


[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

// |*End of support for Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services*

//RLP-134902, RLP-127361

// |NA
// |24.6.1

// |The following APIs are planned for deprecation because Azure has announced the retirement of Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services. Due to this, Prisma Cloud will no longer ingest metadata for the following APIs:

// * azure-data-lake-analytics-account
// * azure-data-lake-analytics-diagnostic-settings
// * azure-data-lake-store-gen1-account
// * azure-data-lake-store-gen1-diagnostic-settings

// In RQL, the key will not be available in the `api.name` attribute auto-completion.

// *Impact*—If you have a saved search or custom policies based on this API, you must delete those manually. The policy alerts will be resolved as Policy_Deleted.


|tt:[*Deprecation of Compliance Standards*]

The following legacy Compliance Standards are planned for deprecation at the end of May 2024. The standards will be removed from the Prisma Cloud console at the end of July 2024.

* MITRE ATT&CK v10.0
* MITRE ATT&CK v6.3
* MITRE ATT&CK v8.2
* HITRUST CSF v9.3
* HITRUST v.9.4.2

//RLP-140241

|24.5.2
|24.7.2
|You must upgrade to the latest version of the Compliance Standards:

* MITRE ATT&CK v14.0 Cloud IaaS for Enterprise
* HITRUST CSF v.11.2.0


|tt:[*Resource Explorer API*]

//RLP-131482

* https://pan.dev/prisma-cloud/api/cspm/get-resource/[GET/resource]
* https://pan.dev/prisma-cloud/api/cspm/get-timeline-for-resource/[POST /resource/timeline]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-raw/[POST /resource/raw]

|23.9.2
|24.6.2
|* https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[POST /uai/v1/asset]


|tt:[*Change to Compliance Trendline and Deprecation of Compliance Filters*]
//RLP-126719, need to check if this notice can be moved to current features in 24.1.2
| - 
| - 
|To provide better performance, the *Compliance trendline* will start displaying data only from the past one year. Prisma Cloud will not retain the snapshots of data older than one year.
The Compliance-related filters (*Compliance Requirement, Compliance Standard, and Compliance Section*) will not be available on Asset Inventory (*Inventory > Assets*).

|The following endpoints are deprecated as the date filters—time object or time string in query parameters or the request body—used by these APIs will be removed in the updated API endpoints. The updated API endpoints will always return current data.

tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|24.9.1

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA


|===