== Look Ahead—Planned Updates to Secure the Infrastructure

Here are the changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 25.10.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and is not a cumulative list of all announcements.

[NOTE]
====
The details and functionalities listed below are a preview and the actual release date is subject to change.
====

//* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>

//There are currently no API ingestions or Policy Updates in the pipeline for 25.8.1.


//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior 

//[cols="50%a,50%a"]

//|===

//|*Feature*
//|*Description*
//|===


[#new-policies] 
=== New Policies

To learn about the upcoming new Prisma Cloud policies and updates to existing Prisma Cloud policies, you need access to the *private* Prisma Cloud policies repository on GitHub. The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. 

Contact your Prisma Cloud representative, who will let you know the information required to get access to the repository. Once you receive access to the Prisma Cloud policies repository:

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has a monthly release, the release naming convention in GitHub is PCS-<year>.<month>.<1>. For example, PCS-25.10.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates


[cols="40%a,60%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*Azure App Service web apps with public network access*
//RLP-156747

|*Changes–* The RQL is updated to consider private endpoints as well to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled and config.ipSecurityRestrictions[?any(action equals Allow and ipAddress equals Any)] exists'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist and (properties.privateLinkIdentifiers does not exist or properties.privateLinkIdentifiers is empty))) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where private link identifiers exist will be resolved. App service where the IP rule allowing 0.0.0.0/0 will be alerted. 


|*Azure Key Vault audit logging is disabled*
//RLP-156668

|*Changes–* RQL updated to resolve a syntax issue.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND  api.name = 'azure-key-vault-list' AND json.rule =  "not ( diagnosticSettings.value[*].properties.logs[*].enabled any equal true and diagnosticSettings.value[*].properties.logs[*].enabled size greater than 0 )" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-key-vault-list' AND json.rule = not(diagnosticSettings.value[?any(properties.logs[?any(enabled equals "true")] exists )] exists and diagnosticSettings.value[*].properties.logs[*].enabled size > 0) 
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* No Impact

|*Azure Network Watcher Network Security Group (NSG) flow logs are disabled*
//RLP-156741

|*Changes–*  Prisma policy updated to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings does not exist or flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.storageId is not empty and flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Current Remediation Steps–* 
To configure Network Watcher Network Security Group (NSG) flow log, follow below URL:
https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-portal#enable-nsg-flow-log

*Proposed Remediation Steps–* 

Follow the below steps to enable flow logs for Network security group via Azure Portal:

1. Log in to the Azure portal.
2. Search *Network foundation*.
3. Under *Virtual Network*, Select *Network security groups*
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under *Monitoring*, Select *NSG flow logs*'.
6. Select the flow log with Status *Disabled*, Click on *Enable* at the top.
7. Confirm the flow log name and click *Enable* at the bottom. 

Use the command below to enable flow logs for Network security group via Azure CLI:

`az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --location <location>`

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.


|*Azure Network Watcher Network Security Group (NSG) flow logs retention is less than 90 days*
//RLP-156742

|*Changes–*  Prisma policy updated to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule =  ' $.flowLogsSettings does not exist or  $.flowLogsSettings.enabled is false or  ($.flowLogsSettings.retentionPolicy.days does not equal 0 and $.flowLogsSettings.retentionPolicy.days less than 90) '
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.retentionPolicy.days does not equal 0 and flowLogsSettings.retentionPolicy.days less than 90) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Proposed Remediation Steps–* 

Follow the below steps to update retention days for flow logs via Azure Portal:

1. Log in to the Azure portal.
2. Search *Network foundation*.
3. Under *Virtual Network*, Select *Network security groups*
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under *Monitoring*, Select *NSG flow logs*'.
6. Click the flow log, and under *Storage Account*, Set the *Retention days* to 90 days or greater.
7. *Save* your changes.  

Use the command below to enable flow logs for Network security group via Azure CLI: 

`az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --retention <Retention Days> --location <location>`

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.


|*Azure App Service web apps with public network access*
//RLP-156747

|*Changes–* RQL update to consider private endpoints and reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled and config.ipSecurityRestrictions[?any(action equals Allow and ipAddress equals Any)] exists'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist and (properties.privateLinkIdentifiers does not exist or properties.privateLinkIdentifiers is empty))) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low.  Open alerts where private link identifiers exist will be resolved. App service where the IP rule allowing 0.0.0.0/0 will be alerted.

|*Azure Key Vault audit logging is disabled{}*
//RLP-156668

|*Changes–* RQL update to resolve syntax issue.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND  api.name = 'azure-key-vault-list' AND json.rule =  "not ( diagnosticSettings.value[*].properties.logs[*].enabled any equal true and diagnosticSettings.value[*].properties.logs[*].enabled size greater than 0 )" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-key-vault-list' AND json.rule = not(diagnosticSettings.value[?any(properties.logs[?any(enabled equals "true")] exists )] exists and diagnosticSettings.value[*].properties.logs[*].enabled size > 0) 
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* No Impact

|*Azure Microsoft Defender for Cloud disk encryption monitoring is set to disabled*
//RLP-156565

|*Changes–* RQL logic and remediation is updated for this Policy.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.diskEncryptionMonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))' 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and (properties.parameters.gcLinuxDiskEncryptionMonitoringEffect.value equals Disabled or properties.parameters.gcWindowsDiskEncryptionMonitoringEffect.value equals Disabled)) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* All alerts will be resolved as Policy Updated.

|*Azure Key Vault audit logging is disabled{}*
//RLP-156565

|*Changes–* RQL logic and remediation is updated for this Policy.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.systemUpdatesMonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'  
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.systemUpdatesV2MonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* All alerts will be resolved as Policy Updated.

|*Azure Network Watcher Network Security Group (NSG) flow logs retention is less than 90 days*
//RLP-156742

|*Changes–* RQL update to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule =  ' $.flowLogsSettings does not exist or  $.flowLogsSettings.enabled is false or  ($.flowLogsSettings.retentionPolicy.days does not equal 0 and $.flowLogsSettings.retentionPolicy.days less than 90) ' 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.retentionPolicy.days does not equal 0 and flowLogsSettings.retentionPolicy.days less than 90) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Current Remediatin Steps*

To enable Flow Logs:

1. Log in to the Azure portal.
2. Select 'Network Watcher'.
3. Select 'NSG flow logs'.
4. Select the NSG for which you need to modify the flow log settings.
5. Set the Flow logs 'Status' to 'On'.
6. Select the destination 'Storage account'.
7. Set the 'Retention (days)' to 90 days or greater.
8. 'Save' your changes.

*Proposed Remediation Steps*

1. Log in to the Azure portal.
2. Search 'Network foundation'.
3. Under 'Virtual Network', Select 'Network security groups'
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under 'Monitoring', Select 'NSG flow logs'.
6. Click the flow log, and under 'Storage Account', Set the 'Retention days' to 90 days or greater.
7. 'Save' your changes.  

Use the command below to enable flow logs for Network security group via Azure CLI: 
----
az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --retention <Retention Days> --location <location>
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–*  Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.

|*Azure Network Watcher Network Security Group (NSG) flow logs are disabled*
//RLP-156741

|*Changes–* RQL updated with the latest CSP changes to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings does not exist or flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.storageId is not empty and flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Current Remediatin Steps*

To configure Network Watcher Network Security Group (NSG) flow log, follow below URL:
https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-portal#enable-nsg-flow-log

*Proposed Remediation Steps*

Follow the below steps to enable flow logs for Network security group via Azure Portal:

1. Log in to the Azure portal.
2. Search 'Network foundation'.
3. Under 'Virtual Network', Select 'Network security groups'
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under 'Monitoring', Select 'NSG flow logs'.
6. Select the flow log with Status 'Disabled', Click on 'Enable' at the top.
7. Confirm the flow log name and click 'Enable' at the bottom. 

Use the below command to enable flow logs for Network security group via Azure CLI:
----
az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --location <location>
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–*  Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.

|*GCP PostgreSQL instance database flag log_min_messages is not set to Warning or higher*
//RLP-156777

|*Changes–* Policy updated to no longer alert on GCP PostgreSQL instances where the log_min_messages database flag is not explicitly configured, as the default value of "warning".

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_messages')].value is not member of ( "warning", "error", "log", "fatal", "panic")
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_messages')].value exists and settings.databaseFlags[?(@.name=='log_min_messages')].value is not member of ( "warning", "error", "log", "fatal", "panic")
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. This update will resolve existing alerts on GCP PostgreSQL instances where the log_min_messages database flag was not explicitly configured.

|*GCP PostgreSQL instance database flag log_min_error_statement is not set to Error or higher*
//RLP-156779

|*Changes–* Policy updated to no longer alert on GCP PostgreSQL instances where the log_min_error_statement database flag is not explicitly configured, as the default value of "Error".

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_error_statement')].value is not member of ( "error" , "log", "fatal", "panic")
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_error_statement')].value exists and settings.databaseFlags[?(@.name=='log_min_error_statement')].value is not member of ( "error" , "log", "fatal", "panic")
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. This update will resolve existing alerts on GCP PostgreSQL instances where the log_min_error_statement database flag was not explicitly configured.


2+|*Policy Deletion*

|*Azure Policy Deletions*
//RLP-156560

|The policies below have been deleted due to the vendor update to the service:

* Azure Microsoft Defender for Cloud adaptive application controls monitoring is set to disabled (7363990f-b1fb-42c8-ad4a-fbb06de0310d)
* Azure Microsoft Defender for Cloud endpoint protection monitoring is set to disabled (5315a853-6a6b-43eb-a771-5906f41130b8)
* Azure Microsoft Defender for Cloud security configurations monitoring is set to disabled (19f4c5f1-1785-41b6-95be-2a393f537dad)

*Impact*: All alerts will be resolved as Policy Deleted.

|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*Google AI Applications*
//RLP-156754

|*gcloud-ai-applications-cmek-config*

Additional permissions required:

* `discoveryengine.cmekConfigs.list`

The Viewer role includes the permission.


|===


[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[*Asset Trendline and Compliance APIs*]
//PCS-4515, PCS-4556

It is recommended that you start using the Asset Inventory and Compliance Summary APIs once they're available since they provide the latest snapshot of data. The Asset Trendline and Compliance APIs listed have been deprecated. They will remain accessible until 25.9.1, ensuring you get ample time for a smooth transition to use the Asset Inventory and Compliance Summary APIs to get the latest state.

//new apis - still lga? - https://docs.prismacloud.io/en/enterprise-edition/assets/pdf/asset-inventory-compliance-api-documentation.pdf

*Asset Trendline*

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/

*Compliance*

* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/


|25.4.1

|25.9.1

|Will be provided in an upcoming release.

|tt:[*Audit Logs API*]
//RLP-151119

Starting from November 2024, you must transition to the new Audit Logs API. Prisma Cloud will provide a migration period of six months after which the https://pan.dev/prisma-cloud/api/cspm/rl-audit-logs/[current API] will be deprecated.

Once the deprecation period is over, you will have access to only the new API with pagination and filter support.

|24.11.1

|25.6.1

|https://pan.dev/prisma-cloud/api/cspm/get-audit-logs/[POST /audit/api/v1/log]


|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823, Abinaya - They are not planning to sunset the APIs anytime soon and they want the sunset column to be left blank.

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|NA

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*Asset Explorer APIs*]
//RLP-139337
|24.8.1
|NA

|The `accountGroup` response parameter was introduced in error and is now deprecated for Get Asset - https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[GET - uai/v1/asset] API endpoint.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA

|===