== Look Ahead—Planned Updates to Secure the Runtime

//Review changes planned in the next Prisma Cloud release to ensure the security of your runtime.

//(Edited in the month of Feb 20 as per Manu's suggestion)There are no previews or look ahead announcements for the upcoming `32.03` release. Details on the updates included in the `32.03` release will be shared in the release notes that accompany the release.

//The following text is a simplification of the earlier notes
The following sections preview the updates planned for the upcoming `v33.01` release of Prisma Cloud to ensure your runtime security:

* <<enhancements>>
* <<addressed-issues>>

// * <<defender-upgrade>>
// * <<new-ips-for-runtime>>
// //* <<announcement>>
// * <<upcoming-major-change>>
// * <<api-changes>>
// * <<deprecation-notices>>
// * <<eos-notices>>


*NOTE*: 

* Both the updates and the actual release date are subject to change.

* The Look Ahead announcements are for an upcoming release and are not a cumulative list of all announcements.




// // [#new-ips-for-runtime]
// // === New IPs for Runtime Security


// //[cols="40%a,30%a,30%a"]
// //|===

// //|===


//[#announcement]
//=== Announcements

// [#upcoming-major-change]

[#enhancements]
=== Enhancements

The following enhancements are planned. The details will be available at release:

[cols="30%a,70%a"]
|===
//CWP-61917
|*Intelligence Stream Versioning*
|The upcoming release will introduce versioning for Intelligence Stream (IS) to ensure compatibility with older versions of Defenders and self-hosted Consoles.

This update aims to minimize disruptions caused by changes in external feed formats that are not supported by older Defender versions, such as updates to certain fields in the downloaded JSON files that could affect CVE accuracy or cause duplicate CVEs.

IS versioning ensures that Consoles and Defenders continue to operate, even if they cannot support newer Intelligence feeds.

To maintain consistency in vulnerability reporting, the upcoming release of Prisma Cloud will align IS releases to Console versions. This will ensure that changes in IS behavior (due to changes in Intelligence Stream logic or algorithms) do not affect vulnerability metrics and reporting in the Console.

All versions of the IS will have up-to-date vulnerability information and will consume the latest data, but changes in the IS logic will be deployed to the newer versions of IS.


To summarize:

* Prisma Cloud Enterprise Edition (SaaS) customers always have the latest version of Console, and will not be affected by this change.
* Prisma Cloud Compute Edition (self-hosted) customers, who choose not to upgrade and continue using earlier versions of the Consoles and Defenders, will continue to receive up-to-date vulnerability information supported by their running version. Support for the latest IS changes will be added after customers upgrade to the latest version of the Console.

The following mappings show the corresponding Intelligence Stream (IS) version for each self-hosted Console version: 

- Console 33.01 → *IS version 33.01*
- Console 33.00 → *IS version 33.00*
- Console 32.xx → *IS version 33.00*
- Console 31.xx → *IS version 33.00*

//CWP-61840
|*Support for Podman*

|Previously, Prisma Cloud supported scanning Podman images in the CI pipeline using `twistcli`. In the upcoming release, it will also allow deploying Defenders on Podman containers, offering complete visibility and protection for workloads in Podman environments.

This enhancement will enable full protection for Podman containers, including continuous vulnerability monitoring, compliance policy enforcement, and active runtime security monitoring.


//CWP-32911
|*Scanning Support for Red Hat UBI Micro-Images*

|In the upcoming release, Prisma Cloud will introduce support for scanning of Red Hat UBI micro-images (versions 7, 8, and 9). 


|===

// [#deprecation-notices]
// === Deprecation Notices
// [cols="30%a,70%a"]
// |===

// |===

// [#api-changes]
// === API Changes

// [cols="30%a,70%a"]
// |===
// |*Change*
// |*Description*

// |===

[#addressed-issues]
=== Addressed Issues

[cols="30%a,70%a"]

|===
//CWP-59654
|*Support for Amazon Linux CVEs*
|In the upcoming release, Prisma Cloud will resolve prior instances of false positive vulnerabilities reported for Amazon Linux CVEs that were marked as "not affected" by Amazon. 

The supported Amazon Linux distributions include Amazon Linux, Amazon Linux 2, and Amazon Linux 2023.

//CWP-58952
|*Improved Vulnerability Detection for Multiple Python Versions*

|In the upcoming release, Prisma Cloud will resolve issues where vulnerabilities were detected only for a single Python installation, resulting in False Negatives (FN) for other installed versions.

With the latest Defender version, Prisma Cloud will now scan and report vulnerabilities for all the installed Python versions.
|===

// |===

// [#eos-notices]
// === End of Support Notices
// |===

// |===


