== Look Ahead—Planned Updates to Secure the Infrastructure

Here are the changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 25.7.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and is not a cumulative list of all announcements.

[NOTE]
====
The details and functionalities listed below are a preview and the actual release date is subject to change.
====

* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>

//There are currently no API ingestions or Policy Updates in the pipeline for 25.7.1.


[#new-policies] 
=== New Policies

To learn about the upcoming new Prisma Cloud policies and updates to existing Prisma Cloud policies, you need access to the *private* Prisma Cloud policies repository on GitHub. The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. 

Contact your Prisma Cloud representative, who will let you know the information required to get access to the repository. Once you receive access to the Prisma Cloud policies repository:

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has a monthly release, the release naming convention in GitHub is PCS-<year>.<month>.<1>. For example, PCS-25.7.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="40%a,60%a"]
|===
|*Policy Updates*
|*Description*


//2+|*Policy Updates—Metadata*

|*AWS Kinesis streams encryption using default KMS keys instead of Customer's Managed Master Keys*
//RLP-156182

|*Changes–* The policy RQL will be updated to include the resource using AWS managed key via alias.

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-kinesis-list-streams' as X; config from cloud.resource where api.name = 'aws-kms-get-key-rotation-status' as Y; filter '(($.Y.keyMetadata.keyManager equals AWS and $.Y.key.keyArn equals $.X.keyId) or $.X.keyId contains "alias/aws/") and $.X.encryptionType equals KMS'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* Low. New alerts will be created for the resource which is using aws key managed key via alias.



|*AWS S3 bucket encrypted using Customer Managed Key (CMK) with overly permissive policy*
//RLP-156319

|*Changes–* The policy will be updated to check for Actions and Effect in the KMS policy to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'aws' AND api.name= 'aws-s3api-get-bucket-acl' AND json.rule = (sseAlgorithm contains "aws:kms" or sseAlgorithm contains "aws:kms:dsse") and kmsMasterKeyID exists as X; config from cloud.resource where api.name = 'aws-kms-get-key-rotation-status' AND json.rule = keyMetadata.keyState equals Enabled and keyMetadata.keyManager equals CUSTOMER and policies.default.Statement[?any((Principal.AWS equals * or Principal equals *)and Condition does not exist)] exists as Y; filter '$.X.kmsMasterKeyID contains $.Y.key.keyArn' ; show X;
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'aws' AND api.name= 'aws-s3api-get-bucket-acl' AND json.rule = (sseAlgorithm contains "aws:kms" or sseAlgorithm contains "aws:kms:dsse") and kmsMasterKeyID exists as X; config from cloud.resource where api.name = 'aws-kms-get-key-rotation-status' AND json.rule = keyMetadata.keyState equals Enabled and keyMetadata.keyManager equals CUSTOMER and policies.default.Statement[?any(Effect equals Allow and (Principal.AWS equals * or Principal equals *) and Condition does not exist and (Action equals "*" or Action equal ignore case "kms:*"))] exists as Y; filter '$.X.kmsMasterKeyID contains $.Y.key.keyArn' ; show X;
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where Effect is not "Allow" and Action is specific will be resolved.


|*AWS Auto Scaling group launch configuration not configured with Instance Metadata Service v2 (IMDSv2)*
//RLP-156261

|*Changes–* The policy will be updated to exclude instance configurations created by the Elastic Beanstalk service where the IMDSv1 is deactivated.

*Current RQL–* 
----
config from cloud.resource where api.name = 'aws-ec2-autoscaling-launch-configuration' AND json.rule = (metadataOptions.httpEndpoint does not exist) or (metadataOptions.httpEndpoint equals "enabled" and metadataOptions.httpTokens equals "optional") as X; config from cloud.resource where api.name = 'aws-describe-auto-scaling-groups' as Y; filter ' $.X.launchConfigurationName equal ignore case $.Y.launchConfigurationName'; show X;
----

*Updated RQL–*
----
config from cloud.resource where api.name = 'aws-ec2-autoscaling-launch-configuration' AND json.rule = (launchConfigurationName does not start with "awseb" and launchConfigurationName does not contain "AWSEBAutoScalingLaunchConfiguration") and ((metadataOptions.httpEndpoint does not exist) or (metadataOptions.httpEndpoint equals "enabled" and metadataOptions.httpTokens equals "optional")) as X; config from cloud.resource where api.name = 'aws-describe-auto-scaling-groups' as Y; filter ' $.X.launchConfigurationName equal ignore case $.Y.launchConfigurationName'; show X;
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where the launch configurations were automatically created by Elastic Beanstalk where the IMDSv1 was deactivated, will be resolved.

|*AWS RDS instance without Automatic Backup setting*
//RLP-155976

|*Changes–* The policy RQL will be updated to exclude SQL Server (Enterprise edition) read replica as automatic backup can't be enabled for such instances.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-rds-describe-db-instances' AND json.rule = 'backupRetentionPeriod equals 0 or backupRetentionPeriod does not exist'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'aws' and api.name = 'aws-rds-describe-db-instances' AND json.rule = '(backupRetentionPeriod equals 0 or backupRetentionPeriod does not exist) and not(engine equal ignore case sqlserver-ee and statusInfos[*].statusType contains "read replication")'
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts for SQL Server (Enterprise edition) read replica will be resolved.


|*AWS EKS cluster does not have secrets encryption enabled*
//RLP-156100

|*Changes–* The policy will be updated to identify EKS clusters with versions lesser than 1.28 as per the latest CSP updates.

*Current Description–* 

This policy identifies AWS EKS clusters that do not have secrets encryption enabled.

AWS EKS cluster secrets are, by default, stored unencrypted in the API server's underlying data store (etcd). Anyone with direct access to etcd or with API access can retrieve or modify the secrets. Using secrets encryption for your Amazon EKS cluster allows you to protect sensitive information such as passwords and API keys using Kubernetes-native APIs.

It is recommended to enable secrets encryption to ensure its security and reduce the risk of unauthorized access or data breaches.

*Updated Description–*

This policy identifies AWS EKS clusters that do not have secrets encryption enabled. 

AWS EKS cluster secrets are, by default, stored unencrypted in the API server's underlying data store (etcd). Anyone with direct access to etcd or with API access can retrieve or modify the secrets. Using secrets encryption for your Amazon EKS cluster allows you to protect sensitive information such as passwords and API keys using Kubernetes-native APIs. 

It is recommended to enable secrets encryption to ensure its security and reduce the risk of unauthorized access or data breaches. 

NOTE: The policy identifies secret encryptions for EKS clusters with versions lesser than 1.28. 

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-eks-describe-cluster' AND json.rule = encryptionConfig does not exist or (encryptionConfig exists and encryptionConfig[*].provider.keyArn does not exist and encryptionConfig[*].resources[*] does not contain secrets)
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-eks-describe-cluster' AND json.rule = version is member of ( "1.25", "1.26", "1.27") and (encryptionConfig does not exist or (encryptionConfig exists and encryptionConfig[*].provider.keyArn does not exist and encryptionConfig[*].resources[*] does not contain secrets))
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts for EKS clusters with versions higher than 1.27 will be resolved. 



|*Azure SQL server public network access setting is enabled*
//RLP-156277

|*Changes–* The policy description and remediation steps will be updated to reflect the latest changes in Azure to ensure accurate remediation of flagged resources.

*Current Description–*

This policy identifies Azure SQL servers which have public network access setting enabled. Publicly accessible SQL servers are vulnerable to external threats with risk of unauthorized access or may remotely exploit any vulnerabilities. It is recommended to configure the SQL servers with IP-based strict server-level firewall rules or virtual-network rules or private endpoints so that servers are accessible only to restricted entities.

*Updated Description–*

This policy identifies Azure SQL servers which have public network access setting enabled. Publicly accessible SQL servers are vulnerable to external threats with risk of unauthorized access or may remotely exploit any vulnerabilities. It is recommended to disable public network access to the Azure SQL servers and use private endpoints or virtual network service endpoints to secure connectivity.

|*Azure SQL server using insecure TLS version*
//RLP-156262

|*Changes–* The policy RQL will be updated to eliminate the check for "NONE" since it now defaults to using version 1.2 or 1.3 in accordance with the latest CSP updates.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = ['sqlServer'].['properties.state'] equal ignore case "Ready" and (['sqlServer'].['properties.minimalTlsVersion'] equal ignore case "None" or ['sqlServer'].['properties.minimalTlsVersion'] equals "1.0" or ['sqlServer'].['properties.minimalTlsVersion'] equals "1.1")
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = ['sqlServer'].['properties.state'] equal ignore case "Ready" and (['sqlServer'].['properties.minimalTlsVersion'] equals "1.0" or ['sqlServer'].['properties.minimalTlsVersion'] equals "1.1")
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alerts where minimalTlsVersion is set to "NONE" will be resolved.


|*Azure Front Door Web application firewall (WAF) policy rule for Remote Command Execution is disabled*
//RLP-156263

|*Changes–* The policy name and description will be updated as per the CSP updates.

*Current Name–*

Azure Front Door Web application firewall (WAF) policy rule for Remote Command Execution is disabled

*Updated Name–*

Azure Front Door (Classic) Web application firewall (WAF) policy rule for Remote Command Execution is disabled

*Current Description–* 

This policy identifies Azure Front Door Web application firewall (WAF) policies that have the Remote Command Execution rule disabled. It is recommended to define the criteria in the WAF policy with the rule ‘Remote Command Execution (944240)’ under managed rules to help in detecting and mitigating Log4j vulnerability. 
For details see: 
https://www.microsoft.com/security/blog/2021/12/11/guidance-for-preventing-detecting-and-hunting-for-cve-2021-44228-log4j-2-exploitation/ 

*Updated Description–*

This policy identifies Azure Front Door (Classic) Web application firewall (WAF) policies that have the Remote Command Execution rule disabled. It is recommended to define the criteria in the WAF policy with the rule ‘Remote Command Execution (944240)’ under managed rules to help in detecting and mitigating Log4j vulnerability. 
For details see: 
https://www.microsoft.com/security/blog/2021/12/11/guidance-for-preventing-detecting-and-hunting-for-cve-2021-44228-log4j-2-exploitation/ 

*Impact–* None. This change will not affect the functionality of the policy. 

*Impact on Alerts–* None.


|*Azure Microsoft Defender for Cloud automatic provisioning of log Analytics agent for Azure VMs is set to Off*
//RLP-156201

|*Changes–* The policy will be deleted since Azure has deprecated the https://learn.microsoft.com/en-us/azure/defender-for-cloud/prepare-deprecation-log-analytics-mma-agent[Log Analytics] agent.

*Impact–* All alerts will be resolved as Policy Deleted.

|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|tt:[Update] *Amazon API Gateway*
//RLP-156118

|*aws-apigatewayv2-stage*

The API will be updated to ingest an additional `apidId` attribute.

No additional permissions are required.


|*Azure Container Apps*
//RLP-156126

|*azure-app-container-apps*

Additional permissions required:

* `microsoft.app/containerapps/read`
* `microsoft.app/containerapps/authconfigs/read`

The Reader role includes the permissions.


|*Azure Container Apps*
//RLP-156125

|*azure-app-container-apps-managed-environment*

Additional permission required:

* `Microsoft.app/managedenvironments/read`

The Reader role includes the permission.


|*Azure Fluid Relay*
//RLP-156123

|*azure-fluid-relay-server*

Additional permission required:

* `Microsoft.FluidRelay/fluidRelayServers/read`

The Reader role includes the permission.


|*Azure Web PubSub Service*
//RLP-156120

|*azure-signalrservice-web-pub-sub-diagnostic-settings*

Additional permissions required:

* `Microsoft.SignalRService/WebPubSub/read`
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions.


|*OCI IAM*
//RLP-155561

|*oci-iam-tag-default*

Additional permission required:

* `TAG_DEFAULT_INSPECT`

The Reader role includes the permission.

|===


[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[*Asset Trendline and Compliance APIs*]
//PCS-4515, PCS-4556

It is recommended that you start using the Asset Inventory and Compliance Summary APIs once they're available since they provide the latest snapshot of data. The Asset Trendline and Compliance APIs listed have been deprecated. They will remain accessible until 25.9.1, ensuring you get ample time for a smooth transition to use the Asset Inventory and Compliance Summary APIs to get the latest state.

//new apis - still lga? - https://docs.prismacloud.io/en/enterprise-edition/assets/pdf/asset-inventory-compliance-api-documentation.pdf

*Asset Trendline*

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/

*Compliance*

* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/


|25.4.1

|25.9.1

|Will be provided in an upcoming release.

|tt:[*Audit Logs API*]
//RLP-151119

Starting from November 2024, you must transition to the new Audit Logs API. Prisma Cloud will provide a migration period of six months after which the https://pan.dev/prisma-cloud/api/cspm/rl-audit-logs/[current API] will be deprecated.

Once the deprecation period is over, you will have access to only the new API with pagination and filter support.

|24.11.1

|25.6.1

|https://pan.dev/prisma-cloud/api/cspm/get-audit-logs/[POST /audit/api/v1/log]


|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823, Abinaya - They are not planning to sunset the APIs anytime soon and they want the sunset column to be left blank.

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|NA

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*Asset Explorer APIs*]
//RLP-139337
|24.8.1
|NA

|The `accountGroup` response parameter was introduced in error and is now deprecated for Get Asset - https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[GET - uai/v1/asset] API endpoint.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA

|===