== Look Ahead—Planned Updates to Secure the Runtime

The following sections provide a preview of the planned updates for the `v33.02` release of Runtime Security. 

*NOTE*: 

The details and functionality listed below provide a preview of what is planned for the `v33.02` release. Both the updates and the actual release date are subject to change.

*<<announcement>>

*<<enhancements>>

//* <<changes-in-existing-behavior>>
//* <<new-policies>>
//* <<policy-updates>>
//* <<iam-policy-update>>
//* <<new-compliance-benchmarks-and-updates>>
//* <<api-ingestions>>
//* <<deprecation-notices>>

=== Announcement
//CWP-61660
//CWP-62319
Prisma Cloud plans to use the following additional NAT IP addresses on the Google Cloud for the respective Prisma Cloud Enterprise Edition (SaaS) regions.

The following table lists the regions and the additional reserved Ingress IP addresses.

[cols="50%a,50%a"]
|===
| *Region* | *Additional Ingress IP Addresses*

|  us-east1 | * 34.23.229.147  
* 34.74.93.165
* 35.185.127.202
|  us-west1 | * 34.19.57.46  
* 34.83.186.93
* 34.168.3.165
| northamerica-northeast1 | * 34.118.176.160  
* 34.47.2.35
| europe-west9            | * 34.163.241.103  
* 34.163.12.56
| europe-west3            | * 35.198.174.6  
* 34.141.93.246
* 34.141.89.174
* 34.141.2.56
* 35.198.185.51
| europe-west2            | * 34.142.29.59  
* 34.89.33.47
| australia-southeast1    | * 34.116.88.189  
* 35.189.14.189
| asia-southeast1         | * 35.186.153.185  
* 34.87.100.14
| asia-south1             | * 34.93.124.157  
* 34.47.154.73
| asia-northeast1         | * 35.187.195.198  
* 34.85.99.145
|===
*NOTE*: 

No changes have been made at this time. These additional IP addresses will be activated with the upcoming release.


=== Enhancements
The following enhancements are planned. Detailed information will be available at release.

[cols="50%a,50%a"]
|===
| *Feature* | *Description*
//CWP-32911
|Scanning Support for Red Hat UBI Micro-images 

tt:[Pending approval]
 | In the upcoming release, Prisma Cloud will introduce support for scanning of Red Hat UBI micro-images (versions 7, 8, and 9). 
|Improved Vulnerability Detection for non-RPM OpenShift Packages 
//CWP-61504

tt:[Pending approval] | In the upcoming release, vulnerability reporting for OpenShift non-RPM container components will be enhanced to ensure consistent vulnerability matching across all OpenShift packages. This improvement will reduce false positives by applying only relevant CVEs and excluding CVEs that have already been patched.

//CWP-61508
|Improved Vulnerability Detection for Google Kubernetes Engine (GKE) Clusters 

tt:[Pending approval] | In the upcoming release, vulnerability detection for Google Kubernetes Engine (GKE) Clusters
will include the following enhancements:

* Integration with Google security bulletins

* Aligning CVEs with specific GKE cluster types and versions

* Expanded support for all GKE modes, including Autopilot

|===

