[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates to Secure the Infrastructure

Here are the changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 25.4.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and is not a cumulative list of all announcements.

[NOTE]
====
The details and functionalities listed below are a preview and the actual release date is subject to change.
====

//* <<announcement>>
//* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
//* <<new-compliance-benchmarks-and-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior

//[cols="50%a,50%a"]
//|===
//|*Feature*
//|*Description*

//|===


[#new-policies]
=== New Policies

//Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

To learn about the upcoming new Prisma Cloud policies and updates to existing Prisma Cloud policies, you need access to the *private* Prisma Cloud policies repository on GitHub. The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. 

Contact your Prisma Cloud representative, who will let you know the information required to get access to the repository. Once you receive access to the Prisma Cloud policies repository:

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has a monthly release, the release naming convention in GitHub is PCS-<year>.<month>.<1>. For example, PCS-25.4.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


//==== Access the Look Ahead for New Policies
//To learn about the new policies that will be added in the next release:

//. Find the Prisma Cloud policies folder on GitHub.
//+
//The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].



[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*AWS MFA is not enabled on Root account.*
//RLP-155483

|*Changes—* The Policy RQL will be updated to consider the Centralised root access introduced by AWS thereby reducing false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-iam-get-credential-report' AND json.rule = 'user equals "<root_account>" and mfa_active is false and arn does not contain gov:' 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-iam-get-credential-report' AND json.rule = 'user equals "<root_account>" and password_enabled is true and mfa_active is false and arn does not contain gov:' 
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where the centralised root access is enabled will be resolved.


|*Azure Function app configured with public network access*
//RLP-155139

|*Changes—* This policy will check for private endpoints with `publicnetworkaccess` and report accordingly.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind contains functionapp and kind does not contain workflowapp and kind does not equal app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist)) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind contains functionapp and kind does not contain workflowapp and kind does not equal app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist and (properties.privateLinkIdentifiers does not exist or properties.privateLinkIdentifiers is empty))) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where private link identifiers exists will be resolved.

|*Azure Microsoft Defender for Cloud email notification for subscription owner is not set*
//RLP-151399

|*Changes—* The Policy RQL will be updated to check for notifications configured for Owner role as per the latest CSP updates.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = (securityContacts is empty or securityContacts[*].properties.email is empty or securityContacts[*].properties.alertsToAdmins equal ignore case Off) and pricings[?any(properties.pricingTier equal ignore case Standard)] exists
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = (securityContacts is empty or securityContacts.properties.email is empty or securityContacts[*].properties.notificationsByRole.roles[*] does not contain "Owner") and pricings[?any(properties.pricingTier equal ignore case Standard)] exists
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* Low. New Alerts are generated if the Owner is not configured to receive email notifications. Open alerts for the security contact where the email is configured will be resolved.


|*Azure SQL server public network access setting is enabled*
//RLP-155660

|*Changes—* The Policy RQL will be updated to align with the latest changes and updates in Azure Cloud. This enhancement ensures improved compatibility and performance, providing users with the most up-to-date security and compliance checks specific to Azure Cloud environments.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = ['sqlServer'].['properties.state'] equal ignore case Ready and ['sqlServer'].['properties.publicNetworkAccess'] equal ignore case Enabled and ['sqlServer'].['properties.privateEndpointConnections'] is empty and firewallRules[*] is empty 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = ['sqlServer'].['properties.state'] equal ignore case Ready and ['sqlServer'].['properties.publicNetworkAccess'] equal ignore case Enabled and firewallRules[*] is not empty 
----

*Policy Type–* Config 

*Policy Severity–* Medium

//*Impact–* Low. New Alerts are generated if the Owner is not configured to receive email notifications. Open alerts for the security contact where the email is configured will be resolved.


|*Azure Microsoft Defender for Cloud email notification for subscription owner is not set*
//RLP-155399

|*Changes—* The Policy RQL will be updated to check for notifications configured for Owner role as per the latest CSP updates.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = (securityContacts is empty or securityContacts[*].properties.email is empty or securityContacts[*].properties.alertsToAdmins equal ignore case Off) and pricings[?any(properties.pricingTier equal ignore case Standard)] exists
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = (securityContacts is empty or securityContacts[*].properties.emails is empty or securityContacts[*].properties.notificationsByRole.roles[*] does not contain "Owner") and pricings[?any(properties.pricingTier equal ignore case Standard)] exists
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* Low. New Alerts will be generated in case the Owner is not configured to receive email notifications. Open alerts for the security contact where the email is configured would be resolved.


|*Azure Cosmos DB Virtual network is not configured*
//RLP-155550

|*Changes—* The Policy RQL will be updated to consider cosmos DB is configured with private access to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-cosmos-db' AND json.rule = properties.provisioningState equals Succeeded AND properties.publicNetworkAccess equal ignore case Enabled AND properties.virtualNetworkRules[*] is empty 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-cosmos-db' AND json.rule = properties.provisioningState equals Succeeded AND properties.publicNetworkAccess equal ignore case Enabled AND properties.virtualNetworkRules[*] is empty and properties.privateEndpointConnections does not exist
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open alert where private access is configured will be resolved.


|*Azure Network Watcher Network Security Group (NSG) flow logs are disabled*
//RLP-155573

|*Changes—* The Policy will be updated to exclude resources created by Prisma for agentless scans to reduce the noise.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = flowLogsSettings does not exist or flowLogsSettings.enabled is false  
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings does not exist or flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where the resource is created by "prismacloud-agentless-scan" will be resolved.


|*GCP SQL database instance deletion protection is disabled*
//RLP-155109

|*Changes—* The Policy RQL will be updated with the right attribute to raise alerts on the vulnerable resources only.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equals "RUNNABLE" and deletionProtectionEnabled is false 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equals "RUNNABLE" and settings.deletionProtectionEnabled is false
----

*Policy Type–* Config

*Policy Severity–* Informational

*Impact–* Low. Open Alerts where the deletion protection setting is enabled will be resolved.


|*GCP Vertex AI Workbench Instance has vTPM disabled*
//RLP-155647

|*Changes—* The Policy RQL will be updated to account for CSP side API changes.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND shieldedInstanceConfig.enableVtpm is false 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND gceSetup.shieldedInstanceConfig.enableVtpm is false 
----

*Policy Type–* Config

*Policy Severity–* Low

*Impact–* Low. New alerts will be generated as per the new RQL.


|*GCP Vertex AI Workbench Instance has Integrity monitoring disabled*
//RLP-155649

|*Changes—* The Policy RQL will be updated to account for CSP side API changes.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND shieldedInstanceConfig.enableIntegrityMonitoring is false
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND gceSetup.shieldedInstanceConfig.enableIntegrityMonitoring is false
----

*Policy Type–* Config

*Policy Severity–* Low

*Impact–* Low. New alerts will be generated as per the new RQL.


|*GCP Vertex AI Workbench Instance has Secure Boot disabled*
//RLP-155653

|*Changes—* The Policy RQL will be updated to account for CSP side API changes.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND shieldedInstanceConfig.enableSecureBoot is false
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-vertex-ai-workbench-instance' AND json.rule = state equals "ACTIVE" AND gceSetup.shieldedInstanceConfig.enableSecureBoot is false
----

*Policy Type–* Config

*Policy Severity–* Low

*Impact–* Low. New alerts will be generated as per the new RQL.



// 2+|*Policy Updates - Metadata*

// |**
//RLP-

// |*Changes—* The recommendation steps are updated.

|===

//[#new-compliance-benchmarks-and-updates]
//=== New Compliance Benchmarks and Updates

//[cols="50%a,50%a"]
//|===
//|*Compliance Benchmark*
//|*Description*



//|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*AWS AppFabric*
//RLP-155340
|*aws-appfabric-app-authorization*

Additional permissions needed:

* `appfabric:ListAppBundles`
* `appfabric:ListAppAuthorizations`
* `appfabric:GetAppAuthorization`
* `appfabric:ListTagsForResource`

The Security audit role does not include the permissions.

|*AWS AppFabric*
//RLP-155341
|*aws-appfabric-app-bundle*

Additional permissions needed:

* `appfabric:ListAppBundles`
* `appfabric:GetAppBundle`
* `appfabric:ListTagsForResource`

The Security audit role does not include the permissions.

|*Amazon Detective*
//RLP-155563
|*aws-detective-member*

Additional permissions needed:

* `detective:ListGraphs`
* `detective:ListMembers`
* `detective:GetMembers`

The Security audit role includes the permissions for `detective:ListGraphs` and `detective:ListMembers`. `detective:GetMembers` is not present in the Security audit role.

|*Amazon Keyspaces*
//RLP-155321
|*aws-keyspaces-table*

Additional permissions needed:

* `cassandra:Select`

The Security audit role does not include the permission.

|*Amazon Lex*
//RLP-155564
|*aws-lexv2-slots*

Additional permissions needed:

* `lex:GetBots`
* `lex:ListBotLocales`
* `lex:ListIntents`
* `lex:ListSlots`

The Security audit role does not include the permissions.

|*AWS Organizations*
//RLP-154816
|*aws-organizations-delegated-services-for-account*

Additional permissions needed:

* `organizations:ListDelegatedServicesForAccount`

The Security audit role includes the permission.

|*AWS Organizations*
//RLP-155332
|*aws-organizations-aws-service-access-for-organization*

Additional permissions needed:

* `organizations:ListAWSServiceAccessForOrganization`

The Security audit role includes the permission.

|*AWS Organizations*
//RLP-155328
|*aws-organizations-delegated-services-for-account*

Additional permissions needed:

* `organizations:ListDelegatedServicesForAccount`

The Security audit role includes the permission.

|*Amazon QuickSight*
//RLP-152590
|*aws-quicksight-iam-policy-assignment*

Additional permissions needed:

* `quicksight:DescribeIAMPolicyAssignment`
* `quicksight:ListNamespaces`
* `quicksight:ListIAMPolicyAssignments`

The Security audit role does not include the permissions.

|*Azure API Management Services*
//RLP-155531
|*azure-api-management-service-cache*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read` 
* `Microsoft.ApiManagement/service/caches/read`

The Reader role includes the permissions.

|*Azure API Management Services*
//RLP-155532
|*azure-api-management-service-private-endpoint-connection*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read` 
* `Microsoft.ApiManagement/service/privateEndpointConnections/read`

The Reader role includes the permissions.

|*Azure App Service*
//RLP-155533
|*azure-app-service-certificate-order*

Additional permissions needed:

* `Microsoft.CertificateRegistration/certificateOrders/Read` 

The Reader role includes the permission.

|*Azure Arc*
//RLP-155534
|*azure-app-service-certificate-order*

Additional permissions needed:

* `Microsoft.HybridCompute/licenses/read` 

The Reader role includes the permission.

|*Azure Arc*
//RLP-155535
|*azure-arc-private-link-scope*

Additional permissions needed:

* `Microsoft.HybridCompute/privateLinkScopes/read` 

The Reader role includes the permission.

|*Azure Arc*
//RLP-155537
|*azure-arc-machine*

Additional permissions needed:

* `Microsoft.HybridCompute/machines/read` 

The Reader role includes the permission.

|*Azure Arc*
//RLP-155538
|*azure-arc-machine-license-profile*

Additional permissions needed:

* `Microsoft.HybridCompute/machines/read`
* `Microsoft.HybridCompute/machines/licenseProfiles/read` 

The Reader role includes the permissions.

|*Azure Event Grid*
//RLP-155021
|*azure-event-grid-domain-event-subscription*

Additional permissions needed:

* `Microsoft.EventGrid/domains/read`
* `Microsoft.EventGrid/domains/eventSubscriptions/read`

The Reader role includes the permissions.

|*Azure Event Grid*
//RLP-155044
|*azure-event-grid-topic-event-subscription*

Additional permissions needed:

* `Microsoft.EventGrid/topics/read`
* `Microsoft.EventGrid/topics/eventSubscriptions/read`

The Reader role includes the permissions.

|*Azure Log Analytics*
//RLP-155560
|*azure-log-analytics-data-exports*

Additional permissions needed:

* `Microsoft.OperationalInsights/workspaces/read`
* `Microsoft.OperationalInsights/workspaces/dataexports/read`

The Reader role includes the permissions.

|*Google Backup and DR*
//RLP-155293
|*gcloud-backup-dr-backup-plan*

Additional permissions needed:

* `backupdr.backupPlans.list`

The Viewer role includes the permission.

|*Google Backup and DR*
//RLP-155294
|*gcloud-backup-dr-backup-plan-association*

Additional permissions needed:

* `backupdr.backupPlanAssociations.list`

The Viewer role includes the permission.

|*Google Backup and DR*
//RLP-155295
|*gcloud-backup-dr-backup-vault*

Additional permissions needed:

* `backupdr.backupVaults.list`

The Viewer role includes the permission.

|*Google Backup and DR*
//RLP-155298
|*gcloud-backup-dr-backup-vault-data-source*

Additional permissions needed:

* `backupdr.backupVaults.list`
* `backupdr.bvdataSources.list`

The Viewer role includes the permissions.

|*Google Backup and DR*
//RLP-155299
|*gcloud-backup-dr-backup-vault-data-source-backup*

Additional permissions needed:

* `backupdr.backupVaults.list`
* `backupdr.bvdataSources.list`
* `backupdr.bvbackups.list`

The Viewer role includes the permissions.

|*OCI IAM Password Policy*
//RLP-155562
|*oci-iam-password-policy*

Additional permissions needed:

* `COMPARTMENT_INSPECT`
* `DOMAIN_INSPECT`
* `PASSWORD_POLICY_INSPECT`

The Reader role includes the permissions.

|*OCI IAM*
//RLP-155561
|*oci-iam-tag-default*

Additional permissions needed:

* `TAG_DEFAULT_INSPECT`

The Reader role includes the permission.

|*OCI IAM*
//RLP-155547
|*oci-iam-user-db-credential*

Additional permissions needed:

* `USER_INSPECT`
* `DB_CREDENTIAL_INSPECT`

The Reader role includes the permissions.


|===


[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[*Asset Trendline and Compliance APIs*]
//PCS-4515, PCS-4556

It is recommended that you start using the Asset Inventory and Compliance Summary APIs once they're available since they provide the latest snapshot of data. The Asset Trendline and Compliance APIs listed below will be marked for deprecation by 25.4.1. They will remain accessible until 25.9.1, ensuring you get ample time for a smooth transition to use the Asset Inventory and Compliance Summary APIs to get the latest state.

//new apis - still lga - https://docs.prismacloud.io/en/enterprise-edition/assets/pdf/asset-inventory-compliance-api-documentation.pdf

*Asset Trendline*

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/

*Compliance*

* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/


|25.4.1

|25.9.1

|Will be provided in an upcoming release.

|tt:[*Audit Logs API*]
//RLP-151119

Starting from November 2024, you must transition to the new Audit Logs API. Prisma Cloud will provide a migration period of six months after which the https://pan.dev/prisma-cloud/api/cspm/rl-audit-logs/[current API] will be deprecated.

Once the deprecation period is over, you will have access to only the new API with pagination and filter support.

|24.11.1

|25.5.1

|https://pan.dev/prisma-cloud/api/cspm/get-audit-logs/[POST /audit/api/v1/log]



|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823, Abinaya - They are not planning to sunset the APIs anytime soon and they want the sunset column to be left blank.

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|NA

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*Asset Explorer APIs*]
//RLP-139337
|24.8.1
|NA

|The `accountGroup` response parameter was introduced in error and is now deprecated for Get Asset - https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[GET - uai/v1/asset] API endpoint.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA

//tt:[*Change to Compliance Trendline and Deprecation of Compliance Filters*]
//RLP-126719, need to check if this notice can be moved to current features in 24.1.2
//- 
//- 
//To provide better performance, the *Compliance trendline* will start displaying data only from the past one year. Prisma Cloud will not retain the snapshots of data older than one year.
//The Compliance-related filters (*Compliance Requirement, Compliance Standard, and Compliance Section*) will not be available on Asset Inventory (*Inventory > Assets*).

|===