[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates to Secure the Infrastructure

Review any changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 24.5.1 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and it is not a cumulative list of all announcements.

[NOTE]
====
The details and functionality listed below are a preview and the actual release date is subject to change.
====

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|*Feature*
|*Description*

|*Login Experience Enhancements*
//RLP-135039

|Starting with the 24.5.1 release, users can expect a change in their login experience on the Prisma Cloud console. Updates to the Prisma Cloud login pages will provide support for all available authentication options (excluding IdP-initiated SAML SSO). This update also addresses an issue related to redirection to Palo Alto Networks SSO for login and addresses a bug preventing traversal of deep links for some users.

*Impact*— The SSO Login Page will be updated to more clearly identify OIDC SSO login and add support for Palo Alto Networks SSO login. Redirection to Palo Alto Networks SSO will no longer occur when accessing Prisma Cloud links without a valid session. Deep links will be supported in cases in which previously they were not persisted through login flows.

|*API Rate Limits*
//RLP-129569

|Prisma Cloud uses API https://pan.dev/prisma-cloud/api/cspm/rate-limits/[rate limits] at the endpoint level to protect the performance and availability of its services. Rate limits will be applied to additional APIs starting from the 24.5.2 release. Details of these rate limits will be made available in the supporting API documentation and Look Ahead Notices when these limits are introduced. 

|*Alert Info API*
//RLP-134888

|The Alert Info https://pan.dev/prisma-cloud/api/cspm/get-alert/[GET alert/:id] response will include a new field `connectionDetails` in release 24.5.2.

|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-24.5.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.

[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

|*AWS Application Load Balancer (ALB) is not using the latest predefined security policy*
//RLP-136748

|*Changes*— Use either non-FIPS security policy `ELBSecurityPolicy-TLS13-1-2-2021-06` or FIPS security policy `ELBSecurityPolicy-TLS13-1-2-FIPS-2023-04` to meet compliance and security standards that require disabling certain TLS protocol versions or to support legacy clients that require deprecated ciphers.

*Severity*— Low

*Policy Type*— Config

*Current RQL*— 
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-elbv2-describe-load-balancers' AND json.rule = type equals application and listeners[?any(protocol equals HTTPS and sslPolicy exists and (sslPolicy does not contain ELBSecurityPolicy-TLS13-1-2-2021-06))] exists
----

*Proposed RQL*— 
----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-elbv2-describe-load-balancers' AND json.rule = type equals application and listeners[?any(protocol equals HTTPS and sslPolicy exists and sslPolicy is not member of ('ELBSecurityPolicy-TLS13-1-2-2021-06','ELBSecurityPolicy-TLS13-1-2-FIPS-2023-04'))] exists
----

*Impact*: Low

|*Azure Microsoft Defender for Cloud set to Off for DNS*
//RLP-137209

|*Changes*— The policy RQL will be updated to check if the legacy DNS plan is deprecated.

*Severity*— Low

*Policy Type*— Config

*Current RQL*— 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = pricings[?any(name equals VirtualMachines and properties.pricingTier equal ignore case Standard and properties.subPlan equal ignore case P2)] does not exist or pricings[?any(name equals Dns and properties.pricingTier does not equal Standard)] exists
----

*Proposed RQL*— 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-security-center-settings' AND json.rule = pricings[?any(name equals VirtualMachines and properties.pricingTier equal ignore case Standard and properties.subPlan equal ignore case P2)] does not exist or pricings[?any(name equals Dns and properties.deprecated is false and properties.pricingTier does not equal Standard)] exists
----

*Impact*: Low

|===

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*AWS Network Manager*
//RLP-137198 

|*aws-network-manager-ipam*

Additional permission required:

* `ec2:DescribeIpams`

The Security Audit role includes the permission.

|*AWS Network Manager*
//RLP-137195 

|*aws-network-manager-global-network*

Additional permission required:

* `networkmanager:DescribeGlobalNetworks`

The Security Audit role includes the permission.

|*AWS Network Manager*
//RLP-137185 

|*aws-network-manager-core-network*

Additional permission required:

* `networkmanager:GetCoreNetwork`

The Security Audit role does not include the permission. You will need to add a new role/create a custom role for the permission. 

|*Amazon SNS*
//RLP-131263

|*aws-sns-data-protection-policy*

Additional permissions required:

* `sns:ListTopics`
* `sns:GetDataProtectionPolicy`

The Security Audit role includes the `sns:ListTopics` permission.
You must manually add the `sns:GetDataProtectionPolicy` permission to the CFT template to enable it.

|*Amazon FSx*
//RLP-127615

|*aws-fsx-backup*

Additional permission required:

* `fsx:DescribeBackups`

The Security Audit role includes the permission. 

|*Google Vertex AI Platform*
//RLP-136571

|*gcloud-vertex-ai-aiplatform-notebook-runtime*

Additional permission required:

* `aiplatform.notebookRuntimes.list`

The Viewer role includes the permission. 

|*Google Workspace*
//RLP-135384

|*gcloud-domain-user-last-login-time*

No additional permissions are required.

|*Google Cloud VMware Engine*
//RLP-135383

|*gcloud-vmware-engine-external-address*

Additional permissions required:

* `vmwareengine.locations.list`
* `vmwareengine.privateClouds.list`
* `vmwareengine.externalAddresses.list`

The Viewer role includes the permission.

|*Google Vertex AI Platform*
//RLP-135381

|*gcloud-vertex-ai-aiplatform-feature-online-store*

Additional permission required:

* `aiplatform.featureOnlineStores.list`

The Viewer role includes the permission.

|*Google Vertex AI Platform*
//RLP-135380

|*gcloud-vertex-ai-aiplatform-feature-group*

Additional permission required:

* `aiplatform.featureGroups.list`

The Viewer role includes the permission.

|*Google Cloud Support*
//RLP-131425

|*gcloud-cloud-support-case*

Additional permission required:

* `cloudsupport.techCases.list`

The Viewer role includes the permission.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|*End of support for Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services*

//RLP-134902

|NA
|24.4.2
|The following APIs are planned for deprecation at the end of April 2024 because Azure has announced the retirement of Azure Data Lake Analytics and Azure Data Lake Storage Gen1 Services. Due to this, Prisma Cloud will no longer ingest metadata for the following APIs:

* azure-data-lake-analytics-account
* azure-data-lake-analytics-diagnostic-settings
* azure-data-lake-store-gen1-account
* azure-data-lake-store-gen1-diagnostic-settings

In RQL, the key will not available in the `api.name` attribute auto-completion.

*Impact—* If you have a saved search or custom policies based on this API, you must delete them manually. The policy alerts will be resolved as Policy_Deleted.

|tt:[*Resource Explorer API*]

//RLP-131482

* https://pan.dev/prisma-cloud/api/cspm/get-resource/[GET/resource]
* https://pan.dev/prisma-cloud/api/cspm/get-timeline-for-resource/[POST /resource/timeline]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-raw/[POST /resource/raw]

|23.9.2
|24.6.2
|* https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[POST /uai/v1/asset]


|tt:[*Change to Compliance Trendline and Deprecation of Compliance Filters*]
//RLP-126719, need to check if this notice can be moved to current features in 24.1.2
| - 
| - 
|To provide better performance, the *Compliance trendline* will start displaying data only from the past one year. Prisma Cloud will not retain the snapshots of data older than one year.
The Compliance-related filters (*Compliance Requirement, Compliance Standard, and Compliance Section*) will not be available on Asset Inventory (*Inventory > Assets*).

|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA


|===