[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates to Secure the Infrastructure

Review any changes planned in the next Prisma Cloud release to ensure the security of your infrastructure.

Read this section to learn about what is planned in the 24.7.3 CSPM Platform, Agentless Container Host, Agentless Host Security, CIEM, Data Security, and CDEM releases. 

The Look Ahead announcements are for an upcoming release and it is not a cumulative list of all announcements.

[NOTE]
====
The details and functionality listed below are a preview and the actual release date is subject to change.
====

* <<changes-in-existing-behavior>>
* <<new-policies>>
//* <<policy-updates>>
* <<iam-policy-updates>>
* <<api-ingestions>>
* <<new-compliance-benchmarks-and-updates>>
//* <<rest-api-updates>>
* <<deprecation-notices>>

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|*Feature*
|*Description*


|*Role-Based Access Control for Compliance and Alert Reports*
//RLP-140182

|Starting with the 24.8.1 release, user-generated reports will only be visible to System Administrators and to users with the same role.

Implementing Role-Based Access Control (RBAC) enhances data security by streamlining report access for users with the same role, while also preventing unauthorized access.

|*Create or Update Policy Permissions*
//RLP-139027

|Starting with the 8.1 release, Create/Update Policy Permissions will be divided into the two granular permissions below:

* Policy
* Manage Policy Compliance Mapping

*Impact—* 

* Starting with the 8.1 release release, users managing new custom permission groups will have to select both permissions explicitly if they want to assign compliance mappings during policy create/update operation.
* Manage policy compliance mapping will be added by default to all existing permission groups with policy create/update permissions.

|*Change in Amazon EC2 Ingestion*
//RLP-145171

|Starting with the 24.9.1 release, Prisma Cloud will no longer ingest private Amazon Machine Images (AMIs) owned by other accounts unless they are actively used by EC2 instances within the current account.

*Impact—* No impact on out-of-the-box (OOTB) policies. However, if you have custom policies, you must manually update them to check for private AMIs not owned by the same account and not currently deployed.

If you have any questions, contact your Prisma Cloud Customer Success Representative.



|===

[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, IAM, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-24.7.3.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


//[#policy-updates]
//=== Policy Updates

//There are no policy updates planned for 24.7.3 release.

//[cols="50%a,50%a"]
//|===

//|*Policies*
//|*Description*

//|===

[#iam-policy-updates]
=== IAM Policy Updates

The following IAM OOTB policies will be updated in 24.7.3 release.

[cols="50%a,50%a"]
|===
|*Policies*
|*Description*

|*AWS Users and Machine Identities with Excessive Policies*
//RLP-145657

|*Changes—* The policy RQL will be updated to narrow down the resource based policies and remove false positives.

*Severity—* High

*Cloud—* AWS

*Updated RQL—*

----
config from iam where source.cloud.type = 'AWS' and grantedby.cloud.policy.isexcessive = true and source.cloud.resource.type IN ('user', 'instance', 'function')
----

|*Roles with high privileges can be assumed by a service in an external account*
//RLP-145373

|*Changes—* This policy descrption and recommendation steps will be updated to better match the policy.

*Severity—* High

*Cloud—* AWS

*Updated Description—*
	
Identifies roles which have administrative permissions and can be assumed by an identity in an "external account". An external account is one not known to Prisma cloud as part of your organization and not that of a known vendor. This policy relies on the default account group, therefore if the group is changed this policy will not reflect the environment entirely. The default account group is created upon onboarding to Prisma Cloud, and contains all instance-related accounts known to Prisma Cloud. External accounts are considered as such if Prisma are unaware of them in the context of your environment (i.e not part of the onboarded accounts). As we do not have visibility or control over the external entity, giving it the ability to gain administartive permissions in the environment is considered high risk.

*Recommendation Steps—*

How to investigate?

1. In the Prisma Cloud Console, select 'Investigate'
2. Paste the following query into the investigation prompt, replacing the placeholder with the account ID you wish to verify: config from iam where dest.cloud.type = 'AWS' AND source.cloud.account='<account-id>' and dest.cloud.account='<account-id>'

3a. If results are returned, this is an indicator that Prisma is scanning the account, and as such is aware of it
If this is the case, select 'settings' and then 'Account Groups'
Search for the default account group, under 'Actions' select 'Edit'. Search for the account in question and add it

3b. If no results are returned, this means Prisma has no knowledge of the account in question (i.e it is not onboarded and in the eyes of Prisma, external)

In order to continue the investigation, using the AWS CLI, run 'aws organizations list-accounts', and you will recieve a list of all the accounts within the AWS organization
Repeat this process for every AWS organization you own. If the account in question does not appear, it can be concluded as external

In order to remove its access, use the following remediation steps:

Log in to your AWS account
Navigate to the affected role, and select the 'Trusted entities' tab.
Select 'Edit trust policy' and remove the entries allowing assumption from external sources.
Ensure the remaining entries are required, and save your changes.


|*AWS Role With Administrative Permissions Can Be Assumed By All Users*
//RLP-145656

|*Changes—* This policy will be updated include recommendation steps on how to investigate and remediate isAdmin policies.

*Severity—* High

*Cloud—* AWS

*Recommendation Steps—*

How to investigate?

1. In the Prisma Cloud Console, under the "Alerts" tab, take note of the "Asset Name". Then select the "Alert ID", then "Investigate"
2. In the results, you will see the policy granting the administrative permissions to the role ("Granted By Policy"), and the specific administrative permissions ("Destination")
3. Sign in to the AWS Console
4. Navigate to the affected role\n5. Examine the role's trust relationship and permissions as well as its use case

In order to remove any administrative permissions and minimize trusted entities which can assume the role, use the following remediation steps:

Browse to the role in the AWS Console and select "Trust relationships"->"Edit trust policy". Modify the role's trust relationship as per requirements. Under the "Permissions" tab, select the relevant policy and remove unnecessary administrative permissions by either editing the policy or replacing it (notice: editing a managed policy could affect other roles).

|*GCP Cloud Run with administrative permissions*
//RLP-145656

|*Changes—* This policy will be updated include recommendation steps on how to investigate and remediate isAdmin policies.

*Severity—* Medium

*Cloud—* GCP

*Recommendation Steps—*

How to investigate?

1. In the Prisma Cloud Console, under the "Alerts" tab, select the "Asset Name", the "View JSON{}"
2. Scroll down to the "data" field, and under "spec/template/spec" make note of the service account listed
3. Still in the Prisma Cloud Console, select 'Investigate'\n2. Paste the following query into the investigation prompt, replacing the placeholder with the name of the service account you obtained in the previous steps: config from iam where dest.cloud.type = 'GCP' AND grantedby.cloud.entity.name ='<service account name>'
4. In the results, under "Granted By Policy", you will see the policies attached to the service account

Once examining the policies and determining which permissions are unnecessary and can be removed based on the Cloud Run instance's intended use, sign in to your GCP account. In order to remove any unnecessary permissions , use the following remediation steps:

Navigate to the IAM service, and search for the Service account. Select the pencil icon to edit it's permissions, removing the relevant policy for a less privileged one sufficient for the account intended purpose.

|*User account with excessive admin privileges*
//RLP-145656

|*Changes—* This policy will be updated include recommendation steps on how to investigate and remediate isAdmin policies.

*Severity—* Medium

*Cloud—* All

*Recommendation Steps—*

How to investigate?

1. In the Prisma Cloud Console, under the "Alerts" tab, take note of the "Asset Name". Then select the "Alert ID", then "Investigate"
2. In the results, you will see the policy granting unused administrative permissions to the user ("Granted By Policy"), the specific unused permissions ("Destination"), and the last recorded event when the permissions were used by the user ("Last Access"). Prisma Cloud's event tracking period begins upon onboarding. As such, depending on the onboarding date, further investigation may be required using the cloud provider logs to determine last access

Once examining the permissions and determining which permissions are unnecessary and can be removed based on their last usage, in order to remove them, use the following remediation steps:

Log in to your Cloud instance, navigate to the affected user, and edit the user's permissions following the principle of least privilege and based on the information collected.

|*Cloud service account with excessive admin privileges*
//RLP-145656

|*Changes—* This policy will be updated include recommendation steps on how to investigate and remediate isAdmin policies.

*Severity—* Medium

*Cloud—* All

*Recommendation Steps—*

How to investigate?

1. In the Prisma Cloud Console, under the "Alerts" tab, select "Asset Name" and take note of the "Name" and "Asset Type", then exit the tab. Select the "Alert ID", then "Investigate"
2. In the results, you will see the service account attached to the asset ("Granted By Entity"), the policy granting unused administrative permissions to the service account ("Granted By Policy"), the specific unused permissions ("Destination"), and the last recorded event when the permissions were used by the user ("Last Access"). Prisma Cloud's event tracking period begins upon onboarding. As such, depending on the onboarding date, further investigation may be required using the cloud provider logs to determine last access

Once examining the permissions and determining which permissions are unnecessary and can be removed based on their last usage, in order to remove them, use the following remediation steps:

Log in to your Cloud instance, and navigate to the affected service account, and edit the entity's permissions following the principle of least privilege and based on the information collected.

|*Third-party service account can assume a service account with high privileges*
//RLP-145656

|*Changes—* This policy will be updated include recommendation steps on how to investigate and remediate isAdmin policies.

*Severity—* High

*Cloud—* AWS

*Recommendation Steps—*

How to investigate?

1. Sign in to the AWS Console
2. Navigate to the affected role
3. Examine the role's trust relationship and permissions as well as its use case - if needed reach out to the vendor to validate which permissions are necessary for their functions and why

In order to remove any unnecessary permissions and minimize trusted entities which can assume the role, use the following remediation steps:

To revoke the vendor's access to assume the role altogether, browse to the role in the AWS Console and select "Trust relationships"->"Edit trust policy". Modify the role's trust relationship as per requirements. To minimize the access the vendor has using the role, under the "Permissions" tab, select the relevant policy and remove unnecessary permissions by either editing the policy or replacing it (notice: editing a managed policy could affect other roles).

|*GCP Cloud Run Job Public Execution via Default Compute SA Modification*
//RLP-145655

|*Changes—* The policy RQL will be updated to narrow down results (for example remove basic roles which are caught by other policies) and provide a more effective view.

*Severity—* High

*Cloud—* GCP

*Updated RQL—*

----
config from iam where dest.cloud.type = 'GCP' AND action.name contains all('run.jobs.setIamPolicy', 'iam.serviceAccounts.actAs') AND grantedby.cloud.policy.type != 'GCP Basic Role'
----

|*GCP Lateral Access Expansion by Making Cloud Run Publicly Executable*
//RLP-145655

|*Changes—* The policy RQL will be updated to narrow down results (for example remove basic roles which are caught by other policies) and provide a more effective view.

*Severity—* High

*Cloud—* GCP

*Updated RQL—*

----
config from iam where dest.cloud.type = 'GCP' AND action.name contains all('run.services.setIamPolicy', 'iam.serviceAccounts.actAs') AND grantedby.cloud.policy.type != 'GCP Basic Role'
----


|===



[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*Amazon S3*

tt:[24.7.3]
//RLP-142168

|*aws-s3api-get-bucket-acl*

Additional permission required:

* `s3:GetAccelerateConfiguration`

The Security Audit role includes the permission.

Also, this API has been updated to include the following new field in the resource JSON:

* `bucketAccelerateConfiguration`

|*AWS Application Migration Service*
//RLP-145208

|*aws-mgn-replication-configuration-template*

Additional permission required:

* `mgn:DescribeReplicationConfigurationTemplates`

The Security Audit role does not include the permission. You must manually add the above permission to the CFT template to enable it.


|*Amazon EMR*
//RLP-145210 

|*aws-emr-serverless-application*

Additional permissions required:

* `emr-serverless:ListApplications`
* `emr-serverless:GetApplication`

The Security Audit role includes the permissions. 

|*AWS Systems Manager*
//RLP-145209

|*aws-ssm-activation*

Additional permission required:

* `ssm:DescribeActivations`

The Security Audit role includes the permission. 

|*AWS Systems Manager*
//RLP-145206

|*aws-ssm-session*

Additional permission required:

* `ssm:DescribeSessions`

The Security Audit role includes the permission. 

|*Azure Compute*
//RLP-144994

|*azure-compute-snapshots*

Additional permission required:

* `Microsoft.Compute/snapshots/read`

The Reader role includes the permission.

|*Azure Monitor*
//RLP-144988

|*azure-monitor-smart-detector-alert-rules*

Additional permission required:

* `Microsoft.AlertsManagement/smartDetectorAlertRules/read`

The Reader role includes the permission.

|*Azure Monitor*
//RLP-144974

|*azure-monitor-prometheus-rule-groups*

Additional permission required:

* `Microsoft.AlertsManagement/prometheusRuleGroups/read`

The Reader role includes the permission.

|*Azure Monitor*
//RLP-141429

|*azure-monitor-query-packs*

Additional permission required:

* `Microsoft.OperationalInsights/querypacks/read`

The Reader role includes the permission.


|*Azure Resource Manager*
//RLP-142469

|*azure-template-specs*

Additional permission required:

* `Microsoft.Resources/templateSpecs/read`

The Reader role includes the permission.

|tt:[Update] *Google Anthos GKE Fleet Management*
//RLP-138227, RLP-131184

|To improve performance, the `gkehub.locations.list` permission is no longer required for the following APIs:

* *gcloud-anthos-gke-fleet-membership*
* *gcloud-anthos-gke-fleet-feature*


|tt:[Update] *Google Certificate Manager*
//RLP-144501, RLP-144500

|To improve performance, the `certificatemanager.locations.list` permission is no longer required for the following APIs:

* *gcloud-certificate-manager-dns-authorization*
* *gcloud-certificate-manager-certificate*

|tt:[Update] *Google Cloud Deploy*
//RLP-144504, RLP-144503

|To improve performance, the `clouddeploy.locations.list` permission is no longer required for the following APIs:

* *gcloud-cloud-deploy-target*
* *gcloud-cloud-deploy-delivery-pipeline*

|tt:[Update] *Google Cloud Memorystore for Memcached*
//RLP-144510

|To improve performance, the `networkconnectivity.locations.list` permission is no longer required for the *gcloud-memorystore-memcached-instance* API.


|tt:[Update] *Google Cloud VMware Engine*
//RLP-144519, RLP-144518, RLP-144517, RLP-144516, RLP-144515, RLP-144514

|To improve performance, the `vmwareengine.locations.list` permission is no longer required for the following APIs:

* *gcloud-vmware-engine-subnet*
* *gcloud-vmware-engine-private-cloud*
* *gcloud-vmware-engine-network*
* *gcloud-vmware-engine-network-policy*
* *gcloud-vmware-engine-hcx-activation-key*
* *gcloud-vmware-engine-cluster*

|tt:[Update] *Google Datastream*
//RLP-144508, RLP-144507, RLP-144505

|To improve performance, the `datastream.locations.list` permission is no longer required for the following APIs:

* *gcloud-datastream-stream*
* *gcloud-datastream-private-connection*
* *gcloud-datastream-connection-profile*



|tt:[Update] *Google Hybrid Connectivity*
//RLP-144511

|To improve performance, the `memcache.locations.list` permission is no longer required for the *gcloud-hybrid-connectivity-spoke* API.


|tt:[Update] *Google Traffic Director*
//RLP-144513, RLP-144512

|To improve performance, the `networkservices.locations.list` permission is no longer required for the following APIs:

* *gcloud-traffic-director-network-service-mesh*
* *gcloud-traffic-director-network-service-gateway*

|tt:[Update] *Google Workflows*
//RLP-144520

|To improve performance, the `workflows.locations.list` permission is no longer required for the *gcloud-workflows-workflow* API.

|===

[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|*Compliance Benchmark*
|*Description*

|*Policy Mapping Update for CIS GCP v2.0.0 Level 1/Level 2 and v3.0.0 Level 2*
//RLP-145840

|New Policy mappings will be added to CIS v2.0.0 (GCP) Level 1, CIS v2.0.0 (GCP) Level 2, and CIS v3.0.0 (GCP) Level 2 compliance standards.

*Impact—* No impact on existing alerts. The compliance score may vary as new mappings are added.

|===


[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*


|tt:[*Resource Explorer API*]

//RLP-131482, RLP-115752

* https://pan.dev/prisma-cloud/api/cspm/get-resource/[GET/resource]
* https://pan.dev/prisma-cloud/api/cspm/get-timeline-for-resource/[POST /resource/timeline]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-raw/[POST /resource/raw]

|23.9.2
|24.10.2
|* https://pan.dev/prisma-cloud/api/cspm/get-asset-details-by-id/[POST /uai/v1/asset]

|tt:[*Deprecation of Compliance Standards*]

The following legacy Compliance Standards are planned for deprecation at the end of May 2024. The standards will be removed from the Prisma Cloud console at the end of July 2024.

* MITRE ATT&CK v10.0
* MITRE ATT&CK v6.3
* MITRE ATT&CK v8.2
* HITRUST CSF v9.3
* HITRUST v.9.4.2

//RLP-140241

|24.5.2
|24.7.3
|You must upgrade to the latest version of the Compliance Standards:

* MITRE ATT&CK v14.0 Cloud IaaS for Enterprise
* HITRUST CSF v.11.2.0


|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

//RLP-120514, RLP-145823

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture/[get /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture/[post /compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend/[get /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard/[get /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard/[post /compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement/[get /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement/[post /compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard/[get /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard/[post /compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement/[get /compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement/[post /compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report/[post /report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info/[get /resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info/[post /resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-2/[get /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-2/[post /v2/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-2/[get /v2/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-2/[post /v2/inventory/trend]


|23.10.1

|24.9.1

|tt:[*Prisma Cloud CSPM REST API for Compliance Posture*]

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

tt:[*Prisma Cloud CSPM REST API for Asset Explorer and Reports*]

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

tt:[*Prisma Cloud CSPM REST API for Asset Inventory*]

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|tt:[*End of support for Google Cloud Function v1 API*]
//RLP-142340

|NA
|24.10.1
|`gcloud-cloud-function-v1` API is planned for deprecation. Due to this change, Prisma Cloud will no longer ingest metadata for `gcloud-cloud-function-v1 API`. 

In RQL, the key will not be available in the api.name attribute auto-completion. As a replacement, it is recommended to use the `gcloud-cloud-function-v2` API.

*Impact*—If you have a saved search or custom policies based on this API, you must delete those manually. The policy alerts will be resolved as Policy_Deleted.

|tt:[*End of support for Azure Active Directory v1 API*]
//RLP-143110

|NA
|24.9.2
|`azure-active-directory-credential-user-registration-details` API is planned for deprecation. Due to this change, Prisma Cloud will no longer ingest metadata for `azure-active-directory-credential-user-registration-details API`. 

In RQL, the key will not be available in the api.name attribute auto-completion. As a replacement, it is recommended to use the `azure-active-directory-user-registration-details` API.

*Impact*—If you have a saved search or custom policies based on this API, you must delete those manually. The policy alerts will be resolved as Policy_Deleted.


|tt:[*Deprecation of End Timestamp in Config Search*]
//RLP-126583, suset release TBD
| - 
| - 
|The end timestamp in the date selector for Config Search will soon be deprecated after which it will be ignored for all existing RQLs. You will only need to choose a start timestamp without having to specify the end timestamp.

|tt:[*Prisma Cloud CSPM REST API for Alerts*]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter `risk.grade` is deprecated for the following requests:

*  `GET /alert`
*  `GET /v2/alert`
*  `GET /alert/policy` 

Request body parameter `risk.grade` is deprecated for the following requests:

*  `POST /alert`
*  `POST /v2/alert`
*  `POST /alert/policy`

Response object property `riskDetail` is deprecated for the following requests:

*  `GET /alert`
*  `POST /alert`
*  `GET /alert/policy`
*  `POST /alert/policy`
*  `GET /alert/{id}`
*  `GET /v2/alert`
*  `POST /v2/alert`

Response object property `risk.grade.options` is deprecated for the following request:

* `GET /filter/alert/suggest`

| -
| -
| NA

//tt:[*Change to Compliance Trendline and Deprecation of Compliance Filters*]
//RLP-126719, need to check if this notice can be moved to current features in 24.1.2
//- 
//- 
//To provide better performance, the *Compliance trendline* will start displaying data only from the past one year. Prisma Cloud will not retain the snapshots of data older than one year.
//The Compliance-related filters (*Compliance Requirement, Compliance Standard, and Compliance Section*) will not be available on Asset Inventory (*Inventory > Assets*).

|===