== Look Ahead—Planned Updates to Secure the Runtime

Review any changes planned in the next Prisma Cloud release to ensure the security of your runtime.

Read this section to learn about what is planned in the upcoming `32.02` release on the Runtime Security tab of the Prisma Cloud console for WAAS, Host Security, Serverless Security, and Container Security.

The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

Currently, there are no previews or announcements for updates.

// [NOTE]
// ====
// The details and functionality listed below are a preview of what is planned for the `v32.02` release; the changes listed herein and the actual release date, are subject to change.
// ====


//* <<defender-upgrade>>
// * <<enhancements>>
// * <<deprecation-notices>>
// * <<eos-notices>>
// * <<addressed-issues>>

[#enhancements]
=== Enhancements

The following enhancements are planned; the details will be available at release:

// [cols="30%a,70%a"]
// |===

// |===


// [#deprecation-notices]
// === Deprecation Notices
// [cols="30%a,70%a"]
// |===

// |===

// [#eos-notices]
// === End of Support Notices



// [#addressed-issues]
// === Addressed Issues
// [cols="30%a,70%a"]
// |===


// |===

