== The MWAA environment is publicly accessible

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/AWS_private_MWAA_environment.yaml[CKV2_AWS_66]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This Checkov policy is checking to ensure that the Amazon Managed Workflows for Apache Airflow (MWAA) environment is not publicly accessible. 

MWAA is a fully managed service that makes it easier to run Apache Airflow on AWS. By making the environment publicly accessible, you introduce potential security risks as it becomes vulnerable to unauthorized access. Attackers may exploit this vulnerability to gain access to the data processed in your environment or disrupt the operation of your workflows.

Hence, the policy checks for this configuration setting to ensure that access to the MWAA environment is restricted to reduce these risks.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_mwaa_environment
* *Arguments:* webserver_access_mode

Terraform configuration should define an aws_mwaa_environment resource with the webserver_access_mode attribute set to PRIVATE_ONLY. Here is an example configuration:

[source,go]
----
provider "aws" {
  region = "us-east-1"
}

resource "aws_mwaa_environment" "example_mwaa" {
  name = "my-mwaa-environment"

  // ... other required configurations for MWAA ...

  network_configuration {
    // ... VPC, Subnet IDs, Security Groups ...
  }

  webserver_access_mode = "PRIVATE_ONLY"  # Ensure the environment is not publicly accessible
}
----

This Terraform snippet defines an MWAA environment with its webserver_access_mode explicitly set to PRIVATE_ONLY. This configuration ensures that the MWAA environment's webserver can only be accessed through your VPC, which complies with the CKV2_AWS_66 policy by restricting public access and enhancing the environment's network security. Remember to replace the placeholder comments with actual configuration values specific to your AWS VPC, subnets, and security groups.

