
== AWS CloudFront web distribution with geo restriction disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| a920a1a2-6856-4eb2-b2db-7aee4ce03f4c

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/CloudFrontGeoRestrictionDisabled.py[CKV_AWS_374]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

The policy is checking whether AWS CloudFront web distributions have geographic restrictions enabled. This involves setting up geo restrictions to control access based on the geographic location of users attempting to access the content distributed by CloudFront.

The reason this is considered important is because enabling geographic restrictions allows for better control over where your content can be accessed from, which can help comply with legal and regulatory requirements specific to certain regions. It can also improve security by preventing access from regions that are not relevant to your business or where you know that malicious activity might originate. Overall, implementing geo restrictions can help protect your data and ensure compliance with regional laws and policies.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_cloudfront_distribution
* *Arguments:* restrictions

Enable geo restriction for your AWS CloudFront distribution. Include a `restrictions` block inside the `aws_cloudfront_distribution` resource to configure geo restrictions by specifying which countries are allowed or denied.

Here is an example of how to enable geo restriction for an AWS CloudFront distribution using Terraform:

[source,hcl]
----
resource "aws_cloudfront_distribution" "example" {
  ...
  restrictions {
    geo_restriction {
      restriction_type = "whitelist"  # Or "blacklist" depending on your use case
      locations        = ["US", "CA", "GB"] # Example of allowed countries
    }
  }
  ...
}
----

