
== AWS API Gateway method without authorization or API keys

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/APIGatewayMethodWOAuth.py[CKV2_AWS_70]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|===

=== Description

This policy is checking whether an API gateway method has authorization or an API key set. It is important to have these security measures to ensure that only authenticated and authorized users can access the API. Without such controls, APIs could be exposed to unauthorized access and potential misuse, leading to data breaches, unauthorized data modifications, and other security vulnerabilities. Proper authorization mechanisms and API keys help safeguard sensitive information and maintain the integrity of the API.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_api_gateway_method, aws_api_gateway_rest_api
* *Arguments:* authorization, api_key_required

Ensure that each method in the API Gateway requires either an authorization or an API key. This can be done by setting the `authorization` property to a suitable type such as `AWS_IAM`, and/or ensuring that the `api_key_required` property is set to `true`.

[source,go]
----
resource "aws_api_gateway_method" "example" {
  ...

  # Ensure that authorization is set
  authorization = "AWS_IAM"
  
  # Optionally, you can also indicate that an API key is required
  api_key_required = true
}
----
