== ALB does not drop HTTP headers


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5dd236e7-f0da-4a06-825d-7691cdbf10be

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/ALBDropHttpHeaders.py[CKV_AWS_131]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


This policy ensures that Application Load Balancers (ALBs) are configured to drop HTTP headers that do not conform to RFC specifications. This improves security by preventing header injection attacks and other potential misuse of faulty headers.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_alb
* *Arguments:* drop_invalid_header_fields


[source,go]
----
resource "aws_alb" "test_success" {
    name               = "test-lb-tf"
    internal           = false
                    load_balancer_type = "network"
                    subnets            = aws_subnet.public.*.id
 +                  drop_invalid_header_fields = true
}
----

*CloudFormation*

To mitigate this issue, ensure the `LoadBalancerAttributes` parameter in the `AWS::ElasticLoadBalancingV2::LoadBalancer` resource includes the attribute `routing.http.drop_invalid_header_fields.enabled` set to `true`.

Example:

[source,json]
----
{
  "Resources": {
    "MyLoadBalancer": {
      "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",
      "Properties": {
        ...
        "Type": "application",
        "LoadBalancerAttributes": [
          {
            "Key": "routing.http.drop_invalid_header_fields.enabled",
            "Value": "true"
          }
        ]
      }
    }
  }
}
----

[source,yaml]
----
Resources:
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      ...
      Type: application
      LoadBalancerAttributes:
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: "true"
----
