== Data source IAM policy document allows all resources with restricted actions

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/data/aws/ResourcePolicyDocument.py[CKV_AWS_356]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to ensure that no IAM (Identity and Access Management) policy documents allow "*" as a statement's resource for actions that can be restricted. If "*", which stands for all resources, is used, it means the statement grants permissions to all AWS resources which is potentially unsafe. This is poor practice because it broadens the scope of access controls and increases the risk of unauthorized access. It's important to define granular permissions to each user access, as unrestricted access can lead to unwanted manipulations or data breaches. Therefore, it's recommended to specify restrictions and assign minimum necessary access rights.

For more info, visit https://cloudsplaining.readthedocs.io/en/latest/glossary/resource-exposure/[cloudsplaning documentation].

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_iam_policy_document
* *Arguments:* policy

You should not use a wildcard (*) as a statement's resource as it grants excessively broad permissions.

Example:

[source,go]
----
data "aws_iam_policy_document" "fail" {
  version = "2012-10-17"

  statement {
    effect = "Allow"
    actions = [
      "s3:Describe*",
    ]
    resources = [
-      "*",
+      "arn:aws:s3:::${var.s3_bucket_name}",
    ]
  }
}
----

