== AWS IAM policy allows full IAM privileges

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/IAMPolicyNotAllowFullIAMAccess.yaml[CKV2_AWS_40]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy detects if an AWS IAM policy allows full IAM privileges. Granting full IAM privileges can lead to unauthorized access, privilege escalation, and potential security breaches.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_iam_policy, aws_iam_role_policy, aws_iam_group_policy, aws_iam_user_policy
* *Arguments:* statement

To fix this issue, review the IAM policy and remove any explicit Allow actions for IAM. Limit the IAM policy to only the necessary permissions required for the specific role or group.

Secure code example:

[source,go]
----
data "aws_iam_policy_document" "example" {
  statement {
    effect = "Allow"
    actions = [
      "s3:Get*",
      "s3:List*",
    ]
    resources = ["arn:aws:s3:::my-bucket/*"]
  }
}
----

The above code is secure because it only allows the necessary actions ("s3:Get*" and "s3:List*") on a specific S3 bucket.