== Data source IAM policy document allows all resources with restricted actions

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| e6549da7-fe94-44b8-9957-84770f3e790b

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/data/aws/ResourcePolicyDocument.py[CKV_AWS_356]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to ensure that no IAM (Identity and Access Management) policy documents allow "\*" as a statement's resource for actions that can and should be restricted. Prisma Cloud checks the AWS documentation for IAM actions that can be restricted to a resource and recommends defining a specific resource rather than "\*". If "\*", which stands for all resources, is used, it means the statement grants permissions to all AWS resources which is potentially unsafe. This is poor practice because it broadens the scope of access controls and increases the risk of unauthorized access. It's important to define granular permissions to each user access, as unrestricted access can lead to unwanted manipulations or data breaches. Therefore, it's recommended to specify restrictions and assign minimum necessary access rights.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_iam_policy_document
* *Arguments:* statement

You should not use a wildcard (*) as a statement's resource with an action that can be restricted to a resource. Specify an ARN or multiple ARNs instead.

Here's an example of a secure piece of Terraform code:

[source,go]
----
data "aws_iam_policy_document" "example" {
  statement {
    sid = "samplePassRole"

    effect = "Allow"

    actions = [
      "s3:PutObject",
      "s3:GetObject",
      "s3:DeleteObject"
    ]

    resources = [
-      "*",
+      "arn:aws:s3:::my_bucket/my_object"
    ]
  }
}
----

In the above Terraform, the actions `s3:PutObject`, `s3:GetObject`, and `s3:DeleteObject` are allowed, but they are limited to the resources specified - "arn:aws:s3:::my_bucket/my_object". This is much more secure as it clearly defines what resources the IAM policy's actions can access, rather than opening up all resources by using a wildcard (*).

