== Alibaba Cloud launch template data disks are not encrypted


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5dea0e04-6728-4a04-a8e4-1dbbff5ec28b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/LaunchTemplateDisksAreEncrypted.py[CKV_ALI_32]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

This policy ensures that the data disks in an Alibaba Cloud ECS Launch Template are encrypted. Encrypting data disks helps protect sensitive data from unauthorized access and ensures data confidentiality and integrity. Encryption is essential for compliance with many regulatory standards and best practices.

Failing to encrypt data disks can result in data breaches, unauthorized access, and potential non-compliance with regulatory requirements.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_ecs_launch_template
* *Arguments:* data_disks.encrypted

To mitigate this issue, ensure the `encrypted` attribute in the `data_disks` block of the `alicloud_ecs_launch_template` resource is set to `true`.

Example:

[source,go]
----
resource "alicloud_ecs_launch_template" "example" {
  ...

  data_disks {
+    encrypted = true
  }
}
----
