== ネットワーク構成クエリー

Prisma Cloudには、ネットワーク構成に基づいたuserinput:[config from network where] ネットワーククエリも用意されています。これを使用して、AWS EC2仮想マシン、DBインスタンス、またはLambdaアプリケーションなどの任意のソースから、インターネット、別のVPC、またはオンプレミスネットワークなどのあらゆる宛先までの、エンドツーエンドのネットワークパスを表示して、過度に露出されたリソースを識別することができます。セキュリティグループとコンピューティングインスタンス間の関連付けを見ることができ、インシデントになる前にネットワーク セキュリティ リスクを特定するのに役立ちます。Prisma Cloudでは、ネットワークパス分析のためにトラフィックの送信やネットワークログの読み取りは行われません。

userinput:[config from network where=]RQLを使用する場合に、PrismaCloudにおけるネットワーク露出を照会できるリソースのリストは次のとおりです。

[cols="50%a,50%a"]
|===
|クラウドサービス
|ネットワーク露出をサポートするリソース


|*AWS*
|* Network (VPC)（ネットワーク（VPC））
* インターネット ゲートウェイ
* サブネット
* NACL
* NATゲートウェイ
* EC2
* ENI
* EIP
* セキュリティグループ
* VPCサービスエンドポイント/PrivateLink
* ルート テーブル
* トランジットゲートウェイとルートテーブル
* VPC ピアリング


|*Azure*
|* 仮想マシン（VM）
* 仮想マシンスケールセット（柔軟なVMSS、均一なVMSS）
* ネットワークインターフェイス（NIC）
* サブネット
* パブリックIPアドレス（PIP、PIPプレフィックス、共有PIP）
* ユーザー定義ルート（有効なUDR）
* 仮想ネットワーク（Vnet）
* NATゲートウェイ
* ロードバランサー（NLB、ALB)
* アプリケーションセキュリティグループ（ASG）
* ネットワークセキュリティグループ（NSG）
* PaaSサービス（PgSQL）


|*GCP*
|* サブネット
* VPCファイアウォール
* 階層構造ファイアウォールール
* バックエンドサービス
* ファイアウォールポリシー
* LB 転送ルール
* VM
* インスタンスグループ
* VPC
* NetworkEndpointGroup
* TargetHttpProxy
* TargetHttpsProxy
* TargetInstance
* TargetPool
* TargetSslProxy
* TargetTcpProxy
* URLMap

|===

[NOTE]
====
ネットワーク公開クエリは現在AWS、Azure、とGCPクラウド環境でのみサポートされており、現在、政府および中国リージョンでは利用できません。
====