== Pull request reviews are not required in repository before merging to the default branch

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_34
|Category |Flow Control
|Provider |
|Severity |MEDIUM
|===
 

=== Impact
User accounts granted with **write** permissions on an actively used repository^*^ can directly push code directly to the default branch without requiring reviews, not required for pull request reviews before the code is merged.
User accounts with 'write' permissions on an actively used repository can push code directly to the default branch without requiring pull request reviews before the code is merged, potentially allowing malicious code to flow through the pipeline to production systems.
Attackers compromising such a user account can directly push code to the default branch, which is likely to flow through the pipeline and be used in production systems.

^*^An actively used repository is defined as having at least two contributors, over 50 commits, and has been updated in the last 90 days.

=== Recommended Solution - Buildtime

It is recommended to restrict direct pushes to the default branch, and to require pull request approvals to ensure the code is reviewed before merged.
To configure require required pull request reviews:
 
. Select a repository > **Settings**.
. Under **Branches**, select **add branch protection rule** > edit the rule that applies to the default branch.
. Check the **Require a pull request reviews before merging** rule.
. Select the required request approvals from the options that are displayed.

Recommended: Select the **Require review from Code Owners** rule that is displayed when executing _step 3 above_. 



