== BitBucket branch protection rule allows push to default branch

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_69
|Category |Flow Control
|Provider |
|Severity |MEDIUM
|Mapped CSPM/KSPM Rule |None
|===


=== Description 

Compromised user accounts with **write** permissions for an actively used repository* configured in the default branch protection rule can directly push and merge code to the default branch without requiring pull request reviews, allowing malicious content to flow through the pipeline to production systems.

*An actively used repository is defined as having at least two contributors, over 50 commits, and has been updated in the last 90 days.

=== Recommended Solution - Buildtime

We recommend removing all entities from the **Write access** field of the default branch protection rule (which is unrelated to repository write permissions), to prevent unreviewed push of code:
 
1. Open the default branch settings editor: navigate to repository **Settings** > **Branch permissions** > edit the rule that applies to the default branch.
2.  Delete all users and groups from the **Write access** field.









