== Repository Prioritization

*WIP*

Security management across code repositories presents a growing challenge as codebases expand and teams adopt microservices architectures. Efficient resource allocation for security efforts hinges on identifying the critical repositories that require the most attention in order to allocate resources effectively.  

The Repository Score is a dynamic metric designed to address the challenges of prioritizing security issues within a multi-repository environment. By incorporating factors like repository maintenance frequency, characteristics, path to production and more, Repository Score provides a quantitative measure (1-10) to guide security teams towards the most impactful remediation efforts. This data-driven approach empowers developers to optimize security resource allocation and focus on vulnerabilities that pose the greatest risk. The data collection processes is automated and scheduled at regular intervals to ensure that scores are based on the latest information.

You can filter CAS findings and insights based on the Code Repository Importance Score across Project, CI/CD Risks, SBOM, and Technologies pages to focus on repositories with higher importance.

////
In the fast-paced world of software development, our customers face significant challenges in efficiently prioritizing security issues across their numerous code repositories. Without a clear understanding of which repositories are most actively used and critical to their operations, it becomes difficult to allocate resources effectively. To address this, we introduce the Repo Score—an innovative solution designed to streamline decision-making processes for security teams.

The Repo Score is a dynamic, actionable metric ranging from 1 to 100 that quantifies the active usage and significance of each integrated code repository relative to others. By providing a clear measure of a repository's importance and priority, this score empowers security teams to focus their efforts on the most crucial areas first, ensuring that resources are allocated where they are needed most. With the Repo Score, our objective is to enhance efficiency and effectiveness in managing and mitigating security risks within code repositories, ultimately contributing to a more secure and robust software development lifecycle.
////
=== Calculate Repository Importance Scores

Repository scores are calculated by collecting and analyzing various data points, including codebase characteristics, maintenance and usage frequency, and path to production environments. This data is then used to generate a dynamic score (1-10) stored within the system's database or repository for easy retrieval and presentation on relevant CAS pages, such as the Application Asset Graph. Data calculated includes:
// TODO -redo the above when concrete data such as where the repo score can be seen, becomes available

* *Repository commits*: Includes the total number of commits, the number of commits over the last *X* months, and the time of the last commit 
* *Repository Issues*: Includes the total number of issues detected in a repository, and the last time an issue was reported
* *Repository releases/tags*: Includes the total number of tags and releases, and the last time a tag or release was created 
* *Repository characteristics*: Includes whether the repository was forked, if it is private or public, if it is part of your organization and whether it is archived
* *Repository relationships*: Includes all collaborators, CI files, connected pipelines (including whether they build an image), and whether the repository is associated with a container  (repo > pipeline > image > container) 

=== Customize Repository Importance Scores

You can customize Repository Importance scores to suit your organization requirements. Provide a comment explaining the manual score, the reasoning behind it, and the name of the user performing the change. When a manual score is applied, a comment explaining the reasoning behind the adjustment is required. Once set manually, the system stops calculating the score for the repository, using the manual score instead. You can restore automatic calculation that will override the manual calculation. 

===  Prioritize Repositories (Graph View)  

You can facilitate efficient security analysis by prioritizing repositories based on the Repository Importance Score attribute of a Repository node as part of a query built through the *Investigate Simple Mode Query Builder*. 
// TODO Is "In addition you can filter repositories specifying a range of scores" part of the query attributes?

For more information on how to build a prioritize a query as part of a query see xref:[]
//TODO link to Query builder with Repository Importance Score attribute 


=== Dashboard View 

You can customize CAS dashboard widgets based on Repository Importance Score to focus on repositories with higher importance.

You can view Repository Importance scores for all integrated code repositories in the *Repositories* table, allowing you to prioritize vulnerabilities based on potential impact. Filters and sorting by Repository Importance scores allow you prioritize repositories that require attention.

Application context allows you to focus on code repositories and issues that are part of high business impact on your organization. 

 Perform the following actions by navigating to *Application Security* > *Repositories* page. 

* Group applications 
* Filter integrated code repositories based on the specific application they belong to
* Filter by application impact level

In addition, you can filter the *Project*, *CI/CD Risks*, *SBOM*, and *Technologies* tables based on Repository Importance scores.

==== Manage Repository Importance Scores via REST API

You can automate application management and run bulk commands through the Prisma Cloud REST API. This empowers you to efficiently automate process and run bulk commands, including:

* Fetching repositories scores
* Setting scores and leaving comments
* Bulk operations: Support for all CRUD operations 
   







