== Missing ‘.npmrc’ file in Azure Repos repository   


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|77a2446a-daf2-49c7-9fc4-5e67130d4e89 

|Severity
|Medium
// add severity level

|Category
|Dependency Chains 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Azure Repos

|=== 

=== Description

The *.npmrc* file is a configuration file used by npm, the Node Package Manager, to manage settings and options related to package installation and publishing. Failing to store the '.npmrc' file in the repository can make the project vulnerable during pipelines to both dependency confusion, by allowing an internal package to be fetched from the public registry, as well as insecure use of credentials.

=== Recommended Solution - Buildtime

Create a *.npmrc* file in the repository and configure it according to the best practices detailed in the npm documentation: 

* Authentication related configurations must be scoped to a specific registry by prefixing with a URI fragment. Refer to https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration for more information

* Use a variable to represent tokens used in the '.npmrc' file. Refer to https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow for more information



