== Secret exposed in registry URL within ‘.npmrc’ file of an Azure Repos repository  


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|eb7900c4-b0f5-4469-a5c4-0ed1810d5f65   

|Severity
|High
// add severity level

|Category
|Dependency Chains 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Azure Repos

|=== 

=== Description

Including secrets in a ‘.npmrc’ file, can allow an attacker who has gained access to the repository to gain unauthorized access to the package or to resources that are protected by the secret.

The attacker could potentially use these secrets to impersonate the owner of the secret and to perform actions on their behalf, such as pushing malicious packages to a registry which could reach the production environment or accessing internal packages on the registry. 

=== Recommended Solution - Buildtime

When exposed secrets are found, it is recommended to:

* Rotate the exposed secret
* Replace the secret with an environment variable placeholder as detailed in NPM’s documentation: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow
