== GitHub Actions pipeline vulnerable to command injection

=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_138
|Category |INPUT_VALIDATION
|Provider |
|Severity |CRITICAL
|Mapped CSPM/KSPM Rule |None
|===


=== Description 

Pipelines are vulnerable to command injection attacks, in which arbitrary commands and scripts are passed through user controlled inputs such as pull request title, commit description etc., which are referenced by the pipeline configuration file and executed in the pipeline job.
When a pipeline job runs, the poisoned controlled inputs can be interpreted as code, which is then executed on the runner, enabling remote code execution attacks to take place in order to access stored secrets or to read or modify the source code. 

=== Recommended Solution - Buildtime

Pipelines should never run unsanitized and/or untrusted input.
To mitigate command injection attacks, the recommended approach is to use an action that processes user input as an argument.
Another approach would be to set the value of the expression to an intermediate environment variable which will cause this attack to fail.

For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks.





