== Plain-text management Telnet is enabled for an Interface Management Profile

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/ansible/checks/graph_checks/PanosInterfaceMgmtProfileNoTelnet.yaml[CKV_PAN_3]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Ansible

|=== 

=== Description

This policy ensures that plain-text management Telnet is not enabled for Interface Management Profiles in Palo Alto Networks devices. Enabling Telnet for management interfaces can significantly increase the risk of eavesdropping and man-in-the-middle attacks due to unencrypted communication. This policy checks that the `telnet` attribute in the `panos_management_profile` resource is not set to true, promoting the use of more secure, encrypted management protocols.

=== Fix - Buildtime

*Palo Alto Networks*

* *Resource:* panos_management_profile
* *Attribute:* telnet

To adhere to this policy, the `telnet` attribute in your `panos_management_profile` resource should not be enabled (set to true). It is recommended to explicitly set this attribute to false or omit it entirely to disable Telnet and encourage the use of secure communication protocols.

Secure code example:

[source,yaml]
----
- name: Ensure Telnet is not used for management profiles
  tasks:
    - name: Interface_mgmt_profile_fail_1
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ provider }}'
        name: 'Test profile'
-        telnet: true # telnet defined as true, which is a fail
+        telnet: false # telnet defined as true, which is a fail
----

Setting the `telnet` attribute to false or ensuring it is not configured in the management profile reinforces this policy's requirement, thus securing the Palo Alto Networks device management interface.
