== Alibaba Cloud RDS instance does not use SSL


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 20f83821-cc13-405f-a437-5926c6ef9919

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RDSInstanceSSL.py[CKV_ALI_20]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 

This policy ensures that RDS instances in Alibaba Cloud use SSL to protect data in transit. Using SSL for database connections helps to encrypt data and prevent unauthorized interception or tampering of data.

Failing to enable SSL for RDS instances can result in sensitive data being transmitted in plaintext, making it vulnerable to interception and attacks.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_db_instance
* *Attribute:* ssl_action

To mitigate this issue, ensure that the `ssl_action` attribute in the `alicloud_db_instance` resource is set to "Open" or "Update".

Example:

[source,go]
----
resource "alicloud_db_instance" "example" {
  ...
+  ssl_action = "Open"
}
----
