
== Azure ACR HTTPS not enabled for webhook

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 9a28b0fb-67cd-4de9-80b0-702bc0ca6177

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/AzureContainerInstanceconfigManagedIdentity.yaml[CKV2_AZURE_28]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

Ensure that Azure Container Instances are configured with a managed identity. This configuration is crucial to augment the security of the container instance through the provision of an identity for Azure resources. It gives the developer the ability to manage credentials directly through Azure instead of creating and maintaining security credentials manually. If not set properly, security credentials may be exposed or misused, which can lead to a significant security risk such as unauthorized access or data breach. Thus, having the container instance managed by Azure greatly enhances the security and compliance of your operations.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_container_group
* *Arguments:* identity.type

To fix the issue, you need to enable the managed identity for Azure Container Instances by adding a `identity` block with `type` set.

[source,hcl]
----
resource "azurerm_container_group" "example" {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  os_type             = "Linux"

+ identity {
+   type = "SystemAssigned"
+ }

  container {
    // other configurations
  }
}
----

