== Possible Python typosquatting detected in a Bitbucket repository  

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|9298bbd8-7dfb-4a61-8a10-e58bf3f2004b 

|Severity
|High 
// add severity level

|Category
|Dependency Chains 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 

=== Description 

Typosquatting attacks involve the registration of malicious packages in public registries, using names that closely resemble popular or internal packages used by an organization.
The objective is to exploit users’ mistakes when typing package names, resulting in the unintentional download of the malicious package.

Running malicious packages on developers endpoints or in CI pipelines can lead to credential theft, source code leakage, code tampering and more.


=== Recommended Solution - Buildtime

Evaluate the event details to determine if the suspected package is malicious. If so, remove the malicious package from project dependency files such as `requirements.txt`, `Pipfile` and `pyproject.toml`.

To ensure your build environment or developers' machines haven’t been infected with a malicious package, perform the necessary steps to investigate for any signs of malicious activity.

