== Potential dependency confusion in a Bitbucket repository due to package name or scope available in registry   

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|fb329a8b-40be-4651-9184-ced59f1abc5d 

|Severity
|High 
// add severity level

|Category
|Dependency Chains 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 

=== Description 

Attackers can discover internal package names by scanning public repositories and artifacts. Then can then upload malicious packages with names identical to an organization’s internal package names and scopes, hoping that improper package fetching configuration will cause internal clients to fetch the malicious package rather than the legitimate internal package with the same name. This is known as a *Dependency Confusion* attack.


=== Recommended Solution - Buildtime

Registering internal package names or scopes in the public *npmjs.com* repository can help prevent misconfigured clients (such as CI servers and developer endpoints) from inadvertently fetching malicious packages from the public NPM repository.
