== Unsafe Go package in use

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 162db9e5-e042-4a20-9037-40bbbaf53b9d

|Checkov ID 
|CKV3_SAST_243

|Severity
|LOW

|Subtype
|Build

|Language
|Go

|CWEs
|https://cwe.mitre.org/data/definitions/242.html[CWE-242: Use of Inherently Dangerous Function]

|OWASP Categories
|N/A

|=== 

=== Description

This policy checks whether unsafe package are used in Go applications. Unsafe packages can compromise type and memory safety, leading to unpredictable behavior and potential vulnerabilities, and can potentially lead to difficult-to-debug errors.

In the following example, the application imports and uses the unsafe package.

[source,Go]
----
package main

import (
    "fmt"
    "unsafe"
)

func main() {
    // Insecure use of the unsafe package
    var i int = 42
    var f float64 = *(*float64)(unsafe.Pointer(&i))
    fmt.Println(f)
}
----

=== Fix - Buildtime

To mitigate this issue, use safe, idiomatic Go code instead of the unsafe package. This will maintain application security and reliability.

In this example, the application uses safe, idiomatic Go code instead of the unsafe package.

[source,Go]
----
package main

import (
    "fmt"
)

func main() {
    // Secure and idiomatic Go code
    var i int = 42
    var f float64 = float64(i)
    fmt.Println(f)
}
----