== Usage of weak DES encryption algorithms

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 35640d3e-f7f7-4289-a97b-a310d4789521

|Checkov ID 
|CKV3_SAST_239

|Severity
|MEDIUM

|Subtype
|Build

|Language
|Go

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021-Cryptographic Failures]

|=== 

=== Description

This policy checks whether DES and Triple DES encryption algorithms from the crypto/des package in Go applications are in use. DES encryption algorithms are considered weak due to their small key size and are vulnerable to modern cryptanalysis techniques. Stronger algorithms such as AES from the crypto/des package with larger key sizes are recommended for enhanced security.

The following code snippet uses the weak and insecure DES encryption algorithm from the crypto/des package.

[source,Go]
----
package main

import (
    "crypto/des"
    "log"
)

func main() {
    // Insecure use of DES encryption
    key := []byte("weakkey")
    _, err := des.NewCipher(key)
    if err != nil {
        log.Fatal(err)
    }
}
----

=== Fix - Buildtime

To mitigate this issue, replace the weak DES encryption with the more secure AES algorithm from the crypto/aes package.

In this example, the application employs AES encryption rather than DES.

[source,Go]
----
package main

import (
    "crypto/aes"
    "log"
)

func main() {
    // Secure use of AES encryption
    key := []byte("a very very very very secret key") // 32 bytes for AES-256
    _, err := aes.NewCipher(key)
    if err != nil {
        log.Fatal(err)
    }
}
----