== IBM Cloud Virtual Private Cloud (VPC) classic access is enabled in Terraform

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/ibm/IBM_VPCclassicAccessIsDisabled.yaml[CKV2_IBM_2]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy ensures that VPC classic access is disabled. It checks for configurations in your cloud infrastructure to confirm that virtual private cloud (VPC) instances are not allowing classic access. Classic access can pose several security risks as it may enable connections from legacy environments that lack modern security features and controls. Disabling this access minimizes the potential attack surface and enhances the overall security posture of your infrastructure.

=== Fix - Buildtime

*Terraform*

* *Resource:* ibm_is_vpc
* *Arguments:* classic_access

To ensure VPC classic access is disabled, you need to set the attribute `classic_access` to `false` within the `ibm_is_vpc` resource. 

In this example, the `classic_access` attribute is set to `false` to disable classic access to the VPC.

[source,go]
----
resource "ibm_is_vpc" "secure_vpc" {
  ...
+  classic_access = false
}
----
