:topic_type: タスク
[.task]
[#custom-compliance-standard]
== カスタムコンプライアンス基準の作成

// Create a custom compliance standard that reflects your company’s rules and regulations.

独自のビジネスニーズ、基準、組織の規則に合わせた、カスタムコンプライアンス基準を作成することができます。カスタムコンプライアンス基準を定義する際に、要件やセクションを追加することができます。最低1つの要件とセクションを持つカスタムコンプライアンス基準を、基準への遵守をチェックするポリシーと関連付けることができます。

新たな基準を作成する、または既存のコンプライアンス基準を複製して、それを編集することができます。

[.procedure]
. カスタマイズする既存のコンプライアンス基準を複製します。

.. Prisma Cloudで、*Compliance（コンプライアンス）> Standards（基準）*を選択します。

.. 複製する基準の上にカーソルを移動して、*Clone（複製）*をクリックします。
+
複製すると、同じ名前の先頭にCopyが付けられた、新しい基準が作成されます。次に、複製されたコンプライアンス基準を編集して、必要な要件、セクション、ポリシーを指定できます。

. 最初からコンプライアンス基準を作成します。

.. Prisma Cloudで、*Compliance（コンプライアンス）> Standards（基準）> + Add New（新規追加）*を選択します。

.. 新しい基準の名前と説明を入力して、*Save（保存）*を選択します。

.. カスタムコンプライアンス基準に要件を追加します。

... 追加したカスタムコンプライアンス基準を選択して、*+ Add New（新規追加）*をクリックします。

... 要件、名前、説明を入力して、*Save（保存）*を選択します。

.. 要件を追加したら、カスタムコンプライアンス基準にセクションを追加します。

... セクションを追加する要件を選択して、*+Add New（新規追加）*をクリックします。

... *Section（セクション）*の名前と*Description（説明）*を入力して、*Save（保存）*を選択します。
+
Prisma Cloudにカスタム基準を追加しても、それに最低1つのポリシーを追加しない限り、*Compliance（コンプライアンス）> Overview（概要）*のコンプライアンス基準テーブルには表示されません。

.. カスタムコンプライアンス基準にポリシーを追加します。
+
クラウドリソースが内部ガイドラインやベンチマークを遵守していることを監視するには、Prisma Cloud Defaultポリシーまたはカスタムポリシーを、コンプライアンス基準に関連付ける必要があります。ポリシー内のRQLは、リソース設定、アノマリ、またはイベントのチェックを指定しています。

... *Policies (ポリシー)*を選択します。
+
基準と関連付けるポリシーをフィルタリングしてください。クラウドタイプ、ポリシータイプ、およびポリシーの重大度でフィルタリングして、目的のルールを検索することができます。

... 編集するポリシールールを選択して、*3 Compliance Standards（コンプライアンス基準）*で*+*を選択し、ポリシーをカスタムコンプライアンス基準と関連付けます。

... 変更内容を*Confirm（確認）*します。
