:topic_type: タスク
[.task]
[#new-compliance-report]
== 新しいコンプライアンスレポートを追加

Prisma Cloudのコンプライアンスレポートツールを使用して、シングルクラウドまたはマルチクラウド環境が義務付けられているコンプライアンス基準に準拠しているかどうかを監視します。クラウドコンプライアンス標準に基づいてxref:../reports/create-and-manage-reports.adoc#compliance[レポートを作成]し、すぐに表示またはダウンロードしたり、定期的なレポートをスケジュールしてコンプライアンスを長期にわたって監視し続けることができます。各レポートには、選択した基準に対するクラウドアカウントのコンプライアンスが統合的に表示されます。このレポートには、基準に照らして現在監視されているリソースとアカウントが一覧表示され、それらのコンプライアンスステータスが詳細に記載されています。クラウドリソースは、特定の標準のすべてのセクションに対するコンプライアンスを追跡し、各セクションの詳細な調査結果と、非コンプライアンスのセクションに対する改善策を含んでいます。

[.procedure]
. Prisma Cloudにログインします。

. *Cloud Security （クラウドセキュリティ）> Compliance（コンプライアンス > Create Compliance Report（コンプライアンスレポートを作成）*を選択し、ダッシュボードの下の標準リストから標準を選択します。

. 以下の必須情報を入力してください。

.. *Name（名前）*フィールドに分かりやすいレポート名を入力します。

.. レポートの*クラウドタイプ*を選択します。

.. レポートの*日付を*選択します。

.. レポート頻度、*1 回*または*繰り返し*を選択します。
+
*繰り返し* を選択した場合は、レポートを実行する頻度とタイミングを指定します。

. 次のオプション情報を入力します。

.. レポートに含める必要がある*アカウントグループ*。

.. レポートに含める必要がある*クラウドアカウント*。

.. レポートに含める必要がある*クラウドリージョン*。

.. 定期レポートの送信先となる*電子メールアドレス*。事前に選択した通知テンプレートを使用する場合は、「カスタムメールテンプレート」チェックボックスを選択します。

. *[レポートの保存]*を選択します。


[#id0800bded-7633-40c6-836f-16d29fdf89a7]
=== レポートの表示および管理

コンプライアンスレポートは、一度生成されると、スケジュールされた時刻に自動的に実行されます。*Reports （レポート）> Compliance（コンプライアンス）*を選択すると、使用可能なすべてのxref:../reports/create-and-manage-reports.adoc#compliance[コンプライアンスレポート]のリストが表示されます。

