
== App Service Environment is not zone redundant

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 0da2edec-f295-4452-8312-47912edfb1c8

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AppServiceEnvironmentZoneRedundant.py[CKV_AZURE_231]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is designed to verify if the App Service Environment is zone redundant. Zone redundancy refers to the distribution of resources across different geographical zones to ensure business continuity and disaster recovery. A lack of zone redundancy could lead to service disruptions if the zone hosting the App Service Environment faces any unexpected issues such as outages or natural disasters. Therefore, it's crucial to establish zone redundancy to prevent service availability issues and potential data loss.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_app_service_environment_v3
* *Arguments:* zone_redundant

To fix this issue, you need to enable zone redundancy for the App Service Environment by setting the `zone_redundant` attribute to `true`. 

[source,hcl]
----
resource "azurerm_app_service_environment_v3" "example" {
  name                = "example-ase"
  // ...
  zone_redundant = true
}
----

