[#disable-pcds-and-offboard-aws-account]
== Prisma Cloud Data SecurityとオフボードAWSアカウントの無効化

* *Prisma Cloudデータセキュリティを無効にする*
+
** *設定 > クラウドアカウント*AWSアカウントを選択し、データセキュリティを無効にする*編集*をクリックし,*データセキュリティ*のオプション選択を解除します。Prisma Cloudは、アカウントのS3バケットに保存されているデータ取り込みを停止します。Prisma Cloud上では、以前のスキャンによるデータセキュリティ情報は削除されず、データセキュリティが有効な期間に生成されたアラートにアクセスできます。
+
このAWSアカウントでData Securityを再有効化する予定がない場合は、SNSトピックを削除することで、SNSトピックがPrisma Cloudにメッセージを送信する追加コストを回避することができます。Prisma Cloud専用に設定した場合は、CloudTrailバケットへのS3イベントの送信を停止することもできます。

** Data Securityは *Setting(設定)> Cloud Accounts(クラウドアカウント)*で簡単に再有効化できます。データセキュリティを有効にするには、AWS アカウントを選択し、*編集*をクリック、*データセキュリティ*オプションを選択します。Prisma Cloudがデータの取り込みを再開し、利用料金が再開されます。すべてのデータ（データセキュリティを無効にする前）と新しいデータ（データセキュリティを再度有効にした後）が利用可能になります。

* *24時間以内にAWSアカウントをオフボードおよびオンボード*
+
** データセキュリティが有効化され、すでにオンボードしているAWSアカウントをオフボードにすると、アラートを含むすべてのスキャンデーがUIやAPIで利用不可となります。Prisma Cloudは、アカウントに保存されたデータの追加取り込みを停止します。

** 24 時間以内に同じ AWS アカウントを追加し、データセキュリティを有効化すれば、以前にスキャンされたすべてのデータが UI と API で再び使用可能となります。アカウントをオフボードする以前に生成された、すべてのアラートが表示されます。例えば、未解決アラートは未解決のまま、解決済みは解決済みです。Prisma Cloudはアカウントのデータ取り込みを再開します。

* *24時間後にAWSアカウントをオフボードおよびオンボード*
+
** データセキュリティが有効化され、すでにオンボードしているAWSアカウントをオフボードにすると、アラートを含むすべてのスキャンデーがUIやAPIで利用不可となります。Prisma Cloudは、アカウントに保存されたデータの追加取り込みを停止します。

** アカウントが24時間以上オフボードになると、Prisma Cloudはテナント内のデータセキュリティに関連するスキャン済みのデータをすべて削除します。

** Prisma Cloudは新しいS3データの取り込みを停止するため、データセキュリティの追加料金も発生しなくなります。

** 24時間後に同じAWSアカウントにオンボードし、Data Securityを有効にすると、Prisma Cloudはそのアカウントに対して再度は最初からデータの取り込みを開始し、利用料金の課金を開始します。（Data Securityを再有効化後の）新しいデータのみが表示されます。過去にスキャンされたデータは、その期間に発生したアラートを除き、すべて利用できなくなります。
+
[NOTE]
====
元のアラートが解決済になるわけではなく、新規アラートが同じオブジェクトに作成され、同じオブジェクトに重複するアラートが作成されます。
====

* *以前にPrisma Cloud DataSecurityが有効になっていたAWSアカウントをオフボードする*
+
** AWSアカウントが24時間以上オフボードさ れた後、Prisma Cloudは以前にスキャンされたすべてのデータとアラートを削除します。

** このAWSアカウントでData Securityを再有効化する予定がない場合、SNSトピックを削除することで、SNSトピックがPrisma Cloudにメッセージを送信する追加コストを回避することができます。Prisma Cloud専用に設定した場合は、CloudTrailバケットへのS3イベントの送信を停止することもできます。
