[#cost-implications-and-control]
== Prisma Cloudのデータセキュリティコストを最適化するためのガイドライン

[#id7e3df400-4ae8-4d23-a29f-4341a24adbbb]
=== コストへの影響と管理
* Prisma Cloudは、CloudTrailによって公開された*データイベント*を利用して、変更を追跡します。これらは、圧縮ログファイルとしてS3バケットにエクスポートされます。これらのログファイルが不要なストレージコストに寄与しないようにするために、Prisma Cloudは、バケットに*1か月のTTL*（存続時間）のバケットライフサイクルポリシーを設定することをお勧めします。これにより、ファイルが月額料金モデルに寄与しないことが保証されます。

* 読み取りと書き込みの代わりに、データ書き込みイベントに対してCloudTrailを有効にします。一般に、読み取りイベントの量は書き込みイベントよりも桁違いに多く、AWSではどちらか一方のみ、または両方を有効にする柔軟性を備えています。Prisma Cloud Data Security機能は現在、読み取りイベントを利用していません。

* Prisma Cloudは、アクティブなCloudTrailバケットと非アクティブなCloudTrailログ、ELBアクセスログ、VPCフローログ、S3アクセスログを、これらのログを他のオブジェクトと区別する方法に関するAWSのドキュメントに基づいて、ベストエフォートベースで自動的にスキップします。Prisma Cloudでは、通常、機密情報は含まれておらず、データセキュリティリスクにさらされないため、これらすべてをスキップしています。ただし、AWSがログ形式を変更する可能性があるため、Prisma Cloudがすべての可能なログをキャッチできるという保証はありません。


[#api-throttling-and-egress-implications]
=== APIスロットリングと出力への影響
* このソリューションは、クラウドサービスプロバイダ（CSP）API駆動型であり、他のCSP APIと同じスロットルを実行します。

* このソリューションでは、クライアント側でAPIスロットリングを行い、CSPが実施するAPIレート制限を使いすぎたり、乱用したりしないようにします。

* クライアント側のレート制限機能は、API制限の完全なクォータがデフォルトで消費されないようにして、プロセスまたはアプリケーションAPIの使用を中断させないようにします。

* ストレージシステムからダウンロードされたデータは、Prisma Cloudインフラストラクチャのどこにも保持されず、データプロファイル分析のためにコンテンツを処理している間のみ保持されるか、最大タイムアウト制限（24時間）のいずれか早い方で制限されます。

* Prisma Cloud Data SecurityがS3バケット内のすべてのコンテンツを評価するため、出力コストに影響があります。スキャンが必要なバケットを選択し、データベースバックアップファイルなど、データプロファイル分析やマルウェア分析を必要としない既知の正常なファイルを除外するだけで、コストを最適化することを選択できます。