== PlanetScale Token detected in code


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_58
|Category |API & Service Keys
|Provider |
|Severity |LOW
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


PlanetScale offers a managed database platform that is designed for developers and developer workflows.
The PlanetScale CLI allows developers to create development branches, open deploy requests, and make non-blocking schema changes directly from a terminal.
PlanetScale provides the ability to create service tokens for your PlanetScale organization via the CLI or directly in the UI.
Service tokens are not recommended for connecting to production databases.
Instead, connect securely to your database using PlanetScale connection strings.

=== Fix - Buildtime


*PlanetScale* 



. Go to the service tokens page for your organization: app.planetscale.com

. Click on the service token ID for the service token you would like to delete.

. Click on the "Delete service token" button in the upper right hand corner.

. Confirm deletion by clicking the "Delete" button in the pop-up modal.

. Deleting a service token will sever any database connections that use the given service token.
