== Fastly Personal Token detected in code


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_41
|Category |API & Service Keys
|Provider |
|Severity |LOW
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


Fastly's API tokens are unique authentication credentials assigned to individual users.
You need to create an API token to use the Fastly API.
You can use API tokens to grant applications restricted access to your Fastly account and services.
For example, an engineer user could limit a token to only have access to a single service, and restrict the scope to only allow that token to purge by URL.
Every Fastly user can create up to 100 API tokens.

=== Fix - Buildtime


*Fastly To delete an account API token or to revoke another user's API token as a superuser, follow the steps below:* 



. Log in to the Fastly web interface and click the Account link from the user menu.
+
Your account information appears.

. Click the Account API tokens link.
+
The Account API Tokens page appears with a list of tokens associated with your organization's Fastly account.

. Find the API token you want to delete and click the trash icon.
+
A warning message appears.

. Click the Delete button to permanently delete the API token.
