== Braintree Access Token detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_78
|Category |API & Service Keys
|Provider |
|Severity |MEDIUM
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
A Braintree Access Token is a type of authentication token used to access the Braintree API. Braintree is a payment gateway service that enables merchants to accept online payments securely and efficiently. The Braintree Access Token allows merchants to securely authenticate their applications and make API calls to the Braintree server on behalf of their customers.

=== How to Fix


*Braintree* 

. Log in to your Braintree account at https://www.braintreegateway.com/login.
. Click on the gear icon in the upper right-hand corner of the screen to access your Account Settings.
. Select the API tab.
. Under the API Keys section, locate the Access Tokens section and click on the Revoke button next to the Access Token that you want to revoke.
. A pop-up window will appear asking you to confirm the revocation. Click on the Revoke button to confirm.
. The Access Token will be revoked and will no longer be valid for making API requests to Braintree.
