== Azure Storage Account without Secure transfer enabled
// Ensure that 'supportsHttpsTrafficOnly' is set to 'true'.

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| bc4e467f-10fa-471e-aa9b-28981dc73e93

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/arm/checks/resource/StorageAccountsTransportEncryption.py[CKV_AZURE_3]

|Severity
|LOW

|Subtype
|Run,Build

|Frameworks
|Terraform, ARM, Bicep

|===

=== Description

This policy detects whether the `supportsHttpsTrafficOnly` property for Azure Storage Accounts is configured to `true`. Azure Storage Accounts offer the capability to store various data types such as blobs, files, queues, tables, and disks. By setting this property, only HTTPS traffic is permitted to access the storage service. Securing the transport of this data is crucial to prevent eavesdropping and man-in-the-middle attacks. HTTPS encryption ensures that the data transmitted between the client and server remains encrypted, thereby enhancing the security of data in transit.

Note: Since API version 2019-04-01, the default value for `supportsHttpsTrafficOnly` is `true`. However, it's essential to verify this setting for Storage Accounts, particularly those created before this API version.

=== Fix - Buildtime

*Terraform*

*Resources:*
- azurerm_storage_account

*Arguments:*
- enable_https_traffic_only

In this example, `enable_https_traffic_only` is explicitly set to `true` to force HTTPS only traffic.

[source,go]
----
resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

+ enable_https_traffic_only = true  # Ensure only HTTPS traffic is allowed.
}

----


*Azure Resource Manager (ARM)*

*Resources:*
- Microsoft.Storage/storageAccounts

*Arguments:*
- properties/supportsHttpsTrafficOnly

In this example, `supportsHttpsTrafficOnly` is explicitly set to `true` to force HTTPS only traffic.

[source,json]
----
{
  "type": "Microsoft.Storage/storageAccounts",
  "apiVersion": "2020-08-01-preview",
  "name": "mystorageaccount",
  "location": "westus",
  "properties": {
+     "supportsHttpsTrafficOnly": true   # Ensure the storage service allows HTTPS traffic only.
     # ... other configurations ...
  }
}
----
