== Azure Synapse SQL Pool does not have a security alert policy

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/SynapseSQLPoolHasSecurityAlertPolicy.yaml[CKV2_AZURE_51]

|Severity
|INFO

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|===

=== Description

This policy detects whether a Synapse SQL Pool has a security alert policy configured. A security alert policy is used to set up alerts for specific security incidents, abnormal activities, and threats in the SQL pool. This is crucial for real-time monitoring and maintaining the security posture of a Synapse workspace, helping to ensure the protection of your data.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_synapse_sql_pool
* *Arguments:* azurerm_synapse_sql_pool_security_alert_policy

Configure a security alert policy for your Synapse SQL Pool. Associate each `azurerm_synapse_sql_pool` resource with a `azurerm_synapse_sql_pool_security_alert_policy` block. This block defines the security alert policies for the pool.

In this example, a security alert policy for an Azure Synapse SQL Pool is configured using Terraform templates.

[source,go]
----
resource "azurerm_synapse_sql_pool" "example" {
  name                 = "examplesqlpool"
  ...
}

+ resource "azurerm_synapse_sql_pool_security_alert_policy" "example" {
+   sql_pool_id                = azurerm_synapse_sql_pool.example.id
+   policy_state               = "Enabled"
+   ...
+ }
----
