
== Databricks Workspaces not using customer-managed key for root DBFS encryption

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/DatabricksWorkspaceDBFSRootEncryptedWithCustomerManagedKey.yaml[CKV2_AZURE_48]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan,ARM,Bicep

|===

=== Description

This policy is checking to ensure that Databricks Workspaces is using a customer-managed key for root DBFS encryption. DBFS, or Databricks File System, is a distributed file system installed on Databricks clusters. The encryption of this file system adds an extra layer of security, ensuring that even in the event of unauthorized access, the data remains inaccessible and secure. The use of a customer-managed key gives users more control and responsibility over their encryption strategy. The failure to use these keys can open up potential security risks, such as key mismanagement or unauthorized encryption key access. Therefore, it's essential to have this policy in place to maintain a robust security posture.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_databricks_workspace,azurerm_databricks_workspace_root_dbfs_customer_managed_key
* *Arguments:* sku,customer_managed_key_enabled

To fix the issue, you have to specify the `customer_managed_key_enabled` attribute while creating the Azure Databricks workspace. This property indicates the customer-managed key to use for encrypting DBFS root data at rest.

[source,go]
----
resource "azurerm_databricks_workspace" "databricks_workspace_good" {
  ...
  customer_managed_key_enabled = true
}

resource "azurerm_databricks_workspace_root_dbfs_customer_managed_key" "databricks_workspace_good" {
  workspace_id     = azurerm_databricks_workspace.databricks_workspace_good.id
  key_vault_key_id = "123456"
}
----

*ARM*

* *Resource:* Microsoft.Databricks/workspaces
* *Arguments:* prepareEncryption/value

To fix the issue, you have to specify the `customer_managed_key_enabled` attribute while creating the Azure Databricks workspace. This property indicates the customer-managed key to use for encrypting DBFS root data at rest.

[source,json]
----
"resources": [
  {
    "type": "Microsoft.Databricks/workspaces",
    "properties": {
      ...
      "parameters": {
        "prepareEncryption": {
+          "value": true
        },
+        "encryption": {
+          "value": {
+            ...
+          }
        },
      }
    }
  }
]
----