
== Azure Synapse SQL pool is not encrypted

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/SynapseSQLPoolDataEncryption.py[CKV_AZURE_241]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy ensures that Synapse SQL pools in Microsoft Azure are encrypted. Encryption is vital for protecting sensitive data from unauthorized access and breaches. By enforcing encryption, the policy aims to safeguard the confidentiality and integrity of the data stored within the SQL pools. Failing to encrypt this data could leave it vulnerable to cyberattacks, resulting in potential data leaks, financial losses, and damage to an organization's reputation.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_synapse_sql_pool
* *Arguments:* data_encrypted

To fix this issue, ensure that `data_encrypted` is set to `true` for your `azurerm_synapse_sql_pool` resource.

[source,go]
----
resource "azurerm_synapse_sql_pool" "example" {
  ...
+  data_encrypted = true
}
----
