
== Azure Synapse Spark Pool not using isolated compute

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureSparkPoolIsolatedComputeEnabled.py[CKV_AZURE_242]

|Severity
|INFO

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan, ARM, Bicep

|===

=== Description

This policy detects whether isolated compute is disabled for Synapse Spark pools in Azure. Isolated compute utilizes dedicated resources that are not shared with other customers. This isolation minimizes data breach and unauthorized access risks, enhancing security for your Spark pools. Enabling isolated compute is crucial for maintaining high security standards, especially when handling sensitive data or running critical applications within Synapse Spark pools.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_synapse_spark_pool
* *Arguments:* compute_isolation_enabled

Enable isolated compute in your Azure Synapse Spark pool: Set the compute_isolation_enabled property to true in the pool's configuration.

[source,go]
----
resource "azurerm_synapse_spark_pool" "example" {
  ...
  compute_isolation_enabled = true
}
----


*ARM*

* *Resource:* Microsoft.Synapse/workspaces/bigDataPools
* *Arguments:* properties/isComputeIsolationEnabled

In this example, the `properties/isComputeIsolationEnabled` property is set to `true` within the `properties` section of the `Microsoft.Synapse/workspaces/bigDataPools` resource definition.

[source,json]
----
{
  ...
  "resources": [
    {
      "type": "Microsoft.Synapse/workspaces/bigDataPools",
      ...
      "properties": {
        ...
        "isComputeIsolationEnabled": true,
      }
    }
  ]
}
----

