
== Azure Microsoft Defender for Cloud set to Off for Resource Manager

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 26ae483e-0df3-4721-833a-c2facfb4d2f2

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureDefenderDisabledForResManager.py[CKV_AZURE_234]

|Severity
|MEDIUM

|Subtype
|Run,Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is designed to ensure that Azure Defender for the cloud is enabled for the Resource Manager. Azure Defender is a key security feature, providing threat protection for workloads running in Azure, on-premises, and in other clouds. If Azure Defender is not enabled, it can open up the system to potential threats, data breaches, and other cyber attacks. The Resource Manager is a key management component, therefore not having proper security measures in place for it increases the risk of unauthorized access and potential harm to resources. In short, having Azure Defender turned on for the Resource Manager increases the overall security posture of the cloud setup.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_security_center_subscription_pricing
* *Arguments:* resource_type, tier


[source,go]
----
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "Arm"
  ...
}
----

In the code above, Azure Defender for Cloud- which is a cloud native security service, has been enabled for the Resource Manager. Once Azure Defender is enabled, it extends Azure Security Center's capabilities to workloads that are hosted inside Azure Resource Manager. 
