== Default VPC is planned to be provisioned misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_148
|Category - Subcategory |Networking - VPC/VCN/VNET
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
A default VPC is a VPC that is created for your AWS account when you create an AWS account.
It includes a default security group and a default network access control list (NACL).
Default VPCs have some limitations that might not be suitable for all use cases.
Therefore, if you have specific requirements for your VPC, such as custom IP address ranges, support for PrivateLink or Transit Gateway, or the ability to delete the VPC, it might be more appropriate to create a custom VPC instead of using the default VPC.

=== How to Fix


*Terraform* 


It is recommended for this resource to not be configured


[source,go]
----
resource "aws_default_vpc" "default" {
            tags = {
                Name = "Default VPC"
            }
        }
----
