
== AWS Load Balancers do not use strong ciphers

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/LBWeakCiphers.yaml[CKV2_AWS_74]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

The policy is checking whether AWS Load Balancers are configured to use strong encryption ciphers for secure communication. Using weak or outdated encryption ciphers can expose data to interception or manipulation during transmission, making it easier for attackers to exploit vulnerabilities and compromise sensitive information. By ensuring that only strong ciphers are used, organizations can enhance the security of their network traffic, protect customer data, and comply with industry security standards and regulations.

=== Fix - Buildtime

*Terraform*

To ensure that AWS Load Balancers use strong ciphers, configure the `ssl_policy` argument. Select a pre-defined policy that enforces the use of strong encryption methods.

[source,go]
----
resource "aws_lb" "example" {
   ...
+   ssl_policy = "ELBSecurityPolicy-TLS-1-2-2017-01"
   ...
}
----

