== Azure Batch Account configured with overly permissive network access

=== Rule Details

[width=45%]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_248
|Category |NETWORKING
|Provider |AZURE
|Severity |HIGH
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |5e1ba43e-121a-4e71-b5e6-d8f8091fe7cd
|===


=== Description

Azure Batch Accounts with unrestricted network access are vulnerable to unauthorized access and compromise. Publicly accessible Batch Accounts allow any entity to connect and potentially execute malicious code or exfiltrate data.

Azure Batch Accounts misconfiguration exposes the account to attacks from untrusted IPs. Malicious actors could exploit this open access to deploy malware, access sensitive data, or perform denial-of-service attacks. Restricting access mitigates these risks significantly.

The impact of this misconfiguration could include data breaches, unauthorized resource consumption, and service disruptions. Enforcing restricted network access ensures only authorized entities can interact with the Batch Account, enhancing security posture and reducing the attack surface.

Implement network restrictions using either an IP firewall to allow only specific IP addresses or address ranges, or by integrating with a Virtual Network for enhanced security. Regularly review and update these allowed IP addresses and Virtual Network configurations to maintain optimal security.

=== Fix - Buildtime

*Terraform*

Ensure your Azure Batch account does not have public network access enabled by setting `public_network_access_enabled` to false and do not set `default_action` to `allow`.

[source,go]
----
resource "azurerm_batch_account" "example" {
  ...
-  public_network_access_enabled       = true
+  public_network_access_enabled       = false
  network_profile {
    account_access {
-      default_action = "allow"
    }
  }
}
----

*ARM*

Ensure your Azure Batch account does not have public network access enabled by setting `publicNetworkAccess` to disabled and do not set `defaultAction` to allow.

[source,json]
----
{
  ...
  "resources": [
    {
      "type": "Microsoft.Batch/batchAccounts",
      "apiVersion": "2024-02-01",
      "name": "example",
      "properties": {
-        "publicNetworkAccess": "Enabled",
        "networkProfile": {
          "accountAccess": {
-            "defaultAction": "Allow"
          }
        }
      }
    }
  ]
}
----

