== Plain-text management Telnet enabled for Interface Management Profile in Palo Alto Networks devices

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_PAN_3
|Category |Networking - Encryption and Protocols
|Provider |
|Severity |MEDIUM
|Framework |Ansible
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This policy detects whether plain-text management Telnet is enabled for Interface Management Profiles in Palo Alto Networks devices. Enabling Telnet for management interfaces, which involves unencrypted communication, can significantly increase the risk of eavesdropping and man-in-the-middle attacks.

=== How to Fix

*Palo Alto Networks*

* *Resource:* panos_management_profile
* *Attribute:* telnet

To mitigate this risk, ensure that the telnet attribute in your panos_management_profile resource is disabled (either set to 'false' or omitted entirely). It is recommended to disable Telnet by explicitly setting this attribute to 'false' or omitting it entirely, thereby encouraging the use of secure communication protocols.

Secure Code Example:

[source,yaml]
----
- name: Example
  tasks:
    - name: Example
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ provider }}'
        name: 'Test profile'
-        telnet: true # telnet defined as true, which is a fail
+        telnet: false # telnet defined as true, which is a fail
----

In this example, setting the `telnet` attribute to false or ensuring it is not configured in the management profile reinforces this policy's requirement, thus securing the Palo Alto Networks device management interface.
