== GCP Kubernetes Engine Clusters have Network policy disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_GCP_12
|Category |Networking - Ingress Controls
|Provider |GCP
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |7d4b6325-1349-400b-bb6a-3ac05387887c
|===


=== Impact
Defining a network policy helps ensure that a compromised front-end service in your application cannot communicate directly with an external interface, for example, a billing or an accounting service several levels down.
Network policy rules can ensure that Pods and Services in a given namespace cannot access other Pods or Services in a different namespace.
We recommend you enable Network Policy on kubernetes engine clusters to determine which Pods and Services can access one another inside your cluster.
This ensures only the required services are communicating and no explicitly indicated traffic is able to reach private clusters.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "google_container_cluster" "pass" {
  name = "google_cluster"
  network_policy {
    enabled = true
  }
}
----

