== Prisma Cloud DSPM Deployment

<<<<<<< HEAD:docs/en/enterprise-edition/content-collections/data-security-posture-management/Prisma Cloud DSPM Deployment/prisma-cloud-dspm-deployment.adoc
Prisma Cloud DSPM can be deployed on different cloud platforms where your data is stored. The deployment process is very simple and includes two major steps:

1. Onboarding Prisma Cloud DSPM Orchestrator to your selected cloud platform environment.
2. Adding accounts from the same cloud platform to be monitored.

After Prisma Cloud DSPM Orchestrator is deployed in your environment, Prisma Cloud DSPM continuously monitors your data and displays insights in the main Prisma Cloud DSPM dashboard.


Prisma Cloud includes out-of-the-box (OOTB) policies that are part of the Prisma Cloud Recommended Policies Pack.

=== Governance at a Glance
=======
.Fragment
|===
| https://main\--prisma-cloud-docs-website\--hlxsites.hlx.page/en/enterprise-edition/dspm/prisma-cloud-dspm-deployment
|===
>>>>>>> origin/dig-docs:docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/prisma-cloud-dspm-deployment.adoc
