== Prisma Cloud DSPM Deployment

Prisma Cloud DSPM can be deployed on different cloud platforms where your data is stored. The deployment process is very simple and includes two major steps:

1. Onboarding Prisma Cloud DSPM Orchestrator to your selected cloud platform environment.
2. Adding accounts from the same cloud platform to be monitored.

After Prisma Cloud DSPM Orchestrator is deployed in your environment, Prisma Cloud DSPM continuously monitors your data and displays insights in the main Prisma Cloud DSPM dashboard.

Prisma Cloud includes out-of-the-box (OOTB) policies that are part of the Prisma Cloud Recommended Policies Pack.


[cols="30%a,70%a"]
|===

|*What do you want to do?*
|*Start here*

|Deploy Prisma Cloud on AWS
|xref:deploy-prisma-cloud-dspm-on-aws.adoc[Deploy Prisma Cloud on AWS]

|Deploy Prisma Cloud on Azure
|xref:deploy-prisma-cloud-dspm-on-azure.adoc[Deploy Prisma Cloud on Azure]

|Deploy Prisma Cloud on GCP
|xref:deploy-prisma-cloud-dspm-on-gcp.adoc[Deploy Prisma Cloud on GCP]

|Deploy Prisma Cloud on Snowflake
|xref:
|Deploy Prisma Cloud on Microsoft
|xref:deploy-prisma-cloud-dspm-on-microsoft-365.adoc[Deploy Prisma Cloud on Microsoft]

|===
