== Onboard GCP Accounts for Agentless Scanning

Prisma Cloud gives you the flexibility to choose between agentless security and agent-based security using Defenders. Agentless scanning lets you inspect the risks and vulnerabilities of a cloud workload without installing an agent or affecting the execution of the workload. Prisma Cloud supports agentless scanning for vulnerabilities and compliance on hosts, clusters, and containers. To learn more about how agentless scanning works, see the xref:../agentless-scanning.adoc[How Agentless Scanning Works?][How Agentless Scanning Works?]

Agentless scanning for GCP accounts can use one of the following xref:../agentless-scanning.adoc#scanning-modes[scanning modes].

To onboard your GCP account for agentless scanning in same account mode you need to complete the following tasks.

. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp[Onboard the GCP project] you want to use for agentless scanning in Prisma Cloud.

. xref:./configure-gcp.adoc[Configure] the onboarded account in Prisma Cloud.

To use the hub account mode, you must complete the following steps.

. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp[Onboard the GCP project] to use as the hub account for agentless scanning to Prisma Cloud.

. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp[Onboard the GCP projects] to Prisma Cloud that you want to scan using Prisma Cloud agentless scanning.

. xref:./configure-gcp.adoc[Configure] the onboarded target accounts to use the onboarded hub account.

include::frag-start-agentless-scan.adoc[leveloffset=1]
