== Fixed and Known Issues in 34.xx

The following table lists the fixed issues for 34.xx releases.

=== Fixed Issues

[cols="23%a,77%a"]
|===
|*ISSUE ID*
|*DESCRIPTION*


|*CWP-63359*
//PCSUP-27651

tt:[Secure the Runtime]

tt:[34.01.126]

|*#IngressNightmare vulnerabilities*

This issue is fixed now.

An enhanced mechanism for identification of packages helps in improved detection of vulnerabilities, such as the #ingressnightmare vulnerability issue. 

This enhancement allows for earlier detection and remediation, proactively mitigating potential exploits.

|*CWP-63421*

tt:[Secure the Runtime]

tt:[34.01.126]

|*The "defended" status for ECS task definitions inocorrectly set to `false`*

ECS task definition entities discovered as part of cloud discovery have a "defended" status. This "defended" status field is set to true if a Fargate defender is detected as installed in one of the containers in the task definition. This "defended" status field was incorrectly set to `false` even when a Fargate defender was installed in one of the containers.

This issue is fixed now.


|*CWP-62961*

tt:[Fixed in 34.00.137]

|*Namespace associations for an image are not refreshed*

When an image that is associated with multiple Kubernetes namespaces is removed from one of the namespaces, the namespace associations for the image are not refreshed and the image continues to list the namespace from which it was removed.

This issue is fixed for on-premise deployments now. 

To enable this fix, you need to:

. Edit the twistlock.cfg file and set the CLEAN_STALE_NAMESPACES flag to true.

. Restart the console.

By default, the flag CLEAN_STALE_NAMESPACES is set to false. When you enable this flag and restart the console, namespaces associated with images are refreshed every 12 hours.


|*CWP-59903*

tt:[Fixed in 34.00.137]

|*Cleanup of system resources after registry scanning*

A new scanner tag is generated when an image is pulled for scanning. In certain cases, this tag was not properly removed after the scan completed.

This issue is fixed now. Improvements to the registry scan mechanism ensure a proper cleanup of system resources after scanning.


|*CWP-60416*

tt:[Fixed in 34.00.137]

| *Incorrect parsing of Ruby advisories that use RC versions*

Incorrect parsing of Ruby advisories that use RC versions (such as '3.0.0-rc.1') caused false positive CVE reporting.  

This issue is fixed now.

|*CWP-61862*

tt:[Fixed in 34.00.137]

| *An incorrect fix date is reported for CVEs that did not provide a fix date initially*

An incorrect fix date is reported for CVEs that did not provide a fix date initially and were then reopened and fixed (again) with a fix date that is later than the date when the issue was first reported as fixed. Prisma Cloud reported the date when the issue was first reported as fixed and did not update the fix date after the issue was reopened and fixed with a different date.           

This issue is fixed now.

|*CWP-62128*

tt:[Fixed in 34.00.137]

| *Changes in the Ubuntu feed caused false positives in some situations*

Changes in the Ubuntu feed format added an asterisk in the condition for some CVE entries. This was not parsed correctly and led to false positives.  

This issue is fixed now.

|*CWP-62193*

tt:[Fixed in 34.00.137]

| *Incorrect fixed version reported for some CVEs reported in NVD*

An issue with the parsing of NVD data led to an incorrect fixed version being reported in some cases.  

This issue is fixed now.

|*CWP-62290*

tt:[Fixed in 34.00.137]

| *Fixed Debian issues that have a CVE with the "nodsa\_reason" property set to "ignored" are reported as a vulnerability*

Debian CVEs that have an Urgency of "unimportant" or a "nodsa\_reason" setting of "ignored" in the Debian feed were not reported as vulnerabilities when detected by Prisma Cloud Compute.  

This issue is fixed now. Now, such CVEs will be reported as vulnerabilities with the status 'will not fix' by Prisma Cloud Compute. 

|*CWP-62394*

tt:[Fixed in 34.00.137]

| *In a few situations serverless credits were consumed even after disabling the serverless functionality* 

In setups/tenants that had a particular (core-serverless-scan-concurrent-flow-enabled) setting enabled, serverless scan results were not deleted. This caused some serverless credits to be consumed even after the serverless feature was disabled in the tenant.   

This issue is fixed now.

|*CWP-62552*

tt:[Fixed in 34.00.137]

| *Defender is unable to identify the OpenShift installation on the OpenShift nodes*

The OpenShift version is not available in the RELEASE\_VERSION environment variable in the running 'openshift-tuned' process due to a change in OpenShift. It has now been replaced by a new process called cluster-node-tuning-operator that receives 'openshift-tuned' via command line args. Defenders were unable to detect the OpenShift installation due to this change.  

This issue is fixed now. 

|*CWP-62562*

tt:[Fixed in 34.00.137]

| *Fixed RHEL issues are incorrectly flagged as unresolved due to an issue in mapping CPEs to RHEL repositories*

After Redhat switched to the new VEX format for reporting CVEs and fixes, some fixed RHEL issues were incorrectly flagged as unresolved due to an issue in mapping CPEs to RHEL repositories.   

This issue is fixed now.

|*CWP-62570*

tt:[Fixed in 34.00.137]

| *Base images when scanned separately  displayed vulnerabilities that were not present*

The scan results for some base images that were scanned separately incorrectly displayed vulnerabilities–even though no vulnerabilities were present in those base images. Whereas, images using those base images reported the vulnerabilities correctly and did not display any vulnerabilities for the underlying base images.  

This issue is fixed now.

|*CWP-62575*

tt:[Fixed in 34.00.137]

| *False positives observed for vulnerabilities reported in the RedHat VEX format without specific distro-release information*

Vulnerabilities reported in the RedHat VEX format without specific distro-release information generated false positives. 

This issue is fixed now. 

|*CWP-62590*

tt:[Fixed in 34.00.137]

|*Prisma Cloud reported incorrect fix dates for RedHat vulnerabilities*

This issue occurred for vulnerabilities reported as fixed through RedHat feeds in the VEX format.  
This issue is fixed now.


|*CWP-62609*

tt:[Fixed in 34.00.137]

| *Including packages of a Go application that are part of the main module in the scan results*

Previously, Prisma Cloud scan results did not include Go packages that were part of the main module, resulting in the omission of these packages and their associated vulnerabilities in the console. 

This issue has now been resolved.

|*CWP-62668*

tt:[Fixed in 34.00.137]

| *Compliance check 598 always fails for Kubernetes containers running Redis if the container was created without using –requirepass parameter*

Compliance check 598 fails and shows the error “App uses weak or default password” for Kubernetes containers running redis even though the container uses a strong password. This issue occurs if the container was created without using –requirepass parameter.  

This issue is fixed now.

|*CWP-62883*

tt:[Fixed in 34.00.137]

| *The 'fix status' column in the vulnerability report is blank for a few CVEs*

The 'fix status' column in the vulnerability report is blank for a few CVEs due to missing information in the NVD vulnerability feed.  

This issue is fixed now. The required information is now gathered using a separate NVD function.


|*CWP-62884*

tt:[Fixed in 34.00.137]

|*Stale unpaired cloud security agents (CSAs) are not deleted*

This issue is fixed now.

|*CWP-62994*

tt:[Fixed in 34.00.137]

| *Container protected by an App embedded defender with File System monitoring enabled crashes when an SSH connection is made to it*

Container protected by an App embedded defender with File System monitoring enabled crashes when an SSH connection is made to it.

This issue is fixed now.

|*CWP-63032*

tt:[Fixed in 34.00.137]

| *Support Jenkins LTS CVEs detection*

Prisma Cloud now extracts software edition information from CVEs and utilizes it for scanning. This enables Prisma Cloud scanners to differentiate software editions, such as Jenkins LTS releases from regular Jenkins releases, and accurately identify vulnerabilities.


|*CWP-63033*

tt:[Fixed in 34.00.137]

| *Improved Vulnerability Reporting for Mirrored RHEL Repositories*

Repository identifiers often change when repositories are mirrored from Red Hat's Content Delivery Network (CDN) to alternative cloud environments, like AWS. This may result in inaccurate vulnerability reporting. 

The issue has now been resolved by extracting the relative URLs of repositories from the image and comparing them with the corresponding relative URLs provided in the repository-to-CPE mapping file for CVE matching.


|*CWP-63110*

tt:[Fixed in 34.00.137]

| *Incorrect data is returned when Prisma Cloud roles that have read only access to Windows hosts try to access and retrieve data from those Windows hosts*

Incorrect data is returned when Prisma Cloud roles that have read only access to Windows hosts try to access and retrieve cloud metadata from those Windows hosts. 

This issue is fixed now.
|===

=== Known Issues

The following table lists the known issues for the 34.00 release.

[cols="23%a,77%a"]
|===
|*ISSUE ID*
|*DESCRIPTION*


|*CWP-63673*
//CWP-63673

tt:[Secure the Runtime]

tt:[34.01.126]

|*RedHat Enterprise Linux 10 incompatibility with  WAAS Defender Agent*

RedHat https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_networking[deprecated iptables in RHEL 9] and the upcoming RHEL 10 will not support iptables.

The WAAS defender agent deployed directly on RHEL10 (as Host Defender), which relies on iptables, is incompatible with RHEL 10 due to this change. A fix is in progress and is expected to be included in the August release.

NOTE:  Containerized varieties of the WAAS Defender will continue to work.  

|*CWP-63632*

tt:[Secure the Runtime]

tt:[34.01.126]

|*Host details display incorrect Windows version*
//CWP-63632

Windows Server 2025 is incorrectly reported as Windows Server 2022 on the Host details panel. 


|*--*

|*Support for scanning Cloud Run Functions ("Gen2")*

Google provides serverless functions in two different versions: the original Cloud Functions service ("Gen1") and the new Cloud Run Functions ("Gen2"), where code executes in a fully managed environment in Cloud Run.

Prisma Cloud vulnerability scanning for serverless functions fully supports the Gen1 version. We're actively working to ensure full support for scanning Gen2 functions as well. We'll update this page in the coming days with further details.


|*CWP-62339*
// tt:[Found in 32.06.113]

|*Discrepancies in Vulnerability Scan Results*

In rare instances, discrepancies were observed between vulnerability scan results from Defender and Twistcli host scans. 

For example, certain compliance checks identified by Twistcli were not reflected in Defender scan results, and vice versa. Additionally, for some operating systems, Twistcli reported a higher number of high-severity findings compared to Defender.

|===
