:toc: macro
== 34.04.160 Hotfix Release Notes

The following table has the release details:

[cols="1,4"]
|===
|Build
|34.04.160

|Code name
|Quinn Update 4

|Release date
|May, 2026

|Type
|Minor release

|SHA-256
|9099536097666d5bce8108135c0bf04857f9c0f5f94412c275faefb0a560e0f8
|===

Review the https://docs.prismacloud.io/en/compute-edition/34/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

// https://cdn.twistlock.com/releases/daxCEyCH/prisma_cloud_compute_edition_console_34.04.145.tar.gz[https://cdn.twistlock.com/releases/AQSilBiU/prisma_cloud_compute_edition_console_34.04.156.tar.gz]

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defenders

With the `v34.00` release, the https://docs.prismacloud.io/en/compute-edition/34/admin-guide/upgrade/support-lifecycle[supported Defender releases (n, n-1, and n-2)] are `v34`, `v33`, and `v32` respectively. In addition, Prisma Cloud will not restrict the usage of Defender versions or REST API calls from the n-3 releases. So, the current release will allow Defenders and REST API calls from release `v31` also. Failure to upgrade Defenders below release `v31`, such as `v30.03`, will result in disconnection of the Defenders from the Console.

However, to maintain full support, you must upgrade your Defenders to a `v32.xx` or later release.

To summarize, the level of support for the different versions of Defenders is as follows:

* Defender versions 34.xx, 33.xx, and 32.xx have full support
* Defender versions 31.xx are functional (will be able to connect to version 34.00 Console) but support is not available for such Defenders
* Defender versions previous to 31.00, such as 30.03, are neither supported nor functional (cannot connect to version 34.xx Console)


[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the `v34.00` release, the https://docs.prismacloud.io/en/compute-edition/34/admin-guide/upgrade/support-lifecycle[supported Console releases (n, n-1, and n-2)] are `v34`, `v33`, and `v32` respectively. 

NOTE: Defenders from the n-3 release will remain functional as described above. 

You can upgrade the Prisma Cloud console directly from any n-1 or n-2 version to n. For example, with `v34` as n and `v33` as n-1, you can upgrade directly from `33.01.137` to `34.00.141`. You can also upgrade directly from an n-2 version (`32.00.161`, `32.01.128`, `32.02.127`, `32.03.123`, `32.04.113`, `32.05.124`, `32.06.113`, `32.07.123`) to `34.00.141`.


[#enhancements]
=== Enhancements
[cols="30%a,70%a"]
|===
|*Feature*
|*Description*

|*Add configurable cap for per-image clusters*
//CWP-64787

|Added a configurable cap on the number of clusters stored per image in MongoDB, preventing excessive document growth for widely-deployed images.

|*Support OCI compartment OCID in addition to compartment name*
//No Jira ticket - Tommer MD file

|Added support for specifying OCI compartments by OCID in addition to compartment name for agentless scanning configuration.

|*Augment binary packages PURLs*
//CWP-64789

|Added Package URL (PURL) augmentation for binary packages, improving software composition analysis accuracy.

|===

[#security-fixes]
=== Security Fixes

[cols="23%a,77%a"]
|===
|*ISSUE ID*
|*DESCRIPTION*


|*Upgrade xmlquery to avoid CVE-2026-32287*
//CWP-64762

|Upgraded xmlquery (and xpath) dependencies to remediate CVE-2026-32287.


|*Remove libnghttp2 from Defender Dockerfile*
//CWP-64794
|Removed the libnghttp2 package from the Defender container image to eliminate a known vulnerability..


|*Bump MongoDB to 7.0.31*
//No ticket 

|Updated MongoDB from 7.0.29 to 7.0.31 to address additional security vulnerabilities.


|===
