:toc: macro
== 34.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|34.00.137

|Code name
|Quinn

|Release date
|March 17, 2025

|Type
|Major release

|SHA-256
|84c4a3f8ec7debab19583159def8ef396ba27f32611f0f969b3f12d08ae0b3b9
|===

Review the https://docs.prismacloud.io/en/compute-edition/34/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

// https://cdn.twistlock.com/releases/orvGojie/prisma_cloud_compute_edition_33_00_169.tar.gz[https://cdn.twistlock.com/releases/orvGojie/prisma_cloud_compute_edition_33_00_169.tar.gz]

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defenders

With the `v34.00` release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported Defender releases (n, n-1, and n-2)] are `v34`, `v33`, and `v32` respectively. In addition, Prisma Cloud will not restrict the usage of Defender versions or REST API calls from the n-3 releases. So the current release will allow Defenders and REST API calls from release `v31` also. Failure to upgrade Defenders below release `v31`, such as `v30.03`, will result in disconnection of the Defenders from the Console.

However, to maintain full support, you must upgrade your Defenders to a `v32.00` or a higher release.

To summarize, the level of support for the different versions of Defenders is as follows:

* Defender versions 34.xx, 33.xx, and 32.xx have full support
* Defender versions 31.xx are functional (will be able to connect to version 34.00 Console) but support is not available for such Defenders
* Defender versions previous to 31.00, such as 30.03, are neither supported nor functional (cannot connect to version 34.xx Console)


[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the `v34.00` release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported Console releases (n, n-1, and n-2)] are `v34`, `v33`, and `v32` respectively. 

NOTE: Defenders from the n-3 release will remain functional as described above. 

You can upgrade the Prisma Cloud console directly from any n-1 version to n. For example, with `v34` as n and `v33` as n-1, you can upgrade directly from `v33.01.137` to `v34.00.139`.

NOTE: You have to upgrade any version of `v32` to `v33` before upgrading to `v34`. For example, you can upgrade from `v32.05.124` to `v33.03.138` before you upgrade to `v34.00.137`.


// [#announcement]
// === Announcement

// [#cve-coverage-update]
// === CVE Coverage Update

[#enhancements]
=== Enhancements
[cols="30%a,70%a"]
|===
|*Feature*
|*Description*

|*Jira Authentication Update for Prisma Cloud Runtime Alerts*
//CWP-63063

|Jira Cloud has deprecated Basic Authentication with passwords and now requires API tokens for authentication. When integrating Prisma Cloud Runtime with Jira as an alert provider, you must use an API token instead of a username-password combination.

*Required Actions*

To set up a new alert profile for Jira Cloud users, do the following:

. Generate an API token from your Jira Cloud account.
+ 
For more information, see https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/[Manage API tokens for your Atlassian account] topic in Jira Documentation site.
. Save the token in Prisma Cloud’s Credentials Store and use this new credential when adding a new Jira Alert profile.
+ 
For more information, see https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/alerts/jira#adding-api-tokens-in-credentials-store-for-jira-cloud-authentication[Adding Jira Cloud Credentials] topic in the Prisma Cloud Admin Guide.

To update an existing alert profile for Jira Cloud users, do the following:

. Generate an API token from your Jira Cloud account.
+ 
For more information, see https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/[Manage API tokens for your Atlassian account] topic in the Jira Documentation site.

. Update the credentials by replacing the password with the API token.
+ 
For more information, see https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/alerts/jira#updating-jira-cloud-credentials-to-use-an-api-token[Updating Jira Cloud Credentials] topic in the Prisma Cloud Admin Guide.


To set Up a new alert profile for Jira Data Center (DC) users, do the following:

. Generate a personal access token from your Jira DC account.
+
For more information, see https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html[Using Personal Access Tokens] topic in the Jira Documentation site.

. Configure the credentials using Basic Authentication with your username and the personal access token as the password when adding a new Jira Alert profile.
For more information, see https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/alerts/jira#adding-api-tokens-in-credentials-store-for-jira-dc-authentication[Adding Jira DC Credentials] topic in the Prisma Cloud Admin Guide.

|Customization for Scanning Amazon Machine Images (AMIs)
//CWP-49786

|Prisma Cloud now offers on-prem users greater flexibility in selecting AMIs.

For on-prem users, the following environment variables enable customization: 

* `AGENTLESS_USE_CUSTOM_AMI` – Enables or disables the use of custom AMIs.

* `AGENTLESS_CUSTOM_AMI_PER_REGION` – Specifies custom AMIs per AWS region

*Example Configuration:*

`AGENTLESS_USE_CUSTOM_AMI=true`
`AGENTLESS_CUSTOM_AMI_PER_REGION='{"us-east-1":"ami-005fc0f236362e99f"}'`

In this example, the custom AMI (`ami-005fc0f236362e99f`) is used in the 'us-east-1' region.
 
*Behavior Based on Configuration:*

* If `AGENTLESS_USE_CUSTOM_AMI` is `false`, Prisma Cloud falls back to the previous scanner image, which is Ubuntu 20.04.

* If `AGENTLESS_USE_CUSTOM_AMI` is set to `true` but `AGENTLESS_CUSTOM_AMI_PER_REGION` is not set, Prisma Cloud uses the LaunchDarkly (LD) custom AMI list.

* If `AGENTLESS_USE_CUSTOM_AMI` is not set, Prisma Cloud defaults to the LD custom AMI list.

* For Cloud (SaaS) users, no action is required—Prisma Cloud automatically selects the latest optimized AMI.


|Better utilization of vendor-specific feeds
//CWP-62711

|The National Vulnerability Database (NVD) provides a valuable baseline CVSS score for vulnerabilities. However, vendors often have a more granular understanding of how a specific vulnerability impacts their implementation of a component. This allows them to provide a more accurate CVSS score, especially when considering environmental factors and the specific ways their product utilizes the vulnerable component. In some cases, vendor-specific vulnerability feeds may have the latest CVSS scores before they are reflected in NVD.

This release leverages additional data from vendor-specific vulnerability feeds, such as those from RedHat, Photon OS, and Ruby Gems, and implements several improvements in the extraction and reporting of CVSS scores. These changes provide more accurate and timely CVSS scores, reflecting the latest vendor-specific mitigations, configurations, and environmental impacts.

*RedHat Security Feed:*
//CWP-62974

* Previously, if a CVE had a CVSS score of 0 in the RedHat security feed, we used the CVSS score provided by NVD for that CVE.

* Now, we use the CVE data and the CVSS score provided by the RedHat feed even if the CVSS score is 0 in the RedHat feed. This ensures that we consider RedHat's specific assessment, which might indicate a mitigated or non-impactful vulnerability in their context.

*Photon OS Security Feed:*
//CWP-62976

* Previously, we extracted CVSS scores for CVEs from the NVD for Photon OS vulnerabilities.

* Now, we use the CVSS scores provided in the Photon OS security feed. This allows us to reflect Photon OS-specific mitigations and impacts more accurately.

*Ruby Gems Security Feed:*
//CWP-62977

* Previously, we ignored the CVSS scores reported by RubySec (https://github.com/rubysec and https://github.com/rubysec/ruby-advisory-db) and used the values from NVD.

* Now, we use the CVSS values provided in the Ruby Advisory DB. This ensures we capture the precise impact and mitigations for Ruby Gems vulnerabilities as assessed by RubySec.

*Amazon Linux Security Feed:*
//CWP-62754)

* Previously, we extracted CVSS scores for Amazon Linux vulnerabilities/CVEs from the NVD.

* Now, we use the CVSS scores provided in the Amazon Linux  security feed. This allows us to reflect Amazon Linux-specific mitigations and impacts more accurately.

*Fallback to NVD CVSS Scores*

If the vendor feed does not provide a CVSS value for any CVE, then the CVSS value from the NVD will be used. This ensures that we always have a CVSS score to guide our risk assessment and mitigation efforts.


|A new Description Field in Create New User screen
//CWP-63066

|A Description field is added to the Create New User screen (Manage > Authentication > Users), allowing additional details to be included for each user.

This field will also be visible in the Users table, which will enable you to refine searches based on the description.

|===


[changes-in-existing-behavior]
=== Changes in Existing Behavior
[cols="30%a,70%a"]
|===
|*Feature*
|*Description*

|Removal of Stale Hosts and Images
//CWP-62948

|We’re implementing a fix that will remove outdated assets that are no longer protected by a Defender. These assets should have been automatically deleted previously, but were not.
With this update, you might notice that certain stale assets are no longer present in your inventory. As a result, you might also see a reduction in vulnerabilities and compliance findings due to their removal.
|===


[#api-changes]
=== API Changes and New APIs
[cols="40%a,60%a"]

|===
|*Feature*
|*Description*

|*Support Description Field*
|A new `Description` parameter has been introduced to the https://pan.dev/prisma-cloud/api/cwpp/get-users/[Get Users] API response. This will help to get more information on the users based on the description field.

|*Support CaaS Specification References Field*
|A new `hasCAASSpecReferences` query parameter has been introduced to https://pan.dev/compute/api/get-registry/[Get Registry Scan Results], https://pan.dev/compute/api/get-registry-download/[Download Registry Scan Results] and https://pan.dev/compute/api/get-registry-names/[Get Registry Image Names] APIs to enable registry image filtering deployed as part of CaaS specifications (AWS Fargate, GCP Cloud Run, ACI). This parameter only applies to Prisma onboarded accounts.

|*Support Images Field*
|A new `images` query parameter has been added to the https://pan.dev/compute/api/get-cloud-discovery-entities/[Get Discovered Cloud Entities] API to filter cloud-discovered entities by the container image names defined in a CaaS specification (AWS Fargate Task Definition, GCP Cloud Run, ACI). This parameter only applies to Prisma onboarded accounts.

|*Support Service Field*
|A new `service` parameter has been introduced to the https://pan.dev/compute/api/get-cloud-discovery-entities/[Get Discovered Cloud Entities] API response to specify the discovered GCP Cloud Run service name. This parameter only applies to Prisma onboarded accounts.

|*Support CaaS Specification References Total Field*
|A new `caasSpecReferencesTotal` parameter has been introduced to https://pan.dev/compute/api/get-hosts/[Get Host Scan Results], https://pan.dev/compute/api/get-images/[Get Image Scan Results], https://pan.dev/compute/api/get-policies-compliance-container-impacted/[Get Impacted Container Compliance Policy], https://pan.dev/compute/api/get-policies-compliance-vms-impacted/[Get Impacted VMs Compliance Policy], https://pan.dev/compute/api/get-policies-firewall-app-host-impacted/[Host App Firewall Policy Impacted], https://pan.dev/compute/api/get-policies-vulnerability-host-impacted/[Get Impacted Host Vulnerability Policy], https://pan.dev/compute/api/get-policies-vulnerability-images-impacted/[Get Impacted Image Vulnerability Policy], https://pan.dev/compute/api/get-registry/[Get Registry Scan Results] and https://pan.dev/compute/api/get-vms/[Get VM Image Scan Results] APIs to specify the referenced number of CaaS specifications (AWS Fargate Task Definition, GCP Cloud Run, ACI). This parameter only applies to Prisma onboarded accounts.

|*Support for a Amazon Fargate Task Definition*
|A new Enum value `aws-fargate-task-definition` has been added to `shared.ScanResultType` schema to specify a new scan result type of Amazon Fargate Task Definition. This parameter only applies to Prisma onboarded accounts.

|===


// [#new-features-core]
// === New Features in Core

// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS

// [#api-changes]
// === API Changes and New APIs

[#addressed-issues]
=== Addressed Issues
[cols="40%a,60%a"]

|===
|*Feature*
|*Description*

|*Prisma Cloud reported incorrect fix dates for RedHat vulnerabilities*

|This issue occurred for vulnerabilities reported as fixed through RedHat feeds in the VEX format.  
This issue is fixed now.

|*Unpair leads to stale CSA defenders*
|Stale unpaired cloud security agents (CSAs) are not deleted. This issue is fixed now.

|===


// [#deprecation-notices]
// === Deprecation Notices

