:toc: macro
== 34.01.129 Release Notes

The following table has the release details:

[cols="1,4"]
|===
|Build
|34.01.129

|Code name
|Quinn Update 1

|Release date
|June 11, 2025

|Type
|Maintenance release

|SHA-256
|c9dd890a734843b60a9da249d10844d805bad53cb58ca1708c017a1307c6ccc6

|===

This 34.01.129 build is a maintenance release for Quinn Update 1 (34.01). The upgrade paths applicable to build 34.01.126 apply to this build as well. 

Review the https://docs.prismacloud.io/en/compute-edition/34/rn/release-information/release-notes-34-01[34.01 (build number 126) release notes] for the upgrade paths and other details on the Quinn Update 1 release.

Review the https://docs.prismacloud.io/en/compute-edition/34/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly with this URL:

//https://cdn.twistlock.com/releases/FXfgOGOu/prisma_cloud_compute_edition_34_01_129.tar.gz[https://cdn.twistlock.com/releases/FXfgOGOu/prisma_cloud_compute_edition_34_01_129.tar.gz]


[#addressed-issues]
=== Addressed Issues

//CWP-62541

* This maintenance release addresses an internal session management issue.