== Download of Machine Learning Model Without Integrity Check

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| f91cc8cd-05e3-4f0f-be35-09009bf5a325

|Checkov ID 
| CKV3_SAST_99

|Severity
| HIGH

|Subtype
| Build

|Language
| Python

|CWEs
| https://cwe.mitre.org/data/definitions/494.html[CWE-494: Download of Code Without Integrity Check]

|OWASP Categories
|https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures[A08:2021-Software and Data Integrity Failures]


|===

=== Description

This SAST policy identifies instances where machine learning models are downloaded without specifying a specific revision, which could lead to the use of untrusted or tampered models.

Vulnerable code example:

[source,python]
----
from huggingface_hub import hf_hub_download

model = hf_hub_download("some_model")
----

In the above example, the `hf_hub_download` function is used without specifying the `revision` parameter, which means the model can be updated or tampered with without verification.

=== Fix - Buildtime

To fix this issue, always specify a specific revision when downloading machine learning models. This ensures that the exact version of the model is used, mitigating the risk of using a compromised model.

Secure code examples:

[source,python]
----
from huggingface_hub import hf_hub_download

model = hf_hub_download("some_model", revision="specific_commit")
----
