== Prisma Cloud Copilot Overview

Prisma Cloud Copilot is a generative AI-powered module available on the Prisma Cloud platform to improve the investigation and response capabilities of your cloud security teams. 

It provides a natural language interface to assist you in your alert and vulnerability management tasks, create support tickets, and search for answers in Prisma Cloud documentation. You can also remediate alerts and vulnerabilities through Prisma Cloud Copilot.

*NOTE:* 

* Prisma Cloud Copilot is available in a phased rollout for Cloud Security on all Prisma Cloud stacks (except app.gov and app.cn). 

* Prisma Cloud Copilot is only available for Enterprise License customers. 

* Only Prisma Cloud users with System Administrators roles have access to Prisma Cloud Copilot.


//removed timeline based on f/b by Bar - from October 7, 2024 to October 24, 2024
//as per the following timeline:

// [cols="30%a,70%a"]

//|===

//|*Date*
//|*Available on*

//|October 7, 2024
//|app.ca, app.fr, app.id, app.sg, app.uk

//|October 10, 2024
//|app.ind, app.jp 

//|October 17, 2024
//|app.anz, app.eu, app2.eu, app3

//|October 24, 2024
//|app, app2, app4

//|===


// RN: Blurb in October 10.1 > New Features
// Doc: Content Collections > New collection > AI Copilot
// Additional content update in:
//  -Alerts
//  -S&I
//  -Vulnerabilities
// Use Cases:
//  -How to open Support Case using Copilot
//  -How to find related docs