== AI Copilot FAQs

Review the frequently asked questions (FAQs) regarding the AI Copilot.

* What language models are used by Prisma Cloud AI Copilot?

The AI Copilot uses the large language models (LLMs) provided by one of the leading LLM providers. Prisma Cloud has an enterprise level agreement with the LLM provider ensuring that no data is used to further train those LLMs.

* Does Prisma Cloud AI Copilot use any customer data for model training?

The AI Copilot *does not* use customer data for training the models used in the copilot. Prisma Cloud uses foundational models (LLMs trained with publicly available data) for two purposes:

Natural language translation: Uses the LLM to understand the questions you ask.

Summarization: Summarizes different pieces of information. For example, use of Prisma Cloud product documentation to answer your question. The LLM generates a response from those text chunks, which might contain important information to provide the answer.


* How does Prisma Cloud Copilot use customers data to answer the questions it receives?

Here's how the AI Copilot works and how it uses your data:

. Step 1 (question contextualization): when a customer types a question in Copilot, the question is analyzed by Copilot to determine if additional data is required to augment the question. 

For example, when a customer asks “do I have instances with the log4j vulnerability?” Copilot identifies that log4j is a software package and adds to the question the list of CVE IDs associated with this software package.

. Step 2 (question translation): the augmented question is sent to the language model, which produces a representation of the question that can be used by Copilot to programmatically answer the question. 

The question “do I have instances with the log4j vulnerability?” in the example, is transformed by the language model into the RQL query: asset where asset.class = 'Compute' AND WITH : vuln where id IN ( 'CVE-2021-44228', 'CVE-2021-45046', 'CVE-2021-44832', 'CVE-2021-45105' )

Please note that no customer data is sent to the language model to generate the RQL statement.

. Step 3 (local query): Copilot takes the response from the language model and checks for its correctness. If the response is correct, Copilot uses it to collect any customer data that is required to provide the final answer. 

In our example, the RQL query is checked by a local language parser and then sent to the local API endpoint /search/asset to identify those cloud instances with vulnerable log4j.

This step involves customer data and stays within Prisma Cloud. It is not sent to the language model. 

. Step 4 (final answer): the answer from the API endpoint is received by the Copilot, which is displayed as a graph. 

In the example, Copilot displays the list of instances with vulnerable log4j as a graph.

//add screenshot
