== Permissions Query Results


Permission queries allow you to derive granular results by customizing the visualization of IAM Permissions to meet your specific requirements. Refine your search results by groups, roles, and users to conduct in depth investigations of a cloud resources' access. Customize RQL results on the *Home > Investigate* page to effectively manage and analyze Permission related tasks. 

[.task]
=== View and Refine Results 

When you run a Permission query, you can optionally aggregate your results by selecting column visbility and updating the order to further focus your investigation. Follow the steps below to use this option:

[.procedure]
. On the Prisma Cloud console, navigate to the *Investigate*.
. *Select a Query Type* and choose the *Permission* query type and enter your query. 
. Optionally configure the columns to suit your needs:
.. Select the column picker icon above your results table.
.. On the *Configure Columns* menu, select any column to make it visible or hide it.
.. Drag the columns up or down to change the column order in your dispalyed results.   







