== Permissions Query Results


Permission queries provide you with the option to derive granular results by customizing the visualization of IAM Permissions to meet your specific requirements. Refine your search results by groups, roles, and users to conduct in depth investigations of a cloud resources' access. Customize RQL results on the *Home > Investigate* page to effectively manage and analyze Permission related tasks. 

[.task]
=== View and Refine Results 

Use the *View By* option to further customize your search and refine your Permission queries. Follow the steps below to use this option:

[.procedure]
. On the Prisma Cloud console, navigate to the *Investigate* page to run a Permission query.
. *Select a Query Type* and choose the *Permission* query type and enter your query.
. Select *View By* and choose a category from the drop-down. For example, select *View By > Asset* to view a filtered list of results aggregated by the Asset category. 
. You can also optionally configure the columns to suit your needs.
.. Select the column picker icon above your results table.
.. On the *Configure Columns* menu, select any column to make it visible or hide it.
.. Drag the columns up or down to change the column order in your dispalyed results.   







