== Vulnerabilities Query Attributes

Learn about Asset query attributes on *Investigate* page.

Review your options when using userinput:[vulnerability where]. Each attribute allows you to narrow your search criteria. As you use these attributes, the auto-suggestion feature shows the available expressions and the operators that are applicable for each attribute.

//vulnerabilty where age = 5 days
//package.name
//prioritized
//risk.factors
//severity
//version

*  userinput:[asset.lifecycle] 
+
Use the userinput:[asset.lifecycle] attribute to view the vulnerable assets across your application lifecycle.

*  userinput:[asset.type] 
+
Use the userinput:[asset.type] attribute to search vulnerability in specific or all asset types. The asset types include: 'Container Registry Image', 'Deployed Image', 'Host', 'Iac', 'Package', 'Serverless Function', and 'Vm Image'.

*  userinput:[cve.id]
+
Use the userinput:[cve.id] attribute to search and show all the assets across your lifecycle impacted by this CVE ID.

*  userinput:[cvss.score]
+
The userinput:[cvss.score] attribute queries all the vulnerabilities with a CVSS score that you select.

* userinput:[source]
+
Use the userinput:[source] to query the vulnerabilities sourced from CAS and Compute.