== AWS MQBroker audit logging is disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6cc22562-8bcd-4e12-8610-77e926cf4fa7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/aws/MQBrokerAuditLogging.py[CKV_AWS_197]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that Amazon MQ Brokers have audit logging enabled. Audit logging is crucial for tracking access and changes to your MQ Brokers, thereby providing visibility into security-relevant events and supporting compliance requirements. This policy checks whether the `logs` property is configured to enable `audit` logging. Note that audit logging is not supported for RabbitMQ engine types.

=== Fix - Buildtime


*Terraform* 

To fix this issue, ensure that the `logs` property in the `aws_mq_broker` resource includes `audit` set to `true`, unless the engine type is `RabbitMQ`.

Example:

[source,go]
----
resource "aws_mq_broker" "example" {
  ...
  logs {
    audit = true
  }
  ...
}
----


*CloudFormation*

To fix this issue, ensure that the `Audit` property in the `Logs` configuration of the `AWS::AmazonMQ::Broker` resource is set to `true`, unless the engine type is `RabbitMQ`.

Example:

[source,yaml]
----
Resources:
  MyMQBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      ...
      Logs:
        Audit: true
      ...
----
