== Neptune logging is not enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a520f182-c20b-4042-95ca-6e0caccf6219

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/NeptuneClusterLogging.py[CKV_AWS_101]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Impact
This policy ensures that logging is enabled for Amazon Neptune clusters. Enabling logging for your Neptune clusters is critical for auditing and monitoring purposes. It helps in capturing database activities that can be useful for debugging and compliance requirements. This check validates that `enable_cloudwatch_logs_exports` includes the required log types.


=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_neptune_cluster
* *Arguments:* enable_cloudwatch_logs_exports


[source,go]
----
resource "aws_neptune_cluster" "Pike" {
  cluster_identifier   = var.DBClusterIdentifier
 
    ...
+ enable_cloudwatch_logs_exports      = ["audit"]
}
----


*CloudFormation* 


* *Resource:* AWS::Neptune::DBCluster
* *Arguments:* Properties.EnableCloudWatchLogExports


[source,yaml]
----
Type: "AWS::Neptune::DBCluster"
    Properties:
        ...
+       EnableCloudwatchLogsExports: ["audit"]
----
