== Alibaba Cloud Action Trail Logging is not enabled for all events


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e0fe6e89-6e05-42c9-b613-54056934ae90

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/ActionTrailLogAllEvents.py[CKV_ALI_5]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that Action Trail in Alibaba Cloud is configured to log all events. Action Trail allows for governance, compliance, and auditing over your Alibaba Cloud account by recording the actions taken on your account. Logging all events ensures that all user and API actions are recorded, providing a comprehensive history of activity for security analysis.

Failing to log all events can result in incomplete logging data, which could obscure the audit trail and hinder investigations and compliance efforts.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_actiontrail_trail
* *Arguments:* event_rw

To mitigate this issue, ensure the `event_rw` attribute in the `alicloud_actiontrail_trail` resource is set to `All`.

Example:

[source,go]
----
resource "alicloud_actiontrail_trail" "example" {
  ...
+  event_rw = "All"
}
----
