== Logging for Dialogflow CX agents is disabled misconfiguration detected in code

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_30
|Category |Logging - Disabled or Missing
|Provider |GCP
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This policy is examining whether logging is enabled for Dialogflow CX agents. Dialogflow CX is a sophisticated conversational AI tool that can be used to build and manage virtual agents. If logging isn't enabled, it would be challenging to track interactions, troubleshoot issues, or monitor the performance and usage of these virtual agents. This could potentially lead to a loss of critical data, failure to adhere to certain compliance requirements, and a lack of visibility over the system. Hence, it's regarded as a poor practice not to have logging enabled for Dialogflow CX agents.

=== How to Fix

*Terraform*

* *Resource:* google_dialogflow_cx_agent
* *Arguments:* enable_stackdriver_logging

To fix the issue, introduce the `enable_stackdriver_logging` field in your `google_dialogflow_cx_agent` resource and set it to `true`:

[source,go]
----
resource "google_dialogflow_cx_agent" "agent" {
  ...
  enable_stackdriver_logging = true
}
----

The above code is secure because it enables Stackdriver logging for the Google Dialogflow CX agent, ensuring all interactions and events are logged and monitored, which is essential for troubleshooting, auditing and security purposes. This aligns with the security best practices, compliance requirements and can help identify potential security concerns or performance issues at an early stage.

