== Alibaba Cloud Action Trail Logging is not enabled for all events


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_ALI_5
|Category |LOGGING-Disabled or missing
|Provider |ALIBABA_CLOUD
|Severity |MEDIUM
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===


=== Description 

This policy ensures that Action Trail in Alibaba Cloud is configured to log all events. Action Trail allows for governance, compliance, and auditing over your Alibaba Cloud account by recording the actions taken on your account. Logging all events ensures that all user and API actions are recorded, providing a comprehensive history of activity for security analysis.

Failing to log all events can result in incomplete logging data, which could obscure the audit trail and hinder investigations and compliance efforts.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_actiontrail_trail
* *Arguments:* event_rw

To mitigate this issue, ensure the `event_rw` attribute in the `alicloud_actiontrail_trail` resource is set to `All`.

Example:

[source,go]
----
resource "alicloud_actiontrail_trail" "example" {
  ...
+  event_rw = "All"
}
----
