== Azure Network Watcher Network Security Group (NSG) flow logs retention is less than 90 days
// Azure Network Watcher Network Security Group (NSG) flow logs retention less than 90 days


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_12
|Category |LOGGING-RETENTION
|Provider |AZURE
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |7c0570f7-d467-4652-b699-9189d5fe86a3
|===


=== Description 


Flow logs enable capturing information about IP traffic flowing in and out of network security groups.
Logs can be used to check for anomalies and give insight into suspected breaches.
We recommend your Network Security Group (NSG) Flow Log *Retention Period* is set to greater than or equal to 90 days.
////
=== Fix - Runtime


* Azure Portal To change the policy using the Azure Portal, follow these steps:* 



. Log in to the Azure Portal at https://portal.azure.com.

. Navigate to * Network Watcher* >  * Logs* section.

. Select the * NSG flow logs* blade.

. For each Network Security Group in the list:  a) Set *  Status* to * On*.
+
b) Set * Retention (days)* to * greater than 90 days*.
+
c) In * Storage account* select your _storage account_.
+
d) Click * Save*.


* CLI Command* 


To enable the * NSG flow logs * and set the * Retention (days)*  to * greater than or equal to 90 days*, use the following command:
----
az network watcher flow-log configure
--nsg & lt;NameorID of the Network Security Group>
--enabled true
--resource-group & lt;resourceGroupName>
--retention 91
--storage-account & lt;NameorID of the storage account to save flow logs>
----
////
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_network_watcher_flow_log
* *Arguments:* days


[source,go]
----
resource "azurerm_network_watcher_flow_log" "test" {
    ...
+   retention_policy {
+   enabled = true
+   days    = <90 or greater>
    }
}
----
