== Alibaba Cloud RDS log audit is disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_ALI_38
|Category |Logging - Disabled or Missing
|Provider |Alibaba Cloud
|Severity |LOW
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This policy ensures that log auditing is enabled for Alibaba Cloud RDS instances. Enabling log audit provides detailed records of database activities, including user actions, queries, and system events. These logs are essential for detecting anomalies, investigating incidents, and maintaining compliance with regulatory and organizational requirements.

Failing to enable log auditing can lead to a lack of visibility into database activity, increasing the risk of undetected malicious actions or compliance violations.

=== Fix - Buildtime

*Terraform*

* *Resource:* alicloud_log_audit
* *Arguments:* variable_map.rds_enabled

To mitigate this issue, ensure the `rds_enabled` attribute in the `alicloud_log_audit` resource is set to True.

Example:

[source,go]
----
resource "alicloud_log_audit" "example" {
  ...
  variable_map = [
    {
+      rds_enabled = true
    }
  ]
}
----
