== Alibaba Cloud OSS bucket has access logging enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| da426a37-d689-4d72-8362-7596f8576a0f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/OSSBucketAccessLogs.py[CKV_ALI_12]

|Severity
|LOW

|Subtype
|Build, Run

|Frameworks
|Terraform

|=== 



=== Impact
This policy identifies Alibaba Cloud Object Storage Service (OSS) buckets that do not have logging enabled.

Enabling logging for OSS buckets helps capture access and operation events, which are critical for security monitoring, troubleshooting, and auditing. Without logging, you lack visibility into who accesses and interacts with your bucket, potentially missing unauthorized access or suspicious behaviour.

As a security best practice, it is recommended to enable logging for OSS buckets.

=== Fix - Buildtime


*Terraform*

* *Resource:* alicloud_oss_bucket
* *Arguments:* logging

To mitigate this issue, ensure the `logging` attribute in the `alicloud_oss_bucket` resource is configured.

Example:

[source,go]
----
resource "alicloud_oss_bucket" "example" {
  ...

+  logging {
+    target_bucket = "my-log-bucket"
+    target_prefix = "log/"
+  }
}
----
