== App service disables detailed error messages misconfiguration detected in code
// Azure App Service detailed error messages disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_65
|Category - Subcategory |Logging - Disabled or Missing
|Provider |Azure
|Severity |LOW
|Framework |ARM, Bicep, Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
Detailed error messages provide more information about an error that occurs in your app, such as the error code, the line of code where the error occurred, and a description of the error.
This information can be very useful for debugging issues with your app and identifying the root cause of the problem.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_app_service
* *Arguments:* detailed_error_messages_enabled


[source,go]
----
resource "azurerm_app_service" "example" {
             ...
+            logs {
+               detailed_error_messages_enabled = true
+            }
             ...
    }
----
