== Neptune logging is not enabled


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_101
|Category |LOGGING-Disabled or missing
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Description 

This policy ensures that logging is enabled for Amazon Neptune clusters. Enabling logging for your Neptune clusters is critical for auditing and monitoring purposes. It helps in capturing database activities that can be useful for debugging and compliance requirements. This check validates that `enable_cloudwatch_logs_exports` includes the required log types.


=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_neptune_cluster
* *Arguments:* enable_cloudwatch_logs_exports


[source,go]
----
resource "aws_neptune_cluster" "Pike" {
  cluster_identifier   = var.DBClusterIdentifier
 
    ...
+ enable_cloudwatch_logs_exports      = ["audit"]
}
----


*CloudFormation* 


* *Resource:* AWS::Neptune::DBCluster
* *Arguments:* Properties.EnableCloudWatchLogExports


[source,yaml]
----
Type: "AWS::Neptune::DBCluster"
    Properties:
        ...
+       EnableCloudwatchLogsExports: ["audit"]
----
