== 接続されている Azure アカウントの表示と編集

Azureクラウドアカウントリソースを追加した後、既存のクラウドリソースの確認や更新、割り当てられた権限の変更を行いたい場合があります。
Azure クラウド アカウント リソースを表示または編集するには、次の手順に従います。

[.task]
[#ds]
=== 追加されたアカウントを表示

[.procedure]
. Prisma Cloud管理コンソールから、*[Settings(設定)] > [Cloud Accounts(クラウドアカウント)]*を選択し、以前に追加したすべてのクラウド アカウントのリストを表示します。

. 変更する Azure アカウントを見つけて、[表示] アイコンをクリックします。

. [*ステータス*] タブには、アカウントの詳細が一覧表示され、有効になっている *セキュリティ機能とアクセス許可* が表示されます。

. [*脅威検出*] タブでは、フロー ログの取り込み設定を編集できます。[*編集*] ボタンを選択し、オンボーディング ワークフローの [*アカウントの構成*] ページで設定を変更します。

. *ワークロード セキュリティ*を使用すると、コンピューティングのセキュリティ機能とアクセス許可を追加または削除できます。*有効化* または *無効化* トグルをクリックして、選択内容を変更します。ページの上部にある [*編集*] ボタンを選択し、 オンボーディングワークフローの* 開始*に移動して、設定を変更することもできます。

. *データ セキュリティ*を有効にして、クラウド アカウントに保存されているデータを検出して分類し、偶発的な露出を防止します。以下の手順に従って、データ セキュリティを構成します。
.. [*Settings(設定)] > [Cloud Accounts(クラウドアカウント)*]を選択し、クラウドアカウントの編集ワークフローから[*Data Security(データ セキュリティ)*]を選択します。
.. すべてのクラウド リソースをスキャンするか、クラウド アカウント内のスキャン設定をカスタマイズするかを選択します。
.. *Status Setup*で データ セキュリティが設定されていることを確認します。

. セキュリティ機能に *Issues Found（問題が検出されました）* フラグが表示される場合。リンクをクリックすると、問題の概要と利用可能な修復オプションを表示できます。

[.task]
=== 追加されたアカウントを編集する

*[クラウド アカウント]* ページでは、既に追加されているアカウントの既存の *セキュリティ機能とアクセス許可*を 編集することもできます。以下の手順に従って、既存のアカウントを編集してください。

[.procedure]
. 修正する Azure アカウントを見つけて、[編集] アイコンをクリックします。

. [*クラウド アカウントの編集*] ページでは、 *セキュリティ機能とアクセス許可*を追加または変更できます。フロー ログの取り込みをオプトインまたはオプトアウトすることもできます。詳細については、xref:connect-azure-tenant.adoc[「Azure テナントを接続する」を] 参照してください。 