== ECR image scan on push is not enabled misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_163
|Category - Subcategory |Compute - Default Credentials or Auth
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
Amazon ECR is a fully managed container registry used to store, manage and deploy container images.
ECR Image Scanning assesses and identifies operating system vulnerabilities.
Using automated image scans you can ensure container image vulnerabilities are found before getting pushed to production.
ECR APIs notify if vulnerabilities were found when a scan completes.


=== How to Fix


*Terraform* 


* *Resource:* aws_ecr_repository
* *Arguments:* scan_on_push - (Required) Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).


[source,go]
----
resource "aws_ecr_repository" "example" {
  ...
  image_tag_mutability = "MUTABLE"
+  image_scanning_configuration {
+    scan_on_push = true
+  }
  ...
}
----


*CloudFormation* 


* *Resource:* AWS::ECR::Repository
* *Arguments:* Properties.ImageScanningConfiguration.ScanOnPush - (Required) Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).


[source,yaml]
----
Resources:
  ImageScanTrue:
    Type: AWS::ECR::Repository
    Properties: 
      ...
+     ImageScanningConfiguration:
+       ScanOnPush: true
----
