== Update instructions are used alone in a Dockerfile


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7cc86b56-dbe0-45a4-98d0-1b982cbce03c

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/dockerfile/checks/UpdateNotAlone.py[CKV_DOCKER_5]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Impact
This rule detects whether OS package manager update instructions, such as apt-get update or yum update, are used alone within Dockerfiles. Using update instructions alone, or in a single line, causes the update layer to be cached. This can lead to stale updates being used in subsequent builds, preventing necessary updates from being applied and potentially introducing vulnerabilities. Therefore, we recommend that update instructions should always be combined with package installation commands in the same RUN instruction.

=== Fix - Buildtime

*Docker* 

To mitigate this issue, combine the update commands with install commands in a single RUN instruction. This ensures that the package list is updated and packages are installed in the same layer.

Example:

[source,dockerfile]
----
- RUN apt-get update
+ RUN apt-get update && apt-get install -y <package-name>
----
