== Base image uses a latest version tag misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_DOCKER_7
|Category |Compute - Unsanctioned Resource or Type
|Provider |
|Severity |LOW
|Framework |Docker
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
When possible, it is recommended to pin the version for the base image in your Dockerfiles.
There are a number of potential issues that may be caused when using the `latest` tag.
Since `latest` is the default tag when a tag is not specified, it does not automatically refer to the latest version of the image.
This can lead to the use of outdated images and in the case of production deployments, using a dynamic version can cause unexpected behavior and difficulty in determining which version is being currently used.
It is best practice to be specific as possible about what is running to make operations predictable and reliable

=== How to Fix


*Docker* 


[source,Dockerfile]
----
- FROM alpine:latest
----

