== AWS DB instance does not get all minor upgrades automatically


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_226
|Category |Compute - Unsanctioned Resource or Type
|Provider |AWS
|Severity |LOW
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
When Amazon Relational Database Service (Amazon RDS) supports a new version of a database engine, you can upgrade your DB instances to the new version.
There are two kinds of upgrades: major version upgrades and minor version upgrades.
Minor upgrades helps maintain a secure and stable RDS with minimal impact on the application.
For this reason, we recommend that your automatic minor upgrade is enabled.
Minor version upgrades only occur automatically if a minor upgrade replaces an unsafe version, such as a minor upgrade that contains bug fixes for a previous version.

=== Fix - Buildtime


*CloudFormation* 




[source,yaml]
----
Resources:
  Example:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: 'example'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'mysql'
      MasterUsername: 'master'
      MasterUserPassword: 'password'
+     AutoMinorVersionUpgrade: true
----


*Terraform* 




[source,go]
----
resource "aws_db_instance" "example" {
  allocated_storage          = 20
  engine                     = "mysql"
  engine_version             = "5.7"
  instance_class             = "db.t3.micro"
  name                       = "mydb"
  username                   = "foo"
  password                   = "foobarbaz"
  parameter_group_name       = "default.mysql5.7"
+ auto_minor_version_upgrade = true
}
----
