== AWS API Gateway caching is disabled misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_120
|Category |Compute - Unsanctioned Resource or Type
|Provider |AWS
|Severity |LOW
|Framework |Terraform, CloudFormation
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
This checks that all methods in an Amazon API Gateway stage to ensure that they have caching enabled.
As AWS puts it "With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API" and so if you need to minimise those, this will help.
See the AWS docs for more information: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-caching.html


=== How to Fix


*Cloudformation* 


* *Resource:* AWS::ApiGateway::Stage
* *Arguments:* CacheClusterEnabled


[source,go]
----
Resources:
  Prod:
    Type: AWS::ApiGateway::Stage
    Properties:
      ...
      + CacheClusterEnabled: True
----

//=== How to Fix


*Terraform* 


* *Resource:* aws_api_gateway_stage
* *Arguments:* cache_cluster_enabled


[source,go]
----
resource "aws_api_gateway_stage" "example" {
...
  + cache_cluster_enabled = true
...
}
----
