== The --streaming-connection-idle-timeout argument is set to 0 misconfiguration detected in code
// '-streaming-connection-idle-timeout' argument set to 0

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_143
|Category |Compute - Unsanctioned Resource or Type
|Provider |
|Severity |LOW
|Framework |Kubernetes, Helm, Kustomize
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Do not disable timeouts on streaming connections.
Setting idle timeouts ensures that you are protected against Denial-of-Service attacks, inactive connections and running out of ephemeral ports.
By default, --streaming-connection-idle-timeout is set to 4 hours which might be too high for your environment.
Setting this as appropriate would addition ally ensure that such streaming connections are timed out after serving legitimate use cases.

=== How to Fix


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kubelet
    tier: control-plane
  name: kubelet
  namespace: kube-system
spec:
  containers:
  - command:
+   - kubelet
+   - --streaming-connection-idle-timeout=1
    image: gcr.io/google_containers/kubelet-amd64:v1.6.0
    ...",
}
----

