== Image pull policy is not set to Always
// Image pull policy not set to 'Always'

=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_15
|Category |Compute-Unsanctioned resource or type
|Provider |
|Severity |LOW
|Framework |Kubernetes, Terraform, Helm, Kustomize, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


The Image Pull Policy of a container is set using the *imagePullPolicy*.
The *imagePullPolicy* and the tag of the image are triggered when the kubelet attempts to pull the specified image.
When the *imagePullPolicy* is set to *Always*, you ensure the latest version of the image is deployed every time the pod is started.
Avoid using the *:latest* tag when deploying containers in production, it is harder to track which version of the image is running and more difficult to roll back correctly.

=== Fix - Buildtime


*Kubernetes* 

*Resource*: Container
*Argument*: imagePullPolicy (Optional)

Defines for the kubelet when he should attempt to pull the specified image.




[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
+   imagePullPolicy: Always
----

