== seccomp profile is not set to Docker/Default or Runtime/Default
// Secure computing mode (seccomp) profile not set to Docker/Default or Runtime/Default

=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_32
|Category |Compute-Unsanctioned resource or type
|Provider |
|Severity |LOW
|Framework |Kubernetes, Terraform, Helm, Kustomize, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


Secure computing mode (seccomp) is a Linux kernel feature used to restrict actions available within the container.
The seccomp() system call operates on the seccomp state of the calling process.
The default seccomp profile provides a reliable setting for running containers with seccomp and disables non-essential system calls.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* metadata:annotations (Optional)  Annotations attach arbitrary non-identifying metadata to objects.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
  annotations:
+   seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
    or
+   seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
----


[source,cronjob]
----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: <>
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
 +                  seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
    or
 +                seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
----

[source,text]
----
apiVersion: <>
kind: <kind>
metadata:
  name: <name>
spec:
  template:
    metadata:
        annotations:
+               seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
    or
+               seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
----