== Read-Only filesystem for containers is not used misconfiguration detected in code
// Read-Only filesystem for containers not used
// Suggest: Container root filesystem mutable


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_22
|Category - Subcategory |Compute - Unsanctioned Resource or Type
|Provider |
|Severity |LOW
|Framework |Kubernetes, Terraform, Helm, Kustomize, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
A read-only root filesystem helps to enforce an immutable infrastructure strategy.
The container should only write on mounted volumes that can persist, even if the container exits.
Using an immutable root filesystem and a verified boot mechanism prevents against attackers from "owning" the machine through permanent local changes.
An immutable root filesystem can also prevent malicious binaries from writing to the host system.

=== How to Fix


*Kubernetes* 


* *Resource:* Container
* *Arguments:* readOnlyRootFilesystem (Optional)

Defines whether a container is able to write into the root filesystem.
Default to false.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <Pod name>
spec:
  containers:
  - name: <container name>
    image: <image>
    securityContext:
+      readOnlyRootFilesystem: true
----

