== AKS Cluster Without Upgrade Channel misconfiguration detected in code
// Ensure AKS cluster upgrade channel is chosen

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_171
|Category - Subcategory |Compute - Unsanctioned Resource or Type
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Kubernetes Service (AKS) provides different upgrade channels that you can set to control the level of version updates for your AKS cluster. These upgrade channels include Patch, Rapid, Stable, and None. The "None" channel means that the cluster won't be upgraded automatically. It's highly recommended to choose an upgrade channel to ensure that your cluster stays updated with the latest security patches and feature improvements.

This rule checks to make sure that an upgrade channel other than "None" is selected for your AKS clusters.

=== How to Fix

*Terraform*

* *Resource:* azurerm_kubernetes_cluster
* *Arguments:* automatic_upgrade_channel

[source,terraform]
----
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  # If using azurerm version below 4.0
+ automatic_channel_upgrade = "stable"
  # If using azurerm version 4.0 and above
+ automatic_upgrade_channel = "stable"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "production"
  }
}
----
