== API Gateway does not have X-Ray tracing enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_73
|Category |Compute - Unsanctioned Resource or Type
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
When an API Gateway stage has the active tracing feature enabled, Amazon API Gateway service automatically samples API invocation requests based on the sampling algorithm specified by AWS X-Ray.
With tracing enabled X-Ray can provide an end-to-end view of an entire HTTP request.
You can use this to analyze latencies in APIs and their backend services.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_api_gateway_stage
* *Arguments:* xray_tracing_enabled - (Optional) Whether active tracing with X-ray is enabled.
Defaults to false.


[source,go]
----
{
 "resource "aws_api_gateway_stage" "test" {
  ...
  stage_name    = "prod"
+ xray_tracing_enabled = true
  ...
}

",
 
}
----


*CloudFormation* 


* *Resource:* AWS::ApiGateway::Stage
* *Arguments:* Properties.TracingEnabled


[source,yaml]
----
{
 "Resources:
  MyStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      ...
+     TracingEnabled: true
      ...",
       
}
----
