:topic_type: task

[.task]
== Connect Bitbucket

Integrate Prisma Cloud with your Bitbucket version control system to gain visibility into, and monitor the systems, technologies, configurations, and pipelines that make up the Bitbucket platform.
This integration enables security scans to identify Infrastructure-as-Code (IaC) misconfigurations, Software Composition Analysis (SCA) vulnerabilities, exposed secrets, license mis-compliance and CI/CD pipeline risks in your Bitbucket environment, allowing you to understand and fix issues as soon as they are detected, resulting in an enhanced security posture for your organization.

The Bitbucket integration will create a webhook that will trigger periodic scans of your code. The scans will be run on all pull requests (PRs), and the results will be displayed in the PR comments and in reports.

[.procedure]

. Before you begin:
+
.. Add the Prisma Cloud IP addresses and hostname for Application Security to an https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.html[allow list], to enable access to the Prisma Cloud Console.

.. Grant *Administrator* permissions in the relevant Bitbucket organization to the Prisma user integrating Prisma Cloud with Bitbucket.

. On the Prisma Cloud Application Security console.
.. In Application Security, select *Settings > *Connect Provider* > *Code & Build Providers* > *Bitbucket* (under Code Repositories).
.. Select *Authorize* in the *Configure Account* step of the installation wizard that is displayed.
+
You are redirected to Bitbucket to authorize Prisma Cloud access.

. Authorize Prisma Cloud on Bitbucket.
.. Review the requested permissions and then select *Grant access*.
+
You are redirected to the *Enable CI/CD Security (Optional)* step of the Bitbucket installation wizard on the Prisma Cloud console. This step is optional and provides protection for the CI/CD systems in your Bitbucket environment. 

. Enable CI/CD Security.
.. To begin, you must first enable the xref:../../code-security-licensing-configuration.adoc[CI/CD Security Module].
.. Fill in the provided fields. 
+
* Bitbucket *User Name*: In Bitbucket, click the Bitbucket settings cog > *Settings* > find your username under *Personal information*.
* Bitbucket *App Password*: To enable CI/CD Security you need to provide an additional App Password with repository read and repository admin permissions: In Bitbucket: Go to your *Personal Settings* page > *App Passwords*. Give your App Password a *Label*. Select the *Repository Read And Repository Admin* permissions. Click *Create* > Copy the generated App password from the *New app password* dialog. The App password is only displayed once and cannot be retrieved later.
+
See https://support.atlassian.com/bitbucket-cloud/docs/create-an-app-password/[here] for more on generating App Passwords on Bitbucket.

.. Select *Next*.
 
. Select which repositories will be scanned: 

* *Permit all existing repositories* 
* *Permit all existing and future repositories*.  This is the recommended option to ensure complete coverage and successful operation of all features. 
* *Choose from repository list* > Select repositories
+
NOTE: The selected repositories associated with the app password will be scanned.

.. Select *Next* to confirm the repository selection and save the changes > *Done*.

. Verify successful integration: select *Settings* > *Code & Build Providers*.
+
Confirm that the status of the integrated *Bitbucket* repositories displays *Connected* under *Status*.
+
NOTE: It may take up to 3 minutes for the integration status to be updated and show as *Succeeded*.

. Next step: Monitor and manage scan results.
+
Your selected Bitbucket repositories will be visible on the *Repositories* page. The next Bitbucket scan will include the selected repositories. 

To view the scan results and resolve issues select *Application Security* > *Projects*. See xref:../../../risk-management/monitor-code-build-issues.adoc[here] for more information.  

=== Manage integrations

On *Code & Build Providers*, you can also manage the integration by reselection of repositories and deletion of the repository and the integration.

* *Reselect repositories*: Enables you to access the list of repositories for a scan.
* *Delete repository*: Enables you to delete repositories for a scan from the account.
* *Manage VCS user tokens*: Enables you to integrate one or more Azure Repos accounts.
