:topic_type: task

[.task]
== Connect GitHub 

Integrate Prisma Cloud with your GitHub version control system to gain visibility into, and monitor the systems, technologies, configurations, and pipelines that make up the GitHub platform.

This integration enables security scans to identify Infrastructure-as-Code (IaC) misconfigurations, Software Composition Analysis (SCA) vulnerabilities, exposed secrets, license mis-compliance and CI/CD pipeline risks in your GitHub environment, allowing you to understand and fix issues as soon as they are detected, resulting in an enhanced security posture for your organization.

The GitHub integration creates a webhook that triggers periodic scans of your code. The scans will be run on all pull requests (PRs), and the results will be displayed in the PR comments and in reports.

[.procedure]

. Before you begin:

.. Add the Prisma Cloud IP addresses and hostname for Application Security to an https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.html[allow list], to enable access to the Prisma Cloud Console

.. Grant the Prisma user integrating Prisma Cloud with GitHub *Administrator* user permissions in the relevant GitHub organization

. On the Prisma Cloud Application Security console.
.. In Application Security, select *Settings > *Connect Provider* > *Code & Build Providers* > *GitHub* (under Code Repositories).
.. In the wizard that is displayed, select *Authorize*.
+
You are redirected to GitHub to authorize Prisma Cloud access.

. On GitHub. 
.. Select *Continue* > *Authorize Prisma Cloud DevOps*.
.. Select the account on which Prisma Cloud will be installed.
.. Select the repositories to be integrated:
+
* *All repositories* applies to all current and future repositories owned by the resource owner 
+
NOTE: This is the recommended option to ensure complete coverage and successful operation of all features.

* *Only select repositories*  > *Select repositories* allows you to authorize selected repositories from the menu 
+
NOTE: Review the permissions granted when authorizing Prisma Cloud on GitHub.

.. Select *Install & Authorize*.
+
You are redirected to the *Select Repositories* step of the GitHub installation wizard on the Prisma Cloud console.
+
NOTE: Refer to the https://docs.github.com/en/apps/using-github-apps/installing-a-github-app-from-a-third-party[GitHub Documentation] for more on authorizing and installing GitHub Apps.

. On the Prisma Cloud console.
.. Select an option to determine which repositories will be scanned:
+
* *Permit all existing repositories*
* *Permit all existing and future repositories*
+
NOTE: This is the recommended option to ensure complete coverage and successful operation of all features.
* *Choose from repository list*  > select repositories

.. Select *Next* > *Done* in the *Status* step of the wizard to complete the integration.

. Verify successful integration: select *Settings* > *Code & Build Providers*.
+
Confirm that the status of the integrated *GitHub* repositories displays *Connected* under *Status*.
+
NOTE: It may take up to 3 minutes for the integration status to be updated and show as *Succeeded*.

. Next step: Monitor and manage scan results.
+
Your selected GitHub repositories will be visible on the *Repositories* page. The next GitHub scan will include the selected repositories. 

To view scan results and resolve issues, select *Application Security* > *Projects*. See xref:../../../risk-management/monitor-code-build-issues.adoc[here] for more information.  

