== Intelligence Stream

The Prisma Cloud Intelligence Stream (IS) is a real-time feed that contains vulnerability data and threat intelligence from a variety of certified upstream sources. Prisma Cloud continuously pulls data from known vulnerability databases, official vendor feeds and commercial providers to provide the most accurate vulnerability detection results.

In addition to the information collected from official feeds, Prisma Cloud feeds are enriched with vulnerability data curated by a dedicated research team. Our security researchers monitor cloud and open source projects to identify security issues through automated and manual means. As a result, Prisma Cloud can detect new vulnerabilities that were only recently disclosed, and even vulnerabilities that were quietly patched.

The Prisma Cloud Console automatically connects to the Intelligence Stream server and downloads updates without any special configuration required. The Intelligence Stream (IS) is updated several times per day, and the consoles check continuously for updates.

ifdef::compute_edition[]
You can update Console vulnerability and threat data even if it runs in an offline environment.
For more information, see xref:../tools/update-intel-stream-offline.adoc[Update Intelligence Stream in offline environments].
endif::compute_edition[]

=== Multiple Intelligence Stream (IS) Builders

Prisma Cloud introduces versioning for the Intelligence Stream (IS) to ensure compatibility across different Console and Defender versions.

The purpose of Intelligence Stream (IS) versioning is to:

* *Maintain functionality for older Consoles and Defenders*: IS versioning ensures that older Consoles and Defenders continue to operate properly, even if they are unable to support the latest intelligence feeds, such as changes in external data feed formats.

* *Reduce disruptions*: Versioning helps minimize disruptions caused by updates, such as changes in downloaded JSON file fields that could impact CVE accuracy or result in duplicate CVEs.

Intelligence Stream (IS) versions will be aligned with specific Console versions. For example, older 31.xx and 32.xx Consoles will be supported by the IS version released for Console 33.00. 

To ensure consistency in vulnerability reporting across all Intelligence Stream (IS) versions, the following approach is implemented:

* *New Intelligence Stream (IS) logic updates*: These updates will only apply to the latest IS versions. When customers upgrade to the latest Console version, they will receive the most recent IS logic updates.

* *Vulnerability data*: All IS versions will continue to provide up-to-date vulnerability information, and changes in IS logic or algorithms will not affect the vulnerability metrics and reporting in the Console.

*Note*: Updates related to the Intelligence Stream will be notified in the *Intelligence Stream Updates* section of the Prisma Cloud Release Notes.



