== Search and Investigate 

Your cloud security teams can use *Search and Investigate* to perform in-depth analysis and investigation of security issues within your cloud applications and infrastructure. They can get answers to questions related to security risks and incidents from *Code to Cloud* with a simple and intuitive point-and-click interface that is powered by a Natural Language Processing (NLP) engine. The keyword search provides you with a curated list of results with rich visualization. You can then drill down the results to explore data, modify and save the query, create custom policies and receive alerts within minutes of a policy violation.

Use *Search and Investigate* to find the latest security incidents identified in your cloud environment and explore what risk factors could have contributed to the incident, for example:

* Which are the EC2 instances that have risky ports open to the internet, have overly permissive IAM permissions, and contain critical vulnerabilities?
* Are there any S3 buckets with encryption disabled?
* Are there any virtual machines that are directly accessible from the internet?
* Which cloud resources have exploitable vulnerabilities that need to be patched?
* Which assets in your cloud environment are impacted by the latest log5j vulnerability?

//PM provided video
search-and-investigate.gif

[cols="30%a,70%a"]
|===
|*What do you want to do?*
|*Start here*

|Launch your query and search using natural language 
|xref:launch-queries.adoc[Launch Queries]
//check if 'NLP' needs to be replaced with 'Keyword'

|Review query types, build and modify your query using simple or advanced modes
|xref:build-modify-queries.adoc[Build and Modify Queries]
//Use the query builder to modify your query using RQL (RQL Ref as an Appendix)
//xref:rql-mode.adoc[Advanced Mode]

|Explore data and findings in graph and table views and create custom policies
|xref:explore-data.adoc[Explore Data and Create Custom Policies]

|Save your query for future use after exploring data and run background jobs
|xref:query-library.adoc[Query Library and Background Jobs]

|What's next? 

Review attributes and examples for the query types using the advanced mode
|* xref:asset-queries.adoc[Asset]
* xref:asset-config-queries.adoc[Asset Configuration]
* xref:application-asset-queries.adoc[Application Asset]
* xref:vulnerability-queries.adoc[Vulnerability]
* xref:audit-event-queries.adoc[Audit Event]
* xref:permissions-queries.adoc[Permissions]
* xref:network-queries.adoc[Network]
* xref:network-configuration.adoc[Network Configuration]

//check with PM on the relevant next step to direct our users in their PC journey
//permissions > Izabella
//application asset > Shlomi
//vulnerability > Alex Cezar
//appdna (not yet confirmed) > Shreyas

* Built a query you think would be useful to other customers Contribute using *Edit on Github* link provided on each page!
//AWS EC2 instance publicly exposed with IAM permissions management access level

|===