== Unencrypted channel used in GitHub repository to download dependencies from NPM registry

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_159
|Category |Dependency Chains
|Provider |
|Severity |MEDIUM
|===
 

=== Impact
Downloading packages using **HTTP** instead of **HTTPS** can make them vulnerable to man-in-the-middle attacks, which could potentially allow malicious code to be injected into the packages and executed on the CI or developer's endpoints. This could also expose internal packages to tampering.
The dependency’s **download URL** can be found in the `package-lock.json` file.

EXAMPLES: The package source displayed in the event field can be specified using one of the following methods described in these examples: 

* **URL**: \https://registry.npmjs.org/example/-/example-1.0.0.tgz

* **Git URL**: git+ssh://git@github.com/org/repo.git

* **Local file path**: file:../foo/bar

* **GitHub repository**: org/repo

=== Recommended Solution - Buildtime

Check the **.npmrc** file, and if it contains configurations for downloading a package using HTTP, modify it to use HTTPS.
To update the dependency URL, uninstall the existing package using the `npm uninstall <package>` command, and then re-install the updated package using `npm install` over an encrypted channel.