== Features Introduced in December 2023

Learn what's new on Prisma® Cloud in December 2023.

[#new-features-nov]
=== New Features Introduced in December 2023

* <<announcement>>
* <<new-features>>
* <<api-ingestions>>
* <<new-policies>>
* <<policy-updates>>
* <<new-compliance-benchmarks-and-updates>>
* <<changes-in-existing-behavior>>
* <<rest-api-updates>>
//* <<deprecation-notices>>


[#announcement]
=== Announcement

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Prisma Cloud Darwin Release*
//received the blurb on Slack from Matangi. No Jira ticket for this.
 
|The *Prisma Cloud Darwin Release* is here for Prisma Cloud environments on *UPDATE* except app.gov. With the  Code to Cloud™ intelligence capabilities in this release, your security and development teams can work together to reduce application risks and prevent breaches.

With this change, your tenant will be updated with the new intuitive user interface and https://live.paloaltonetworks.com/t5/prisma-cloud-customer-videos/prisma-cloud-evolution-amp-transformation/ta-p/556596[rich set of security capabilities]. 

Connect with your Customer Success team for more details.

When you are upgraded to the Darwin release, refer to the https://docs.prismacloud.io/en/enterprise-edition/content-collections/[Enterprise Edition documentation].

|===


[#new-features]
=== New Features

New Attack Path policies are available. Log in to the Prisma Cloud console and filter for the list of available policies.

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Amazon EC2*

tt:[23.12.1]

//RLP-120745
|*aws-ec2-vpc-endpoint-service*

Additional permissions required:

* `ec2:DescribeVpcEndpointServices`

The Security Audit Policy role includes the `ec2:DescribeVpcEndpointServices` permission.  

|*AWS CodeCommit*

tt:[23.12.1]

//RLP-120750
|*aws-code-commit-repository*

Additional permissions required:

* `codecommit:ListRepositories`
* `codecommit:GetRepository`

The Security Audit Policy role includes the `ec2:DescribeVpcEndpointServices` permission.

|*AWS CodeCommit*

tt:[23.12.1]

//RLP-120755
|*aws-code-commit-approval-rule-template*

Additional permissions required:

* `codecommit:ListApprovalRuleTemplates`
* `codecommit:GetApprovalRuleTemplate`

The Security Audit role only includes the `codecommit:ListApprovalRuleTemplates` permission. You must manually add the `codecommit:GetApprovalRuleTemplate` permission to the CFT template to enable the permission.

|*Amazon CodePipeline*

tt:[23.12.1]

//RLP-120757
|*aws-code-pipeline-webhook*

Additional permissions required:

* `codepipeline:ListWebhooks`

You must manually add the `codepipeline:ListWebhooks` permission to the CFT template to enable the permission.

|*Amazon EMR*

tt:[23.12.1]

//RLP-118746
|*aws-emr-instance*

Additional permissions required:

* `elasticmapreduce:ListClusters`
* `elasticmapreduce:ListInstances`

The Security Audit role includes the permission.

|*AWS CodeBuild*

tt:[23.12.1]

//RLP-118748
|*aws-code-build-source-credential*

Additional permissions required:

* `codebuild:ListSourceCredentials`

You must manually add the `codebuild:ListSourceCredentials` permission to the CFT template to enable the permission.

|*AWS Elastic Disaster Recovery*

tt:[23.12.1]

//RLP-118753
|*aws-drs-source-server*

Additional permissions required:

* `drs:DescribeSourceServers`

You must manually add the `drs:DescribeSourceServers` permission to the CFT template to enable the permission.

|*AWS Elastic Disaster Recovery*

tt:[23.12.1]

//RLP-118756
|*aws-drs-replication-configuration*

Additional permissions required:

* `drs:DescribeSourceServers`
* `drs:GetReplicationConfiguration`

You must manually add the `drs:DescribeSourceServers` and `drs:GetReplicationConfiguration` permissions to the CFT template to enable the permission.

|*Azure Cache*

tt:[23.12.1]

//RLP-119062
|*azure-cache-redis-diagnostic-settings*

Additional permissions required:

* `Microsoft.Cache/redis/read`
* `Microsoft.Insights/DiagnosticSettings/Read`

The Reader role includes the permissions.

|*Azure Log Analytics*

tt:[23.12.1]

//RLP-120365
|*azure-log-analytics-clusters*

Additional permissions required:

* `Microsoft.OperationalInsights/clusters/read` 

The Reader role includes the permission.

|*Google Cloud VMware Engine*

tt:[23.12.1]

//RLP-119350
|*gcloud-vmware-engine-private-cloud*

Additional permissions required:

* `vmwareengine.locations.list` 
* `vmwareengine.privateClouds.list`
* `vmwareengine.privateClouds.getIamPolicy`

The Viewer role includes the permissions.

|*Google Cloud VMware Engine*

tt:[23.12.1]

//RLP-119358
|*gcloud-vmware-engine-cluster*

Additional permissions required:

* `vmwareengine.locations.list` 
* `vmwareengine.privateClouds.list`
* `vmwareengine.clusters.list`
* `vmwareengine.clusters.getIamPolicy` 
 
The Viewer role includes the permissions.

|*Google Cloud VMware Engine*

tt:[23.12.1]

//RLP-119359
|*gcloud-vmware-engine-hcx-activation-key*

Additional permissions required:

* `vmwareengine.locations.list` 
* `vmwareengine.privateClouds.list`
* `vmwareengine.hcxActivationKeys.list`
* `vmwareengine.hcxActivationKeys.getIamPolicy` 
 
The Viewer role includes the permissions.

|*Google Cloud VMware Engine*

tt:[23.12.1]

//RLP-119360
|*gcloud-vmware-engine-subnet*

Additional permissions required:

* `vmwareengine.locations.list` 
* `vmwareengine.privateClouds.list`
* `vmwareengine.subnets.list` 
 
The Viewer role includes the permissions.

|*Google Vertex AI AIPlatform*

tt:[23.12.1]

//RLP-120762
|*gcloud-vertex-ai-aiplatform-pipeline-job*

Additional permissions required:

* `aiplatform.pipelineJobs.list`

The Viewer role includes the permissions.

|*Google Vertex AI AIPlatform*

tt:[23.12.1]

//RLP-121265
|*gcloud-vertex-ai-aiplatform-training-pipeline*

Additional permissions required:

* `aiplatform.trainingPipelines.list`

The Viewer role includes the permissions.

|*Google Vertex AI AIPlatform*

tt:[23.12.1]

//RLP-121266
|*gcloud-vertex-ai-aiplatform-endpoint*

Additional permissions required:

* `aiplatform.endpoints.list`

The Viewer role includes the permissions.

|*Google Vertex AI AIPlatform*

tt:[23.12.1]

//RLP-121267
|*gcloud-vertex-ai-aiplatform-custom-job*

Additional permissions required:

* `aiplatform.customJobs.list`

The Viewer role includes the permissions.


|*Google Speech to Text*
//RLP-115608
tt:[23.12.1]

|*gcloud-speech-projects-locations-customClasses-list*

Additional permissions required:

* `speech.customClasses.list`

The Viewer role includes the permissions.

|*Google Speech to Text*
//RLP-115162
tt:[23.12.1]

|*gcloud-speech-projects-locations-phraseSets-list*

Additional permissions required:

* `speech.phraseSets.list`

The Viewer role includes the permissions.

|*Google Cloud Composer*
//RLP-115131
tt:[23.12.1]

|*gcloud-composer-projects-locations-imageVersions-list*

Additional permissions required:

* `composer.imageversions.list`

The Viewer role includes the permissions.

|*OCI Service Catalog*
//RLP-102261
tt:[23.12.1]

|*oci-servicecatalog-catalog*

Additional permissions required:

* `CATALOG_INSPECT`
* `CATALOG_READ`

You must update the Terraform template to enable the permissions.

|*OCI Data Safe*
//RLP-120439
tt:[23.12.1]

|*oci-data-safe-configuration*

Additional permissions required:

* `DATA_SAFE_READ`

You must update the Terraform template to enable the permissions.

|===

[#new-policies]
=== New Policies

//[cols="50%a,50%a"]
//|===
//|NEW POLICIES
//|DESCRIPTION
//|===
The 12.1 release does not include any New Poliies.

[#policy-updates]
=== Policy Updates

//[cols="50%a,50%a"]
//|===
//|POLICY UPDATES
//|DESCRIPTION

//2+|*Policy Updates—RQL*

The following IAM out-of-the-box (OOTB) policies will be updated in Prisma Cloud:
//RLP-120492

[cols="30%a,35%a,35%a"]
|===

|POLICY NAME
|Current RQL
|Updated RQL

|*Azure VM instance associated managed identity with Azure built-in roles of Contributor/Owner permissions*

|*Changes—* The policy name will be updated.

*Current Name—* Azure VM instance associated managed identity with Azure built-in roles of Contributor/Owner permissions

*Updated Name—* Azure VM instance associated managed identity with Azure built-in roles of Owner permissions

|NA


|*AWS IAM policy allows Privilege escalation via PassRole & CodeBuild permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codebuild:CreateProject', 'codebuild:StartBuild', 'codebuild:StartBuildBatch') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codebuild:CreateProject', 'codebuild:StartBuild', 'codebuild:StartBuildBatch') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & CodeStar project permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codestar:CreateProject' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codestar:CreateProject' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Data Pipeline permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'datapipeline:ActivatePipeline', 'datapipeline:CreatePipeline', 'datapipeline:PutPipelineDefinition') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'datapipeline:ActivatePipeline', 'datapipeline:CreatePipeline', 'datapipeline:PutPipelineDefinition') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & EC2 permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'ec2:RunInstances' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'ec2:RunInstances' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue create job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue development endpoint permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateDevEndpoint', 'glue:GetDevEndpoint') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateDevEndpoint', 'glue:GetDevEndpoint') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue update job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:UpdateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:UpdateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create & invoke Function permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:InvokeFunction', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:InvokeFunction', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create Function & Event source mapping permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:CreateEventSourceMapping', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:CreateEventSourceMapping', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create Function & add permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:AddPermission', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:AddPermission', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & SageMaker create processing job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateProcessingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateProcessingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & SageMaker create training job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateTrainingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateTrainingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|===

[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|COMPLIANCE BENCHMARK
|DESCRIPTION

|*Support for MITRE ATT&CK Cloud IaaS v13*
//RLP-121584, RLP-120363

|Prisma Cloud now supports the MITRE ATT&CK Cloud IaaS v13 AND v14.0 compliance standard. This framework includes Att&ck Tactics, Techniques and sub-techniques that attackers can leverage to compromise cloud applications and infrastructure.

You can now view this built-in standard and the associated policies on the *Compliance > Standards* page. You can also generate reports for immediate viewing or download, or schedule recurring reports to track this compliance standard over time.

|===

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

| *Checkov CLI upgrade*

tt:[Secure the Source]

tt:[23.12.1]

//RLP-112353
| The Checkov CLI has been upgraded to Checkov 3.0. The upgrade impacts a few known changes:

* *Level Up*: This capability has been removed. This change is non-disruptive and affects only Bridgecrew standalone sign ups.
* *Multi-Signatures*: Multi-signatures in Python checks are being removed. This will only impact custom Python policies using this method.
* *Deprecating flags for Suppression and Fix*: CLI command of `--skip-fixes` and `--skip-suppressions` are being deprecated. Instead `--skip-download` is a recommended command.
* *API Key Restriction and Repo-ID Parameter*: Scans with  API keys will now require the --repo-id parameter for repository scans allowing for easier platform mapping.
* *Enhanced Argument Handling*: The way to specify frameworks and skip frameworks will align to other flags where multiple values can be listed (like --check). For example: `--framework terraform,arm`..
* *Pyston Docker Build Deprecation*: The Pyston Docker build has been depreciated due to increasing complexities in support. The regular Checkov image will still be available for use.

|===

[#rest-api-updates]
=== REST API Updates

[cols="37%a,63%a"]
|===
|CHANGE
|DESCRIPTION

|*RLP-118362*

tt:[23.12.1]

//RLP-119318

|Placeholder


|*RLP-120514*

tt:[23.12.1]

//RLP-119223

|Placeholder

|===

