:toc: macro
== 31.03 Update 3 Release Notes (Build 31.03.109)

The following table lists the release details:

[cols="1,4"]
|===
|Build
|31.03.109

|Code name
|Newton, 31.03 Update 3

|Release date
|April 08, 2024

|Type
|Maintenance Release

|SHA-256
|4cadb80fd81d0192d3ee9a4b10224102ce4e59ba7bf2b2ff266c96297a4a48b4
|===

This 31.03.109 build is a maintenance release with security fixes.

Review the https://docs.prismacloud.io/en/compute-edition/31/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

=== Addressed Issues

//CWP-57787
//*Fixed an issue in Newton code migration, which in rare cases caused panic for on-premises consoles.
//*Ignored the `GHSA-xm99-6pv5-q363` vulnerability since it is a disputed CVE.

* Added a fix in the Newton code to resolve an issue caused in rare cases during on-premises console migration. 
* Added a fix in the CRI image scans to resolve an issue caused in rare cases due to concurrent map write and read.
* Added a fix in Go packages to avoid false positives in vulnerabilities detection for Go packages.
* Fixed Critical and High vulnerabilities issues discovered in console and defenders. 
* Suppressed `GHSA-xm99-6pv5-q363` vulnerability, also known as CVE-2022-29583, since it is a disputed CVE.