:toc: macro
== 33.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|33.00.169

|Code name
|Pascal

|Release date
|September 09, 2024

|Type
|Major release

|SHA-256
|9d0fa0c4867f47c1a4b515664563d9cf7224902b3cab8fd151ff3b6b1a4f4172
|===

Review the https://docs.prismacloud.io/en/compute-edition/33/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

// {https://cdn.twistlock.com/releases/oPTOxren/prisma_cloud_compute_edition_33_00_168.tar.gz[https://cdn.twistlock.com/releases/oPTOxren/prisma_cloud_compute_edition_33_00_168.tar.gz]} Change in tar file to update latest number.

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defender Versions 22.12 and Earlier

With the `v33.00` release, https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[Defender versions supported (n, n-1, and n-2)] are `v33.00`, `v32.00`, and `v31.00`.

To prepare for this update, you must upgrade your Defenders from version `v22.12` (Lagrange) or earlier to a later version.
Failure to upgrade Defenders will result in disconnection of any Defender version below `v30.00` such as `v22.12`.

[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the `v33.00` release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported Console versions (n, n-1, and n-2)] are `v32.00`, `v31.00`, and `v30.00`.

You can upgrade the Prisma Cloud console directly from any version for n-1 to n.
With `v30.00` as n-1 and `v31.00` as n, you can for example go directly from `v30.01.153` to `v31.00.129`.

You have to upgrade any version of `v22.00` to `v30.00` before upgrading to `v31.00`.
For example, you can upgrade from `v22.12.693` to `v30.02.123` and then upgrade to `v32.00.159`.


[#announcement]
=== Announcement

//CWP-61282

=== Lifecycle Support Update

Prisma Cloud officially guarantees backward compatibility with up to two previous major versions (N-2).

Although the support lifecycle remains unchanged, starting from version 33.xx, Prisma Cloud will not restrict the usage of Defender versions or REST API calls from up to three major releases before the current version (upto N-3 major releases).

For example, with the current version at 33.xx, API calls and Defenders from version 30.xx will be allowed. However, support and complete backward compatibility is guaranteed for the 32.xx and 31.xx releases.

[#cve-coverage-update]
=== CVE Coverage Update

// CWP-60486
=== CVE-2024-6375
The MongoDB package has been successfully upgraded to version 6.0.16. As a result, the console deployed image is no longer vulnerable to CVE-2024-6375 and is no longer present on the ignore list.

[#enhancements]
=== Enhancements

=== Transition from OVAL to VEX Format for Red Hat Security Data

// CWP-61485/CWP-59337

Prisma Cloud is transitioning from the OVAL format to the new VEX format that Red Hat has introduced and adopted for reporting security data and vulnerabilities in Red Hat artifacts.

*Pre-33.00*: Until you upgrade to a 33.xx release, Prisma Cloud will continue using OVAL for vulnerability scanning with no expected impact.

*33.xx*: After upgrading your Console and Defenders to version 33.00 or later, Prisma Cloud will switch to the VEX format for vulnerability reporting. This transition might result in a change in the number of reported CVEs due to the inherent differences between the VEX and OVAL content.

*Comparison Between OVAL and VEX Formats*: With the OVAL format, Prisma Cloud reports vulnerabilities for each binary found during the scan. However, with the new VEX format, Prisma Cloud will report one vulnerability for the source package and provide information on related binaries.

This means that the number of vulnerabilities with the same CVE ID will be reduced, as Prisma Cloud will report one vulnerability for the RPM package instead of multiple reports for each binary.

*Continued Support*: Prisma Cloud will continue to support OVAL format for two major versions—v33.xx and v34.xx—to maintain compatibility with Defenders in pre-33.xx releases, as long as Red Hat continues to produce OVAL files.

*Expected Console Loading Time in the 33.xx release*: For new Consoles paired with new Defenders, the Console loading time after a restart event will be approximately 1-2 minutes.

*Console Memory Usage in the 33.XX release*: For on-premise users upgrading to the latest Console, the Console memory requirement is 8 GB. This requirement is only for the self-hosted editions.

For a more detailed explanation of this transition, see the https://main%2D%2Dprisma-cloud-docs-website%2D%2Dhlxsites.hlx.live/en/compute-edition/assets/pdf/lookahead-transition-to-vex-format.pdf[Transition from Oval to VEX Files] document.

If you have any concerns or need additional information about this transition, contact support@paloaltonetworks.com.

// // CWP-59339
// === Enhancement to WAAS Agentless Support
// WAAS agentless rules now support traffic inspection for AWS Application Load Balancers (ALBs) in addition to AWS EC2 instances. Ensure your AWS account is onboarded to the Prisma Cloud console and then configure the ALB rule.

// To add the ALB rule access *Defend > WAAS > Add Rule > Add Configuration*. Ensure your CloudFormation template is applied with the necessary permissions to your onboarded AWS account in the region where the ALB resides. You can view the scan results in the Prisma Cloud console to monitor and manage your ALB traffic inspection.

// NOTE: This feature is enabled on request. Please contact your Account team for more details.


//[#new-features-agentless-security]
// === New Features in Agentless Security

// [#new-features-core]
// === New Features in Core

// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS

[#api-changes]
=== API Changes and New APIs

// CWP-59340
=== WAAS Agentless - Support AWS LB

The https://pan.dev/prisma-cloud/api/cwpp/put-policies-firewall-app-agentless/[Set Agentless App Firewall Policy] API request is updated to support AWS Application Load Balancers (ALBs):

* The “trafficMirroring > vpcConfig” property is modified to include three new fields for ALBs:
** lbARN - ARN of the observed load balancer.
** lbName - Load balancer name.
** lbType - Load balance type.

* The following existing fields are now applicable as follows:

** instanceNames -  used only in EC2 rules.
** subnetID - used only in EC2 rules.
** tags - used only in EC2 rules.
** vpcID - must be empty (””) for ALB rules.
** autoScalingEnabled - must be true for ALB rules.

// [#addressed-issues]
// === Addressed Issues


// [#deprecation-notices]
// === Deprecation Notices

