== Autoscaling groups did not supply tags to launch configurations


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 660b9b45-f88a-476f-a1f8-292f9e284bd6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/AutoScalingTagging.py[CKV_AWS_153]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


This policy ensures that autoscaling groups supply tags to their launch configurations. Tags help you control access to Auto Scaling groups based on tags through conditions in your IAM policies. They also help identify and organize your AWS resources, as many AWS services support tagging, allowing you to assign the same tag to resources from different services to indicate that the resources are related. Tags enable you to apply tag-based, resource-level permissions in the identity-based policies you create for Amazon EC2 Auto Scaling, giving you better control over which resources a user can create, modify, use, or delete.

=== Fix - Buildtime


*Terraform* 

* *Resource:* aws_autoscaling_group
* *Arguments:* launch_configuration, tags

To mitigate this issue, ensure that the `aws_autoscaling_group` resource includes the `tag` or `tags` attribute with appropriate key-value pairs.

[source,hcl]
----
resource "aws_autoscaling_group" "example" {
    ...
+  tags = concat(
    [
      {
        "key"                 = "interpolation1"
        "value"               = "value3"
        "propagate_at_launch" = true
      },
      ...
    ]
)
}
----
