== AWS Elasticsearch domain has Dedicated master set to disabled

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5727a110-89e3-4f9f-befa-6ed9d2f474a1

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/ElasticSearchDedicatedMasterEnabled.yaml[CKV2_AWS_59]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 

=== Description

This policy checks if Elasticsearch/OpenSearch clusters are configured with a dedicated master node. Having a dedicated master node for Elasticsearch/OpenSearch clusters helps ensure that the cluster’s state and health status is managed properly and prevents the cluster from becoming unstable in case of failures.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_opensearch_domain, aws_elasticsearch_domain
* *Arguments:* cluster_config.dedicated_master_enabled

To fix the issue, ensure the 'dedicated_master_enabled' configuration is set to 'true' inside the 'cluster_config' block of the Elasticsearch or OpenSearch domain resource.

Secure code example:

[source,go]
----
resource "aws_elasticsearch_domain" "example" {
  domain_name = "example"

  cluster_config {
    instance_count = 5
+   dedicated_master_enabled = true
    dedicated_master_type = "m3.medium.elasticsearch"
  }
}
----

The above code is secure as it enables a dedicated master node in the Elasticsearch/OpenSearch domain, which provides better control and stability over the cluster's state and health status.

