== AWS Neptune Cluster does not have Deletion Protection Enabled
                
=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/NeptuneDeletionProtectionEnabled.yaml[CKV2_AWS_58]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 

=== Description

This policy ensures that AWS Neptune clusters have deletion protection enabled. Deletion Protection safeguards against accidental deletion of AWS resources, allowing for greater data protection and security.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_neptune_cluster
* *Arguments:* deletion_protection

To fix this issue, you need to set the 'deletion_protection' parameter to 'true' in the AWS Neptune cluster settings.

Secure code example:

[source,go]
----
resource "aws_neptune_cluster" "example" {
  cluster_identifier      = "example"
+ deletion_protection     = true
}
----

The above code is secure as it has deletion protection enabled, which prevents accidental removal of AWS resources. 

