
== Amazon SageMaker Flow Definition does not use KMS for output configurations

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/SagemakerFlowDefinitionUsesKMS.py[CKV_AWS_372]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan,CloudFormation

|===

=== Description

This policy ensures that Amazon SageMaker Flow Definition is utilizing Key Management Service (KMS) for output configurations. Failing to do so can be problematic as it increases the risk of unauthorized data exposure. KMS encapsulates the key material in a cryptographic envelope and stores it in a system that's physically separated from data stores. KMS offers an additional layer of security control for sensitive data storage, making sure that the data is not directly exposed and reducing the risk of potential data breaches.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_sagemaker_flow_definition
* *Arguments:* output_config/kms_key_id

To fix the issue, you need to add KMS key to your SageMaker Flow Definition output configurations. You can do this by defining a `kms_key_id` in the `output_config` block of your AWS SageMaker Flow Definition.

[source,hcl]
----
resource "aws_sagemaker_flow_definition" "example" {
  ...
  output_config {
+    kms_key_id = "example"
  }
}
----

