== Amazon SageMaker Notebook Instance allows for IMDSv1

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/SagemakerNotebookInstanceAllowsIMDSv2.py[CKV_AWS_371]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan,CloudFormation

|===

=== Description

This policy is checking to ensure that Amazon SageMaker Notebook Instances are only allowing for Instance Metadata Service version 2 (IMDSv2). The reason for ensuring this is that IMDSv1 is vulnerable to server-side request forgery (SSRF) attacks and open to potential unauthorized access. By using IMDSv2, it reduces such security risks by requiring session-oriented requests, hence improving the security posture of your AWS resources.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_sagemaker_notebook_instance
* *Arguments:* instance_metadata_service_configuration/minimum_instance_metadata_service_version

To fix the issue, ensure that the Amazon Sagemaker Notebook Instance is configured to only allow Instance Metadata Service Version 2 (IMDSv2). This can be done by setting the `minimum_instance_metadata_service_version` to 2.

[source,go]
----
resource "aws_sagemaker_notebook_instance" "my_notebook_instance_pass" {
  ...
  instance_metadata_service_configuration {
+    minimum_instance_metadata_service_version = "2"
  }
}
----

*CloudFormation*

* *Resource:* AWS::SageMaker::NotebookInstance
* *Arguments:* Properties/InstanceMetadataServiceConfiguration/MinimumInstanceMetadataServiceVersion

To fix the issue, ensure that the Amazon Sagemaker Notebook Instance is configured to only allow Instance Metadata Service Version 2 (IMDSv2). This can be done by setting the `MinimumInstanceMetadataServiceVersion` to 2.

[source,go]
----
Resources:
  Example:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      ...
      InstanceMetadataServiceConfiguration:
        MinimumInstanceMetadataServiceVersion: "2"
----
