== Ensure that AWS Secrets Manager secrets have automatic rotation enabled

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/SecretsAreRotated.yaml[CKV2_AWS_57]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 

=== Description

This policy detects whether rotation is enabled for Secrets in AWS Secrets Manager. Enabling rotation for secrets helps reduce the risk of unauthorized access to the secrets.

=== Fix - Buildtime
                
*Terraform*

* *Resource:* aws_secretsmanager_secret
* *Arguments:* aws_secretsmanager_secret_rotation


[source,hcl]
----
resource "aws_secretsmanager_secret" "example" {
  name       = "example-secret"
  # Other necessary configurations
}

resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = "YourSecretValue"
  # Other necessary configurations
}

resource "aws_secretsmanager_secret_rotation" "example" {
  secret_id           = aws_secretsmanager_secret.example.id
  rotation_lambda_arn = aws_lambda_function.example.arn
  rotation_rules {
    automatically_after_days = 30
  }
  # Other necessary configurations
}

resource "aws_lambda_function" "example" {
  # Your lambda function configuration
  # This function will handle the rotation logic for the secret
}

# Note: IAM policies and roles would be required for the Lambda function to access the Secrets Manager secret.

----

In this Terraform example, an aws_secretsmanager_secret resource is declared to create a new secret in AWS Secrets Manager, and an aws_secretsmanager_secret_rotation resource is configured to enable automatic rotation for that secret. The aws_secretsmanager_secret_rotation resource references the secret by its ID and specifies a Lambda function ARN that will handle the rotation logic, with rotation rules stating how frequently the secret should be rotated (e.g., every 30 days). To satisfy the policy, the example assumes that the Lambda function and necessary IAM roles and policies are correctly set up to perform the rotation, which are essential components for enabling and executing automatic rotation.
