== AWS CodeGuru Reviewer repository association does not use a Customer Managed Key (CMK)

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/AWSCodeGuruHasCMK.py[CKV_AWS_381]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,Terraform Plan

|===

=== Description

This policy identifies AWS CodeGuru Reviewer repository associations that are not configured with a Customer Managed Key (CMK). Using CMK for encryption ensures that you have full control over the encryption keys, enhancing security for your repository data. Relying on default encryption options may not provide the level of security and compliance required for sensitive environments.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_codegurureviewer_repository_association
* *Arguments:* kms_key_details

To fix this issue, ensure that the `kms_key_details` block is configured with the `encryption_option` set to `CUSTOMER_MANAGED_CMK` in your Terraform configuration.

[source,go]
----
resource "aws_codegurureviewer_repository_association" "example" {
  ...
  kms_key_details {
+    encryption_option = "CUSTOMER_MANAGED_CMK"
  }
}
----
