
== Runtime of Lambda is deprecated

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/DeprecatedLambdaRuntime.py[CKV_AWS_363]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to make sure that the runtime used for Lambda is not deprecated. Lambda is an AWS service which lets you run your code without provisioning or managing servers. A runtime in this context refers to the programming language environment in which your code will be executed. 

Using deprecated runtimes can be problematic for several reasons. Deprecated runtimes may no longer receive security updates, leaving your code vulnerable to newly discovered security threats. Additionally, deprecated runtimes might not support the latest language features, and can result in compatibility issues with other software in your stack. Using outdated runtimes can also lead to increased maintenance costs and technical debt as the runtime becomes further out of date.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_lambda_function
* *Arguments:* runtime

To fix this issue, you must define your AWS Lambda function with a current, supported runtime. Deprecated runtimes are not maintained and may contain vulnerabilities.

Assuming you had originally defined your Lambda function with a deprecated runtime using Terraform, like the following:

[source,hcl]
----
resource "aws_lambda_function" "lambda_function" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = aws_iam_role.lambda.arn
  handler       = "exports.test"
  runtime       = "nodejs8.10" 
}
----

