
== Redshift clusters are not using the default database name.

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 02149f11-1502-4acc-a4f8-4470861f4ef3

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/RedshiftClusterDatabaseName.py[CKV_AWS_320]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to ensure that Redshift clusters are not using the default database name. Using the default database name in AWS Redshift clusters can pose a security risk as it can be easily guessed by malicious actors. They could potentially gain unauthorized access to your database if other security measures are weak or compromised. For enhanced security, it is recommended to use a unique database name that cannot be easily guessed.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_redshift_cluster
* *Arguments:* database_name

To fix the issue, you need to ensure that your Redshift clusters are not using the default database name. You should specify a unique name for every Redshift cluster you create.

[source,go]
----
resource "aws_redshift_cluster" "default" {
  cluster_identifier = "tf-redshift-cluster"
  database_name      = "my_db"
}
----


