== GCP Kubernetes cluster node auto-upgrade configuration disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_GCP_10
|Category |Monitoring - Resource Health
|Provider |GCP
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |ee11eb8a-a8a1-4703-980c-940057b84f24
|===


=== Description 


Node *auto-upgrade* keeps nodes up-to-date with the latest cluster master version when your master is updated on your behalf.
When a new cluster or node pool is created, node *auto-upgrade* is enabled as default.
We recommend you ensure *auto-upgrade* is enabled.
Automatic node upgrade ensures that when new binaries are released you instantly get a fix with the latest security issues resolved.
GKE will automatically ensure that security updates are applied and kept up to date.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "my-node-pool"
  cluster    = google_container_cluster.primary.id
  node_count = 1
  management {
    auto_upgrade = true
  }
    ]
  }
}
----

