== Azure Microsoft Defender for Cloud is set to Off for App Service


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_61
|Category |Monitoring - Alerting and Notifications
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |11e46b7a-6a7d-4500-aef5-f21b0ee608ad
|===


=== Description 


Azure Defender is a cloud workload protection service that utilizes and agent-based deployment to analyze signals from Azure network fabric and the service control plane, to detect threats across all Azure resources.
It can also analyze non-Azure resources, utilizing Azure Arc, including those on-premises and in both AWS and GCP (once they've been onboarded).
Azure Defender for App Service detects attacks targeting applications running over App Service.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_security_center_subscription_pricing
* *Arguments:* resource_type - (Required) The resource type this setting affects.

Ensure that `AppServices` is declared to pass this check.


[source,go]
----
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "AppServices,ContainerRegistry,KeyVaults,KubernetesService,SqlServers,SqlServerVirtualMachines,StorageAccounts,VirtualMachines,ARM,DNS"
}
----
