== AWS resources that support tags do not have Tags misconfiguration detected in code



=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_CUSTOM_1
|Category |Monitoring - Tags and Metadata
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Many AWS resources support tags. Without tags, it is difficult to organize, manage and track resources. 
Tags allow you to add metadata to a resource to help identify ownership, perform cost / billing analysis, and to enrich a resource with other valuable information, such as descriptions and environment names. 

While there are many ways that tags can be used, we recommend you follow a tagging practice.
View AWS's recommended tagging best practices https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf[here].

=== How to Fix


*Terraform* 


The example below shows how to tag a security group in Terraform.
The syntax is generally the same for any taggable resource type.


[source,go]
----
resource "aws_security_group" "sg" {
  name = "my-sg"
  ...
+ tags = {
+   Environment = "dev"
+   Owner = "apps-team"
+ }
}
----
