== The --profiling argument is not set to False for scheduler misconfiguration detected in code
// '--profiling' argument not set to False for scheduler


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_114
|Category |Monitoring - Resource Health
|Provider |
|Severity |LOW
|Framework |Kubernetes, Helm, Kustomize
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
Disable profiling, if not needed.
Profiling allows for the identification of specific performance bottlenecks.
It generates a significant amount of program data that could potentially be exploited to uncover system and program details.
If you are not experiencing any bottlenecks and do not need the profiler for troubleshooting purposes, it is recommended to turn it off to reduce the potential attack surface.

=== How to Fix


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
+   - kube-scheduler
+   - --profiling=false
    image: gcr.io/google_containers/kube-scheduler-amd64:v1.6.0",
}
----

