== Alibaba Cloud Kubernetes node pools are not set to auto repair


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7ad299d9-0dcb-41ce-9f66-0a30c5700b13

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/K8sNodePoolAutoRepair.py[CKV_ALI_31]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that Kubernetes node pools in Alibaba Cloud have the auto-repair feature enabled. Auto-repair automatically replaces unhealthy nodes, ensuring high availability and stability of the cluster. This feature helps reduce manual intervention, minimizes downtime, and ensures that workloads are not disrupted by failed nodes.

Failing to enable auto-repair can result in degraded cluster performance or availability if node failures are not promptly addressed.

=== Fix - Buildtime


*Terraform* 

*Terraform*

* *Resource:* alicloud_cs_kubernetes_node_pool
* *Arguments:* management.auto_repair

To mitigate this issue, ensure the `management.auto_repair` attribute in the `alicloud_cs_kubernetes_node_pool` resource is set to `true`.

Example:

[source,go]
----
resource "alicloud_cs_kubernetes_node_pool" "example" {
  ...

  management {
+    auto_repair = true
  }
}
----
