== Azure Microsoft Defender for Cloud security contact phone number is not set


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_20
|Category |Monitoring - Alerting and Notifications
|Provider |Azure
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |51be4654-4d2d-43c4-9279-58bb38a1d741
|===


=== Impact
Microsoft reaches out to the designated security contact in case its security team finds that the organization's resources are compromised.
This ensures that the correct people are aware of any potential compromise and can mitigate the risk in a timely fashion.
We recommend you provide a security contact phone number, but before taking any action make sure that the information provided is valid because the communication is not digitally signed.
=== How to Fix


*Terraform* 


* *Resource:* azurerm_security_center_contact
* *Arguments:* phone


[source,go]
----
resource "azurerm_security_center_contact" "example" {
    email = "contact@example.com"
    phone = "+1-555-555-5555"
}
----
