== AWS ECS cluster with container insights feature disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_65
|Category |Monitoring - Performance Monitoring
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |577ef22c-f4c5-4a54-8aa0-cc6f58275777
|===


=== Impact
Container Insights can be used to collect, aggregate, and summarize metrics and logs from containerized applications and microservices.
They can also be extended to collect metrics at the cluster, task, and service levels.
Using Container Insights allows you to monitor, troubleshoot, and set alarms for all your Amazon ECS resources.
It provides a simple to use native and fully managed service for managing ECS issues.
We recommend that for existing clusters you use the AWS CLI;
and for new clusters, you use either the Amazon ECS console, or the AWS CLI.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_ecs_cluster
* *Arguments:* setting


[source,go]
----
resource "aws_ecs_cluster" "foo" {
  ...
  name = "white-hart"
+ setting {
+   name  = "containerInsights"
+   value = "enabled"
+ }
}
----


*CloudFormation* 


* *Resource:* AWS::ECS::Cluster
* *Arguments:* Properties.ClusterSettings


[source,yaml]
----
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ...
+     ClusterSettings:
+       - Name: 'containerInsights'
+         Value: 'enabled'
----
