== App Service is not registered with an Azure Active Directory account misconfiguration detected in code
// App Service not registered with an Azure Active Directory account


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_16
|Category |IAM - Authentication Policies
|Provider |Azure
|Severity |MEDIUM
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
Managed service identity in *App Service* increases security by eliminating secrets from the app, for example, credentials in the connection strings.
*App Service* provides a highly-scalable, self-patching web hosting service in Azure.
It also provides a managed identity for apps, which is a turn-key solution for securing access to an Azure SQL Database and other Azure services.
We recommend you register the *App Service* with your Azure Active Directory account ensuring the app will connect securely to other Azure services without the need of usernames and passwords.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_app_service
* *Field:* identity


[source,go]
----
resource "azurerm_app_service" "example" {
    ...
+    identity {
+        type = "UserAssigned"
+        identity_ids = "12345"
    }
}
----
