
== OAuth2 password flow in security definitions for OpenAPI 2.0 file misconfiguration detected in code

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_OPENAPI_11
|Category |IAM - Authentication Policies
|Provider |
|Severity |HIGH
|Framework |OPENAPI
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This rule is specifically geared towards ensuring the security of OpenAPI documents for APIs, specifically for those using OAuth2 authentication in version 2.0 files. The rule checks for the presence of 'password' flow. The usage of 'password' flow allows direct usage of usernames and passwords to obtain access tokens, circumventing stronger methods of authentication. This leaves user credentials, and by extension your API, more susceptible to cyber threats, hence it is not recommended. The rule aims to flag this as an issue in order to maintain the best security practices.

=== How to Fix

*OpenAPI*

To fix this issue, you need to change the OAuth2 authentication flow. Instead of using 'password' flow, try using 'authorizationCode' or 'implicit' flow. This is a more secure way to handle authentication.

[source,yaml]
----
securitySchemes:
    OauthSecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://authorization-server.com/token
          scopes:
            read: Grants read access
            write: Grants write access
----

The above code is secure because it doesn't expose the user's password in the OAuth2 authentication flow, which could potentially lead to credential leaks or unauthorized access. Instead, it uses the 'authorizationCode' flow that relies upon the interaction between the web browser and the server, which is a more secure approach.

