== AWS IAM policy documents allow * (asterisk) as a statement's action misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_63
|Category |IAM - Overly Permissive
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
This policy ensures that IAM policy documents do not allow "*" as a statement's actions. Allowing "*" in the actions of an IAM policy grants permissions to all actions, which can lead to potential security risks and unauthorized access. This policy checks whether any IAM policy documents contain statements with `"Action": "*"`, which should be avoided.


=== How to Fix


*Terraform* 


* *Resource:* aws_iam_policy
* *Arguments:* policy - (Required) The policy document.

This is a JSON formatted string.
For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide.


[source,go]
----
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
-        "*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
----


*CloudFormation*

To fix this issue, ensure that the IAM policy statements do not use "*" in the actions. Instead, specify the specific actions that are required.

Example:

[source,yaml]
----
Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      ...
      Policies:
        - PolicyName: "example-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
-                  - "*"
                Resource:
                  - "arn:aws:s3:::example-bucket"
                  - "arn:aws:s3:::example-bucket/*"
----
