== Azure Cognitive Search Without Managed Identities misconfiguration detected in code
// Ensure Azure Cognitive Search service uses managed identities to access Azure resources.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_207
|Category |IAM - Authentication Policies
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Cognitive Search is a fully managed cloud search service that provides a richer search experience over content in web and mobile applications. An important aspect of security in Cognitive Search is authentication and authorization. Azure offers managed identities as an effective means to authenticate to Azure services without managing credentials manually.

Using Azure managed identities for Azure Cognitive Search has several benefits:
- Eliminates the need for developers to store or manage service credentials.
- Azure automatically handles the creation, rotation, and retrieval of tokens required for the authentication process.
- Can be used to authenticate to any Azure service that supports Azure AD authentication.
- No additional costs are associated with using managed identities.

This rule ensures that the Azure Cognitive Search service is configured to use managed identities for authentication when accessing other Azure services, providing a secure and automated way to manage service-to-service authentication.

=== How to Fix

*Terraform*

*Resource:* 
- azurerm_search_service

*Arguments:* 
- identity

[source,terraform]
----
resource "azurerm_search_service" "example" {
  name                = "example-search-service"
  # ... other configurations ...

+ identity {
+   type = "SystemAssigned"
+ }

  # ... other configurations ...
}
----
