== Alibaba Cloud KMS Key Rotation is disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 57146ef0-2467-4e9c-a474-7f99dc771640

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/KMSKeyRotationIsEnabled.py[CKV_ALI_27]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that KMS (Key Management Service) Key Rotation is enabled for keys in Alibaba Cloud. Enabling automatic key rotation helps to maintain security by periodically changing the cryptographic keys, thereby reducing the risk of key compromise over time. KMS keys without automatic rotation enabled may be left vulnerable to prolonged exposure and potential unauthorized use.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_kms_key
* *Arguments:* automatic_rotation

To mitigate this issue, ensure the `automatic_rotation` attribute of the `alicloud_kms_key` resource is set to `Enabled`.

Example:

[source,go]
----
resource "alicloud_kms_key" "example" {
  ...
+  automatic_rotation = "Enabled"
}
----
