== Azure Service Bus with Local Authentication Enabled misconfiguration detected in code
// Ensure Azure Service Bus Local Authentication is disabled.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_203
|Category |IAM - Authentication Policies
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Service Bus is a messaging service on Azure that supports robust resilience and failover capabilities. To enhance security, it is recommended to disable local authentication and leverage centralized authentication methods such as Azure AD.

Local authentication can potentially allow users with access to the local machine to authenticate, which might not be in line with the enterprise's security policies. This rule ensures that local authentication is disabled for the Azure Service Bus, enforcing the use of more secure authentication methods.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- local_auth_enabled

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ local_auth_enabled = false

  # ... other configurations ...
}
----

