== Azure Event Grid Domain Managed Identity Provider is Disabled misconfiguration detected in code
// Ensure that Managed identity provider is enabled for Azure Event Grid Domain.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_194
|Category |IAM - Authentication Policies
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Event Grid Domain is a custom domain that allows sending events to a topic within the domain. Like Azure Event Grid Topics, Event Grid Domains also provide a runtime environment for sending events.

Using Managed Identities for Azure resources provides Azure services with an automatically managed identity in Azure AD. It can be used to secure access to other Azure resources, eliminating the need for credentials in code.

This rule ensures that a managed identity provider is enabled for Azure Event Grid Domain.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_eventgrid_domain

*Arguments:* 
- identity

[source,terraform]
----
resource "azurerm_eventgrid_domain" "example" {
  name                  = "example-domain"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name

  # ... other configurations ...

+ identity {
+   type = "SystemAssigned"
+ }

  # ... other configurations ...
}
----

