== Credentials exposure actions return credentials in an API response misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_107
|Category |IAM - Credential Exposure
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
AWS IAM users access AWS resources using different types of credentials, such as passwords or access keys.
Credentials Exposure actions return credentials as part of the API response, such as ecr:GetAuthorizationToken, iam:UpdateAccessKey, and others.
For more info, visit cloudsplaning documentation https://cloudsplaining.readthedocs.io/en/latest/glossary/credentials-exposure/

=== How to Fix


*Terraform* 


* *Resource:* aws_iam_policy_document
* *Arguments:* effect + actions


[source,go]
----
data "aws_iam_policy_document" "example" {
  statement {
    sid = "1"
    effect = "Allow"
    actions = [
      "lambda:CreateFunction",
      "lambda:CreateEventSourceMapping",
      "dynamodb:CreateTable",
    ]
    resources = [
      "*",
    ]
  }
}
----


*CloudFormation* 


* *Resource:* AWS::IAM::Policy / AWS::IAM::ManagedPolicy / AWS::IAM::Group / AWS::IAM::Role / AWS::IAM::User
* *Arguments:* Effect + Actions


[source,yaml]
----
Resources:
  AdminDeny:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ...
      PolicyDocument:
        ...
        Statement:
          - Effect: Allow
            Action: 
            -   'lambda:CreateFunction'
                    -   'lambda:CreateEventSourceMapping'
                -   'dynamodb:CreateTable'
            Resource: '*'
----
