== OCI IAM password policy for local (non-federated) users does not have an uppercase character


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_OCI_14
|Category |IAM-AUTHENTICATION_POLICIES
|Provider |ORACLE
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


This policy identifies Oracle Cloud Infrastructure(OCI) accounts that do not have an uppercase character in the password policy for local (non-federated) users.
As a security best practice, configure a strong password policy for secure access to the OCI console.

////
=== Fix - Runtime


* OCI Console* 



. Login to the OCI Console Page:https://console.ap-mumbai-1.oraclecloud.com/

. Go to Identity in the Services menu.

. Select Authentication Settings from the Identity menu.

. Click Edit Authentication Settings in the middle of the page.

. Ensure the checkbox is selected next to MUST CONTAIN AT LEAST 1 UPPERCASE CHARACTER.
+
Note : The console URL is region specific, your tenancy might have a different home region and thus console URL.
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* oci_identity_authentication_policy
* *Arguments:* password_policy.is_uppercase_characters_required


[source,go]
----
resource "oci_identity_authentication_policy" "pass" {
...
  password_policy {
    ...
    is_uppercase_characters_required = true
    ...
  }
}
----

