== AWS Private ECR repository policy is overly permissive


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9f40d30b-97fd-4ec5-827b-f74b50a312b9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/aws/ECRPolicy.py[CKV_AWS_32]

|Severity
|MEDIUM

|Subtype
|Build, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Impact
This policy identifies AWS Private ECR repositories that have overly permissive registry policies. An ECR(Elastic Container Registry) repository is a collection of Docker images available on the AWS cloud. These images might contain sensitive information which should be restricted to unauthorized users.


=== Fix - Buildtime

*Terraform*

To fix this issue, ensure that the `policy` property in the `aws_ecr_repository_policy` resource does not allow public access.

Example:

[source,go]
----
resource "aws_ecr_repository_policy" "example" {
  repository = aws_ecr_repository.example.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage"
        ]
        Resource = aws_ecr_repository.example.arn
        Principal = {
          AWS = "arn:aws:iam::123456789012:role/your-role"
        }
      }
    ]
  })
}
----


*CloudFormation* 


* *Resource:* AWS::ECR::Repository
* *Argument:* Properties.RepositoryPolicyText.Statement.Principal


[source,yaml]
----
Resources: 
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      ...
      RepositoryPolicyText: 
        ...
        Statement: 
          - ...
-           Principal: "*"
+                       Principal:
+             AWS: 
+                - "arn:aws:iam::123456789012:user/Bob"
+                - ...
----
