== AWS IAM password policy does not have a number


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_12
|Category |IAM - Authentication Policies
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |9a5813af-17a3-4058-be13-588ea00b4bfa
|===


=== Description 


Password policies are used to enforce the creation and use of password complexity.
Your IAM password policy should be set for passwords to require the inclusion of different character types.
The password policy should enforce passwords contain at least one number, this increases security, especially from a brute force attack.

////
=== Fix - Runtime


* AWS Console* 


To change the password policy in the AWS Console you will need appropriate permissions to View Identity Access Management Account Settings.
To manually set the password policy with a minimum length, follow these steps:

. Log in to the AWS Management Console as an * IAM user* at https://console.aws.amazon.com/iam/.

. Navigate to * IAM Services*.

. On the Left Pane click * Account Settings*.

. Select * Require at least one number*.

. Click * Apply password policy*.


* CLI Command* 


To change the password policy, use the following command:
[,bash]
----
aws iam update-account-password-policy --require-numbers
----

NOTE:
====
All commands starting with * aws iam update-account-password-policy* can be combined into a single command.
====
////

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "aws_iam_account_password_policy" "strict" {
  ...
+  require_numbers                = true
}
----
