== RDS database does not have IAM authentication enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_161
|Category |IAM - Authentication Policies
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
IAM authentication uses AWS Identity and Access Management (IAM) to authenticate users and applications that connect to your RDS database.
This can be more secure than traditional password-based authentication, as it allows you to use IAM policies and multi-factor authentication to control access to your database.

=== Fix - Buildtime


*Terraform* 


* *Resource:* "aws_db_instance
* *Arguments:* iam_database_authentication_enabled


[source,go]
----
resource "aws_db_instance" "test" {
    ...
+ iam_database_authentication_enabled = true
}
----


*CloudFormation* 


* *Resource:* "AWS::RDS::DBInstance
* *Arguments:* Properties.EnableIAMDatabaseAuthentication


[source,yaml]
----
Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mysql' # or 'postgres'
      ...
+     EnableIAMDatabaseAuthentication: true
----
