== Azure Event Grid Topic Local Authentication Enabled
// Ensure that Azure Event Grid Topic local Authentication is disabled.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_192
|Category |IAM - Authentication Policies
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Azure Event Grid is a managed event routing service based on the publish-subscribe protocol. Event publishers send events to a topic, which then routes events to all subscribed event handlers. When building systems that react to the changes happening in Azure resources, Azure Event Grid can help to streamline and simplify the design and scalability of such systems. 

However, for security purposes, it is recommended to avoid using local authentication mechanisms. These mechanisms can be less secure than managed or cloud-based mechanisms, potentially exposing the system to threats.

This rule ensures that local authentication for Azure Event Grid Topics is disabled.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_eventgrid_topic 

*Arguments:* 
- local_auth_enabled

[source,terraform]
----
resource "azurerm_eventgrid_topic" "example" {
  name                  = "example-topic"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name

  # ... other configurations ...

+ local_auth_enabled = false

  # ... other configurations ...
}
----

