== The RotateKubeletServerCertificate argument for controller managers is not set to True
// 'RotateKubeletServerCertificate' argument for controller managers not set to True

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_K8S_112
|Category |IAM - Authentication Policies
|Provider |
|Severity |MEDIUM
|Framework |Kubernetes, Helm, Kustomize
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Enable kubelet server certificate rotation.
RotateKubeletServerCertificate causes the kubelet to both request a serving certificate after bootstrapping its client credentials and rotate the certificate as its existing credentials expire.
This automated periodic rotation ensures that the there are no downtimes due to expired certificates and thus addressing availability in the CIA security triad.

NOTE: This recommendation only applies if you let kubelets get their certificates from the API server. In case your kubelet certificates come from an outside authority/tool (e.g. Vault) then you need to take care of rotation yourself.


=== Fix - Buildtime


*Kubernetes*

* *Kind:* Pod 


[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kubelet
    tier: control-plane
  name: kubelet
  namespace: kube-system
spec:
  containers:
  - command:
+   - kubelet
+   - --feature-gates=RotateKubeletServerCertificate=true
    image: gcr.io/google_containers/kubelet-amd64:v1.6.0",
}
----

