
== Permissions delegated to AWS services for AWS Lambda functions are not limited by SourceArn or SourceAccount

=== Rule Details

[width=45%]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_364
|Category |IAM-OVERLY_PERMISSIVE
|Provider |AWS
|Severity |HIGH
|Framework |Terraform, Terraform Plan, CloudFormation
|Mapped CSPM/KSPM Rule |None
|===


=== Description

This policy ensures that AWS Lambda function permissions delegated to AWS services are restricted by `SourceArn` or `SourceAccount`. This helps prevent unauthorized access and limits the scope of permissions granted to Lambda functions.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_lambda_permission
* *Arguments:* principal

To fix this issue, you need to ensure that AWS Lambda function permissions delegated to AWS services are limited by SourceArn or SourceAccount. This adds an additional layer of security by explicitly stating where the permissions are coming from.

[source,go]
----
resource "aws_lambda_permission" "with_sns" {
  statement_id  = "AllowExecutionFromSNS"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.example.function_name
  principal     = "sns.amazonaws.com"
+  source_arn    = aws_sns_topic.example.arn
}
----

The above code is secure because it explicitly defines the source of the permissions using the source_arn attribute. This prevents malicious entities from granting themselves permissions to the Lambda function. The attribute source_arn limits the delegation of the permission to the supplied resource, preventing resources outside of the supplied ARN from invoking the Lambda Function.


*CloudFormation*

To mitigate this issue, ensure that the `AWS::Lambda::Permission` resource includes the `SourceArn` or `SourceAccount` property to limit the permissions delegated to AWS services.

Example:

[source,json]
----
{
  "Resources": {
    "MyLambdaPermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": "MyFunction",
        "Principal": "sns.amazonaws.com",
+        "SourceArn": "arn:aws:sns:us-east-1:123456789012:MyTopic"
      }
    }
  }
}
----

[source,yaml]
----
Resources:
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: MyFunction
      Principal: sns.amazonaws.com
+      SourceArn: arn:aws:sns:us-east-1:123456789012:MyTopic
----
