== AWS Customer Master Key (CMK) rotation is not enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_7
|Category |IAM - Expired Key Controls
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |497f7e2c-b702-47c7-9a07-f0f6404ac896
|===


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_7
|Category |IAM - Expired Key Controls
|Provider |AWS
|Severity |LOW
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |497f7e2c-b702-47c7-9a07-f0f6404ac896
|===


=== Impact
AWS Key Management Service (KMS) allows customers to rotate the backing key.
This is where key material is stored within the KMS, and tied to the key ID of the Customer Created customer master key (CMK).
The backing key is used to perform cryptographic operations such as encryption and decryption.
Automated key rotation currently retains all prior backing keys, allowing decryption of encrypted data to take place transparently.
We recommend you enable CMK key rotation to help reduce the potential impact of a compromised key.
Data encrypted with a new key cannot be accessed with a previous key, that may have been exposed.

=== How to Fix


*Terraform* 


* *Resource:* aws_kms_key
* *Arguments:* enable_key_rotation - (Optional) Specifies whether key rotation is enabled.
Defaults to false.


[source,go]
----
resource "aws_kms_key" "kms_key_1" {
  ...
  is_enabled              = true
+ enable_key_rotation    = true
}
----


*CloudFormation* 


* *Resource:* `AWS::KMS::Key`
* *Attribute*: `EnableKeyRotation` - (Optional) Specifies whether key rotation is enabled.
Defaults to false.


[source,yaml]
----
Type: AWS::KMS::Key
Properties: 
  ...
+ EnableKeyRotation: true0
----
