== Azure App Service Web app doesn't have a Managed Service Identity


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_71
|Category |IAM-AUTHENTICATION_POLICIES
|Provider |AZURE
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |b6caba6b-cdb1-4db5-8045-9d0354a602de
|===


=== Description 


Managed service identity in App Service makes the app more secure by eliminating secrets from the app, such as credentials in the connection strings.
When registering with Azure Active Directory in the app service, the app will connect to other Azure services securely without the need of username and passwords.

////
=== Fix - Runtime


* In Azure Console* 



. Log in to the Azure portal.

. Navigate to App Services.

. Click on the reported App.

. Under Setting section, Click on 'Identity'.

. Ensure that 'Status' is set to 'On'.
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_app_service
* *Arguments:* identity.type


[source,go]
----
resource "azurerm_app_service" "example" {
              ...
  +           identity {
  +             type = "SystemAssigned"
                }
              }
----
