== クラウドアカウントを接続する

Prisma Cloud は、クラウドアカウントを保護し、さまざまな業界標準に準拠するための包括的なセキュリティとコンプライアンスを提供しています。簡素化されたオンボーディング エクスペリエンスにより、 *Foundational （基礎）* および *Advanced（詳細）* としてグループ化されたセキュリティ機能を使用して、組織のセキュリティの優先事項に合理化された方法で適応できます (いくつかはデフォルトで有効になっています)。組織のクラウド導入ジャーニーの開始時に *Foundational （基礎）* 機能を使用して、クラウドとオンプレミスの資産を効果的に管理します。*詳細*機能により、クラウド運用をプロアクティブに制御し、ランタイム環境内で問題が顕在化する前に特定し修正することができます。

Prisma Cloudへの投資を最大限に活用し、インフラストラクチャ上のリソースの監視を開始するには、まずパブリッククラウドアカウントをPrisma Cloudに接続する必要があります。オンボーディング プロセスでは、接続とデータの取得を認証および承認するために、Prisma Cloud とクラウド アカウントに対する適切なアクセス許可を持っている必要があります。システム管理者およびクラウドプロビジョニング管理者ロールを持つPrisma Cloud管理者は、クラウドアカウントオンボーディングのプロセスを使って、サポートされているクラウドサービスプロバイダー（Alibaba Cloud, Amazon Web Services, Microsoft Azure, Google Cloud Platform, Oracle Cloud Infrastructure）で初めての実行を快適に行うことができます。

* xref:onboard-aws/onboard-aws.adoc[Amazon Web Services アカウントのオンボーディング]
* xref:onboard-your-azure-account/onboard-your-azure-account.adoc[Microsoft Azureアカウントのオンボーディング]
* xref:onboard-gcp/onboard-gcp.adoc[Google Cloud Platformアカウントのオンボーディング]
* xref:onboard-your-oci-account/onboard-your-oci-account.adoc[Oracle Cloud Infrastructureアカウントのオンボーディング]
* xref:onboard-your-alibaba-account/onboard-your-alibaba-account.adoc[Alibaba Cloudアカウントのオンボーディング]