:topic_type: task
[.task]
== Get Started with OIDC JIT

Prisma Cloud offers System Administrators the ability to auto-provision users within the OPen ID Connect(OIDC) Single Sign-On (SSO)configuration. This option allows you to manage my user identities outside of Prisma Cloud in your organization’s Identity Provider (IdP). Configure OIDC Just in Time (JIT) provisioning to create new Prisma Cloud users on the fly when users with the appropriate entitlements log in via OIDC SSO. 

Complete the steps below on the Prisma Cloud console and your IdP to set up OIDC:
[.procedure]

. Log in to Prisma Cloud using an account with System Administrator privileges to configure SSO.

. Complete the following steps on your Prisma Cloud tenant:
.. Select *Access Control > SSO* and select *OIDC* as shown below.

Field order

Scopes

Info message:openid, email, and profile are always enabled. Additional scopes may be specified here.

Cannot delete, opeid, email and profile, when try to delete got this message:"openid, email, and profile" are required and can not be removed

It is not optional

Role Name Claim

Info Message: The “groups” claim is used by default, you may specify a different claim here if required.

It is not optional

Default Role

Info Message: “ Authenticated users that do not present a valid Prisma Cloud Role under the Role Name Claim will be granted access to this role if specified. If a default role is not specified, users will not be able to access Prisma Cloud via the OIDC SSO integration.”

It is an optional field
