== Application Security Posture Management (ASPM)

Prisma Cloud ASPM is a comprehensive approach to managing the security posture of your organization's applications throughout their lifecycle, from code to cloud to runtime. It helps you proactively identify, prioritize, and remediate security weaknesses, allowing you to safeguard data, prevent attacks and comply with industry standards and regulations.   

=== Key Features

* *Unified security data*: Establish a central hub by onboarding and consolidating security data from diverse sources including cloud assets, accounts, code repositories (version control systems), CI/CD pipelines, registries, and cloud logs. This unified view is enriched by organizational business context. Additionally, Prisma Cloud leverages Abstract Syntax Tree (AST) technology to analyze your code for vulnerabilities and security issues, enabling early detection and granular analysis. This combined approach provides a holistic understanding of your security posture

//* *Onboard and create a Centralized Data Source*: A unified data hub, gathering all your security data from cloud assets, accounts, code repositories, and more.  Additionally, an Abstract Syntax Tree (AST) is created, providing detection and granular analysis of issues within your code 
//* *Application Visibility*: Detects and maps all your databases, dependencies and services
//* *Assets Inventory*: An inventory of all assets (software bill of materials (SBOM))

* *Findings and alerts*: Detect and identify problems, including code issues, SCA vulnerabilities, IaC misconfigurations, CI/CD risks, runtime information amd SOC insights. Prisma Cloud also identify databases containing sensitive and critical data to ensure data privacy, and automate compliance checks to streamline regulatory adherence

* *Prioritization and application security profiling*: Prioritize and deduplicate alerts with code-to-cloud context. Additionally, create business application profiles and context to understand your security posture

* *Actionable security insights*: Security insights including business impact, application profiling, application grouping, application attack surface, drift detection, and graph-based toxic flows allow you to make informed decisions and prioritize security efforts effectively 

* *Produce security insights*: Understand the root cause for common issues, and fix the blast radius (the potential impact) of each issue   

* *Create automated workflows*: Streamline security with out-of-the-box and custom remediation and preventions workflows designed to manage your code-cloud-soc security posture

=== Key Concepts

* *Case*: Represent groups of issues. Cases are categorized according to type such as "Secrets Management", Vulnerability and CI/CD security", and are assigned a progress status such as "New, "In Progress", Resolved"

* *Related Issue*: The fundamental unit of actionable tasks within the system. These tasks represent specific actions that the user or automated processes need to take to address security concerns. The system generates related issues based on pre-defined rules or customer configurations. By design, related issues represent security findings that warrant attention. However, their criticality might vary depending on the specific context

// Initial definition of issue from the Platform Concepts pptx: The basic unit of actionable tasks - when the system (sometimes based on customer configuration) wants the user/automation to handle something. By this nature, they represent something “relatively important”

* *Insight*: Provide deeper context and understanding of the underlying issue, leveraging data analytics to contribute to prioritizing cases based on their potential impact, risk assessment and more

// * *Finding*: From the Platform Concepts pptx: represent information/world description we were able to deduce from raw data. 
