== Deploy App-Embedded Defender on ACI

toc::[]

The App-Embedded Defender for Azure Container Instances (ACI) is deployed at the ACI container group level, which enables you to protect all containers in a container group through the ACI deployment YAML.

Use the following procedure to deploy and validate the Prisma Cloud App-Embedded Defender for an ACI container group:

=== Prerequisites

* An Azure account with a subscription.
* The Azure CLI installed and configured.
* Access to the Prisma Cloud Console.
* A YAML file that defines the ACI container group you want to protect. 

=== Deployment Procedure

Follow these steps to generate and deploy the YAML file required for deploying the GCR app-embedded defender.
Follow these steps to generate and deploy the YAML file required for deploying an ACI container group with the Prisma Cloud app-embedded defender for ACI.

==== Configure the defender and generate the deployment YAML

. Go to *Manage > Defenders > Defenders: Deployed*.
. Select *Manual deploy*.
. Open *Basic Settings*:
.. Select *Single Defender* as the deployment method.
.. Select *Container Defender App-Embedded* as the defender type.
.. Select *ACI container group* as the deployment type.
. Generate the protected deployment YAML: Submit a valid ACI deployment YAML to the Prisma Cloud Console. The console modifies this YAML to include the defender's init container and other essential settings.
.. Enter a valid ACI deployment YAML in *Insert deployment definition*.
+
For more information about ACI container group deployment YAML, see https://learn.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml[YAML reference: Azure Container Instances].
.. Click *Generate protected deployment definition*.
.. The output is displayed in *Generated deployment definition*. Copy the YAML generated by Prisma Cloud Console for deployment in your Azure cloud.

==== Deploy the generated YAML in ACI

After the console processes your original YAML file, it will return a modified version that includes the defender instrumentation.

. Save the YAML generated by the Prisma Cloud Console to a file. For example, `defended-service.yaml`. 
. (If required) Create a resource group:
+
`az group create --name <RESOURCE-GROUP-NAME> --location eastus`
. Deploy this YAML in ACI by running the following command: 
`az container create --resource-group <RESOURCE-GROUP-NAME> --file defended-deploy-aci.yaml`

=== Validate Defender Visibility

The app-embedded defender is an init container that executes and terminates upon completion. You can verify the successful deployment of the defender and your ACI container group within the Azure Cloud environment and the Prisma Cloud Console using the following steps.

==== In ACI:

. To verify that the container group and the app-embedded defender are running, run the command: 
`az container show --resource-group <RESOURCE-GROUP-NAME> --name <CONTAINER-GROUP-NAME> --output table`

A successful deployment will show `provisioningState` as `Succeeded` and `instanceView.state` as `Running`. 

==== In the Prisma Cloud Console

. Onboard the ACI container group in Prisma Cloud. See the Prisma Cloud documentation for account setup procedures.
. Go to *Radar > Defenders > Deployed defenders*.
. Filter the view to locate your new Defender. It will be uniquely identified by a combination of its provider, container name, container group, and resource group.


=== Run Cloud Discovery

Run a cloud discovery scan to ensure the Prisma Cloud Console accurately correlates the running defender with the discovered ACI container group.

. In the Prisma Cloud Console, manually initiate a cloud discovery scan for the relevant ACI container group.
. When the scan is complete, go to the *Radar* view.
. Locate the *container group* asset for your deployment and confirm its status in the *Is Defended* column.

