== Usage of insecure SHA1 hashing algorithm

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5fa237e7-a850-47be-a42b-2659a705a5e4

|Checkov ID 
|CKV3_SAST_242

|Severity
|LOW

|Subtype
|Build

|Language
|Go

|CWEs
|https://cwe.mitre.org/data/definitions/328.html[CWE-328: Use of Weak Hash]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021-Cryptographic Failures]

|=== 

=== Description

This policy checks whether the outdated and insecure SHA1 hash function from the crypto/sha1 package in Go applications is in use.

In the following example the application uses insecure SHA1 hashing from the imported crypto/sha1 package.

[source,Go]
----
package main

import (
    "crypto/sha1"
    "fmt"
)

func main() {
    // Insecure use of SHA1 hashing
    data := []byte("sensitive data")
    hash := sha1.Sum(data)
    fmt.Printf("%x\n", hash)
}
----

=== Fix - Buildtime

To mitigate this issue, replace the insecure SHA1 hashing with modern hash functions such as SHA256 from the crypto/sha256 package. SHA256 provides enhanced security due to its resistance to collision attacks.

In this example, the code uses the SHA-256 hashing algorithm instead of the less secure SHA1.

[source,Go]
----
package main

import (
    "crypto/sha256"
    "fmt"
)

func main() {
    // Secure use of SHA256 hashing
    data := []byte("sensitive data")
    hash := sha256.Sum256(data)
    fmt.Printf("%x\n", hash)
}
----