== AWS IAM policies that allow full administrative privileges are created


=== Policy Details 

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| 2a28f982-ed75-48b0-9e50-f6fccd015335

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/serverless/checks/function/aws/AdminPolicyDocument.py[CKV_AWS_1]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,Serverless,TerraformPlan

|===


=== Description


IAM policies are the means by which privileges are granted to users, groups, and roles.
Standard security practice is to grant _least privilege_ this is granting only the permissions required to perform a task.
Providing full administrative may expose resources to potentially unwanted actions.
We recommend:

* You determine what users need to do, then craft policies allowing them to perform only those tasks.
* You do not allow all users full administrative privileges.
* You start with a minimum set of permissions and grant additional permissions as necessary.
* IAM policies that have a statement with Effect: Allow with Action: * over Resource: * are removed.


=== Fix-Buildtime

*Terraform*

*Resource: aws_iam_policy_document* 

[source,go]
----
data "aws_iam_policy_document" "fail" {
  version = "2012-10-17"

  statement {
    effect = "Allow"
    actions = [
-      "*"
+      "s3:Describe*"
    ]
    resources = [
      "*",
    ]
  }
}
----

*Serverless*


[source,yaml]
----
functions:
  myFunc:
    ...
    iamRoleStatements:
      - Effect: Allow
        Action:
-          - "*"
+          - "s3:Describe*"
        Resource:
          - "*"
----