== Azure Synapse Workspaces do not enable managed virtual networks misconfiguration detected in code
// Managed virtual networks in Azure Synapse Workspaces disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_58
|Category |AI & Machine Learning - Public Exposure
|Provider |Azure
|Severity |LOW
|Framework |ARM, Bicep, Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
Enabling managed virtual networks in Azure Synapse Workspaces can help to improve security and isolation for your data and workloads.
By using a managed virtual network, you can control access to your data and resources by defining network security rules and configuring network routing.
Managed virtual networks can also help to improve the performance of your data and analytics workloads by reducing network latency and optimizing network traffic.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_synapse_workspace
* *Arguments:* managed_virtual_network_enabled


[source,go]
----
resource "azurerm_synapse_workspace" "example" {
                            ...
+             managed_virtual_network_enabled      = true                
            }
----

