== AWS SageMaker notebook instance allows for IMDSv1 misconfiguration detected in code

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_371
|Category |AI & Machine Learning - Permissions
|Provider |AWS
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, CloudFormation
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This rule checks whether SageMaker Notebook Instances are configured to use Instance Metadata Service version 2 (IMDSv2). MDSv2 reduces security risks by requiring session-oriented requests, unlike the vulnerable IMDSv1 which is susceptible to server-side request forgery (SSRF) attacks and potential unauthorized access. This improves the overall security posture of your AWS resources.

=== How to Fix

*Terraform*

* *Resource:* aws_sagemaker_notebook_instance
* *Arguments:* instance_metadata_service_configuration/minimum_instance_metadata_service_version

Ensure that the Amazon Sagemaker Notebook Instance is configured to only allow Instance Metadata Service Version 2 (IMDSv2), by setting the `minimum_instance_metadata_service_version` to `2`, as displayed in the example below.

[source,go]
----
resource "aws_sagemaker_notebook_instance" "my_notebook_instance_pass" {
  ...
  instance_metadata_service_configuration {
+    minimum_instance_metadata_service_version = "2"
  }
}
----

*CloudFormation*

* *Resource:* AWS::SageMaker::NotebookInstance
* *Arguments:* Properties/InstanceMetadataServiceConfiguration/MinimumInstanceMetadataServiceVersion

Ensure that the Amazon Sagemaker Notebook Instance is configured to only allow Instance Metadata Service Version 2 (IMDSv2), by setting the `MinimumInstanceMetadataServiceVersion` to `2`, as displayed in the example below.

[source,yaml]
----
Resources:
  Example:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      ...
      InstanceMetadataServiceConfiguration:
        MinimumInstanceMetadataServiceVersion: "2"
----
