
== Azure Cognitive Services account is not configured with managed identity

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 041ba0a8-ee0c-4bc7-91ed-4e244be5e086

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/CognitiveServicesManagedIdentity.py[CKV_AZURE_238]

|Severity
|INFO

|Subtype
|Run,Build

|Frameworks
|Terraform,TerraformPlan,ARM,Bicep

|===

=== Impact
Configuring Azure Cognitive Services accounts with a managed identity enhances security by eliminating the need to store credentials in code or configuration files. It also provides seamless integration with other Azure services and simplifies the management of credentials.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_cognitive_account
* *Arguments:* identity.type

To fix this issue, ensure that your Azure Cognitive Services account is configured with a managed identity in your Terraform configuration.

[source,go]
----
resource "azurerm_cognitive_account" "example" {
  ...
  identity {
+    type = "SystemAssigned"
  }
}
----

*ARM*

* *Resource:* Microsoft.CognitiveServices/accounts
* *Arguments:* identity.type

To fix this issue, ensure that your Azure Cognitive Services account is configured with a managed identity in your ARM configuration.

[source,json]
----
{
    "resources": [
        {
            "type": "Microsoft.CognitiveServices/accounts",
            ...
            "identity": {
+                "type": "SystemAssigned"
            },
        }
    ]
}
----