== Azure Cognitive Services account hosted with OpenAI is not configured with data loss prevention

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 4c4ae367-8609-4b55-ac11-e9d52849658a

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/OpenAICognitiveServicesRestrictOutboundNetwork.py[CKV_AZURE_247]

|Severity
|HIGH

|Subtype
|Run,Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Impact
Azure Cognitive Services accounts hosted with OpenAI lacking data loss prevention settings risk unauthorized data exfiltration. This misconfiguration allows sensitive data processed by the service to be sent to unintended destinations.

OpenAI-hosted Azure Cognitive Services utilize outbound network connections. Without data loss prevention enabled, these connections are unrestricted, creating an opportunity for malicious actors to exploit misconfigured settings and exfiltrate sensitive data. An attacker could potentially leverage this to gain access to confidential information.

The impact of this misconfiguration includes data breaches, regulatory non-compliance, and reputational damage. Implementing data loss prevention is crucial for maintaining data confidentiality and integrity, minimizing the risk of sensitive information leakage.

To mitigate this risk, explicitly configure allowed outbound URLs within the Azure Cognitive Services account's data loss prevention settings. Restrict access only to trusted domains, regularly review and update these settings, and enforce the principle of least privilege to limit potential exposure.

=== Fix - Buildtime

*Terraform*

Ensure that your Azure Cognitive Services has the  `outbound_network_access_restricted` argument set to `true` and has valid `fqdns`.

[source,go]
----
resource "azurerm_cognitive_account" "example" {
  ...
  kind                = "OpenAI"

+  outbound_network_access_restricted = true  # Restricted outbound
+  fqdns = ["openai.example.com"]  # Valid FQDN
}
----

