== Azure Synapse workspace administrator login password exposed

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_239
|Category |AI & Machine Learning - Permissions
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This rule detects whether the administrator login password for an Azure Synapse workspace is exposed, checking for any instances where the password might be publicly accessible or improperly stored. Keeping administrator credentials secure is essential for maintaining the overall security and integrity of the Azure environment. Exposing such sensitive information can lead to unauthorized access, data breaches, and potential misuse of resources.

=== Fix - Buildtime

Inject the administrator login password securely in your configuration instead of hardcoding it to fix the issue where an Azure Synapse Workspace password is exposed.

*Terraform*

* *Resource:* azurerm_synapse_workspace
* *Arguments:* sql_administrator_login_password

This example shows the Terraform configuration for an Azure Synapse workspace with the `sql_administrator_login` and `sql_administrator_login_password` attributes removed to avoid hardcoding sensitive information.


[source,go]
----
resource "azurerm_synapse_workspace" "example" {
  ...

-  sql_administrator_login              = "sqladminuser"
-  sql_administrator_login_password     = "H@Sh1CoR3!"
}
----


*ARM*

* *Resource:* Microsoft.Synapse/workspaces
* *Arguments:* sqlAdministratorLoginPassword

This example shows the ARM template configuration for an Azure Synapse workspace with the `sqlAdministratorLogin` and `sqlAdministratorLoginPassword` properties removed to prevent hardcoding sensitive information.

[source,json]
----
{
  ...
  "resources": [
    {
      "type": "Microsoft.Synapse/workspaces",
      ...
      "properties": {
-        "sqlAdministratorLogin": "sqladminuser",
-        "sqlAdministratorLoginPassword": "H@Sh1CoR3!",
----
