== Intelligence Stream

The Prisma Cloud Intelligence Stream (IS) is a real-time feed that contains vulnerability data and threat intelligence from a variety of certified upstream sources. Prisma Cloud continuously pulls data from known vulnerability databases, official vendor feeds and commercial providers to provide the most accurate vulnerability detection results.

In addition to the information collected from official feeds, Prisma Cloud feeds are enriched with vulnerability data curated by a dedicated research team. Our security researchers monitor cloud and open source projects to identify security issues through automated and manual means. As a result, Prisma Cloud can detect new vulnerabilities that were only recently disclosed, and even vulnerabilities that were quietly patched.

The Prisma CLoud console automatically connects to the intelligence server and downloads updates without any special configuration required. The IS is updated several times per day, and consoles continuously check for updates.

ifdef::compute_edition[]
You can update Console vulnerability and threat data even if it runs in an offline environment.
For more information, see xref:../tools/update-intel-stream-offline.adoc[Update Intelligence Stream in offline environments].
endif::compute_edition[]

When the Prisma Cloud Intelligence Stream is updated, the changes affect all customers, even if their console isn't updated to the latest version. Some updates to the Intelligence Stream might require upgrading the Prisma Cloud Console and Defenders to support these changes. Such details will be provided in the *Intelligence Stream Updates* section of the Prisma Cloud Release Notes.



