== AWS Postgres RDS have Query Logging disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a31de650-cada-4311-97c9-460f7d48e9e7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/graph_checks/aws/PostgresRDSHasQueryLoggingEnabled.yaml[CKV2_AWS_30]

|Severity
|LOW

|Subtype
|Run,Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description

This policy identifies RDS Postgres clusters with query logging disabled.

In AWS RDS PostgreSQL, by default, the logging level captures login failures, fatal server errors, deadlocks, and query failures. To log data changes, we recommend enabling cluster logging for monitoring and troubleshooting. To obtain adequate logs, an RDS cluster should have log_statement and log_min_duration_statement parameters configured.

It is a best practice to enable additional RDS cluster logging, which will help in data change monitoring and troubleshooting.

=== Fix - Buildtime


*Terraform*

To enable query logging, configure the associated `aws_rds_cluster_parameter_group` resource with the appropriate logging parameters.

Example:

[source,go]
----
resource "aws_rds_cluster_parameter_group" "example" {
  name   = "example-aurora-pg-logs"
  family = "aurora-postgresql10"

  parameter {
    name  = "log_statement"
    value = "all"
  }

  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }
}
----
