== AWS DocumentDB logging is not enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0c7e0ca3-8c29-43a8-831b-b561ffb5d996

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/DocDBLogging.py[CKV_AWS_85]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 

This policy ensures that Amazon DocumentDB (DocDB) clusters have logging enabled. Enabling logging helps you monitor and troubleshoot your DocDB clusters by providing visibility into database activity and operations. This policy checks whether the `EnableCloudwatchLogsExports` property includes the required log types (`profiler` and/or `audit`).

=== Fix - Buildtime


*Terraform*

To fix this issue, ensure that the `enabled_cloudwatch_logs_exports` property in the `aws_docdb_cluster` resource includes one or both of the required log types (`profiler` and/or `audit`).

Example:

[source,hcl]
----
resource "aws_docdb_cluster" "example" {
  ...
  enabled_cloudwatch_logs_exports = ["profiler", "audit"]
  ...
}
----


*CloudFormation*

To fix this issue, ensure that the `EnableCloudwatchLogsExports` property in the `AWS::DocDB::DBCluster` resource includes one or both of the required log types (`profiler` and/or `audit`).

Example:

[source,json]
----
{
  "Resources": {
    "MyDocDBCluster": {
      "Type": "AWS::DocDB::DBCluster",
      "Properties": {
        "DBClusterIdentifier": "example-cluster",
        "EnableCloudwatchLogsExports": ["profiler", "audit"],
        ...
      }
    }
  }
}
----

[source,yaml]
----
Resources:
  MyDocDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      DBClusterIdentifier: example-cluster
      EnableCloudwatchLogsExports:
        - profiler
        - audit
      ...
----