[.task]
== Ingest SARIF Data

//You can import and consolidate findings from Static Application Security Testing (SAST) vendors that support SARIF output. This enables you to view all your Application Security (AppSec) vulnerabilities on a single platform, whether they are from third-party sources or native tools.


Upload SAST data from third-party tools (for vendors that support SARIF output) to the Prisma Cloud platform using SARIF (Static Analysis Results Interchange Format) to analyze and remediate SAST issues directly within the platform. This feature is particularly useful for vendors that are not directly supported by Prisma Cloud. When SARIF files are uploaded, they are parsed to create CWE weaknesses.  

Supported SARIF versions include 2.0 and 2.1, accepting .zip, .json, and .sarif ile formats.

You can upload SARIF files using either  the Prisma Cloud platform or via an API.

[.procedure]
. Before you begin:
+
* Grant the user ingesting the SARIF data Administrator privileges
* Onboard the repository into the system before SARIF findings for that repository can be uploaded
* Ensure that uploaded findings follow the standard SARIF specification
* Only upload findings relevant to the repository 
* Add the Prisma Cloud IP addresses and hostname for Application Security to an xref:../../../get-started/console-prerequisites.adoc[allow list] to enable access to the Prisma Cloud console

. In Application Security, select *Repositories* > 

