== Third-Party Ingestion

By ingesting static application security testing (SAST) findings from supported third-party tools (in addition to native SCA scanner findings when the Application Security SCA scanner module is activated, Prisma Cloud consolidates and enriches your security vulnerability data within a single management platform, providing a deeper understanding of SAST and SCA violations through contextual enrichment.

Supported third party ingestion includes:

* xref:veracode-ingestion.adoc[Veracode] 
* xref:sarif-ingestion.adoc[SARIF]

NOTE: Only onboarded and scanned repositories can be mapped. It is recommended to use supported third-party vendor integrations for data ingestion over manual SARIF file uploads. Native integrations provide automated synchronization of periodic scan data and increased data precision.

=== Manage ingested data

To view and manage ingested third-party ingested data, refer to xref:../../../risk-management/monitor-and-manage-code-build/third-party-ingest-manage.adoc[Manage Third+Party Ingested Data]. 

