== Alibaba Cloud RAM password policy does not prevent password reuse


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a7faf958-448d-4046-aa2e-8ce36ca3a538

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RAMPasswordPolicyReuse.py[CKV_ALI_18]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 

This policy ensures that RAM (Resource Access Management) password policies prevent password reuse by specifying a value for `password_reuse_prevention`. Restricting password reuse forces users to create unique passwords for each password change, reducing the likelihood of credential compromise through previously used or weak passwords.

Failing to set a password reuse prevention policy can increase the risk of unauthorized access due to predictable or previously compromised passwords being reused.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_ram_account_password_policy
* *Arguments:* password_reuse_prevention

To mitigate this issue, ensure the `password_reuse_prevention` attribute in the `alicloud_ram_account_password_policy` resource is set to a value of 24 or higher.

Example:

[source,go]
----
resource "alicloud_ram_account_password_policy" "example" {
  ...
-  password_reuse_prevention    = 5
+  password_reuse_prevention    = 24
}
----
