== AWS RDS database instance is publicly accessible


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_17
|Category |Public Exposure - Database Endpoints
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |b3897fb4-5241-403b-8770-69f90cea0f11
|===


=== Impact
Ensure that all your public AWS Application Load Balancer are integrated with the Web Application Firewall (AWS WAF) service to protect against application-layer attacks.
An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.
After the load balancer receives a request, it evaluates the listener rules in priority order to determine which rule to apply, and then selects a target from the target group for the rule action.
You can configure listener rules to route requests to different target groups based on the content of the application traffic.
Routing is performed independently for each target group, even when a target is registered with multiple target groups.


=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_db_instance
* *Arguments:* publicly_accessible


[source,go]
----
resource "aws_db_instance" "default" {
  ...
+ publicly_accessible   = false
}
----


*CloudFormation* 


* *Resource:* AWS::RDS::DBInstance
* *Arguments:* Properties.PubliclyAccessible


[source,yaml]
----
Type: 'AWS::RDS::DBInstance'
    Properties:
      ...
+     PubliclyAccessible: false
----
