== Kubernetes dashboard is not disabled misconfiguration detected in code
// Kubernetes dashboard enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_8
|Category - Subcategory |Public Exposure - Admin Interface
|Provider |Azure
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
The Terraform provider for Azure provides the capability to disable the Kubernetes dashboard on an AKS cluster.
This is achieved by providing the Kubernetes dashboard as an AKS add-on like the Azure Monitor for containers integration, AKS virtual nodes, or HTTP application routing.
The dashboard add-on is disabled by default for all new clusters created on Kubernetes 1.18 or greater.
In mid-2019 Tesla was hacked and their Kubernetes dashboard was open to the internet.
Hackers browsed around and found credentials, eventually managing to deploy pods running bitcoin mining software.
We recommend you disable the Kubernetes dashboard to prevent the need to manage its individual access interface, eliminating it as an attack vector.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_kubernetes_cluster
* *Arguments:* kube_dashboard (required): Is the Kubernetes Dashboard enabled?


[source,go]
----
{
 "...
  addon_profile {
    kube_dashboard {
      enabled = false
    }

  }
...",
}
----


*ARM Templates* 


* *Resource:* Microsoft.ContainerService/managedClusters
* *Arguments:* kubeDashboard


[source,go]
----
{
 "...
        "addonProfiles": {
          "kubeDashboard": {
            "enabled": false
          }

        },
...",
 
}
----
