== Azure Data Factory (V2) configured with overly permissive network access misconfiguration detected in code
// Azure Data Factory (V2) configured with excessive permissive network access


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_104
|Category - Subcategory |Public Exposure - Ingress Controls
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |c181a29b-b48e-4fd1-ab10-80bd7f930093
|===
 



=== Impact
By ensuring that your Azure Data factory is not public, you can help protect your data from unauthorized access or tampering.
Public Azure Data factory instances are accessible over the internet, which can make them vulnerable to external threats such as hackers or malware.
By making it private, you can help ensure that only authorized users can access the data.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_data_factory
* *Arguments:* public_network_enabled


[source,go]
----
resource "azurerm_data_factory" "example" {
              ...
+             public_network_enabled = false
            }
----

