== GCP Container Registry repositories are anonymously or publicly accessible misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_9
|Category |Public Exposure - Storage Buckets
|Provider |GCP
|Severity |HIGH
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===
 

GCP Container Registry repositories are anonymously or publicly accessible
*GCP Container Registry repositories are anonymously or publicly accessible* 

_Google Container Registry (GCR)_ is a GCP service that contains repositories for your container images.
A GCR repo is publicly accessible if the host location's underlying storage bucket is publicly accessible because GCR images are stored in GCS.
Public GCR repositories can put your data at risk of exposure and should be adjusted to a more secure configuration (private).
We recommend you ensure that neither anonymous or public access to *GCR Repositories* is allowed.


=== How to Fix


*Terraform* 


* *Resource:* google_storage_bucket_iam_binding
* *Field:* members
* *Resource:* google_storage_bucket_iam_member
* *Field:* member
Google Container Registry (GCR) does not have IAM-specific resources in Terraform.
Instead, GCR IAM is handled via GCS IAM resources as seen in the below examples.


[source,go]
----
resource "google_storage_bucket_iam_binding" "gcr_public_binding" {
  bucket = google_storage_bucket.default.name
  role = "roles/storage.viewer"

  members = [
-    "allUsers",
-    "allAuthenticatedUsers",
  ]
}
----


[source,go]
----
resource "google_artifact_registry_repository_iam_member" "public_member" {
  provider = google-beta
  location = google_artifact_registry_repository.my-repo.location
  repository = google_artifact_registry_repository.my-repo.name
  role = "roles/artifactregistry.writer"

-  member = "allUsers"
-  member = "allAuthenticatedUsers"
}
----


[source,go]
----
resource "google_storage_bucket_iam_member" "gcr_public_member" {
  bucket = google_storage_bucket.default.name
  role = "roles/storage.viewer"

-  member = "allUsers"
-  member = "allAuthenticatedUsers"
}
----
