== AWS Elasticsearch does not have node-to-node encryption enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| f978f4db-d9b9-41df-bf4f-d8ce52019a9c

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/cloudformation/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py[CKV_AWS_6]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation, Terraform, TerraformPlan, Serverless

|=== 



=== Impact
The AWS Elasticsearch Service allows you to host sensitive workloads with node-to-node encryption using Transport Layer Security (TLS) for all communications between instances in a cluster.
Node-to-node encryption ensures that any data sent to the Amazon Elasticsearch Service domain over HTTPS remains encrypted in-flight while it is being distributed and replicated between the nodes.

=== Fix - Buildtime

*Terraform*

To fix this issue, ensure that the `node_to_node_encryption` block in the `aws_elasticsearch_domain` or `aws_opensearch_domain` resource is configured with `enabled` set to `true`.

Example:

[source,go]
----
resource "aws_elasticsearch_domain" "example" {
  ...
  node_to_node_encryption {
    enabled = true
  }
}
----


*CloudFormation* 


* *Resource:* AWS::Elasticsearch::Domain 
* *Argument:* Properties.NodeToNodeEncryptionOptions.Enabled


[source,yaml]
----
{
 "Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ...
      NodeToNodeEncryptionOptions:
+       Enabled: True",
}
----
