
== TPU v2 VM is public misconfiguration detected in code

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_32
|Category |Public Exposure - APIs
|Provider |GCP
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This rule is checking to ensure that Tensor Processing Units (TPU) virtual machines are set to private in a Google Cloud Platform (GCP) environment. TPUs are Google's custom-developed application-specific integrated circuits (ASICs) used to accelerate machine learning workloads. 

Keeping TPU VMs set to private is necessary as it makes sure the TPU resources are not exposed to the public internet, thereby reducing the risk of unauthorized access. If a TPU is not private, it can be exposed to potential cyber threats including data breaches, hacking, and data corruption. Hence, the non-compliance with this policy can lead to potential security vulnerabilities.

=== How to Fix

*Terraform*

* *Resource:* google_tpu_v2_vm
* *Arguments:* network_config.enable_external_ips

To fix this issue, set the "enable_external_ips" attribute to "false" in your resource configuration.

[source,go]
----
resource "google_tpu_v2_vm" "tpu_good" {
  ...
  network_config {
    ...
    enable_external_ips = false
  }
}
----

