== Azure Key Vault Public Network Access Control misconfiguration detected in code
// Ensure that Azure Key Vault disables public network access.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_189
|Category |Public Exposure - Encryption and Protocols
|Provider |Azure
|Severity |HIGH
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===
 

*Description*

Azure Key Vault is a cloud service for securely storing and accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, or certificates. A vault is a logical group of secrets. It's crucial to restrict public network access to such vaults to mitigate potential security threats. This policy ensures that the public network access to Azure Key Vault is disabled.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_key_vault 

*Arguments:* 
- public_network_access_enabled
- network_acls

[source,terraform]
----
resource "azurerm_key_vault" "example" {
  name                = "example-kv"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # ... other configurations ...

+ public_network_access_enabled = false

  network_acls {
    #... configurations...
+   ip_rules = ["<valid_ip_range>"]
  }
}
----
