== Azure cache for Redis has public network access enabled misconfiguration detected in code
// Azure Cache for Redis public network access enabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_89
|Category |Public Exposure - Database Endpoints
|Provider |Azure
|Severity |LOW
|Framework |ARM, Bicep, Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
By ensuring that your Azure cache for Redis is not public, you can help protect your data from unauthorized access or tampering.
Public cache for Redis are accessible over the internet, which can make them vulnerable to external threats such as hackers or malware.
By making it private, you can help ensure that only authorized users can access the data.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_redis_cache
* *Arguments:* public_network_access_enabled


[source,go]
----
resource "azurerm_redis_cache" "example" {
                      ...
+                     public_network_access_enabled  = false
                                            ...
                }
                    }
----

