== MariaDB servers do not have public network access enabled set to False
// Azure MariaDB servers public network access enabled  


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_48
|Category |PUBLIC_EXPOSURE - DATABASE_ENDPOINTS
|Provider |AZURE
|Severity |HIGH
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


It is generally a good security practice to ensure that your MariaDB servers do not have public network access enabled, as this means that they are only accessible from within your private network.
This can help to protect your database servers from unauthorized access, as external parties will not be able to connect to them over the internet.
It is especially important to ensure that public network access is disabled if your MariaDB servers contain sensitive or confidential data.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_mariadb_server
* *Arguments:* public_network_access_enabled is set to False.


[source,go]
----
resource "azurerm_mariadb_server" "example" {
   ...
+  public_network_access_enabled = false

}
----

