== AWS Elasticsearch domain is not configured with HTTPS


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_83
|Category |Public Exposure - Encryption and Protocols
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |10a1868c-c97b-4fd1-8dd3-dc2ac172f2f1
|===


=== Description

This policy identifies Elasticsearch domains that are not configured with HTTPS. Amazon Elasticsearch domains allow all traffic to be submitted over HTTPS, ensuring all communications between application and domain are encrypted. It is recommended to enable HTTPS so that all communication between the application and all data access goes across an encrypted communication channel to eliminate man-in-the-middle attacks.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_elasticsearch_domain, aws_opensearch_domain
* *Arguments:* domain_endpoint_options

To fix this issue, you should ensure that your Elasticsearch or OpenSearch domain enforces HTTPS by setting the `enforce_https` option to `true` in the `domain_endpoint_options` block as shown below:

[source,go]
----
resource "aws_elasticsearch_domain" "example" {
  domain_name = "example-domain"

  domain_endpoint_options {
+    enforce_https = true
  }
}
----


*CloudFormation* 


* *Resource:* AWS::Elasticsearch::Domain
* *Argument:* Properties.DomainEndpointOptions.EnforceHTTPS


[source,yaml]
----
Resources:
  Resource0:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
        ...
      DomainEndpointOptions:
+       EnforceHTTPS: True
----
