== API Management with Public Access misconfiguration detected in code
// Ensure API management public access is disabled

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_174
|Category |Public Exposure - APIs
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure API Management provides capabilities to secure your service and data. One of the first lines of defense is limiting access to the service by making it private. Allowing public access can potentially expose the service and its data to unnecessary risks. This rule ensures that public network access is disabled for Azure API Management.

=== How to Fix

*Terraform*

* *Resource:* azurerm_api_management
* *Arguments:* public_network_access_enabled

[source,terraform]
----
resource "azurerm_api_management" "example" {
  name                = "example-api"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

+ public_network_access_enabled = false

  tags = {
    Environment = "production"
  }
}
----
