== AWS EC2 instances with public IP and associated with security groups have Internet access


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_88
|Category |Public Exposure - VPC/VCN/VNET
|Provider |AWS
|Severity |HIGH
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless, Ansible
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
A public IP address is an IPv4 address that is reachable from the Internet.
You can use public addresses for communication between your instances and the Internet.
Each instance that receives a public IP address is also given an external DNS hostname.
We recommend you control whether your instance receives a public IP address as required.

=== How to Fix


*Terraform* 


* *Resource:* aws_instance
* *Arguments:* associate_public_ip_address - (Optional) Associate a public ip address with an instance in a VPC.

Boolean value.


[source,go]
----
resource "aws_instance" "bar" {
  ...
- associate_public_ip_address = true
}
----


*CloudFormation* 


* *Resource:* AWS::EC2::Instance / AWS::EC2::LaunchTemplate
* *Arguments:* NetworkInterfaces.AssociatePublicIpAddress - (Optional) Associate a public ip address with an instance in a VPC.
Boolean value.


[source,yaml]
----
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ...
      NetworkInterfaces: 
        - ...
-                   AssociatePublicIpAddress: true

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ...
        NetworkInterfaces: 
          - ...
-           AssociatePublicIpAddress: true
----

*Ansible*

[source,yaml]
----
- name: Launch an EC2 instance without a public IP
  amazon.aws.ec2_instance:
    name: my_secure_ec2
    image_id: ami-123456
    instance_type: t2.micro
    network:
-      assign_public_ip: true
+      assign_public_ip: false
----
In this example, `assign_public_ip` is changed from `true` to `false`, removing the public IP address and DNS resolution.

