== Alibaba Cloud API Gateway API Protocol does not use HTTPS


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a2b6fc74-b931-4679-a6ca-f6ccced850c6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/APIGatewayProtocolHTTPS.py[CKV_ALI_21]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that Alibaba Cloud API Gateway APIs are configured to only accept HTTPS traffic. HTTPS ensures that communications between the clients and the API Gateway are securely encrypted, protecting against potential eavesdropping and man-in-the-middle attacks.

Failing to enforce HTTPS can result in sensitive data being transmitted over unsecure connections, making it vulnerable to interception and tampering.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_api_gateway_api
* *Attribute:* request_config.protocol

To mitigate this issue, ensure that the `protocol` attribute in the `request_config` block of the `alicloud_api_gateway_api` resource is set to `HTTPS`.

Example:

[source,go]
----
resource "alicloud_api_gateway_api" "example" {
  ...

  request_config {
    ...
+   protocol = "HTTPS"
  }
}
----
