== VNET Using External DNS Addresses misconfiguration detected in code
// Ensure that VNET uses local DNS addresses

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_183
|Category |Public Exposure - VPC/VCN/VNET
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Virtual Networks (VNETs) play a critical role in routing network traffic and facilitating domain name resolution via DNS servers. However, relying on external DNS servers for local communications, especially those deployed on-premises, can introduce unnecessary complexity, potential security risks, and additional latency. 

To avoid taking a dependency on external DNS servers, it is advisable to use local DNS addresses within the VNET's address range. This can be achieved by deploying Azure Private DNS Zones, a platform-as-a-service (PaaS) DNS service designed for VNETs.

This rule ensures that any DNS server addresses specified for a VNET are within the VNET's address space, thereby promoting the use of local DNS addresses.

=== How to Fix

*Terraform*

*Resource:* 
- azurerm_virtual_network

*Arguments:* 
- dns_servers
- address_space

[source,terraform]
----
resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  address_space       = ["10.0.0.0/16"]
  
  # ... other configurations ...

+ dns_servers = ["10.0.0.5"]  // Ensure DNS servers are within the VNET's address space
}
----
