== Azure App Service web apps with public network access
// Ensure that Azure Web App public network access is disabled.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_222
|Category |Public Exposure - APIs
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |6db58a3a-760a-4cf6-bb3e-b807f6e41bfc
|===


=== Description

Azure Web Apps are a fully managed platform for building, deploying, and scaling web apps. They can be configured to allow public access over the internet or restricted access through Virtual Networks and VPNs. This policy checks whether public network access to Azure Web Apps is disabled.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_linux_web_app 
- azurerm_windows_web_app

*Arguments:* 
- public_network_access_enabled

[source,terraform]
----
resource "azurerm_linux_web_app" "example" {
  name                = "example-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # ... other configurations ...

+ public_network_access_enabled = false
}

resource "azurerm_windows_web_app" "example" {
  name                = "example-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # ... other configurations ...

+ public_network_access_enabled = false
}
----
