== Azure storage account has a blob container with public access misconfiguration detected in code
// Ensure that Storage blobs restrict public access.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_190
|Category |Public Exposure - Storage Buckets
|Provider |Azure
|Severity |HIGH
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |c085d057-d5a4-4118-afdf-f653e6b47995
|===
 

*Description*

Azure Storage Blobs are used for storing vast amounts of unstructured object data, such as text or binary data. Restricting public access to these blobs is crucial to ensure data confidentiality and to prevent unauthorized access. This policy ensures that the public access to Azure Storage Blobs is restricted.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_storage_account 

*Arguments:* 
- allow_nested_items_to_be_public

[source,terraform]
----
resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  # ... other configurations ...

+ allow_nested_items_to_be_public = false

  # ... other configurations ...
}
----
