== Azure PostgreSQL database server with log connections parameter disabled
// Azure PostgreSQL Database Server 'log connections' parameter disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_31
|Category |Public Exposure - Database Endpoints
|Provider |Azure
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |0222b3d5-49a2-49af-9073-847f9a55c289
|===


=== Impact
Enabling *log_connections* allows a PostgreSQL Database to log attempted connections to the server in addition to logging the successful completion of client authentication.
Log data can be used to identify, troubleshoot, repair configuration errors, and identify sub-optimal performance issues.
We recommend you set *log_connections* to *On* for PostgreSQL Server Databases.
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_postgresql_configuration
* *Arguments:* name + value


[source,go]
----
- resource "azurerm_postgresql_configuration" "example" {
-    name                = "log_connections"
-    resource_group_name = data.azurerm_resource_group.example.name
-    server_name         = azurerm_postgresql_server.example.name
-    value               = "off"
}
----
