== Alibaba Cloud RDS instance does not use SSL misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_ALI_20
|Category - Subcategory |Public Exposure - Database Endpoints
|Provider |Alibaba Cloud
|Severity |LOW
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===




=== Impact
This rule ensures that RDS instances in Alibaba Cloud use SSL to protect data in transit. Using SSL for database connections helps to encrypt data and prevent unauthorized interception or tampering of data.

Failing to enable SSL for RDS instances can result in sensitive data being transmitted in plaintext, making it vulnerable to interception and attacks.

=== How to Fix


*Terraform* 

* *Resource:* alicloud_db_instance
* *Attribute:* ssl_action

To mitigate this issue, ensure that the `ssl_action` attribute in the `alicloud_db_instance` resource is set to "Open" or "Update".

Example:

[source,go]
----
resource "alicloud_db_instance" "example" {
  ...
+  ssl_action = "Open"
}
----
