== Azure MariaDB database server with SSL connection disabled misconfiguration detected in code
// Azure MariaDB Database Server SSL connection disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_47
|Category |Public Exposure - Encryption and Protocols
|Provider |Azure
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |221dd55b-2020-4d55-a8d2-b51a74efaa56
|===
 



=== Impact
Azure Database for MariaDB supports connecting your Azure Database for MariaDB server to client applications using Secure Sockets Layer (SSL).
Enforcing SSL connections between your database server and your client applications helps protect against 'man in the middle' attacks by encrypting the data stream between the server and your application.
This configuration enforces that SSL is always enabled for accessing your database server.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_mariadb_server
* *Arguments:* ssl_enforcement_enabled


[source,go]
----
resource "azurerm_mariadb_server" "example" {
  ...
+  ssl_enforcement_enabled = true
}
----

