== Azure Service Bus with Public Network Access Enabled misconfiguration detected in code
// Ensure 'public network access enabled' is set to 'False' for Azure Service Bus.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_204
|Category - Subcategory |Public Exposure - APIs
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


*Description*

Azure Service Bus provides robust messaging services on Azure with capabilities such as message routing, temporal decoupling, publish/subscribe, and more. One key configuration for ensuring the security of Azure Service Bus instances is the restriction of public network access. 

When public network access is enabled, the Azure Service Bus can be accessed from the internet, which could lead to potential security risks. Therefore, it's a best practice to disable public network access, and restrict access to a private network or through a VPN.

This rule checks and ensures that the 'public network access enabled' is set to 'False' for Azure Service Bus, thus enhancing its security posture.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- public_network_access_enabled

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ public_network_access_enabled = false

  # ... other configurations ...
}
----
