== Azure Front Door does not have the Azure Web application firewall (WAF) enabled
// Azure Web Application Firewall (WAF) disabled for Azure Front Door


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_121
|Category |PUBLIC_EXPOSURE - INGRESS_CONTROLS
|Provider |AZURE
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |79734546-c8e7-45f3-a350-f14ad01fdda6
|===


=== Description 


WAF is a security feature that provides protection for web applications by inspecting incoming traffic and blocking malicious requests before they reach the application.
When WAF is enabled on an Azure Front Door, it analyzes incoming traffic to the front door and blocks requests that are determined to be malicious based on a set of rules.
This can help to protect your application from a variety of threats, such as SQL injection attacks, cross-site scripting (XSS) attacks, and other types of attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_frontdoor
* *Arguments:* web_application_firewall_policy_link_id


[source,go]
----
resource "azurerm_frontdoor" "example" {
              ...
+             web_application_firewall_policy_link_id = "this_is_id"
              ...
            }
----

