== Alibaba Cloud MongoDB is not deployed inside a VPC


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8f96497a-ecbd-4ee2-a77b-4495a21d521e

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/MongoDBInsideVPC.py[CKV_ALI_41]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Impact
This policy ensures that MongoDB instances in Alibaba Cloud are deployed inside a VPC (Virtual Private Cloud). Deploying MongoDB inside a VPC provides network isolation and enhanced security, ensuring that the database is accessible only to resources within the same VPC and not exposed to the public internet.

Failing to deploy MongoDB inside a VPC can result in exposure to public internet traffic, increasing the risk of unauthorized access and potential data breaches.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_mongodb_instance
* *Attribute:* network_type

To mitigate this issue, ensure that the `network_type` attribute in the `alicloud_mongodb_instance` resource is set to `VPC`.

Example:

[source,go]
----
resource "alicloud_mongodb_instance" "example" {
  ...
+  network_type = "VPC"
}
----
