== GCP GCR Container Vulnerability Scanning is disabled


=== Rule Details

[width=45%]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_11
|Category |PUBLIC_EXPOSURE-ENCRYPTION_AND_PROTOCOLS
|Provider |GCP
|Severity |LOW
|Framework |Terraform
|Mapped CSPM/KSPM Rule |71151e4f-b104-43c7-84e1-008d0811d61d
|===


=== Description 


This policy identifies GCP accounts where GCR Container Vulnerability Scanning is not enabled.
GCR Container Analysis and other third party products allow images stored in GCR to be scanned for known vulnerabilities.
Vulnerabilities in software packages can be exploited by hackers or malicious users to obtain unauthorized access to local cloud resources.
It is recommended to enable vulnerability scanning for images stored in Google Container Registry.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
{
 "resource "google_project_services" "pass_1" {
  project = "your-project-id"
  services   = ["iam.googleapis.com", "cloudresourcemanager.googleapis.com", "containerscanning.googleapis.com"]
}

",
}
----

