== AWS Elastic Load Balancer v2 (ELBv2) listener that allow connection requests over HTTP


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 81c50f65-faa1-4d66-b8e2-d26eaeb08447

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py[CKV_AWS_2]

|Severity
|MEDIUM

|Subtype
|Build, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Impact
This policy identifies Elastic Load Balancers v2 (ELBv2) listener that are configured to accept connection requests over HTTP instead of HTTPS. As a best practice, use the HTTPS protocol to encrypt the communication between the application clients and the application load balancer.

=== Fix - Buildtime

*Terraform*

To fix this issue, ensure that the `protocol` property in the `aws_lb_listener` or `aws_alb_listener` resource is set to "HTTPS", "TLS", "TCP", "UDP", "TCP_UDP", or if using `HTTP`, redirect it to `HTTPS`.

Example:

[source,hcl]
----
resource "aws_lb_listener" "example_https" {
  ...
  protocol          = "HTTPS"
}
----

[source,hcl]
----
resource "aws_lb_listener" "example_http" {
  ...
  protocol          = "HTTP"

  default_action {
    type = "redirect"

    redirect {
      ...
      protocol = "HTTPS"
    }
  }
}
----


*CloudFormation* 


* *Resource:* AWS::ElasticLoadBalancingV2::Listener
* *Arguments:* Properties.Protocol / Properties.DefaultActions


[source,yaml]
----
Resources:
    ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      ...
      # Option 1:
+     Protocol: HTTPS # Or TCP / TLS / UDP / TCP_UDP
      # Option 2:
+     DefaultActions:
+       - Type: redirect
+         RedirectConfig:
+           Protocol: HTTPS
            ...
----
