== public network access enabled' is not set to 'False' for mySQL servers
// mySQL servers enable public network access 


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_53
|Category |PUBLIC_EXPOSURE-DATABASE_ENDPOINTS
|Provider |AZURE
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


By disabling public network access and only allowing connections from trusted IP addresses or networks, you can help to mitigate these risks and ensure that only authorized users and systems are able to connect to the MySQL server.
This can help to protect the server and its data from unauthorized access or attacks, and can help to maintain the confidentiality, integrity, and availability of the server and its resources.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_mysql_server
* *Arguments:* public_network_access_enabled


[source,go]
----
resource "azurerm_mysql_server" "examplea" {
  ...
+ public_network_access_enabled = false
}
----
