== AWS Neptune cluster deletion protection is disabled
                
=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_AWS_58
|Category |PUBLIC_EXPOSURE - DATABASE_ENDPOINTS
|Provider |AWS
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |a07cf01a-a77c-4947-ac7f-498e8254b707
|===


=== Description

This policy ensures that AWS Neptune clusters have deletion protection enabled. Deletion Protection safeguards against accidental deletion of AWS resources, allowing for greater data protection and security.

=== Fix - Buildtime

*Terraform*

* *Resource:* aws_neptune_cluster
* *Arguments:* deletion_protection

To fix this issue, you need to set the 'deletion_protection' parameter to 'true' in the AWS Neptune cluster settings.

Secure code example:

[source,go]
----
resource "aws_neptune_cluster" "example" {
  cluster_identifier      = "example"
+ deletion_protection     = true
}
----

The above code is secure as it has deletion protection enabled, which prevents accidental removal of AWS resources. 

