== Azure Service Bus Without Latest TLS Encryption misconfiguration detected in code
// Ensure Azure Service Bus is using the latest version of TLS encryption.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_205
|Category |Public Exposure - APIs
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===
 

*Description*

Azure Service Bus is a comprehensive messaging service in Azure that offers message routing, temporal decoupling, publish/subscribe mechanisms, and more. Ensuring the security of data in transit is paramount. Using the latest version of the TLS protocol can protect data from a range of vulnerabilities in earlier versions of TLS and ensures the confidentiality and integrity of data in transit.

This policy checks if the Azure Service Bus is using the latest version of TLS encryption, specifically TLS 1.2, which provides strong data encryption and is considered the current standard for secure connections.

By enforcing the use of TLS 1.2, organizations can safeguard their Azure Service Bus instances against potential vulnerabilities associated with earlier TLS versions.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- minimum_tls_version

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ minimum_tls_version = "1.2"

  # ... other configurations ...
}
----
