== Azure MySQL Database Server SSL connection is disabled
// Azure MySQL Database Server SSL connection disabled


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_28
|Category |Public Exposure - Encryption and Protocols
|Provider |Azure
|Severity |LOW
|Framework |ARM, Terraform, Bicep, Terraform Plan
|Mapped CSPM/KSPM Rule |cf375c15-dee3-46a7-8b2e-def63bf0a473
|===


=== Impact
SSL connectivity provides a new layer of security by connecting a database server to client applications using Secure Sockets Layer (SSL).
Enforcing SSL connections between a database server and client applications helps protect against _man-in-the-middle_ attacks.
This is achieved by encrypting the data stream between the server and application.
We recommend you set *Enforce SSL connection* to *Enable* on MYSQL Server databases.
=== How to Fix


*Terraform* 


* *Resource:* azurerm_mysql_server
* *Arguments:* ssl_enforcement_enabled


[source,go]
----
resource "azurerm_mysql_server" "example" {
    ...
 +  ssl_enforcement_enabled             = true
}
----

