== GCP Cloud KMS Key Rings are anonymously or publicly accessible misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_8
|Category |Public Exposure - Encryption and Protocols
|Provider |GCP
|Severity |HIGH
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC2_GCP_8
|Category |Public Exposure - Encryption and Protocols
|Provider |GCP
|Severity |HIGH
|Framework |Terraform
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
GCP Cloud KMS key rings contain your encryption keys, and allowing anonymous or public access to a key ring grants permissions for anyone to access the cryptokeys stored inside the ring.
CryptoKeys should only be accessed by trusted parties because they are commonly used to protect sensitive data.
We recommend you ensure anonymous and public access to KMS key rings is not allowed.

=== How to Fix


*Terraform* 


* *Resource:* google_kms_key_ring_iam_member
* *Field:* member 
* *Resource:* google_kms_key_ring_iam_binding
* *Field:* members


[source,text]
----
{
 "
 //Option 1
resource "google_kms_key_ring_iam_member" "member" {
  key_ring_id = google_kms_key_ring.default.id
  role          = "roles/cloudkms.cryptoKeyEncrypter"
-  member        = "allUsers"
-  member        = "allAuthenticatedUsers"
}


//Option 2
resource "google_kms_key_ring_iam_binding" "binding" {
  key_ring_id = google_kms_key_ring.default.id
  role          = "roles/cloudkms.cryptoKeyEncrypter"
  members = [
-    "allUsers",
-    "allAuthenticatedUsers"
  ]
}

",
}
----

