== GCP VM instance with Shielded VM features disabled misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_GCP_39
|Category |Public Exposure - VPC/VCN/VNET
|Provider |GCP
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |6a132d82-267f-40ed-a6c9-1b426df1e928
|===


=== Impact
Shielded VMs are virtual machines (VMs) on a Google Cloud Platform hardened by a set of security controls that help defend against rootkits and bootkits.
Shielded VM offers verifiable integrity on your Compute Engine VM instances, so you can be confident your instances have not been compromised by boot- or kernel-level malware or rootkits.
The verifiable integrity of a Shielded VM is achieved through the use of Secure Boot and integrity monitoring, see below for further details.
We recommend you launch Compute instances with Shielded VM enabled to defend against advanced threats, and ensure that the boot loader and firmware on your VMs are signed and untampered.
Shielded VM instances run firmware signed and verified using Google's Certificate Authority, ensuring the instance's firmware is unmodified and the root of trust for Secure Boot is established.
*Secure Boot* is a virtual trusted platform module (vTPM)-enabled Measured Boot.
It helps ensure that the system only runs authentic software by verifying the digital signature of all boot components and halting the boot process if signature verification fails.
*Integrity monitoring* helps you understand and make decisions about the state of your VM instances.
The Shielded VM vTPM enables Measured Boot by performing the measurements needed to create the integrity policy baseline used for comparison with measurements from subsequent VM boots to determine any changes.

=== How to Fix


*Terraform* 


* *Resource:* google_compute_instance
* *Arguments:* enable_integrity_monitoring - set to true by default, should not be overriden, i.e should not be set to false.
enable_vtpm - set to true by default, should not be overriden, i.e should not be set to false.


[source,go]
----
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"
  boot_disk {}
+    shielded_instance_config {
-        enable_integrity_monitoring = false
-        enable_vtpm                 = false
        }
}
----

