== Azure file sync enables public network access misconfiguration detected in code
// Azure File Sync enables public network access


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_64
|Category |Public Exposure - Storage Buckets
|Provider |Azure
|Severity |LOW
|Framework |Terraform, Terraform Plan, ARM, Bicep
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
By ensuring that your Azure file sync is not public, you can help protect your data from unauthorized access or tampering.
Public Azure file sync are accessible over the internet, which can make them vulnerable to external threats such as hackers or malware.
By making it private, you can help ensure that only authorized users can access the data.

=== How to Fix


*Terraform* 


* *Resource:* azurerm_storage_sync
* *Arguments:* incoming_traffic_policy


[source,go]
----
resource "azurerm_storage_sync" "test" {
                            ...
+             incoming_traffic_policy = AllowVirtualNetworksOnly
            }
----

