== Azure application gateway does not have WAF enabled
// Web Application Firewall (WAF) for Azure Application Gateway disabled


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_120
|Category |PUBLIC_EXPOSURE-INGRESS_CONTROLS
|Provider |AZURE
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


WAF is a security feature that provides protection for web applications by inspecting incoming traffic and blocking malicious requests before they reach the application.
When WAF is enabled on an Azure application gateway, it analyzes incoming traffic to the gateway and blocks requests that are determined to be malicious based on a set of rules.
This can help to protect your application from a variety of threats, such as SQL injection attacks, cross-site scripting (XSS) attacks, and other types of attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_application_gateway
* *Arguments:* waf_configuration.enabled


[source,go]
----
resource "azurerm_application_gateway" "network" {
              ...
+             waf_configuration {
+               enabled = true
              }
            }
----

