== AWS Elasticsearch does not have node-to-node encryption enabled misconfiguration detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AWS_6
|Category - Subcategory |Public Exposure - Encryption and Protocols
|Provider |AWS
|Severity |MEDIUM
|Framework |CloudFormation, Terraform, Terraform Plan, Serverless
|Mapped CSPM/KSPM Rule |None
|===
 



=== Impact
The AWS Elasticsearch Service allows you to host sensitive workloads with node-to-node encryption using Transport Layer Security (TLS) for all communications between instances in a cluster.
Node-to-node encryption ensures that any data sent to the Amazon Elasticsearch Service domain over HTTPS remains encrypted in-flight while it is being distributed and replicated between the nodes.

=== How to Fix

*Terraform*

To fix this issue, ensure that the `node_to_node_encryption` block in the `aws_elasticsearch_domain` or `aws_opensearch_domain` resource is configured with `enabled` set to `true`.

Example:

[source,go]
----
resource "aws_elasticsearch_domain" "example" {
  ...
  node_to_node_encryption {
    enabled = true
  }
}
----


*CloudFormation* 


* *Resource:* AWS::Elasticsearch::Domain 
* *Argument:* Properties.NodeToNodeEncryptionOptions.Enabled


[source,yaml]
----
{
 "Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ...
      NodeToNodeEncryptionOptions:
+       Enabled: True",
}
----
