== Azure container container group is not deployed into a virtual network
// Azure Container group not deployed into a virtual network


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_98
|Category |PUBLIC_EXPOSURE-VPC_VCN_VNET
|Provider |AZURE
|Severity |LOW
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


A virtual network is a logical network in Azure that is isolated from other networks.
When you deploy a container group into a virtual network, you can control the inbound and outbound network traffic to and from your container group using network security groups (NSGs) and service endpoints.
This can help to improve the security of your container group and protect it from unauthorized access or attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_container_group
* *Arguments:* network_profile_id


[source,go]
----
resource "azurerm_container_group" "example" {
              ...
              
  +           network_profile_id = "network_profile_id"    
            }
----

