== Azure Container Instance is not configured with virtual network

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| d480c1d2-06b3-4e53-81c9-a21ed83cb5fc

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureContainerInstancePublicIPAddressType.py[CKV_AZURE_245]

|Severity
|LOW

|Subtype
|Run,Build

|Frameworks
|Terraform,Terraform Plan

|===

=== Impact
This policy detects whether Azure Container Instances (ACI) are configured with a virtual network. When ACIs are not deployed within a virtual network, they become publicly accessible, creating a security risk as they are directly exposed to the internet. To mitigate this risk, it is strongly recommended to configure all your container instances within a virtual network. By doing so, you establish a secure and isolated environment where your containers can communicate securely with other resources within the virtual network, preventing potential unauthorized access.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_container_group
* *Arguments:* ip_address_type

To remediate this issue, set the `ip_address_type`` attribute to Private or None in your Terraform configuration.

Example:

[source,go]
----
resource "azurerm_container_group" "example" {
  ...
-  ip_address_type = "Public"
+  ip_address_type = "Private"
}
----
