
== Global schemes use 'httpa' protocol instead of 'https'

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_OPENAPI_18
|Category |Public Exposure - APIs
|Provider |
|Severity |HIGH
|Framework |OPENAPI
|Mapped CSPM/KSPM Rule |None
|===


=== Impact
This policy is checking to ensure that global schemes in the API are using 'https' protocol instead of 'http'. 'Http' protocol is insecure as it does not encrypt the data being transferred, making it susceptible to interception by malicious third parties. On the other hand, 'https' ensures that the communication between the client and the server is encrypted, hence providing a secure connection. If an API is using 'http', it poses a security threat as confidential data transferred can be easily intercepted and misused. Ensuring that global schemes use 'https' protocol hence provides an important safeguard for sensitive data.

=== Fix - Buildtime

*OpenAPI*

To fix the issue, you need to change the schemes from 'http' to 'https'. You should update the `schemes` field in the OpenAPI document to only include 'https' and remove 'http'. 

[source,yaml]
----
swagger: '2.0'
info:
  version: 1.0.0
  title: Simple API
schemes:
  - https
----
 
The above code is secure because it ensures that all data transmitted between the client and server is encrypted, preventing man-in-the-middle attacks, eavesdropping, and data tampering. This is essential for protecting sensitive information such as usernames, passwords, and API keys.

