== Azure CDN Endpoint Custom domains is not configured with HTTPS misconfiguration detected in code
// Ensure the Azure CDN enables the HTTPS endpoint.

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_AZURE_198
|Category - Subcategory |Public Exposure - APIs
|Provider |Azure
|Severity |MEDIUM
|Framework |Terraform, Terraform Plan
|Mapped CSPM/KSPM Rule |037748a3-155b-4fca-b286-5fa6a4f07dc9
|===


*Description*

Azure Content Delivery Network (CDN) is designed for delivering high-bandwidth content. By caching static assets closer to the end-users, it enhances user experiences. Ensuring that CDN endpoints are secure is paramount for the safety and privacy of user data.

Enabling HTTPS for CDN endpoints ensures that your content is securely transmitted over the network. It guarantees the data's confidentiality and integrity, and it provides authentication.

This rule checks that Azure CDN endpoints have the HTTPS endpoint enabled.


=== How to Fix

*Terraform*

*Resource:* 
- azurerm_cdn_endpoint

*Arguments:* 
- is_https_allowed

[source,terraform]
----
resource "azurerm_cdn_endpoint" "example" {
  name                = "example-cdn-endpoint"
  # ... other configurations ...

+ is_https_allowed = true

  # ... other configurations ...
}
----

