== Features Introduced in May 2025

Learn what's new on Prisma® Cloud in May 2025.

//* <<new-features>>
* <<enhancements>>
//* <<changes-in-existing-behavior>>
* <<api-ingestions>>
//* <<new-policies>>
* <<policy-updates>>
//* <<iam-policy-updates>>
* <<new-compliance-benchmarks-and-updates>>
//* <<rest-api-updates>>
//* <<deprecation-notices>>


//[#new-features]
//=== New Features
//[cols="30%a,70%a"]
//|===
//|*Feature*
//|*Description*
//|===


[#enhancements]
=== Enhancements
[cols="50%a,50%a"]
|===
|*Feature*
|*Description*

|*Ingestion of Azure VNet Flow Logs*

|Prisma Cloud now supports the ingestion of VNet flow logs in addition to the existing ingestion of NSG flow logs, for Microsoft Azure account onboarding. VNet flow logs will also be added as a data source to existing Azure policies. There will be no impact to existing tenants and no additional action is needed.

|*Ingestion of AWS ca-west-1 Resources*

|Prisma Cloud AWS resource discovery is now extended to resources on AWS ca-west-1 (Canada/Calgary). With this added ingestion support, assets in this region are discoverable on the *Asset Inventory* page. No additional action is needed.   

|===

//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior
//[cols="30%a,70%a"]
//|===
//|*Feature*
//|*Description*

//|===



[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*AWS HealthLake*
//RLP-155698

|*aws-healthlake-datastore*

Additional permissions required:

* `healthlake:ListFHIRDatastores`
* `healthlake:DescribeFHIRDatastore`

The Security audit role includes `healthlake:ListFHIRDatastores` permission but does not include `healthlake:DescribeFHIRDatastore` permission.

|*Azure API Management Services*
//RLP-155662

|*azure-api-management-service-named-value*

Additional permissions required:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.ApiManagement/service/namedValues/read`

The Reader role includes the permissions.

|*Azure Healthcare Apis*
//RLP-155671

|*azure-healthcare-apis-workspace-fhir-service*

Additional permissions required:

* `Microsoft.HealthcareApis/workspaces/read 
* `Microsoft.HealthcareApis/workspaces/fhirservices/read`

The Reader role includes the permission.

|*Azure Healthcare Apis*
//RLP-155670

|*azure-healthcare-apis-workspace-dicom-service*

Additional permissions required:

* `Microsoft.HealthcareApis/workspaces/read`
* `Microsoft.HealthcareApis/workspaces/dicomservices/read`

The Reader role includes the permissions.


|*Azure IoT Central*
//RLP-155708

|*azure-iot-central-private-endpoint-connections*

Additional permissions required:

* `Microsoft.IoTCentral/IoTApps/read`
* `Microsoft.IoTCentral/IoTApps/privateEndpointConnections/read`

The Reader role includes the permissions.

|*Azure IoT Hub*
//RLP-155705

|*azure-iot-hub-device-provisioning-service*

Additional permission required:

* `Microsoft.Devices/provisioningServices/Read`

The Reader role includes the permission.

|*Azure IoT Hub*
//RLP-155700

|*azure-devices-iot-hub-private-endpoint-connections*

Additional permissions required:

* `Microsoft.Devices/iotHubs/Read`
* `Microsoft.Devices/iotHubs/PrivateEndpointConnections/Read`

The Reader role includes the permissions.


|*Azure Kusto*
//RLP-155669

|*azure-kusto-database-principal-assignment*

Additional permissions required:

* `Microsoft.Kusto/Clusters/read `
* `Microsoft.Kusto/Clusters/Databases/read`
* `Microsoft.Kusto/Clusters/Databases/PrincipalAssignments/read`

The Reader role includes the permissions.

|*Azure Kusto*
//RLP-155668

|*azure-kusto-cluster-private-link-resource*

Additional permissions required:

* `Microsoft.Kusto/Clusters/read`
* `Microsoft.Kusto/Clusters/PrivateLinkResources/read`

The Reader role includes the permissions.

|*Azure Kusto*
//RLP-155666

|*azure-kusto-cluster-principal-assignment*

Additional permissions required:

* `Microsoft.Kusto/Clusters/read`
* `Microsoft.Kusto/Clusters/PrincipalAssignments/read`

The Reader role includes the permissions.

|*Azure Kusto*
//RLP-155664

|*azure-kusto-cluster-managed-private-endpoint*

Additional permissions required:

* `Microsoft.Kusto/Clusters/read`
* `Microsoft.Kusto/Clusters/ManagedPrivateEndpoints/read`

The Reader role includes the permissions.

|*Azure Recovery Services*
//RLP-155923
|*azure-recovery-service-private-link*

Additional permissions required:

* `Microsoft.RecoveryServices/Vaults/read`
* `Microsoft.RecoveryServices/Vaults/privateLinkResources/read`

The Reader role includes the permissions.

|*Azure Storage*
//RLP-155925
|*azure-storage-account-blob-service-property*

Additional permissions required:

* `Microsoft.Storage/storageAccounts/read`
* `Microsoft.Storage/storageAccounts/blobServices/read`

The Reader role includes the permissions.

|tt:[Update] *Azure Synapse Analytics*
//RLP-155930
|*azure-synapse-workspace*

Additional permission required:

* `Microsoft.Synapse/workspaces/dedicatedSQLminimalTlsSettings/read `

The additional permission above is now required.

|tt:[Update] *Azure Synapse Analytics*
//RLP-155926
|*azure-synapse-workspace-sql-pools*

Additional permission required:

* `Microsoft.Synapse/workspaces/sqlPools/transparentDataEncryption/read`

The additional permission above is now required.

|*Google Resource Manager*
//RLP-131423
|*gcloud-project-tag-key*

Additional permissions required:

* `resourcemanager.tagKeys.list`
* `resourcemanager.tagKeys.getIamPolicy`

The Viewer role includes the permissions.

|*Google Resource Manager*
//RLP-131424
|*gcloud-organization-tag-key*

Additional permissions required:

* `resourcemanager.tagKeys.list`
* `resourcemanager.tagKeys.getIamPolicy`

The Viewer role includes the permissions.

|*Google Cloud TPU*
//RLP-155869
|*gcloud-tpu-node*

Additional permission required:

* `tpu.nodes.list`

The Viewer role includes the permission.


|*OCI IAM*
//RLP-155562
|*oci-iam-password-policy*

Additional permissions required:

* `COMPARTMENT_INSPECT`
* `DOMAIN_INSPECT`
* `PASSWORD_POLICY_INSPECT`

The Reader role includes the permissions.

|===


// [#new-policies]
// === New Policies

// [cols="40%a,60%a"]
// |===
// |*Policies*
// |*Description*

// |===



[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*Cognito service role with wide privileges does not validate authentication*
//RLP-155781

|*Changes—* Policy RQL has been updated with including the condition matching '*' in policy action

*Current RQL–* 
----
config from cloud.resource where api.name = 'aws-iam-list-roles' AND json.rule = role.assumeRolePolicyDocument.Statement[*].Action contains "sts:AssumeRoleWithWebIdentity" and role.assumeRolePolicyDocument.Statement[*].Principal.Federated contains "cognito-identity.amazonaws.com" and role.assumeRolePolicyDocument.Statement[*].Effect contains "Allow" and role.assumeRolePolicyDocument.Statement[*].Condition contains "cognito-identity.amazonaws.com:amr" and role.assumeRolePolicyDocument.Statement[*].Condition contains "unauthenticated" as X; config from cloud.resource where api.name = 'aws-iam-get-policy-version' AND json.rule = document.Statement[?any(Effect equals Allow and Action contains :* and Resource equals * )] exists as Y; filter "($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action contains :* ) or ($.X.attachedPolicies[*].policyArn intersects $.Y.policyArn)"; show X;  
----

*Updated RQL–*
----
config from cloud.resource where api.name = 'aws-iam-list-roles' AND json.rule = role.assumeRolePolicyDocument.Statement[*].Action contains "sts:AssumeRoleWithWebIdentity" and role.assumeRolePolicyDocument.Statement[*].Principal.Federated contains "cognito-identity.amazonaws.com" and role.assumeRolePolicyDocument.Statement[*].Effect contains "Allow" and role.assumeRolePolicyDocument.Statement[*].Condition contains "cognito-identity.amazonaws.com:amr" and role.assumeRolePolicyDocument.Statement[*].Condition contains "unauthenticated" as X; config from cloud.resource where api.name = 'aws-iam-get-policy-version' AND json.rule = document.Statement[?any(Effect equals Allow and (Action contains :* or Action equals *) and Resource equals * )] exists as Y; filter "($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action contains :* ) or ($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action equals * ) or ($.X.attachedPolicies[*].policyArn intersects $.Y.policyArn)"; show X;  
----

*Policy Type–* Config 

*Policy Severity–* High

*Impact–* Low. New alerts will be generated as per new RQL.


|*AWS Cognito service role with wide privileges does not validate authentication*
//RLP-155781

|*Changes—* Policy RQL has been updated with including the condition matching '*' in policy action

*Current RQL–* 
----
config from cloud.resource where api.name = 'aws-iam-list-roles' AND json.rule = role.assumeRolePolicyDocument.Statement[*].Action contains "sts:AssumeRoleWithWebIdentity" and role.assumeRolePolicyDocument.Statement[*].Principal.Federated contains "cognito-identity.amazonaws.com" and role.assumeRolePolicyDocument.Statement[*].Effect contains "Allow" and role.assumeRolePolicyDocument.Statement[*].Condition contains "cognito-identity.amazonaws.com:amr" and role.assumeRolePolicyDocument.Statement[*].Condition contains "unauthenticated" as X; config from cloud.resource where api.name = 'aws-iam-get-policy-version' AND json.rule = document.Statement[?any(Effect equals Allow and Action contains :* and Resource equals * )] exists as Y; filter "($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action contains :* ) or ($.X.attachedPolicies[*].policyArn intersects $.Y.policyArn)"; show X; 
----

*Updated RQL–*
----
config from cloud.resource where api.name = 'aws-iam-list-roles' AND json.rule = role.assumeRolePolicyDocument.Statement[*].Action contains "sts:AssumeRoleWithWebIdentity" and role.assumeRolePolicyDocument.Statement[*].Principal.Federated contains "cognito-identity.amazonaws.com" and role.assumeRolePolicyDocument.Statement[*].Effect contains "Allow" and role.assumeRolePolicyDocument.Statement[*].Condition contains "cognito-identity.amazonaws.com:amr" and role.assumeRolePolicyDocument.Statement[*].Condition contains "unauthenticated" as X; config from cloud.resource where api.name = 'aws-iam-get-policy-version' AND json.rule = document.Statement[?any(Effect equals Allow and (Action contains :* or Action equals *) and Resource equals * )] exists as Y; filter "($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action contains :* ) or ($.X.inlinePolicies[*].policyDocument.Statement[?(@.Effect=='Allow' && @.Resource=='*')].Action equals * ) or ($.X.attachedPolicies[*].policyArn intersects $.Y.policyArn)"; show X; 
----

*Policy Type–* Config 

*Policy Severity–* High

*Impact–* Low. New alerts will be generated as per new RQL.

2+|*Policy Updates—Metadata*

|*AWS S3 bucket not configured with secure data transport policy*
//RLP-155761

|*Changes—* Policy description updated to include the publicly accessible check.

*Policy Type*: Config

*Policy Severity*: Medium

*Impact*: No impact on alerts

*Updated Description*: 
----
AWS S3 buckets that are publicly accessible and lacking secure data transport are highly susceptible to data breaches during transit.
AWS S3 buckets should enforce data encryption using Secure Sockets Layer (SSL) to protect data transmitted between clients and the S3 service. Failure to enforce HTTPS allows attackers to intercept sensitive data in transit, leading to data exposure and potential breaches. Additionally, because the bucket is publicly accessible, untrusted IPs can access sensitive data without encryption.
The impact of this misconfiguration includes unauthorized access to sensitive data, data breaches, and potential regulatory fines. Enforcing HTTPS ensures all communication with publicly accessible S3 buckets is encrypted, protecting data confidentiality and integrity.
To mitigate this, configure bucket policies to explicitly deny all access except via HTTPS ('aws:SecureTransport: true') and remove public access permissions. Regularly review and update bucket policies to reflect evolving security needs and ensure that public access is minimized or removed.
----

|*AWS S3 bucket not configured with secure data transport policy*
//RLP-155761

|*Changes—* Policy description updated to include the publicly accessible check.

*Policy Type*: Config

*Policy Severity*: Medium

*Impact*: Low

*Updated Description*: 
----
AWS S3 buckets that are publicly accessible and lacking secure data transport are highly susceptible to data breaches during transit.
AWS S3 buckets should enforce data encryption using Secure Sockets Layer (SSL) to protect data transmitted between clients and the S3 service. Failure to enforce HTTPS allows attackers to intercept sensitive data in transit, leading to data exposure and potential breaches. Additionally, because the bucket is publicly accessible, untrusted IPs can access sensitive data without encryption.
The impact of this misconfiguration includes unauthorized access to sensitive data, data breaches, and potential regulatory fines. Enforcing HTTPS ensures all communication with publicly accessible S3 buckets is encrypted, protecting data confidentiality and integrity.
To mitigate this, configure bucket policies to explicitly deny all access except via HTTPS ('aws:SecureTransport: true') and remove public access permissions. Regularly review and update bucket policies to reflect evolving security needs and ensure that public access is minimized or removed.
----

|===


[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|*Compliance Benchmark*
|*Description*

|*[Update] Australian Cyber Security Centre (ACSC) Essential Eight*
//RLP-156067

|New Policy mappings are added to Australian Cyber Security Centre (ACSC) Essential Eight compliance standard across all the levels..

*Impact*: As new mappings are introduced, compliance scoring might vary.


|*FedRAMP (High)*
//RLP-156047

|FedRAMP High compliance is the highest level of security within the Federal Risk and Authorization Management Program (FedRAMP), designed to protect highly sensitive and classified government data stored in cloud environments.

You can now access this built-in standard and related policies on the *Compliance > Standards* page. Additionally, you can generate reports to instantly view or download them, or set up scheduled reports to continuously monitor compliance.


|*[Update] CIS v3.0.0 (OCI) - Level 1 & CIS v3.0.0 (OCI) - Level 2*
//RLP-156044

|Prisma Cloud now supports the latest version of CIS Oracle Cloud Infrastructure Foundations Benchmark . This compliance standard supports two levels - Level 1 and Level 2. CIS Oracle Cloud Infrastructure Foundations Benchmark, provides prescriptive guidance for establishing a secure baseline configuration for the Oracle Cloud Infrastructure environment.

You can now access this built-in standard and related policies on the *Compliance > Standards* page. Additionally, you can generate reports to instantly view or download them, or set up scheduled reports to continuously monitor compliance.

|===


//[#rest-api-updates]
//=== REST API Updates
//[cols="37%a,63%a"]
//|===
//|*REST API*
//|*Description*
//|===

//[#deprecation-notices]
//=== Deprecation Notices
//[cols="50%a, 50%a"]
//|===
//|*Deprecated Endpoints*
//|*Replacement Endpoints*
//|===