== Features Introduced in March 2025

Learn what's new on Prisma® Cloud in March 2025.

// * <<new-features>>
//* <<changes-in-existing-behavior>>
* <<api-ingestions>>
* <<new-policies>>
* <<policy-updates>>
//* <<iam-policy-updates>>
* <<new-compliance-benchmarks-and-updates>>
* <<rest-api-updates>>
//* <<deprecation-notices>>


//[#new-features]
//=== New Features
//[cols="30%a,70%a"]
//|===
//|*Feature*
//|*Description*


//|===

//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior

//[cols="50%a,50%a"]

//|===
//|*Feature*
//|*Description*


//|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|*Service*
|*API Details*

|*Amazon Cognito*
//RLP-154816
|*aws-cognito-identity-pool-role*

Additional permissions needed:

* `cognito-identity:ListIdentityPools`
* `cognito-identity:GetIdentityPoolRoles`

The Security audit role includes the permissions.

|*Amazon Connect*
//RLP-152592
|*aws-connect-instance-user*

Additional permissions needed:

* `connect:ListUsers`
* `connect:DescribeUser`
* `connect:ListInstances`

The Security audit role includes the `connect:ListUsers` permissions.

|*Amazon Connect*
//RLP-152591
|*aws-connect-instance-security-profile*

Additional permissions needed:

* `connect:ListSecurityProfiles`
* `connect:DescribeSecurityProfile`
* `connect:ListInstances`

The Security audit role includes the `connect:ListInstances` permissions.

|tt:[Update] *Amazon EC2*
//RLP-154720
|*aws-ec2-describe-images*

Additional permission needed:

* `ec2:DescribeImageAttribute`

The Security audit role includes the permission.

Also, the JSON resource for this API includes a new `imageAttributes` field.

|tt:[Update] *Amazon EC2*
//RLP-155041
|*aws-ec2-describe-vpcs*

Additional permission needed:

* `ec2:DescribeImageAttribute`
* `ec2:DescribeVpcAttribute`

The Security audit role includes the permission.

This update requires the new permission`ec2:DescribeVpcAttribute` be added in addition to the existing permission.


|*Amazon EC2*
//RLP-152589
|*aws-ec2-instance-connect-endpoint*

Additional permission needed:

* `ec2:DescribeInstanceConnectEndpoints`

The Security audit role includes the permission.

|*Amazon EC2*
//RLP-155008
|*aws-ec2-image-block-public-access-state*

Additional permission needed:

* `ec2:GetImageBlockPublicAccessState`

The Security audit role includes the permission.


|*Amazon EC2*
//RLP-155011
|*aws-ec2-snapshot-block-public-access-state*

Additional permission needed:

* `ec2:GetSnapshotBlockPublicAccessState`

The Security audit role does not include the permission. You must manually add the permission in the CFT template to enable it.


|*Amazon EventBridge Pipes*
//RLP-154730
|*aws-event-bridge-pipe*

Additional permissions needed:

* `pipes:ListPipes`
* `pipes:DescribePipe`

The Security audit role does not include the permissions. You must manually add the permissions in the CFT template to enable them.

|*Amazon RDS*
//RLP-154775
|*aws-rds-db-instance-automated-backup*

Additional permission needed:

* `rds:DescribeDBInstanceAutomatedBackups`

The Security audit role includes the permission.

|*Amazon RDS*
//RLP-154773
|*aws-rds-db-proxy*

Additional permission needed:

* `rds:DescribeDBProxies`

The Security audit role includes the permission.

|*Amazon RDS*
//RLP-154771
|*aws-rds-db-proxy-target*

Additional permissions needed:

* `rds:DescribeDBProxies`
* `rds:DescribeDBProxyTargets`
* `rds:DescribeDBProxyTargetGroups`

The Security audit role includes the permissions.

|tt:[Update] *Amazon RDS*
//RLP-154718
|*aws-rds-describe-db-instances*

The JSON resource for the API will be updated to include a new field `latestRestorableTime`.

|*Amazon S3*
//RLP-154767
|*aws-s3-storage-lens-configuration*

Additional permission needed:

* `s3:ListStorageLensConfigurations`

The Security audit role does not include the permission. You must manually add the permission in the CFT template to enable it.

|*Amazon SNS*
//RLP-154818
|*aws-sns-subscriptions-by-topic*

Additional permissions needed:

* `sns:ListTopics`
* `sns:ListSubscriptionsByTopic`

The Security audit role includes the permissions.


|*Amazon SQS*
//RLP-155006
|*aws-sqs-message-move-task*

Additional permissions needed:

* `sqs:ListQueues`
* `sqs:ListMessageMoveTasks`

The Security audit role only includes the `sqs:ListQueues` permission. 
You must manually include the `sqs:ListMessageMoveTasks` permission in the CFT template to enable it.


|tt:[Update] *AWS Glue*
//RLP-154723
|*aws-glue-connection*

Additional permission needed:

* `glue:GetTags`

The Security audit role includes the permission.

Also, the JSON resource for this API includes `tags` field.

|*AWS Glue*
//RLP-155004
|*aws-glue-blueprint*

Additional permissions needed:

* `glue:ListBlueprints`
* `glue:GetBlueprint`

The Security audit role does not include the permissions. You must manually add the permissions in the CFT template to enable them.

|*AWS Glue*
//RLP-154994
|*aws-glue-blueprint-run*

Additional permissions needed:

* `glue:GetBlueprintRuns`
* `glue:GetBlueprintRun`

The Security audit role does not include the permissions. You must manually add the permissions in the CFT template to enable them.

|*AWS Lambda*
//RLP-154713
|*aws-lambda-function-event-invoke-config*

Additional permissions needed:

* `lambda:ListFunctions`
* `lambda:GetFunctionEventInvokeConfig`

The Security audit role includes the permissions.

|*AWS Lambda*
//RLP-154706
|*aws-lambda-versions-by-function*

Additional permissions needed:

* `lambda:ListFunctions`
* `lambda:ListVersionsByFunction`

The Security audit role includes the permissions.

|*AWS Lambda*
//RLP-154710
|*aws-lambda-function-concurrency*

Additional permissions needed:

* `lambda:ListFunctions`
* `lambda:GetFunctionConcurrency`

The Security audit role only includes the `lambda:ListFunctions` permission. You must manually include the `lambda:GetFunctionConcurrency` permission in the CFT template to enable it.

|*AWS Lambda*
//RLP-154701
|*aws-lambda-runtime-management-config*

Additional permissions needed:

* `lambda:ListFunctions`
* `lambda:GetRuntimeManagementConfig`

The Security audit role only includes the `lambda:ListFunctions` permission. You must manually include the `lambda:GetRuntimeManagementConfig` permission in the CFT template to enable it.

|tt:[Update] *AWS Regions*
//RLP-154718
|*aws-region*

The JSON resource for the API is updated to include a new field `accountId`.


|tt:[Update] *AWS Regions*
//RLP-155012
|*aws-region*

The resource output of the API aws-region includes the new field `accountId`.

|*Azure API Management Services*
//RLP-155045
|*azure-api-management-service-authorization-server*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.ApiManagement/service/authorizationServers/read`

The Reader role includes the permissions.

|*Azure API Management Services*
//RLP-155046
|*azure-api-management-service-backend*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.ApiManagement/service/backends/read`

The Reader role includes the permissions.

|*Azure API Management Services*
//RLP-155047
|*azure-api-management-service-openid-connect-provider*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.ApiManagement/service/openidConnectProviders/read`

The Reader role includes the permissions.

|*Azure API Management Services*
//RLP-155048
|*aazure-api-management-service-user*

Additional permissions needed:

* `Microsoft.ApiManagement/service/read`
* `Microsoft.ApiManagement/service/users/read`

The Reader role includes the permissions.

|*Azure Kubernetes Service*
//RLP-155179
|*azure-kubernetes-connected-cluster*

Additional permissions needed:

* `Microsoft.Kubernetes/connectedClusters/Read`

The Reader role includes the permission.

|*Azure CDN*
//RLP-154729
|*azure-frontdoor-standardpremium-origin-groups-origin*

Additional permissions needed:

* `Microsoft.Cdn/profiles/read`
* `Microsoft.Cdn/profiles/origingroups/read`
* `Microsoft.Cdn/profiles/origingroups/origins/read`

The Reader role includes the permissions.

|*Azure Network Manager*
//RLP-154727
|*azure-network-manager-static-members*

Additional permissions needed:

* `Microsoft.Network/networkManagers/read`
* `Microsoft.Network/networkManagers/networkGroups/read`
* `Microsoft.Network/networkManagers/networkGroups/staticMembers/read`

The Reader role includes the permissions.


|*Azure Network Manager*
//RLP-154784
|*azure-network-manager-security-admin-configuration*

Additional permissions needed:

* `Microsoft.Network/networkManagers/read` 
* `Microsoft.Network/networkManagers/securityAdminConfigurations/read`

The Reader role includes the permissions.

|*Azure Network Manager*
//RLP-154783
|*azure-network-manager-network-group*

Additional permissions needed:

* `Microsoft.Network/networkManagers/read`
* `Microsoft.Network/networkManagers/networkGroups/read`

The Reader role includes the permissions.

|*Azure Recovery Services*
//RLP-155176
|*azure-recovery-service-site-recovery-protected-item*

Additional permissions needed:

* `Microsoft.RecoveryServices/Vaults/read`
* `Microsoft.RecoveryServices/vaults/replicationProtectedItems/read`

The Reader role includes the permissions.


|*Azure Storage*
//RLP-154786
|*azure-storage-account-blob-container*

Additional permissions needed:

* `Microsoft.Storage/storageAccounts/read`
* `Microsoft.Storage/storageAccounts/blobServices/containers/read`

The Reader role includes the permissions.

|*Azure Storage*
//RLP-154785
|*azure-storage-account-file-service-property*

Additional permissions needed:

* `Microsoft.Storage/storageAccounts/read`
* `Microsoft.Storage/storageAccounts/fileServices/read`

The Reader role includes the permissions.

|*Google Data Catalog*
//RLP-154782
|*gcloud-data-catalog-tag-template*

Additional permissions needed:

* `datacatalog.catalogs.searchAll`
* `datacatalog.tagTemplates.get`
* `datacatalog.tagTemplates.getIamPolicy`

The Viewer role includes the permissions.



|===

[#new-policies]
=== New Policies

[cols="40%a,60%a"]
|===
|*Policies*
|*Description*

|*AWS Lightsail bucket accessible to unmonitored cloud accounts*
//RLP-155140

|*Policy Description—* AWS Lightsail buckets with permissions granted to unmonitored cloud accounts pose a significant security risk. These buckets, offering internet-accessible storage, could be compromised if unauthorized accounts gain access.

Lightsail buckets provide object storage, allowing data retrieval from anywhere. Granting 'read' access to unmonitored cloud accounts introduces a substantial risk. Attackers might exploit this misconfiguration to exfiltrate sensitive data or inject malicious content, potentially leading to data breaches or system compromise.

To mitigate this risk, restrict access to Lightsail buckets to only explicitly trusted and monitored cloud accounts. Only trusted and monitored cloud accounts should possess the necessary permissions.

Regularly review and audit bucket permissions, removing access for any unmonitored or untrusted accounts. Implement robust monitoring and alerting to detect any unauthorized access attempts.

*Policy Severity—* Medium

*Policy Type—* Config

----
`config from cloud.resource where cloud.type = 'aws' and api.name = 'aws-lightsail-storage-bucket' AND json.rule = 'readonlyAccessAccounts is not empty and _AWSCloudAccount.isRedLockMonitored($.readonlyAccessAccounts[*]) is false'`
----

|*AWS Lightsail bucket publicly readable*
//RLP-155141

|*Policy Description—* Publicly readable objects in AWS Lightsail buckets expose sensitive data to unauthorized access, increasing the risk of data breaches and reputational harm.

AWS Lightsail provides object storage through buckets, enabling data storage and retrieval. A misconfiguration allowing public readability exposes all stored data. Untrusted parties can freely access this information, leading to data exfiltration, intellectual property theft, and financial losses.

To mitigate this risk, enforce the principle of least privilege. Restricting bucket access to authorized users is crucial for maintaining data confidentiality and integrity.

Configure bucket permissions to be private, only granting access to specific users or groups needing it. Regularly review and audit bucket access controls to detect and address any misconfigurations promptly.

*Policy Severity—* High

*Policy Type—* Config

----
config from cloud.resource where api.name = 'aws-lightsail-storage-bucket' AND json.rule = accessRules.getObject equal ignore case public as X; config from cloud.resource where api.name = 'aws-s3control-public-access-block' AND json.rule = blockPublicAcls is false or blockPublicPolicy is false or ignorePublicAcls is false or restrictPublicBuckets is false as Y; filter '$.X.arn contains $.Y.accountId' ; show X;
----

|*AWS Lightsail bucket object versioning is disabled*
//RLP-155138

|*Policy Description—* AWS Lightsail buckets lacking object versioning are susceptible to data loss and unauthorized modification. Disabling this feature removes the ability to revert to previous versions of objects after accidental deletion or malicious alteration.

Lightsail buckets provide object storage, allowing data access from anywhere. Object versioning creates version history for every object stored. Without versioning, accidental deletion or malicious overwrites result in permanent data loss, severely impacting data integrity and potentially leading to business disruption or data breaches. Attackers could exploit this misconfiguration to permanently delete or modify critical data.

To mitigate this risk, enable object versioning on all AWS Lightsail buckets, this ensures data recoverability, protecting against accidental or malicious actions and mitigating the risk of significant data loss.

Regularly review bucket configurations to ensure object versioning remains active. Implement robust access control mechanisms.

*Policy Severity—* Low

*Policy Type—* Config

----
config from cloud.resource where cloud.type = 'aws' and api.name = 'aws-lightsail-storage-bucket' AND json.rule = objectVersioning does not equal ignore case Enabled
----


|===

[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*


2+|*Policy Updates—RQL*

|*AWS CloudTrail is not enabled with multi-trail and not capturing all management events*
//RLP-154181

|*Changes—* The policy RQL is updated to reduce false positives when both management events and network activity events are configured.

*Current RQL–* 
----
config from cloud.resource where api.name= 'aws-cloudtrail-describe-trails' AND json.rule = 'isMultiRegionTrail is true and includeGlobalServiceEvents is true' as X; config from cloud.resource where api.name= 'aws-cloudtrail-get-trail-status' AND json.rule = 'status.isLogging equals true' as Y; config from cloud.resource where api.name= 'aws-cloudtrail-get-event-selectors' AND json.rule = '(eventSelectors[*].readWriteType contains All and eventSelectors[*].includeManagementEvents equal ignore case true) or (advancedEventSelectors[*].fieldSelectors[*].equals contains "Management" and advancedEventSelectors[*].fieldSelectors[*].field does not contain "readOnly" and advancedEventSelectors[*].fieldSelectors[*].field does not contain "eventSource")' as Z; filter '($.X.trailARN equals $.Z.trailARN) and ($.X.name equals $.Y.trail)'; show X; count(X) less than 1
----

*Updated RQL–*
----
config from cloud.resource where api.name= 'aws-cloudtrail-describe-trails' AND json.rule = 'isMultiRegionTrail is true and includeGlobalServiceEvents is true' as X; config from cloud.resource where api.name= 'aws-cloudtrail-get-trail-status' AND json.rule = 'status.isLogging equals true' as Y; config from cloud.resource where api.name= 'aws-cloudtrail-get-event-selectors' AND json.rule = '(eventSelectors[*].readWriteType contains All and eventSelectors[*].includeManagementEvents equal ignore case true) or (advancedEventSelectors[?any(name exists and name contains "Management events selector" and fieldSelectors[*].field does not contain "readOnly" and fieldSelectors[*].field does not contain "eventSource")]exists)' as Z; filter '($.X.trailARN equals $.Z.trailARN) and ($.X.name equals $.Y.trail)'; show X; count(X) less than 1 
----

*Policy Type–* Config

*Policy Severity–* Informational

*Impact–* Low. Existing alerts where all management event is configured and the event selector is configured as part of network activity event will be resolved.

|*Azure Container Registry with anonymous authentication enabled*
//RLP-154856

|*Changes—* The policy RQL will be updated to trigger an alert on Azure container registry when anonymous pull is enabled, resolving false alerts.

*Current RQL–* 
----
config from cloud.resource where api.name = 'azure-container-registry' AND json.rule = (skuName contains Standard or skuName contains Premium) and properties.provisioningState equal ignore case Succeeded and properties.anonymousPullEnabled is false
----

*Updated RQL–*
----
config from cloud.resource where api.name = 'azure-container-registry' AND json.rule = (skuName contains Standard or skuName contains Premium) and properties.provisioningState equal ignore case Succeeded and properties.anonymousPullEnabled is true
----

*Policy Type–* Config

*Policy Severity–* High

*Impact–* High. Existing alerts where the anonymous pull is disabled will be resolved and new alerts will be generated where the anonymous pull is enabled.

|*GCP Load balancer HTTPS target proxy is not configured with QUIC protocol*
//RLP-154209

|*Changes—* The policy RQL policy will be updated in the case of regional internal load balancers.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-compute-target-https-proxies' AND json.rule = 'quicOverride does not contain ENABLE'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-compute-target-https-proxies' AND json.rule = 'quicOverride does not contain ENABLE' as X; config from cloud.resource where api.name = 'gcloud-compute-internal-lb-backend-service' as Y; filter 'not ($.Y.usedBy[*].reference contains $.X.urlMap)'; show X;
----

*Policy Type–* Config

*Policy Severity–* Informational

*Impact–* Low. Existing alerts for regional internal application load balancer will be resolved.

|*Instance affected by Spring Cloud Function SpringShell vulnerability is exposed to network traffic from the internet [CVE-2022-22963]*
//RLP-154951

|*Changes—* The policy RQL policy will be updated to consider internet network traffic as the source.

*Current RQL–* 
----
network from vpc.flow_record where bytes > 0 AND source.resource IN (resource where finding.type IN ( 'Host Vulnerability' ) AND finding.source IN ( 'Prisma Cloud' ) AND finding.name IN ('CVE-2022-22963')) AND destination.publicnetwork IN ('Internet IPs', 'Suspicious IPs')
----

*Updated RQL–*
----
network from vpc.flow_record where bytes > 0 AND dest.resource IN (resource where finding.type IN ( 'Host Vulnerability' ) AND finding.source IN ( 'Prisma Cloud' ) AND finding.name IN ('CVE-2022-22963')) AND source.publicnetwork IN ('Internet IPs', 'Suspicious IPs')
----

*Policy Type–* Network

*Policy Severity–* Critical

*Impact–* Low.

|*Azure Storage account encryption key is not rotated regularly*
//RLP-153985

|*Changes—* The policy RQL policy will be updated to consider internet network traffic as the source.

*Current RQL–* 
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = properties.encryption.keySource equal ignore case "Microsoft.Keyvault" as X; config from cloud.resource where api.name = 'azure-key-vault-list' and json.rule = keys[?any(attributes.exp equals -1 and attributes.enabled contains true)] exists as Y; filter '$.Y.properties.vaultUri contains $.X.properties.encryption.keyvaultproperties.keyvaulturi'; show X; 
----

*Updated RQL–*
----
config from cloud.resource where api.name = 'azure-storage-account-list' AND json.rule = 'properties.encryption.keySource equal ignore case "Microsoft.Keyvault" and _DateTime.ageInDays(properties.encryption.keyvaultproperties.currentVersionedKeyExpirationTimestamp) > 1' 
----

*Policy Type–* Config

*Policy Severity–* Low

*Impact–* Low.  Open alerts where multiple keys exist and a correct key is associated with the Storage Account for encryption will be resolved.

|===


[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|*Compliance Benchmark*
|*Description*


|*Cloud Security Assurance Program*
//RLP-155215

|Prisma Cloud now supports the latest version of Cloud Security Assurance Program (CSAP). This compliance standard supports five different levels - IaaS, SaaS Standard,  SaaS Simplified, Low and Low SaaS.  CSAP aims to boost confidence among public and private sector users, promoting secure cloud adoption and enhancing overall national cybersecurity.

You can now access this built-in standard and related policies on the *Compliance > Standards* page. Additionally, you can generate reports to instantly view or download them, or set up scheduled reports to continuously monitor compliance.

|*[Update] Korea – Information Security Management System*
//RLP-155226

|New Policy mappings are added to Korea – Information Security Management System (ISMS) compliance standard.

*Impact*: As new mappings are introduced, compliance scoring might vary.

|*[Update] NIST CSF v2.0*
//RLP-155206

|New Policy mappings are added to the National Institute of Standards and Technology (NIST) Cybersecurity Framework (CSF) v2.0 compliance standard.

*Impact*: As new mappings are introduced, compliance scoring might vary.


|===

[#rest-api-updates]
=== REST API Updates

[cols="37%a,63%a"]
|===
|*REST API*
|*Description*

|*Perform Event Search API*
//RLP-155188
|The request body for *Perform Event Search* - https://pan.dev/prisma-cloud/api/cspm/search-events[POST /search/event] has been updated.

Possible values for sort fields are updated from upper case to lower case.

|===

//[#deprecation-notices]
//=== Deprecation Notices

//[cols="50%a, 50%a"]
//|===

//|*Deprecated Endpoints*
//|*Replacement Endpoints*




//|===



