== Features Introduced in September 2025

Learn what's new in the Prisma® Cloud September 2025 release.


//* <<new-features>>
//* <<enhancements>>
//* <<changes-in-existing-behavior>>
* <<api-ingestions>>
//* <<new-policies>>
* <<policy-updates>>
//* <<iam-policy-updates>>
//* <<new-compliance-benchmarks-and-updates>>
//* <<rest-api-updates>>
//* <<deprecation-notices>>


//[#enhancements]
//=== Enhancements
//[cols="30%a,70%a"]
//|===
//|*Feature*
//|*Description*

//|===

//[#changes-in-existing-behavior]
//=== Changes in Existing Behavior
//[cols="30%a,70%a"]
//|===
//|*Feature*
//|*Description*

//|===


[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===

|*Google AI Applications*
//RLP-156754

|*gcloud-ai-applications-cmek-config*

Additional permissions required:

* `discoveryengine.cmekConfigs.list`

The Viewer role includes the permission.


|===


// [#new-policies]
// === New Policies
// [cols="40%a,60%a"]
// |===
// |*Policies*
// |*Description*
// |===




[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|*Policy Updates*
|*Description*

2+|*Policy Updates—RQL*

|*Azure App Service web apps with public network access*
//RLP-156747

|*Changes–* The RQL is updated to consider private endpoints as well to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled and config.ipSecurityRestrictions[?any(action equals Allow and ipAddress equals Any)] exists'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist and (properties.privateLinkIdentifiers does not exist or properties.privateLinkIdentifiers is empty))) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open alerts where private link identifiers exist will be resolved. App service where the IP rule allowing 0.0.0.0/0 will be alerted. 


|*Azure Key Vault audit logging is disabled*
//RLP-156668

|*Changes–* RQL updated to resolve a syntax issue.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND  api.name = 'azure-key-vault-list' AND json.rule =  "not ( diagnosticSettings.value[*].properties.logs[*].enabled any equal true and diagnosticSettings.value[*].properties.logs[*].enabled size greater than 0 )" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-key-vault-list' AND json.rule = not(diagnosticSettings.value[?any(properties.logs[?any(enabled equals "true")] exists )] exists and diagnosticSettings.value[*].properties.logs[*].enabled size > 0) 
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* No Impact

|*Azure Network Watcher Network Security Group (NSG) flow logs are disabled*
//RLP-156741

|*Changes–*  Prisma policy updated to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings does not exist or flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.storageId is not empty and flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Current Remediation Steps–* 
To configure Network Watcher Network Security Group (NSG) flow log, follow below URL:
https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-portal#enable-nsg-flow-log

*Proposed Remediation Steps–* 

Follow the below steps to enable flow logs for Network security group via Azure Portal:

1. Log in to the Azure portal.
2. Search *Network foundation*.
3. Under *Virtual Network*, Select *Network security groups*
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under *Monitoring*, Select *NSG flow logs*'.
6. Select the flow log with Status *Disabled*, Click on *Enable* at the top.
7. Confirm the flow log name and click *Enable* at the bottom. 

Use the command below to enable flow logs for Network security group via Azure CLI:

`az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --location <location>`

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.


|*Azure Network Watcher Network Security Group (NSG) flow logs retention is less than 90 days*
//RLP-156742

|*Changes–*  Prisma policy updated to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule =  ' $.flowLogsSettings does not exist or  $.flowLogsSettings.enabled is false or  ($.flowLogsSettings.retentionPolicy.days does not equal 0 and $.flowLogsSettings.retentionPolicy.days less than 90) '
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.retentionPolicy.days does not equal 0 and flowLogsSettings.retentionPolicy.days less than 90) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Proposed Remediation Steps–* 

Follow the below steps to update retention days for flow logs via Azure Portal:

1. Log in to the Azure portal.
2. Search *Network foundation*.
3. Under *Virtual Network*, Select *Network security groups*
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under *Monitoring*, Select *NSG flow logs*'.
6. Click the flow log, and under *Storage Account*, Set the *Retention days* to 90 days or greater.
7. *Save* your changes.  

Use the command below to enable flow logs for Network security group via Azure CLI: 

`az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --retention <Retention Days> --location <location>`

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.


|*Azure App Service web apps with public network access*
//RLP-156747

|*Changes–* RQL update to consider private endpoints and reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled and config.ipSecurityRestrictions[?any(action equals Allow and ipAddress equals Any)] exists'
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-app-service' AND json.rule = 'kind starts with app and properties.state equal ignore case running and ((properties.publicNetworkAccess exists and properties.publicNetworkAccess equal ignore case Enabled) or (properties.publicNetworkAccess does not exist and (properties.privateLinkIdentifiers does not exist or properties.privateLinkIdentifiers is empty))) and config.ipSecurityRestrictions[?any((action equals Allow and ipAddress equals Any) or (action equals Allow and ipAddress equals 0.0.0.0/0))] exists'
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–* Low.  Open alerts where private link identifiers exist will be resolved. App service where the IP rule allowing 0.0.0.0/0 will be alerted.

|*Azure Key Vault audit logging is disabled{}*
//RLP-156668

|*Changes–* RQL update to resolve syntax issue.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND  api.name = 'azure-key-vault-list' AND json.rule =  "not ( diagnosticSettings.value[*].properties.logs[*].enabled any equal true and diagnosticSettings.value[*].properties.logs[*].enabled size greater than 0 )" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-key-vault-list' AND json.rule = not(diagnosticSettings.value[?any(properties.logs[?any(enabled equals "true")] exists )] exists and diagnosticSettings.value[*].properties.logs[*].enabled size > 0) 
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* No Impact

|*Azure Microsoft Defender for Cloud disk encryption monitoring is set to disabled*
//RLP-156565

|*Changes–* RQL logic and remediation is updated for this Policy.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.diskEncryptionMonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))' 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and (properties.parameters.gcLinuxDiskEncryptionMonitoringEffect.value equals Disabled or properties.parameters.gcWindowsDiskEncryptionMonitoringEffect.value equals Disabled)) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* All alerts will be resolved as Policy Updated.

|*Azure Key Vault audit logging is disabled{}*
//RLP-156565

|*Changes–* RQL logic and remediation is updated for this Policy.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.systemUpdatesMonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'  
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-policy-assignments' AND json.rule = '((name == SecurityCenterBuiltIn and properties.parameters.systemUpdatesV2MonitoringEffect.value equals Disabled) or (name == SecurityCenterBuiltIn and properties.parameters[*] is empty and properties.displayName does not start with "ASC Default"))'
----

*Policy Type–* Config 

*Policy Severity–* Informational

*Impact–* All alerts will be resolved as Policy Updated.

|*Azure Network Watcher Network Security Group (NSG) flow logs retention is less than 90 days*
//RLP-156742

|*Changes–* RQL update to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule =  ' $.flowLogsSettings does not exist or  $.flowLogsSettings.enabled is false or  ($.flowLogsSettings.retentionPolicy.days does not equal 0 and $.flowLogsSettings.retentionPolicy.days less than 90) ' 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.retentionPolicy.days does not equal 0 and flowLogsSettings.retentionPolicy.days less than 90) and tags.created-by does not contain "prismacloud-agentless-scan"
----

*Current Remediatin Steps*

To enable Flow Logs:

1. Log in to the Azure portal.
2. Select 'Network Watcher'.
3. Select 'NSG flow logs'.
4. Select the NSG for which you need to modify the flow log settings.
5. Set the Flow logs 'Status' to 'On'.
6. Select the destination 'Storage account'.
7. Set the 'Retention (days)' to 90 days or greater.
8. 'Save' your changes.

*Proposed Remediation Steps*

1. Log in to the Azure portal.
2. Search 'Network foundation'.
3. Under 'Virtual Network', Select 'Network security groups'
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under 'Monitoring', Select 'NSG flow logs'.
6. Click the flow log, and under 'Storage Account', Set the 'Retention days' to 90 days or greater.
7. 'Save' your changes.  

Use the command below to enable flow logs for Network security group via Azure CLI: 
----
az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --retention <Retention Days> --location <location>
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–*  Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.

|*Azure Network Watcher Network Security Group (NSG) flow logs are disabled*
//RLP-156741

|*Changes–* RQL updated with the latest CSP changes to reduce false positives.

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings does not exist or flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-network-nsg-list' AND json.rule = (flowLogsSettings.storageId is not empty and flowLogsSettings.enabled is false) and tags.created-by does not contain "prismacloud-agentless-scan" 
----

*Current Remediatin Steps*

To configure Network Watcher Network Security Group (NSG) flow log, follow below URL:
https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-portal#enable-nsg-flow-log

*Proposed Remediation Steps*

Follow the below steps to enable flow logs for Network security group via Azure Portal:

1. Log in to the Azure portal.
2. Search 'Network foundation'.
3. Under 'Virtual Network', Select 'Network security groups'
4. Search and Click the Network security group for which you need to modify the flow log settings.
5. Under 'Monitoring', Select 'NSG flow logs'.
6. Select the flow log with Status 'Disabled', Click on 'Enable' at the top.
7. Confirm the flow log name and click 'Enable' at the bottom. 

Use the below command to enable flow logs for Network security group via Azure CLI:
----
az network watcher flow-log update --name <Flow Log name> --nsg <NSG name> --resource-group <Resource Group name> --storage-account <Storage account> --enabled true --location <location>
----

*Policy Type–* Config 

*Policy Severity–* Medium

*Impact–*  Low. Open Alerts where the Flow logs did not exist for NSG will be resolved.

|*GCP PostgreSQL instance database flag log_min_messages is not set to Warning or higher*
//RLP-156777

|*Changes–* Policy updated to no longer alert on GCP PostgreSQL instances where the log_min_messages database flag is not explicitly configured, as the default value of "warning".

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_messages')].value is not member of ( "warning", "error", "log", "fatal", "panic")
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_messages')].value exists and settings.databaseFlags[?(@.name=='log_min_messages')].value is not member of ( "warning", "error", "log", "fatal", "panic")
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. This update will resolve existing alerts on GCP PostgreSQL instances where the log_min_messages database flag was not explicitly configured.

|*GCP PostgreSQL instance database flag log_min_error_statement is not set to Error or higher*
//RLP-156779

|*Changes–* Policy updated to no longer alert on GCP PostgreSQL instances where the log_min_error_statement database flag is not explicitly configured, as the default value of "Error".

*Current RQL–* 
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_error_statement')].value is not member of ( "error" , "log", "fatal", "panic")
----

*Updated RQL–*
----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-sql-instances-list' AND json.rule = state equal ignore case "RUNNABLE" and databaseVersion contains POSTGRES and settings.databaseFlags[?(@.name=='log_min_error_statement')].value exists and settings.databaseFlags[?(@.name=='log_min_error_statement')].value is not member of ( "error" , "log", "fatal", "panic")
----

*Policy Type–* Config 

*Policy Severity–* Low

*Impact–* Low. This update will resolve existing alerts on GCP PostgreSQL instances where the log_min_error_statement database flag was not explicitly configured.


2+|*Policy Deletion*

|*Azure Policy Deletions*
//RLP-156560

|The policies below have been deleted due to the vendor update to the service:

* Azure Microsoft Defender for Cloud adaptive application controls monitoring is set to disabled (7363990f-b1fb-42c8-ad4a-fbb06de0310d)
* Azure Microsoft Defender for Cloud endpoint protection monitoring is set to disabled (5315a853-6a6b-43eb-a771-5906f41130b8)
* Azure Microsoft Defender for Cloud security configurations monitoring is set to disabled (19f4c5f1-1785-41b6-95be-2a393f537dad)

*Impact*: All alerts will be resolved as Policy Deleted.

|===


//[#new-compliance-benchmarks-and-updates]
//=== New Compliance Benchmarks and Updates

//[cols="50%a,50%a"]
//|===
//|*Compliance Benchmark*
//|*Description*
//|===


//[#rest-api-updates]
//=== REST API Changes and New APIs

//[cols="37%a,63%a"]
//|===
//|*REST API*
//|*Description*



//|===

//[#deprecation-notices]
//=== Deprecation Notices
//[cols="50%a, 50%a"]
//|===
//|*Change*
//|*Description*
//|===