== Saved Views

Create *Saved Views* to prioritize and organize your alerts into appropriate threat vector categories. Prisma Cloud provides a set of default views — Overview, Misconfigurations, Incidents, Malware, and Highest Priority.

[NOTE]
====
Default (*System*) views are initially the opinionated suggestion of what a view should be based upon the problem being solved. If you make changes to a Default view, the changes are persisted each time you return to that view. Default views do not reset to the initial System view.
====

[.procedure]
. *Add View*.

.. Select *Alerts > Overview* to see the default views. Each view includes preset filters that display the most relevant alerts for the category.

.. *Add View* to clone the view that you’re currently on or the default overview. You can create a maximum of 20 views.

. *Manage Views*.

.. Select *Overview > Manage Views* to reorder, hide/show, duplicate, and delete your saved views.
+
[NOTE]
====
Default (*System*) views cannot be deleted or reordered.*Overview*, which is the first view, also cannot be hidden.
====

.. Select *Done* to confirm your changes.