== Create Views

Create customized views to prioritize alerts.

Create *Saved Views* to organize your alerts into appropriate threat vector categories. Prisma Cloud provides a set of default views—Overview, Incidents, Exposure, Vulnerabilities, Misconfigurations, and Risky Attack Paths.

[NOTE]
====
Default (*System*) views are initially the opinionated suggestion of what that view should be based upon the problem being solved. If you, as a user, make changes while inside a Default (*System*) view, those changes will be persisted each time you return to that view. Default (*System*) views do not reset to the initial opinionated suggestion.
====

[.procedure]
. *Add View*.

.. Select *Alerts > Overview* to see the default views. Each view includes preset filters that display the most relevant alerts for the category.

.. *Add View* to clone the view that you’re currently on or the default overview. You can create a maximum of 20 views.

. *Manage Views*.

.. *Manage Views* to reorder, hide/show, duplicate, and delete your saved views.
+
[NOTE]
====
You cannot delete or rename the default (*System*) views and you cannot reorder or hide *Overview*, which is the first view.
====

.. *Done* and *Confirm* to view your changes (the Confirm option displays only when you want to delete a view).