== GitHub Actions is enabled and not used in a GitHub repository

=== Rule Details

[width=45%]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_60
|Category |SYSTEM_CONFIGURATION
|Provider |
|Severity |LOW
|Mapped CSPM/KSPM Rule |None
|===


=== Description

GitHub Actions is the built-in CI solution offered by GitHub, allowing to execute code within the context of GitHub repositories. GitHub Actions is enabled by default for all GitHub organizations and repositories.

As any organization member can run workflows, execute actions against repository code, and interact with the GitHub API from within the workflow (including API actions that require 'write' permissions), GitHub Actions serves as a potential attack surface for the repository and organization, even if the service is not actively used.

=== Recommended Solution - Buildtime

If GitHub Actions is not in use in the organization, disable it completely at the organization level. If it is in use in the organization, restrict it to the specific repositories in which it is used:

. Browse to the organization settings.
. Click *Actions*, and under *Policies*, disable GitHub Actions, or restrict to specific repositories.

