== Create and Manage Saved Views

Prisma Cloud offers the ability to create *Saved Views* to prioritize and organize your data into categories that are meanigful to your organization. Saved views are available on the Governance, Alerts, Compliance and Dashboards pages. For instance on the Alerts page Prisma Cloud provides a set of default views — Overview, Misconfigurations, Incidents, Malware, and Highest Priority, but you can also create a custom view and share it with others in your organization or tenant. Review the Alerts page workflows below to create, manage, and share your Saved Views.


[NOTE]
====
Default (*System*) views are initially the opinionated suggestion of what a view should be based upon the problem being solved. Views such as *High-Priority*, *Attack Paths*, and *Incidents* etc, include preset filters that display the most relevant alerts for each category. If you make changes to a Default view, the changes are persisted each time you return to that view. Default views do not reset to the initial System view and cannot be deleted or reordered. *Overview*, which is the first view, also cannot be hidden.
====

[.procedure]

. Add a view to your *Saved Views*.

.. Navigate to *Home > Alerts*. Provide a unique identifier for your new View.

.. Select *Menu > Add View* to create your custom view. Check the *Copy current view configuration* box to clone the your current Alerts view configuration.

.. Select *Add New View* to save your custom view. Custom views are limited to a maximum of 20. 

. *Manage Views*

.. Select *Menu> Manage Views* to reorder, hide/show, duplicate, and delete your saved views.
.. Select *Done* to confirm your changes.

. *Share Views: Update Access Setting*

.. Select *Alerts > Menu* and navigate to the custom view that you've created that you wish to share.
.. Choose the action menu on the right and select *Share*.
.. Select *Public* from the *Access Settings* drop-down and click *Update*.
.. Share the URL of your View with anyone in your organization to provide access.

. Optionally, follow the steps below to help your users discover the View you've created:

.. We recommend that you guide users to toggle on the the *Visibility* setting of the shared View under *Alerts> Menu > Manage Views*. 
.. Once the View is shared globally, it will appear by default at the bottom of the *Manage Views* list and can be reordered to the top by individual users for easy access. If the user you wish to share a view with, is currently on the Alerts page, they will also need to refresh the page to see the shared view. 

NOTE: If you are a user and you've received a URL for a shared View and you haven't updated the View's *Visibility* settings, the shared View will only show up temporarily on the Menu tab. To ensure it's always accessible follow the steps listed above. 





