== Application Query Attributes

Learn about Application query attributes on *Investigate* page.

Review your options when using `application where`. Each attribute allows you to narrow your search criteria. As you use these attributes, the auto-suggestion feature shows the available expressions and the operators that are applicable for each attribute.

* `business.criticality`
+
Use the `business.criticality` attribute and enter a string value to find applications by the name of the defined criticality of the business.

*  `environment` 
+
Use the `environment` attribute enter a string value to find applications by the defined name environment.

*  `name` 
+
Use the `name` attribute and enter a string value to find specific applications. Note that the application names are not case sensitive.

*  `owner` 
+
Use the `owner` attribute and enter a string value to find all the applications associated with a specific business owner. 

*  `with.asset` 
+
Use the `with.asset`  attribute along with `Has Finding` or `Has Vulnerability` attributes to narrow down an application search and its impacted assets.

**  `finding`
+
Use the `finding` attribute to search an application based on xref:../prisma-cloud-findings.adoc[findings]. Findings are driven by security policies and inherit the attributes of the policy, such as name, severity, and description. Finding type is a set of findings with a specific security focus. You can select specific `finding.type` and `finding.name` to see the list of applications, its impacted assets, and findings.

** `vulnerability`
+
Use the `vulnerability` attribute to see the list of applications, their impacted assets, and vulnerabilities. Use the vulnerability attribute along with the following attributes:
+
***  `cve.id`
+
Use the `cve.id` attribute to search and show all the assets across your lifecycle impacted by this CVE ID.

*** `cvss.score`
+
The `cvss.score` attribute queries all the vulnerabilities with a CVSS score that you select.

*** `severity`
+
The `severity` attribute queries the vulnerabilities with the severity levels (Critical, High, Informational, Low, Medium) that you select.