== Pre-requisites and Supported Objects and Platforms

Make sure to fulfill the pre-requisites and verify the supported objects and platforms before you Satellite deployment.

=== Pre-requisites

Make sure to fulfill the following requirements in order to successfully install Satellite. 

*Connectivity* 

Satellite should have outgoing access to the following Prisma Cloud domains and subdomains:

* prismacloud.io 
* amazonaws.com 
* gcr.io 

If you have firewalls blocking the traffic, add the following values to their allow lists: 

* *.prismacloud.io 
* gcr.io 
* *.amazonaws.com

*Node*

At a minimum, Satellite requires a Kubernetes Node with 256MB RAM and 900mCPU. 

=== Supported Kubernetes Objects

Satellite ingests the following objects:

* Service
* Deployment
* Pod
* ReplicaSet
* StatefulSet
* DaemonSet
* NetworkPolicy
* Core DNS Logs


=== Supported Platforms

Satellite is supported on the following platforms and versions: 

[cols="50%a,50%a"]
|===
|*Platform*
|*Versions*

|AWS EKS
|1.25, 1.26, 1.27

|Azure AKS
|1.25, 1.26, 1.27

|Google Cloud GKE
|1.25, 1.26, 1.27

|===