== Unrobust cryptographic keys

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 81cc0536-af53-4e7c-bee0-40a618a1cc3d

|Checkov ID 
|CKV3_SAST_197

|Severity
|MEDIUM

|Subtype
|Build

|Language
|JavaScript, TypeScript

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021-Cryptographic Failures]

|=== 

=== Description

This policy detects whether cryptographic keys generated using the Node.js crypto module are not robust, particularly for RSA, DSA, and EC algorithms. Insufficient key lengths or risky named curves in these algorithms can compromise data security by making encrypted data vulnerable to decryption attacks.

In this example, an RSA key pair is generated with a modulus length of 1024 bits, which is considered weak by modern cryptographic standards. Additionally, using insecure named curves in Elliptic Curve Cryptography (ECC) can also introduce vulnerabilities.

[source,JavaScript]
----
const crypto = require('crypto');
const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 1024,
});
----


=== Fix - Buildtime

Ensure that cryptographic keys are generated with sufficient strength. Use keys with at least 2048-bit modulus length for RSA. When using ECC, select secure named curves.

In this example, the RSA key pair is generated with a modulus length of 2048 bits, improving its resistance to decryption attacks.

[source,JavaScript]
----
const crypto = require('crypto');
const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
});
----

In this example an ECC key pair is generated using a secure named curve, ensuring robust cryptographic security.

[source,JavaScript]
----
const crypto = require('crypto');
const { publicKey, privateKey } = crypto.generateKeyPair('ec', {
  namedCurve: 'prime256v1',
});
----

