
== Ensure no sensitive data is being logged

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
|CKV3_SAST_183

|Severity
|LOW

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/532.html[CWE-532: Insertion of Sensitive Information into Log File]

|OWASP Categories
|https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/[A09:2021-Security Logging and Monitoring Failures]

|=== 


=== Description

This policy is designed to detect instances where sensitive data, such as credit card numbers and personal details, are being logged. In AWS development using JavaScript, it focuses on situations where secret parameters are created with the AWS Secrets Manager or when environment variables containing potentially sensitive information (e.g., a password, key or secret) are being logged to the console.

Vulnerable code example:

[source, javascript]
----
const AWS = require('aws-sdk');
const secretsManager = new AWS.SecretsManager();
secretsManager.getSecretValue({SecretId: 'my_secret_key'}, function(err, data) {
    console.log(data.SecretString);
});
----
This code is considered vulnerable as it's logging sensitive data to the console. This can lead to information exposure if the logs are not properly managed and secured.

=== Fix - Buildtime

To fix the issue, avoid logging sensitive data to the console. If the value needs to be checked, it should be done in a secure manner without exposing the sensitive data.

Secure code example:

[source, javascript]
----
const AWS = require('aws-sdk');
const secretsManager = new AWS.SecretsManager();
secretsManager.getSecretValue({SecretId: 'my_secret_key'}, function(err, data) {
    if (err) {
        console.log(err);
    }
    // Do something secure with data.SecretString, but don't log it.
});
----
In this fixed version of the code, error is logged to console instead of the actual secret data. This way, the secret data never gets exposed in the logs.
