== Unsafe DOM updates lead to cross-site scripting (XSS) risks

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9743b4fb-4e52-484e-bc51-e8700e9f99aa

|Checkov ID 
|CKV3_SAST_196

|Severity
|HIGH

|Subtype
|Build

|Language
|JavaScript, TypeScript

|CWEs
|https://cwe.mitre.org/data/definitions/79.html[CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')]

|OWASP Categories
|https://owasp.org/Top10/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This policy detects whether JavaScript and TypeScript applications perform unsafe DOM updates that can introduce Cross-Site Scripting (XSS) vulnerabilities. XSS vulnerabilities occur when untrusted data is written to the DOM without proper validation or sanitization, allowing attackers to inject malicious scripts.

In this example, user input from document.location.search is directly written to the DOM using document.write and innerHTML without any validation or sanitization. This exposes the application to XSS attacks, potentially allowing attackers to inject malicious scripts through user input.

[source,JavaScript]
----
const userInput = document.location.search;
document.write(userInput);
document.getElementById('output').innerHTML = userInput;
----


=== Fix - Buildtime

To fix this issue, ensure that user input is not directly sent to `document.write` and `innerHTML`.  Instead, use safe DOM manipulation methods like `textContent` or `createTextNode` to update the DOM with user input.

In this example, user input is sanitized using DOMPurify before being written to the DOM. This ensures that any potentially harmful scripts are removed from the user input, mitigating the risk of XSS attacks.

[source,JavaScript]
----
const userInput = document.location.search;

// Use safe DOM manipulation methods
const outputElement = document.getElementById('output');
if (outputElement) {
    outputElement.textContent = userInput;
}
----
