
== Sensitive data logging

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a636d134-db6a-4abd-b27b-11580a94d5e1

|Checkov ID 
|CKV3_SAST_183

|Severity
|LOW

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/532.html[CWE-532: Insertion of Sensitive Information into Log File]

|OWASP Categories
|https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/[A09:2021-Security Logging and Monitoring Failures]

|=== 


=== Description

This policy detects whether sensitive information, such as credit card numbers and personal details, is being logged. In AWS development with JavaScript, it targets scenarios where secret parameters are generated using the AWS Secrets Manager or where environment variables containing potentially sensitive data (e.g., passwords, keys, or secrets) are logged to the console.


Vulnerable code example:

[source, javascript]
----
const AWS = require('aws-sdk');
const secretsManager = new AWS.SecretsManager();
secretsManager.getSecretValue({SecretId: 'my_secret_key'}, function(err, data) {
    console.log(data.SecretString);
});
----

In this example, the code is considered vulnerable as it logs sensitive data to the console. This could potentially result in information exposure if the logs are not adequately managed and secured.


=== Fix - Buildtime

To fix this issue, avoid logging sensitive data to the console. If the value requires verification, ensure it is handled securely without exposing the sensitive information.


Secure code example:

[source, javascript]
----
const AWS = require('aws-sdk');
const secretsManager = new AWS.SecretsManager();
secretsManager.getSecretValue({SecretId: 'my_secret_key'}, function(err, data) {
    if (err) {
        console.log(err);
    }
    // Do something secure with data.SecretString, but don't log it.
});
----

In this example, errors, and not the actual sensitive data, are logged to the console. This prevents the exposure of sensitive information in the logs.
