== Excessive user permissions to a GitLab project

=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_CICD_95
|Category |Identity & Access Management
|Provider |
|Severity |HIGH
|Mapped CSPM/KSPM Rule |None
|===
 


=== Impact
A user with **write** permissions (‘developer’ role) to a project who has not performed any actions requiring write permissions for more than 90 days, may not require these permissions. This poses a threat, as attackers who gain control of a user account can access the project which the user potentially should not have write permissions to (as they are not active in the project), thereby enlarging the surface of the attack.



=== Recommended Solution - Buildtime

Consider reducing permissions to the necessary minimum:

* Modify user permissions from **write** to **read** OR:

* Remove user permissions entirely if the user does not require access to the repository

For more information about managing access to repositories refer to https://docs.gitlab.com/ee/user/permissions.html.

