== Alibaba Cloud KMS Key is disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9b1cdf52-7013-4642-9c48-4427b8247fa0

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/KMSKeyIsEnabled.py[CKV_ALI_28]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

This policy ensures that Alibaba Cloud KMS (Key Management Service) keys are enabled. Enabling KMS keys ensures they are active and can be used for cryptographic operations such as data encryption and decryption. Disabled keys cannot perform these operations, which may cause disruptions in applications relying on the keys.

Keeping KMS keys enabled ensures they remain operational and available for secure data handling processes.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_kms_key
* *Arguments:* status

To mitigate this issue, ensure the `status` attribute in the `alicloud_kms_key` resource is set to `Enabled`.

Example:

[source,go]
----
resource "alicloud_kms_key" "example" {
  ...
+  status = "Enabled"
}
----
