== Alibaba Cloud MongoDB does not have transparent data encryption enabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5a432551-8705-4aa2-b9fc-7f541e56669a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/MongoDBTransparentDataEncryptionEnabled.py[CKV_ALI_44]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

Transparent Data Encryption (TDE) for your Alibaba Cloud MongoDB instance helps safeguard your data from unauthorized access or tampering. TDE encrypts data as it is written to disk and transparently decrypts it when accessed. By enabling TDE, you ensure that only authorized users with the correct keys can access and decrypt the data, providing robust protection for data at rest.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_mongodb_instance
* *Arguments:* tde_status

To mitigate this issue, ensure the `tde_status` attribute in the `alicloud_mongodb_instance` resource is set to `enabled`.

Example:

[source,go]
----
resource "alicloud_mongodb_instance" "example" {
  ...
+  tde_status = "enabled"
}
----
