:toc: macro
== 32.07 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|//TODO: 32.06.113
|Code name
|O'Neal - Update 7, 32.07

|Release date
|//TODO: July 21st, 2024

|Type
|Maintenance Release

|//TODO: SHA-256
|//TODO: 540772e5de63f9d70d428152254a1d7de5417325e435d18a2b157295eefd6897

|===

Review the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtime, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

//[LINK]

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defender Versions

With the v32.xx release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported (n, n-1, and n-2) Defender versions] are v32.xx, v31.xx, and v30.xx. Defender versions below v30.xx such as v22.12 cannot connect to the current version.

//To prepare for this update, upgrade your Defenders from version `v22.06` (Kepler) or earlier to a later version.

==== Upcoming Defender Obsolescence

With the upcoming v33.00 release, release v30.xx defenders will be obsolete. To prepare for this upcoming update, plan to upgrade defenders to release v31.xx or later.

[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the v32.xx release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported (n, n-1, and n-2) Console versions] are v32.xx, v31.xx, and v30.xx.  For example: for the current (n) major release v32.xx, the supported n-1 and n-2 versions are v31.xx and v30.xx respectively.

You can upgrade the Prisma Cloud Console from a major release to the next major release, but not to a major release that follows the next. So, to upgrade from the v30.xx release to the v32.xx release, you will have to first upgrade to v31.xx and then upgrade to the v32.xx release.


[#announcement]
=== Announcement

[cols="1,1", options="header"]
|===
|FEATURE
|DESCRIPTION

|*Enhancement to Photon OS and Amazon Linux OS Feeds*
//TODO: ADD JIRA tickets
|Prisma Cloud now parses Photon OS and Amazon Linux OS feeds using CVE IDs as the primary vulnerability identifier instead of advisory IDs. This change enhances Prisma Cloud’s ability to correlate third-party data, and use vendor-provided information, including backports, severity assessments, and vulnerability scores.

|*Support for Azure Container Registry and VM image scanning*
//TODO: ADD JIRA tickets
|Prisma Cloud now supports scanning Azure Container Registry (ACR) and Virtual Machine (VM) images for Azure cloud accounts that are onboarded directly through the platform.
|===


[#enhancements]
=== Enhancements
[cols="1,1", options="header"]
|===
|FEATURE
|DESCRIPTION



|===

[#rest-api-changes]
=== API Changes and New APIs
[cols="1,1", options="header"]

|===
|FEATURE
|DESCRIPTION


|===

[#addressed-issues]
=== Addressed Issues
// [cols="1,1", options="header"]
There are no Addressed Issues for this release.


// [#backward-compatibility]
=== Backward Compatibility for New Features
There is no backward compatibility for new features in this release.

// [#change-in-behavior]
=== Change in Behavior
There are no changes in behavior for this release.

// ==== Breaking fixes compare with SaaS RN

// [#end-of-support]
=== End of Support Notifications
There are no End of Support notifications for this release.

// [#deprecation-notices]
=== Deprecation Notices
There are no Deprecation Notices for this release.
