:toc: macro
== 31.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|32.00.159

|Code name
|O'Neal

|Release date
|December 3, 2023

|Type
|Major release

|SHA-256
|39d1f808550f7491dcc63e392b5eb55e8f9068494b4f49c07c71da17433f7396
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/31/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

//LINK

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defender Versions 22.06 and Earlier

With the 32.00.xxx release, https://docs.paloaltonetworks.com/prisma/prisma-cloud/31/prisma-cloud-compute-edition-admin/welcome/support_lifecycle[Defender versions supported (n, n-1, and n-2)] are v32.xx.xxx, v31.xx.xxx, and v30.xx.xxx.

To prepare for this update, you must upgrade your Defenders from version v22.06.xx.xxx (Kepler) or earlier to a later version.
Failure to upgrade Defenders will result in disconnection of any Defender version below 22.12 such as 22.06.

[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the 31.00.xxx release, the https://docs.paloaltonetworks.com/prisma/prisma-cloud/31/prisma-cloud-compute-edition-admin/welcome/support_lifecycle[supported Console versions (n, n-1, and n-2)] are v32.xx.xxx, v31.xx.xxx, and v30.xx.xxx.

You can upgrade the Prisma Cloud console directly from any version for n-1  to n.
With 30.xx as n-1 and 31.xx as n, you can for example go directly from 30.01.153 to 31.00.129.

You have to upgrade any version of 22.xx.xxx to 30.xx before upgrading to 31.xx.
For example, you can upgrade from 22.12.693 to 30.02.123 and then upgrade to 31.00.129.

//[#cve-coverage-update]
//=== CVE Coverage Update

[#enhancements]
=== Enhancements



// [#new-features-agentless-security]
// === New Features in Agentless Security

// [#new-features-core]
// === New Features in Core

// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS

[#api-changes]
=== API Changes and New APIs


[#addressed-issues]
=== Addressed Issues

[#end-of-support]
=== End of Support Notifications


[#deprecation-notices]
=== Deprecation Notices
