:toc: macro
== 32.04 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|32.04.TBD
|Code name
|O'Neal - Update 4, 32.04

|Release date
|March 24th, 2024

|Type
|Maintenance Release

|SHA-256
|TBD

|===

Review the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/install/system-requirements[system requirements] to learn about the supported operating systems, hypervisors, runtime, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

// LINK

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defender Versions 22.06 and Earlier

With the `v32.00` release, https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[Defender versions supported (n, n-1, and n-2)] are `v32.00`, `v31.00`, and `v30.00`.

To prepare for this update, you must upgrade your Defenders from version `v22.06` (Kepler) or earlier to a later version.
Failure to upgrade Defenders will result in disconnection of any Defender version below `v22.12` such as `v22.06`.

//
==== Upcoming Defender Obsolescence

With the upcoming `v33.00` release, release `v30.xx` defenders will be obsolete. To prepare for this coming update, plan for upgrading to release `v31.xx` or later at the earliest. 

[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the `v32.00` release, the https://docs.prismacloud.io/en/compute-edition/32/admin-guide/upgrade/support-lifecycle[supported Console versions (n, n-1, and n-2)] are `v32.00`, `v31.00`, and `v30.00`.

You can upgrade the Prisma Cloud console directly from any version for n-1 to n.
With `v30.00` as n-1 and `v31.00` as n, you can for example go directly from `v30.01.153` to `v31.00.129`.

You have to upgrade any version of `v22.00` to `v30.00` before upgrading to `v31.00`.
For example, you can upgrade from `v22.12.693` to `v30.02.123` and then upgrade to `v32.00.159`.

// [#cve-coverage-update]
// === CVE Coverage Update

[#enhancements]
=== Enhancements
[cols="40%a,60%a"]
|===

|FEATURE
|DESCRIPTION

|===

[#api-changes]
=== API Changes and New APIs
[cols="40%a,60%a"]
|===


|===

// [#new-features-core]
// === New Features in Core


// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS


// [#breaking-api-changes]
// === Breaking Changes in API
// [cols="30%a,70%a"]


// [#end-of-support]
// === End of Support Notifications


[#addressed-issues]
=== Addressed Issues
[cols="40%a,60%a"]
|===


// [#backward-compatibility]
// === Backward Compatibility for New Features

// [#change-in-behavior]
// === Change in Behavior

// ==== Breaking fixes compare with SaaS RN
