== Non Permissive License Policies

=== Policy Details

[cols="1,1"]
|===

|Prisma Cloud ID 
|a0dea5f8-51ba-44be-b82d-597cd9bc7a89 
|Checkov ID
|BC_LIC_5
|Severity
|High
|Policy type
|Config
|Subtype
|Build
|===

=== Description

Non Permissive licenses policies identify software packages distributed under non-permissive or restrictive licenses. These licenses restrict how you can use, modify, and distribute the software. They might limit your ability to integrate the software into certain projects or require you to purchase a commercial license for specific uses.

=== SPDX Identifiers

The following table lists SPDX identifiers falling under the Non Permissive licenses policy category.

[cols="1,1,1,1"]
|===

|BUSL-1.1
|C-UDA-1.0
|CC-BY-NC-3.0-DE
|CC-BY-NC-ND-3.0-DE

|CC-BY-NC-ND-3.0-IGO
|CC-BY-NC-SA-2.0-DE
|CC-BY-NC-SA-2.0-FR
|CC-BY-NC-SA-2.0-UK

|CC-BY-NC-SA-3.0-DE
|CC-BY-NC-SA-3.0-IGO
|CC-BY-ND-3.0-DE
|Hippocratic-2.1

|JPL-image
|MS-LPL
|NCGL-UK-2.0
|PolyForm-Noncommercial-1.0.0

|PolyForm-Small-Business-1.0.0
|SSPL-1.0
|
|

|===
