== Strong Copyleft License Policies

=== Policy Details

[cols="1,1"]
|===

|Prisma Cloud ID 
|3112fbce-cc30-4d03-a5b2-22f84953a80f 
|Checkov ID
|BC_LIC_4
|Severity
|High
|Policy type
|Config
|Subtype
|Build
|===

=== Description

Strong Copyleft licenses policies identify software packages distributed under strong copyleft licenses, such as the GNU General Public License (GPL). These licenses require derivative works to be distributed under the same copyleft license terms as the original work. This ensures broader access and modification rights.

=== SPDX Identifiers

SPDX Identifiers are unique codes assigned to software licenses by the Software Package Data Exchange (SPDX) project. In the context of Strong Copyleft License Policies, SPDX Identifiers are used to categorize and identify software packages distributed under strong copyleft licenses. These identifiers help in precisely identifying the licenses associated with the policies.

The following table lists SPDX identifiers falling under the Strong Copyleft Licenses Policies category.

[cols="1,1,1"]
|===
| AGPL-1.0 | AGPL-1.0-only | AGPL-1.0-or-later
| AGPL-2.0 | AGPL-3.0 | AGPL-3.0-only
| AGPL-3.0-or-later | Arphic-1999 | CERN-OHL-S-2.0
| copyleft-next-0.3.0 | copyleft-next-0.3.1 | GPL-2.0
| GPL-3.0 | Linux-man-pages-copyleft | OpenPBS-2.3
|===