== Weak Copyleft License Policies

=== Policy Details

[cols="1,1"]
|===

|Prisma Cloud ID 
|ee2b753a-0c21-4c09-befa-4b6d6f48a4af 
|Checkov ID
|BC_LIC_3
|Severity
|Medium
|Policy type
|Config
|Subtype
|Build
|===

=== Description

Weak Copyleft Licenses policies identify software packages distributed under weak copyleft licenses. These licenses permit combining code with other licenses, including proprietary licenses, without mandating the entire derivative work to be released under the same copyleft license.

=== SPDX Identifiers

SPDX Identifiers are unique codes assigned to software licenses by the Software Package Data Exchange (SPDX) project. In the context of Weak Copyleft License Policies, SPDX Identifiers are used to categorize and identify software packages distributed under weak copyleft licenses. These identifiers help in precisely identifying the licenses associated with the policies.

The following table lists SPDX identifiers falling under the Weak Copyleft Licenses Policies category.

[cols="1,1,1"]
|===
| Artistic-1.0 | Artistic-2.0 | APSL
| CAL-1.0-Combined-Work-Exception | CC-BY-SA-2.0-UK | CC-BY-SA-2.1-JP
| CC-BY-SA-3.0-AT | CC-BY-SA-3.0-DE | CC-BY-SA-4.0
| CDDL-1.0 | CDLA-Sharing-1.0 | CERN-OHL-W-2.0
| CPOL-1.02 | EPL-1.0 | EPL-2.0
| eCos-2.0 | EUPL-3.0 | FDK-AAC
| LGPL-2.0 | LGPL-2.1 | LGPL-3.0
| MPL-1.1 | MPL-2.0 | MS-RL
| OSL-3.0 | QPL-1.0-INRIA-2004 | Sendmail-8.23
| SimPL-2.0 | TAPR-OHL-1.0 | TPL-1.0
| UCL-1.0 | wxWindows 
|=== 