== Azure storage account has a blob container with public access
// Ensure that Storage blobs restrict public access.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7a506ab4-d0a2-48ee-a6f5-75a97f11397d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/StorageBlobRestrictPublicAccess.py[CKV_AZURE_190]

|Severity
|HIGH

|Subtype
|Run,Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Storage Blobs are used for storing vast amounts of unstructured object data, such as text or binary data. Restricting public access to these blobs is critical to ensure data confidentiality and to prevent unauthorized access. This policy ensures that the public access to Azure Storage Blobs is restricted.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_storage_account 

*Arguments:* 
- allow_nested_items_to_be_public

In this example, `allow_nested_items_to_be_public` is set to `false` to prevent nested items from becoming public.

[source,terraform]
----
resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  # ... other configurations ...

+ allow_nested_items_to_be_public = false

  # ... other configurations ...
}
----
