== Azure Machine learning workspace is not configured with private endpoint


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| a8e6f787-f937-42eb-9f71-ffc4cb17ba8a

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/arm/checks/resource/AzureMLWorkspacePrivateEndpoint.py[CKV_AZURE_239]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|ARM,Bicep

|===

=== Description

This policy detects whether an Azure Machine Learning workspace is configured with a private endpoint. Configuring a private endpoint for the Azure Machine Learning workspace is recommended to enhance security by restricting network access and preventing public internet access to the workspace.

=== Fix - Buildtime

*ARM*

* *Resource:* Microsoft.MachineLearningServices/workspaces
* *Arguments:* managedNetwork.outboundRules

Configure the Azure Machine Learning workspace to use a private endpoint. To achieve this, add an outboundRule with the type set to PrivateEndpoint. This effectively directs traffic to the workspace solely through the secure private network connection.

[source,json]
----
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
      {
        "type": "Microsoft.MachineLearningServices/workspaces",
        "apiVersion": "2022-12-01",
        "name": "fail1",
        "location": "West US",
        "properties": {
          "managedNetwork": {
            "outboundRules": {
                "rule1": {
+                    "type": "PrivateEndpoint"
                }
            }
          }
        }
      }
    ]
  }
----
