== The Transparent Data Encryption (TDE) for Azure SQL database is enabled

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/AzureSqlDbEnableTransparentDataEncryption.yaml[CKV2_AZURE_25]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to make sure that Transparent Data Encryption (TDE) is enabled for Azure SQL databases. TDE is a security feature that provides real-time encryption and decryption of data and log files to protect information at rest. If TDE is not enabled, the data stored in the Azure SQL Database could be at risk for unauthorized access or data breaches. Therefore, enabling TDE helps in maintaining the confidentiality and integrity of the data by ensuring that it can only be accessed, read or modified by authorized entities.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_mssql_database
* *Arguments:* transparent_data_encryption_enabled

To fix the issue of Transparent Data Encryption (TDE) not being enabled on your Azure SQL database, you just need to set the argument `transparent_data_encryption` to `enabled` in your Terraform script. 

Secure code example:

[source,go]
----
resource "azurerm_mssql_database" "tde" {
  ...
  transparent_data_encryption_enabled = true
  ...
}
----

The above Terraform code is secure based on the policy because it enables Transparent Data Encryption on the database by setting `transparent_data_encryption_enabled` to `true`. This means data stored on the SQL server will be automatically encrypted, helping to protect against the threat of malicious activity, ensuring data privacy, and meeting regulatory compliance.

