== AWS S3 Bucket BlockPublicPolicy is not set to True


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 93d2336f-0c9c-448e-b18e-bc7122cbf8a0

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/S3BlockPublicPolicy.py[CKV_AWS_54]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


This policy ensures that Amazon S3 buckets have the `block public policy` setting enabled. Enabling this setting ensures that public bucket policies cannot be set, which helps prevent unauthorized access to the data stored in the S3 bucket. This policy checks whether the `BlockPublicPolicy` option is enabled in the `PublicAccessBlockConfiguration` of S3 buckets.


=== Fix - Buildtime


*Terraform* 


To fix this issue, ensure that the `block_public_policy` property in the `aws_s3_bucket_public_access_block` resource is set to `true`.


[source,go]
----
resource "aws_s3_bucket_public_access_block" "artifacts" {
  ...
+ block_public_policy = true
}
----


*CloudFormation*

To fix this issue, ensure that the `BlockPublicPolicy` property in the `PublicAccessBlockConfiguration` of the `AWS::S3::Bucket` resource is set to `true`.

Example:

[source,yaml]
----
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: example-bucket
      PublicAccessBlockConfiguration:
+        BlockPublicPolicy: true
        ...
----
