== Alibaba Cloud RDS instance has log_disconnections disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 70df95e5-51d6-4a46-9966-a0ea302ab91c

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RDSInstanceLogDisconnections.py[CKV_ALI_36]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

This policy ensures that the `log_disconnections` parameter is enabled for Alibaba Cloud RDS instances. Enabling this parameter helps log disconnection events, which can be useful for monitoring, troubleshooting, and auditing purposes. Capturing these logs provides insights into connection behaviors and can help detect anomalies or potential issues with database connections.

Disabling this parameter may result in a lack of visibility into disconnection events, potentially hindering diagnostic and monitoring efforts.

=== Fix - Buildtime


*Terraform* 

* *Resource:* alicloud_rds_instance
* *Arguments:* log_disconnections

To mitigate this issue, ensure the `log_disconnections` parameter is set to `on` in the RDS instance configuration.

Example:

[source,go]
----
resource "alicloud_rds_instance" "example" {
  ...
  parameter {
+    name  = "log_disconnections"
+    value = "on"
  }
}
----
