== Welcome to Prisma Cloud Multitenant Management 

The Prisma Cloud® Multitenant Management offering provides the Prisma Cloud Multitenant Management console, a single centralized dashboard, that is used to manage a potentially large number of Prisma Cloud tenants. Use the quick links below to learn more about MSSP. Prisma Cloud tenants that are managed by the Prisma Cloud Multitenant Management console, are referred to as managed Prisma Cloud tenants. 



=== Multitenant Management at a Glance

[cols="60%a,30%a"]
|===

|*What do you want to do?*
|*Start here*

|Learn more about Multitenant Management
|xref:multitenant-management-introduction.adoc[Multitenant Management Overview]

|Create Tenants
|xref:create-and-manage-tenants.adoc[Create and Manage Tenants]

|Create Policy Groups
|xref:create-and-manage-policy-groups.adoc[Create and Manage Policy Groups]

|===


=== Rights and Use Restrictions

Customers may elect to utilize the Prisma Cloud Enterprise Multitenant Management console to manage the Credits it has licensed under an applicable quote or order form by providing Palo Alto Networks with a written request and executing an Opt-In Letter provided to the Customer by Palo Alto Networks. The Product, including the Console, shall not be used for any other purposes, including without limitation providing managed security services to any third party, as set forth under the applicable Agreement Use Restrictions. Additionally, Credits may not be consolidated, shifted, assigned to, transferred, swapped, or the like between multiple entities (i.e. if Customer purchases Credits on behalf of a subsidiary or Affiliated entity and in compliance with the applicable Agreement Affiliate terms and Use Restrictions, such Credits may not be consolidated, shifted, assigned to, transferred, swapped or used by any other subsidiary or Affiliated entity throughout the term).