== Prisma Cloud Multitenant Management 

The Prisma Cloud® Multitenant Management offering provides the Prisma Cloud Multitenant Management console, a single centralized dashboard, that is intended for use by an *MSSP (Managed Security Service Provider) or an end customer* to manage a potentially large number of Prisma Cloud tenants. 

See <<rights>> for more information on constraints and limitations.

=== Multitenant Management at a Glance

[cols="60%a,30%a"]
|===

|*What do you want to do?*
|*Start here*

|Learn more about Multitenant Management
|xref:multitenant-management-introduction.adoc[Multitenant Management Overview]

|Create Tenants
|xref:create-and-manage-tenants.adoc[Create and Manage Tenants]

|Create Policy Groups
|xref:create-and-manage-policy-groups.adoc[Create and Manage Policy Groups]

|Configure SSO for User Onboarding
|xref:multitenant-management-sso.adoc[Configure Users]

|===

[#rights]
=== Rights and Use Restrictions

*End User Customer*

A Customer may elect to utilize the Prisma Cloud Enterprise Multitenant Management Console feature (“Console”) as a standard end user in order to manage the Credits licensed under an applicable quote or order form by providing Palo Alto Networks with a written request and executing the Opt-In Letter provided by Palo Alto Networks. Such usage shall be subject to the End User License Agreement available on the Palo Alto Networks website, unless Customer and Palo Alto Networks have entered into a separate written agreement that specifically overrides such agreement (either "Agreement"). For such end user customer use-case, the Product, including the Console, shall not be used for any other purposes, including without limitation to provide managed security services to any third party, and as otherwise set forth under the applicable Agreement Use Restrictions. Additionally, Credits may not be consolidated, shifted, assigned to, transferred, swapped, or the like between multiple entities (i.e. if Customer purchases Credits on behalf of a subsidiary or Affiliated entity and in compliance with the applicable Agreement Affiliate terms and Use Restrictions, such Credits may not be consolidated, shifted, assigned to, transferred, swapped or used by any other subsidiary or Affiliated entity throughout the term).