
== Logging for Dialogflow CX webhooks is disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| d839d6a4-9ac2-4135-8af6-2fc6a339a9d8

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/gcp/GCPDialogFlowCxWebhookLoggingEnabled.yaml[CKV2_GCP_31]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to see if logging is enabled for Dialogflow CX webhooks. Dialogflow CX is a conversational AI platform that can be used to create virtual agents, IVR systems, and chatbots. Webhooks provide a way to deliver data to other applications, therefore logging for these webhooks is essential.

Not having logging enabled for Dialogflow CX webhooks could lead to several problems. For instance, without logging, it becomes extremely difficult to debug issues or understand the performance and usage patterns of your webhooks. Additionally, this may expose the system to security threats as potential malicious activities or breaches cannot be traced or understood. Therefore, enabling logging is an important best practice for monitoring and maintaining the security, performance and reliability of the system.

=== Fix - Buildtime

*Terraform*

* *Resource:* google_dialogflow_cx_webhook
* *Arguments:* enable_stackdriver_logging

To fix the issue, you should enable logging for Dialogflow CX webhooks in the Google Cloud Platform.

[source,go]
----
resource "google_dialogflow_cx_webhook" "default" {
  ...
  enable_stackdriver_logging = true
}
----

In the above secure Terraform code, `enable_stackdriver_logging` is set to `true`. This ensures that logging is enabled for Dialogflow CX webhooks, which helps in monitoring and debugging. Compliance with this policy will decrease the chance of data loss, unauthorized access, or downtime.

