== Logging is disabled for Dialogflow agents

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/gcp/GCPDialogFlowAgentLoggingEnabled.yaml[CKV2_GCP_29]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to ensure that logging is enabled for Dialogflow agents in the Google Cloud Platform (GCP). Dialogflow is a tool used to create conversational interfaces and chatbots. It's important to have logging enabled for this tool to monitor its activity and performance. If logging is not enabled, potential issues or abnormalities within the system might go undetected, making it harder to debug and troubleshoot problems. Additionally, the absence of logging hampers auditability, hence thwarting any efforts to uphold compliance with certain regulations that require logging and monitoring of activities.

=== Fix - Buildtime

*Terraform*

* *Resource:* google_dialogflow_agent
* *Arguments:* enable_logging

To fix this policy issue, you need to ensure that logging is enabled for Dialogflow agents. The attribute `enable_logging` must be set to `true` in the settings for your Dialogflow agents.

[source,hcl]
----
resource "google_dialogflow_agent" "default" {
  ...
  enable_logging = true
}
----

The above Terraform code is secure because it enables logging for the Dialogflow agent. This means that all interactions with the agent are logged and can be reviewed later on for debugging or auditing purposes. This is an important security requirement for monitoring and detecting potential issues or malicious activities.

