
== Vertex AI endpoint is public

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| 33fee74c-548e-4ff2-b36c-068a28002661

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/gcp/GCPVertexAIPrivateEndpoint.yaml[CKV2_GCP_33]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy is checking to make sure that the Vertex AI endpoint is private. This is important because if the endpoint is public, it could be easily accessible to anyone on the internet, increasing the risk of unauthorized access and potential data breaches. By ensuring that the endpoint is private, it helps in safeguarding sensitive data and mitigating potential security threats.

=== Fix - Buildtime

*Terraform*

* *Resource:* google_vertex_ai_endpoint
* *Arguments:* network

To fix this issue, make sure there is a network attached to your Vertex AI endpoint. This makes sure that the Vertex AI endpoint remains private and not exposed to public internet.

[source,go]
----
resource "google_vertex_ai_endpoint" "example" {
  ...
  network = google_service_networking_connection.private_vpc_connection.id
}
----

