== Vertex AI index endpoint is public

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
| TBD

|Checkov ID
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/gcp/GCPVertexAIPrivateIndexEndpoint.yaml[CKV2_GCP_34]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|===

=== Description

This policy evaluates whether the Vertex AI index endpoint is set to private in Google Cloud Platform. If it is not private, it means that the endpoint could be exposed to the public, potentially disclosing sensitive information and opening up avenues for undesired changes to be made. This could lead to security vulnerabilities, such as data breaches or unauthorized access. Thus, ensuring that the Vertex AI index endpoint is private enhances the security of the system.

=== Fix - Buildtime

*Terraform*

* *Resource:* google_vertex_ai_index_endpoint
* *Arguments:* public_endpoint_enabled

To fix this issue, set `public_endpoint_enabled` to `false` or do not include this parameter.

[source,hcl]
----
resource "google_vertex_ai_index_endpoint" "default" {
  ...
-  public_endpoint_enabled = true
}
----

