== Create and Manage Tenants
 

Tenant Groups in MSSP are logical groupings of multiple managed Prisma Cloud tenants. Administer multiple tenants with ease by creating tenant groups and mapping individual tenants to them. Additionally, Policy groups can be mapped to tenant groups in order to apply the constituent policies of the policy group on to the individual tenants. 

Follow the steps below to create a Tenant Group:

. On the MSSP console, select the *Tenant Groups* tab. 

. Select *Create Tenant Group* and provide a name for the group. 

. Click *Save* to complete tenant group creation. 

=== Create Tenant 

You can also create a (managed) Prisma Cloud tenantfrom the Tenant Group dashboard. Follow the steps below to create a Tenant:

[NOTE]
====
When creating a tenant, the details pertaining to the user should be those of the end customer who will be the “owner” of the tenant. The email address specified will be used to send a Welcome email message to the user with instructions pertaining to account creation and use of the MSSP console. 
====

. Click on the *Tenant Groups* tab. 

. Select the on the *Create Tenant* button. 

. Provide Tenant details as shown below.

.. In the First Name, Last Name and email address fields, provide details pertaining to the individual who will be System Administrator on the tenant.  This user will receive a welcome email from Prisma Cloud in order to manage and administer the Prisma Cloud tenant. MSSP admin users, mapped as System Administrators on the managed Prisma Cloud tenants cannot be deleted by an Admin on managed Prisma Cloud tenants. 

.. In the Company Name field, provide the name of the company or organization the Tenant is provisioned for. 

.. Optionally assign the tenant to a *Tenant Group*. 
+
[NOTE]
====
Policy Groups can only be assigned to tenant groups. Therefore, if you know which tenant group this tenant should belong to, we recommend completing this step at this time. A tenant can alternatively be assigned to a group at a later time as well. Policies mapped from the MSSP Console are immutable on the managed Prisma Cloud tenants. 
====

. Provide the *License Configuration* details. 

.. Select a *License Pool*. 

.. Input the total number of credits to allocate to the tenant. 
+
[NOTE]
====
A minimum of 100 credits needs to be allocated to a tenant and the total number of credits cannot exceed the amount that is allocatable to the tenant. 
====

.. Select a *Plan Type* to assign to the Tenant. 

.. On the *Capabilities* tab select the Default and Optional Modules you would like to enable on the tenant. Click *Next* to continue. 

. Review the summary and click *Save* to create the tenant. 


=== Tenant Deletion and Credit Reallocation 

Credits can be reallocated from one tenant to another tenant or tenants at any time. Follow the steps below to edit an existing tenant and reduce the number of credits allocated to them:

[NOTE] 
====
A tenant MUST have a minimum of 100 credits allocated at all times while the tenant is active.
====

. Navigate to the *Tenant Groups* dashboard and select any tenant that you wish to remove or reduce credits from.
. Select the pencil icon to launch the *Edit Tenant* view. 
. Select *License Configuration* from the left navigation menu.
. Update the *Allocated Credits* field to the appropriate credit value.

Once the credits are reduced from a tenant, these credits are placed back into the *Credits available for allocation*  quantity. Users on the MSSP console can now leverage these credits, in addition to any credits which previously existed on the *Credits available for allocation* quantity to create a new tenant and allocated credits or edit existing tenants to increase credits allocated to the tenant. 

==== Tenant Deletion 

Keep the following caveats in mind when deleting tenants:

* Credits will remain allocated to a deleted tenant for a period of 120 days. After 120 days, the credits are available in the *Credits that are allocatable* pool from which they can be applied to other tenants. 

* When a tenant is deleted, reduce the credits associated with the tenant to 100 (which is the minimum) and then delete a tenant, for efficient credit management. This ensures that these credits are immediately available in the *Total Purchased* quantity, available for allocation.  




