== Prisma Cloud Managed Security Service Provider


Effectively deliver security at scale with Prisma Cloud®'s Managed Security Service Provider (MSSP) service. MSSP offers a  rich set of features that provides a centralized dashboard for the efficient management of a large number of tenants. 

With the MSSP console you can streamline the following functions: 

* Manage and operate a large number of tenants from a single console.
* Dynamically create and delete tenants on demand.
* Efficiently segment and manage customers into industry defined groups such as Healthcare, Finance, and more.
* Segment tenants by reallocating credits as needed, between tenants under management.
* Isolate customer data in adherence with established security best practices.
* Get centralized visibility into security telemetry such as incidents, attack paths and misconfigurations.
* Create policy groups from a set of out of the box policies and custom policies. Policy groups can be mapped to tenant groups from the MSSP console. 
* Module management — selective enablement of optional modules during tenant creation. 
* Visibility into credit usage across all Prisma Cloud tenants under management.


=== MSSP Console Features 

The MSSP console features three key dashboards that help you streamline the creation and management for tenants, policies and their related operations. The image below provides an overview of the three available dashboards:

*Operation Alerts* 

On the MSSP console you can select the bell icon to view *Operation Alerts* for the status of all actions that are performed by a user on the MSSP console. The following operations are displayed on the alarm center: 

* Operation Name
* Operation Description 
* Mapping Policy
* When a user ‘maps’ a policy group to a tenant group.
* Unmapping Policy 
* When a user ‘unmaps’ a policy group from a tenant group.
* User Creation 
* Creation of user on the MSSP console 
* Tenant Provisioning 
* When a user creates a tenant 
* Tenant Update
* When a user updates a tenant (ex. Tenant group change, credit change, etc)


Failed user initiated operations are listed as an entry on the *Operation Alerts* page. Additionally, users have the option to retry the failed operation. Click on the retry button available on the listing of each failed operation to retry a previous attempt. 


*Licensing Dashboard*

Select *MSSP console > Licensing* to view details about credit purchased/allocated and the tenants groups that they are allocated to as shown below.

[NOTE]
====
You may experience an issue on the licensing dashboard, where there is a mismatch between the credits reported on a tenant group and the credits reported on the dashboard, when a tenant fails to create successfully.

To resolve this issue, retry the failed tenant create operation from the *Operations Alerts* panel. Alternatively, create a new tenant from the Tenant creation workflow. 

This is a benign issue and only impacts the credits reported for the tenant on the tenant group on the licensing dashboard. It does not impact the accurate reporting of the credits purchased quantity, the credits allocated quantity or the balance.
====

=== Key Concepts 

Reference the table below to clarify your understanding of MSSP concepts and terminology.

[cols="50%a,50%a"]
|===

|Term
|Definition

|MSSP Console
|A centeralized dashboard that allows yous to manage and operate multiple Prisma Cloud Tenants (referred to as Managed Prisma Cloud Tenants in MSSP).

|Managed Prisma Cloud Tenant
|A tenant managed by the MSSP console.

|Prisma Cloud Tenant for Policy Creation (aka Synthetic Tenant) 
|A tenant used to create custom policies and testing out RQL queries. This is a limited capability tenant with other capabilities disabled. 

|Tenant Groups
|A logical grouping of managed Prisma Cloud tenants.

|Policy Groups
|A logical grouping of either out of the box Prisma Cloud policies or custom Prisma Cloud policies (that maps to Tenant groups). 

|User 
|An entity on the MSSP console that provides the subject access to the MSSP console. +
`NOTE:` All users created on the Prisma Cloud MSSP console are MSSP admins on the console. Users created on the console are replicated and created as an Admin on all Prisma Cloud managed tenants. 

|Policy Groups Mapping (to Tenant Group Mapping)
|Process of mapping policies in a policy group to the tenants of the selected tenant group.

|Licensing
|Reporting framework for Prisma Cloud tenant credit usage.

|===

Reference the table below to learn more about the functions that the MSSP *System Administrator* role can perform on the MSSP console.

[cols="50%a,40%a"]
|===


|Function
|Permission Status

|Create Tenant
|Allowed

|Create Tenant Group
|Allowed

|Create Policy 
|Allowed

|Create Policy Group 
|Allowed

|Map Policy Group to Tenant Group
|Allowed

|View Tenants Groups 
|Allowed

|View Policies and Policy Groups
|Allowed

|View Licensing
|Allowed

|Seamless login into Managed Prisma Cloud Tenant
|Allowed

|Prisma Cloud Tenant Operations (Managed Prisma Cloud Tenant)
|System Admin Privileges


|===

