== Heroku Platform Key detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_48
|Category |Cloud & Infrastructure
|Provider |
|Severity |LOW
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


Heroku is a cloud platform as a service (PaaS) supporting several programming languages.
The Heroku network runs the customer's apps in virtual containers which execute on a reliable runtime environment.
Heroku calls these containers "Dynos".
These Dynos can run code written in Node, Ruby, PHP, Go, Scala, Python, Java, or Clojure.
Heroku also provides custom buildpacks with which the developer can deploy apps in any other language.
Heroku lets the developer scale the app instantly just by either increasing the number of dynos or by changing the type of dyno the app runs in.

=== Fix - Buildtime


*Heroku* 



.  Revoke the Key

. In Heroku, click on Account Settings

. Click on API Key

. Find the compromised key and click on Revoke

.  Monitor for abuse
