== Docker Swarm Join Token detected in code


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_89
|Category |Cloud & Infrastructure
|Provider |
|Severity |MEDIUM
|Mapped CSPM/KSPM Rule |None
|===


=== Description

A Docker Swarm Join Token is a secret identifier used when adding new nodes to a Docker Swarm. Docker generates two types of tokens when you initialize a swarm: one for adding manager nodes and another for adding worker nodes. These tokens are used for authentication, ensuring that only authorized nodes can join the swarm. This token needs to be provided to a node for it to join the swarm as a worker or a manager.


=== Fix - Buildtime


*Docker Swarm*

Access the manager node of the Docker Swarm via your terminal or command line.

- To rotate the worker token, use the command: `docker swarm join-token --rotate worker`
- To rotate the manager token, use the command: `docker swarm join-token --rotate manager`

After rotating the tokens, you will get new join commands with the new tokens. Any nodes using the old tokens will still remain in the swarm, but new nodes will need to use the new tokens to join.
