== AWS Access Key detected in code


=== Rule Details

[cols="1,3"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_2
|Category |Cloud & Infrastructure
|Provider |
|Severity |HIGH
|Mapped CSPM/KSPM Rule |None
|===


=== Description 


AWS Access Keys are long-term credentials for an IAM user or the AWS account root user.
You can use access keys to sign programmatic requests to the AWS CLI or AWS API (directly or using the AWS SDK).
Access keys consist of two parts: an access key ID (for example, `AKIAIOSFODNN7EXAMPLE`) and a secret access key (for example, `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`).

=== Fix - Buildtime


*AWS* 



.  Revoke the exposed secret.

. Sign in to the AWS Identity and Access Management (IAM) console as the root user.

. Choose your account name on the navigation bar, and then choose My Security Credentials.

. If you see a warning about accessing the security credentials, choose Continue to security credentials.

. Expand the Access keys (access key ID and secret access key) section.

. Choose Delete next to the access key that you want to delete.
+
In the confirmation box, choose Yes.
+
Expand the "Access keys" section then click on the delete button.

.  Clean the git history.
+
Go under the settings section of your GitHub project and chose the change visibility button at the bottom.

.  Inspect AWS CloudTrail access logs to ensure the key was not utilized during the compromised period.
