== Azure Subscription Key detected in code


=== Rule Details

[cols="1,2"]
|===
|Cortex AppSec Rule ID |APPSEC_SECRET_178
|Category |Cloud & Infrastructure
|Provider |
|Severity |HIGH
|===



=== Impact
The Azure Subscription Key is essential for accessing Azure services and APIs. Exposing this key can allow unauthorized access, leading to resource misuse and potential operational and financial impacts. To secure your Azure integration, manage your Subscription Key carefully and securely and regularly review security practices.
For comprehensive security guidelines and best practices regarding Azure Subscription Key management, refer to the latest documentation and support resources available in the https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits[Azure documentation and support].

=== How to Fix

*Azure*

Regenerate a new key through your Azure account and replace the exposed key with the new key in all relevant applications. This action secures your access to Azure services and also maintains the confidentiality and integrity of your cloud resources.

1. Leverage one of the methods in the https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#manually-rotate-access-keys[documentation] to revoke the access key.
NOTE: Ensure that regenerating your key does not disrupt any applications or services by testing all uses of the key and monitoring for application errors.

2. Generate and save the new key securely and ensure it is not hardcoded in your source code or exposed in public repositories.

3. Update all applications and services that use the Azure Subscription Key with the new key values.

After updating the key, it is recommended to audit all recent uses of the Azure Subscription Key to detect any unauthorized access or unusual activities. This will help you assess the impact of the exposure and enhance your security measures.
