[#permissions]
== Permissions by feature

When you set up Prisma Cloud Compute to secure your cloud workloads, you'll need to ensure you've granted Prisma Cloud the right permissions.
The following tables list the permissions required for each of Compute's protection capabilities.

You can review the permissions needed for each cloud service provider:

* <<#aws,AWS required permissions>>
* <<#azure,Azure required permissions>>
* <<#gcp,GCP required permissions>>

You can review the permissions needed for agentless scanning in each cloud service provider:

* <<#aws-agentless,AWS required permission for agentless scanning>>
* <<#azure-agentless,Azure required permission for agentless scanning>>
* <<#gcp-agentless,GCP required permission for agentless scanning>>

[#aws]
=== AWS

The following table shows the required permissions needed if you are using AWS.
You can also review the <<#aws-agentless,permissions needed for agentless scanning in AWS>>.

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=aws-used-in-docs-for-22.12
|===

[#aws-agentless]
==== AWS Agentless Permissions

The following table shows the required permissions, conditions, and resources for agentless scanning.

Go to the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#ebs-encryption-requirements[AWS documentation for the official list of permissions needed to support EBS encryption].

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=aws-agentless-30-03
|===

[#gcp]
=== GCP

The following table shows the required permissions needed if you are using GCP.
You can also review the <<#gcp-agentless,permissions needed for agentless scanning in GCP>>.

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=gcp-used-in-docs-for-22.12
|===

[#gcp-agentless]
==== GCP Agentless Permissions

The following table shows the required permissions for agentless scanning.

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=gcp-agentless-30-03
|===

[#azure]
=== Azure

The following table shows the required permissions needed if you are using Azure.
You can also review the <<#azure-agentless,permissions needed for agentless scanning in Azure>>.

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=azure-used-in-docs-for-22-12
|===

[#azure-agentless]
==== Azure Agentless Permissions

The following table shows the required permissions for agentless scanning.

[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/compute-edition/assets/compute-feature-wise-permissions?sheet=azure-agentless-30-03
|===

Agentless Workload Scanning permissions listed in the table below are scoped under the resource group `PCC_agentless_resource_group` instead of the Root Management group, for both Azure Tenant and Subscription onboarding. The tenant onboarding Terraform template creates `PCC_agentless_resource_group` under the subscriptions in the tenant, if not already present with the `prisma-agentless-scan tag`, and scopes these permissions under that resource group. 

In addition, you can also add custom tags to the `PCC_agentless_resource_group`, by running the Terraform with `PCC_agentless_resource_group_tags` as shown below:

----
`terraform apply -var="PCC_agentless_resource_group_tags=key1=value1 key2=value2"`
----

[cols="40%a,60%a"]
|===

|*Feature*
|*Permissions*

|Agentless Workload Scanning
|Microsoft.Network/virtualNetworks/write
Microsoft.Network/virtualNetworks/delete
Microsoft.Compute/snapshots/write 
Microsoft.Compute/snapshots/delete
Microsoft.Network/networkInterfaces/write   
Microsoft.Network/networkInterfaces/delete
Microsoft.Network/networkInterfaces/join/action
Microsoft.Network/networkSecurityGroups/write
Microsoft.Network/networkSecurityGroups/delete
Microsoft.Network/networkSecurityGroups/join/action
Microsoft.Network/virtualNetworks/subnets/join/action  
Microsoft.Compute/disks/write
Microsoft.Compute/disks/delete
Microsoft.Compute/virtualMachines/write      
Microsoft.Compute/virtualMachines/delete


|===
