[#permissions]
== Permissions by feature

When you set up Prisma Cloud Compute to secure your cloud workloads, ensure you've granted Prisma Cloud the correct permissions.
The following tables list the permissions required for each of Compute's protection capabilities.

Review the permissions required for each cloud service provider:

* <<#aws,AWS required permissions>>
* <<#azure,Azure required permissions>>
* <<#gcp,GCP required permissions>>

Review the permissions required for agentless scanning in each cloud service provider:

* <<#aws-agentless,AWS required permission for agentless scanning>>
* <<#azure-agentless,Azure required permission for agentless scanning>>
* <<#gcp-agentless,GCP required permission for agentless scanning>>

[#aws]
=== AWS

The following table lists the required permissions needed if you are using AWS.

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=aws-used-in-docs-for-22.12
|===

[#aws-agentless]
==== AWS Agentless Permissions

The following table lists the required permissions, conditions, and resources for agentless scanning.

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=aws-agentless-30-03
|===

Go to the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#ebs-encryption-requirements[AWS documentation for the official list of permissions needed to support EBS encryption].

[#gcp]
=== GCP

//CWP-53019
https://docs.prismacloud.io/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/onboard-accounts/configure-gcp#gcp-encrypted-volumes[Follow these instructions] to scan encrypted volumes with the hub mode.

The following table lists the required permissions needed if you are using GCP.

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=gcp-used-in-docs-for-22.12
|===

//CWP-58230
[NOTE]
=====
The purpose for `Microsoft.Web/sites/config/list/Action` is to list Web App's security sensitive settings, such as publishing credentials, app settings, and connection strings.

The purpose for `Microsoft.ContainerInstance/containerGroups/containers/exec/action` is to allow execution within a specific container, which is essential for compute workload discovery. Get/list permissions only provide external cloud object information and do not access critical node-level details like container runtime or Kubernetes version. This permission is necessary to ensure accurate and comprehensive workload discovery.

=====
[#gcp-agentless]
==== GCP Agentless Permissions

The following table lists the required permissions for agentless scanning.

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=gcp-agentless-30-03
|===

[#azure]
=== Azure

The following table lists the required permissions needed if you are using Azure.

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=azure-used-in-docs-for-22-12
|===

[#azure-agentless]
==== Azure Agentless Permissions

Azure Agentless Scanning permissions listed in the table below are scoped under the resource group `PCCAgentlessScanResourceGroup` instead of the Root Management group, for both Azure Tenant and Subscription onboarding. The tenant onboarding Terraform template creates `PCCAgentlessScanResourceGroup` under the subscriptions in the tenant, if not already present with the `prisma-agentless-scan` tag, and scopes these permissions under that resource group. 

In addition, you can also add custom tags to the `PCCAgentlessScanResourceGroup`, by running the Terraform with `PCC_agentless_resource_group_tags` as shown below:

----
`terraform apply -var="PCC_agentless_resource_group_tags=key1=value1 key2=value2"`
----

[format=csv, options="header"]
|===
https://docs.prismacloud.io/en/compute-edition/assets/compute-feature-wise-permissions?sheet=azure-agentless-30-03
|===