== Application Notion

// alternate title: Prioritizing Security with Applications in CAS ASPM (Cloud Application Security Platform)

*WIP*

In CAS ASPM, 'Applications' group artifacts like code repositories and containers, providing a centralized view of your security posture. Associating code repositories with specific applications allows you to prioritize security issues based on the application's business impact. This empowers security teams to focus on addressing vulnerabilities that pose the greatest risk, minimizing exposure to critical threats while maximizing resource utilization. 

Applications reduce the noise of security alerts by allowing you to focus on issues within a specific context. You can define essential details for each application, such as its business impact. This empowers you to prioritize and remediate security issues related to the most critical aspects of your organization. By tracking metrics like resolved issues for high-impact applications compared to low-impact ones, you can assess the impact of each application on your overall security posture. This streamlined approach maximizes resource use and minimizes exposure to critical threats.


[.tasks]

=== Create an Application

[.procedure]

. Navigate to ....*TBD*

. Provide the following details.
+
* Name and description
* Contact details such as developer and security owners (optional)
* Business impact. Values: High, Low, Medium
* Whether the application is business/customer facing
* Regulation standards such as FEDRAMP, ISO27701, SOC2 (optional)
* Environment such as Production, Staging, Development (optional)

. Select the repositories associated with the application. 
+
NOTE: A code repository can only belong to a single application. If a code repository matches multiple patterns, it will be assigned to the first matching application.

// TODO: Describe the step including integrating below - perhaps as a link - depending on the UI

=== Assign repositories by name pattern

You can assign code repositories to an application based on name patterns. This allows you to define selection criteria for each application using pattern matching (for example `/myOrg/MyProject/*`) alongside other options such as runtime context. This combined approach provides the flexibility required to optimize your application security posture. Name pattern assignment can be applied to existing integrated code repositories or configured to affect future repositories only.

=== Assign repositories to applications by runtime context

You can assign code repositories to applications based on runtime context. This allows you to assign existing repositories, and automatically assign new repositories with an application.

You can leverage runtime context by defining rules based on runtime entities such as Kubernetes containers and their connections to code repositories. This allows automatic assignment based on runtime context, for instance, selecting all repositories 'connected to' a specific Kubernetes container within a particular cluster/namespace.

Runtime context assignment can be applied to existing integrated code repositories or configured to affect future repositories only.

=== Application Context

Application context allows you to focus on code repositories and issues that are part of high business impact on your organization. 

 Perform the following actions by navigating to *Application Security* > *Repositories* page. 

* Group applications 
* Filter integrated code repositories based on the specific application they belong to
* Filter by application impact level

In addition, you can filter the *Project*, *CI/CD Risks*, *SBOM*, and *Technologies* tables based on applications.

=== View and Manage Applications

You can view and manage applications on the *_____* page: Navigate to *describe*. 

* To view all applications:

* To view the application configurations and selected or matched code repositories:

* To edit the application settings, including adding/removing code repositories. 

* To delete an application:
+
After deleting an application, its associated repositories can be reassigned to another application.

==== CAS Application Management via REST API

You can automate application management and run bulk commands through our REST API. This empowers you to efficiently consume and manage applications including.

* *CRUD operations*: Create, edit, and delete CAS applications. Each API endpoint includes required as well as optional parameters for precise control
* *Bulk operations*: Supported for all CRUD operations, including bulk actions for managing multiple CAS applications in a single request
* *Data retrieval*: Retrieve detailed information about a CAS application, including attached repositories

s
