== Application Notion

// alternate title: Prioritizing Security with Applications in CAS ASPM (Cloud Application Security Platform)

*WIP*

In CAS ASPM, 'Applications' group artifacts such as code repositories and containers, providing a centralized view of your security posture. Associating code repositories with specific applications allows you to prioritize security issues based on the application's business impact. This empowers security teams to focus on addressing vulnerabilities that pose the greatest risk, minimizing exposure to critical threats while maximizing resource utilization. 

Applications reduce the noise of security alerts by allowing you to focus on issues within a specific context. You can define essential details for each application, such as its business impact. This empowers you to prioritize and remediate security issues related to the most critical aspects of your organization. By tracking metrics like resolved issues for high-impact applications compared to low-impact ones, you can assess the impact of each application on your overall security posture. This streamlined approach maximizes resource use and minimizes exposure to critical threats.


[.tasks]

=== Create an Application

[.procedure]

. Navigate to *Application Security* > *Applications* in the left navbar.
+
//image::application-security/[]
. Select *Create Application*. 
+
The Add Details step of the wizard is displayed.
//image::application-security/[]

. Fill in the provided fields:
+
* *Name*: An alias of your choice
* *Description*
* *Business Criticality*. Values include ..... //TODO
* *Point of Contact* (Optional): Details such as developer and security owners // //TODO
//* Business impact. Values: High, Low, Medium
//* Whether the application is business/customer facing
//* Regulation standards such as FEDRAMP, ISO27701, SOC2 (optional)
* *Environment* (Optional). Values include such as Production, Staging, Development 

. Select *Next*.
+
The *Select Repositories* step of the wizard is displayed. You can choose to manually select repositories associated with the application, or automatically select them by name pattern. 
+
image::application-security/[]

. 

.. Manually select repositories from the Manual selection menu.
.. Automatically select repositories:
+
* Provide a name pattern. For more on name patterns, refer to <<Assign Repositories by Name Pattern>> below.

* Enable future repositories (Optional).
+
NOTE: A code repository can only belong to a single application. If a code repository matches multiple patterns, it will be assigned to the first matching application.

.. Select *Next*.

. Review the Application details in the *Status* step of the wizard > *Save*.


//TODO define name pattern
//image::application-security/[]

NOTE: A code repository can only belong to a single application. If a code repository matches multiple patterns, it will be assigned to the first matching application.

// TODO: Describe the step including integrating below - perhaps as a link - depending on the UI

[#assign-repo-name-pattern]
=== Assign repositories by name pattern

You can assign code repositories to an application based on name patterns. This allows you to define selection criteria for each application using pattern matching (for example `/myOrg/MyProject/*`) alongside other options such as runtime context. This combined approach provides the flexibility required to optimize your application security posture. Name pattern assignment can be applied to existing integrated code repositories or configured to affect future repositories only.

=== Assign repositories to applications by runtime context

You can assign code repositories to applications based on runtime context. This allows you to assign existing repositories, and automatically assign new repositories with an application.

You can leverage runtime context by defining rules based on runtime entities such as Kubernetes containers and their connections to code repositories. This allows automatic assignment based on runtime context, for instance, selecting all repositories 'connected to' a specific Kubernetes container within a particular cluster/namespace.

Runtime context assignment can be applied to existing integrated code repositories or configured to affect future repositories only.

=== Application Context

Application context allows you to focus on code repositories and issues that are part of high business impact on your organization. 

Perform the following actions by navigating to *Application Security* > *Repositories* page. 

* Group applications 
* Filter integrated code repositories based on the specific application they belong to
* Filter by application impact level

In addition, you can filter the *Project*, *CI/CD Risks*, *SBOM*, and *Technologies* tables based on applications context.

=== View Applications

You can view and manage Applications on the dedicated *Application* page, as well as see the list of Applications associated to a repository in the *Repositories* page.

=== View and Manage Applications on the Applications page

In *Application Security*, select *Applications* in the left navbar.

// image:application-security[]

The Applications page displays an inventory of applications in your organization, including the following details:

* *Business Criticality*: The importance of the application to the organization. Values include “High”, “Medium” and “Low” 
* *Owners*: The “Dev owner”.  View this value in the Status step of the wizard when creating the application
* *Regulation Standards*: Regulation standards that the application complies with, such as FEDRAMP, ISO27701, SOC2
* *Environment*: The environment that the application is found in, such as production, development and so on
* *Repositories*: the repositories associated with the application
* *Actions*: Select the menu under *Action* to <<,Edit Applications>> or <<,Delete Applications>>  

//add info about actions

Selecting an application in the table opens a sidecar with additional information about the application.

// image:application-security[]


The *Overview* tab includes details such as the description of the application, business criticality and more. The *Repositories* tab includes. 
// Missing details


//* To view all applications:

//* To view the application configurations and selected or matched code repositories:

==== Edit Applications

To edit an application:
.  On the *Application* page, select the menu under the *Actions* column > *Edit*.
+
You are redirected to the *Add Details* step of the Application Creation wizard.

. Edit the Application details > complete the steps of the wizard - see <<Create an Application>> above.

==== Delete Applications

To delete an application:
. On the *Applications* page, select the menu under the *Actions* column > *Delete*.
. Confirm the deletion when prompted.

NOTE: After deleting an application, its associated repositories can be reassigned to another application.

=== View Applications on Repositories Page

The Repositories page provides two distinct viewing modes for entities. The default view groups and presents entities based on their associated repository, offering a well-organized layout.  Alternatively, users can switch the view to display applications linked to each repository. This mode facilitates deeper exploration of assets connected to those applications.

==== View Applications by Repositories

. In *Application Security*, select *Repositories* in the left navbar.
. View the Applications associated to a repository under the *Application* column.
+
image::application-security/[]

//TODO check whether there is a redirect if clicking on an app

You can filter by *Application* in order to prioritize repositories or understand which are at risk and require attention and so on.

==== Application View

To view a list of all Applications  and their associate assets, select Applications from the *Group by* filter.

image::application-security/[]

==== Manage Applications via REST API

You can automate application management and run bulk commands through through the Prisma Cloud REST API. This empowers you to efficiently consume and manage applications including:

* *CRUD operations*: Create, edit, and delete CAS applications. Each API endpoint includes required as well as optional parameters for precise control
* *Bulk operations*: Supported for all CRUD operations, including bulk actions for managing multiple CAS applications in a single request
* *Data retrieval*: Retrieve detailed information about a CAS application, including attached repositories


