[#idc682745c-c041-4724-8af4-583c45f2bbc2]
== Prisma Cloud統合
Prisma® Cloudがサポートしているサードパーティ製システムとの、統合のタイプについて学びます。

Prisma® Cloudには、既存のセキュリティワークフローおよびすでに使用しているテクノロジーと統合できるように、さまざまな統合オプションが用意されています。Amazon GuardDuty、AWS Inspector、Qualys、およびTenable統合は、インバウンドまたはプルベースの統合で、Prisma Cloudが定期的にデータのポーリングを行い、そのデータを外部統合システムから取得します。その他の統合はすべてアウトバウンドまたはプッシュベースの統合で、Prisma Cloudがアラートやエラーに関するデータを外部統合システムに送信します。


[NOTE]
====
中国大陸リージョンのAlibaba Cloudは、下記のすべての統合をサポートしていません。サポートされている*統合*は、Amazon SQS、電子メール、Splunk、およびWebhooksです。
====
* *Amazon GuardDuty*—Amazon GuardDutyは、悪意のある行動や不正行為を継続的に監視して、AWSアカウントやワークロードを保護する脅威検出サービスです。Prisma CloudをAmazon GuardDutyと統合して脆弱性データを取り込むことで、クラウド内のリスクに関する情報や状況を把握することができます。

* *AWS Inspector*—AWS Inspectorは、暴露、脆弱性、ベストプラクティスからの差異などについて、アプリケーションを評価します。また、重大度レベルで優先分けされた、セキュリティ検出事項の詳細のリストも生成します。Prisma CloudをAWSと統合して脆弱性データとセキュリティ上のベストプラクティス間の差異を取り込むことで、クラウド内のリスクに関する情報や状況を把握することができます。

* *Amazon S3*—Amazon Simple Storage Service（Amazon S3）は、ウェブスケールのコンピューティングを容易にするように設計されています。Amazon S3を使用すると、拡張性、信頼性、高速、安価なデータストレージを使用して、あらゆる量のデータを保存および取得できます。Prisma CloudはAmazon S3バケット/フォルダにアラートを送信できます。

* *AWS Security Hub*—AWS Security Hubは、Amazonコンソールから直接、クラウドアセットのセキュリティ体制を表示、監視できる集中型コンソールです。Prisma CloudアプリケーションがAWSクラウド上のアセットを監視し、リソースの設定誤り、コンプライアンス違反、ネットワークのセキュリティリスク、不審なユーザー行動に対するアラートを送信することで、Prisma Cloudコンソールから各AWSアカウントのすべてのクラウドアセットを総合的に把握することができます。

* *Amazon SQS*—Amazon Simple Queue Service（SQS）は、ソフトウェアコンポーネント間でやり取りされる任意の量のメッセージを、送信、受信、保管するために役立ちます。メッセージを失ったり、他のサービスを常に利用可能な状態に保っておいたりする必要はありません。Prisma Cloudは Amazon SQSにアラートを送信でき、カスタムワークフローを有効にするように AWS CloudFormationサービスを設定できます。

* *Azure Service Busキュー*—Azure Service Bus は、アプリケーション間でメッセージとしてデータを転送するように設計された、管理されたメッセージングインフラストラクチャです。Prisma CloudとAzure Service Busキューの統合により、キューにアラートを送信し、カスタムワークフローを設定してアラートのペイロードを処理できます。

* *Cortex XSOAR*—Cortex XSOAR（従来のDemisto）は、SOAR（Security Orchestration, Automation and Response）プラットフォームで、インシデント管理ワークフローを効率化します。Prisma CloudとCortex XSOARを統合することで、Prisma Cloudアラートおよびインシデントのライフサイクルの管理プロセスを、プレイブックによる対応アクションを利用して自動化することができます。

* *Email*—Prisma Cloudがアラートをメールアカウントに送信するように設定します。

* *Google SCC*—Google Cloud Security Command Center (SCC) は、Google Cloud Platform向けのセキュリティ/データリスクデータベースです。Google Cloud SCCは、アセットのインベントリ、検出、検索、管理機能を提供することで、セキュリティおよびデータ攻撃可能面を理解することができますアセット。Prisma CloudをGoogle Cloud SCCと統合して、アラートをGoogle Cloud SCCコンソールに送信することで、クラウドアセットのセキュリティおよびコンプライアンスリスクを一元的に把握することができます。

* *Jira*—Jiraは、問題追跡、チケット発行、プロジェクト管理ツールです。Prisma CloudとJiraを統合して、Prisma Cloudアラートの通知をJiraアカウントに送信できます。

* *Microsoft Teams*—Microsoft TeamsはOffice 365スイートの一部であるクラウドベースのチームコラボレーションソフトウェアで、チャット、ビデオ会議、ファイル保管、およびアプリケーションの統合に使用されます。Prisma CloudをMicrosoft Teamsと統合することで、アセットを監視し、リソースの設定誤り、コンプライアンス違反、ネットワークセキュリティ上のリスク、および不審なユーザー行動などの発生時にアラートを送信できます。

* *PagerDuty*—PagerDutyは、アラート、オンコール スケジュール、エスカレーションポリシー、インシデント追跡により、アプリ、サーバー、Webサイト、データベースなどのアップタイムを向上することができます。PagerDuty統合により、Prisma Cloudアラート情報をPagerDutyサービスに送信することができます。インシデント応答チームは、セキュリティインシデントの調査と修正を行えます。

//Removed QRadar support based on issues reported from the field and CS teams. Confirmed with Bharat. *QRadar*—IBM QRadar is an enterprise security information and event management product. Integrate Prisma Cloud with QRadar so that you can view Prisma Cloud alerts on the QRadar console to proactively detect threats and continuously improve detection.

* *Qualys*—Qualysは、脆弱性の管理を専門とするセキュリティソフトウェアで、ホストの潜在的な脆弱性をスキャンします。Prisma CloudとQualysプラットフォームを統合して、脆弱性データを取り込むことで、クラウド内のリスクに関する詳細を理解することができます。

* *ServiceNow*—ServiceNowは、インシデント、アセット、チケット管理ツールです。Prisma CloudとServiceNowを統合して、Prisma Cloudアラートの通知をServicenowチケットとして送信できます。

* *Slack*—Slackはオンラインのインスタントメッセージング/コラボレーションシステムで、すべての通知を集中管理することができます。Slackチャネル経由でPrisma Cloudアラートの通知を送信するように、Prisma Cloudを設定することができます。

* *Splunk*—Splunkは、Webサイト、アプリケーション、センサー、およびデバイスから収集された、マシンが生成したデータの検索、分析、および視覚化を行うための、ソフトウェアプラットフォームです。Prisma CloudをクラウドベースのSplunk展開環境と統合して、Splunkイベントコレクタ経由でPrisma Cloudアラートを参照することができます。Prisma CloudはAWS SQS統合を介して、オンプレミスSplunkインスタンスと統合することができます。

* *Tenable*—Tenable.ioは、クラウドが提供する脆弱性管理ソリューションで、動的なアセットと脆弱性に関する視認性と洞察力を提供します。Prisma CloudをTenableと統合して脆弱性データを取り込むことで、クラウド内のリスクに関する情報や状況を把握することができます。

* *Webhooks*—Webhooks統合により、Prisma Cloudをネイティブにサポートしていないサードパーティの統合に、JSON形式で情報を渡すことができます。Webhook統合により、Prisma CloudがWebhook URLにアラートをHTTP POSTリクエストとして送信するように設定し、Webhook URLに登録したサービスやアプリケーションにPrisma Cloudが検出した問題に対するアラート通知を即座に送信することができます。

アウトバウンド統合の場合：

* 関連する統合の*Get Status（ステータスを取得）*アイコンをクリックすると、*Settings（設定） > Integrations（統合）*でオンデマンドでステータスの更新を確認できます。ステータスチェックは、統合がアクセシビリティまたは認証情報の検証チェックに失敗した場合は赤色で、統合が機能していてすべてのテンプレートが有効である場合は緑色で表示されます。ステータスチェックをサポートしていないインテグレーションのリストを確認するには、xref:integrations-feature-support.adoc[Prisma Cloud インテグレーション - サポートされている機能]を参照してください。ステータスエラーは、潜在的な問題を見つけて修正するのに役立ちます。
+
[NOTE]
====
* 通知の処理で例外または失敗が発生すると、アラームが生成されます。Alarms（アラーム）を有効にしていれば、Alarm Center（アラームセンター）に表示できます。

* Prisma Cloudが外部ツールと統合された場合、外部ツールからの応答が遅れることがあります。この場合、約10秒間のタイムアウトが発生するため、期間中に送信失敗した際には、Prisma Cloudが通知再送を実行します。そのため、遅れて通知を受け取る場合があります。このような遅延が発生した場合は、ベストプラクティスとして、お使いのネットワークインフラを見直し、問題を調査し、よりスムーズな動作を確認してください。
====


* xref:../../alerts/send-prisma-cloud-alert-notifications-to-third-party-tools.adoc[Prisma Cloudアラート通知をサードパーティツール]に送信する場合、アラートを生成したリソースのcloudTypeフィールドのクラウドサービスプロバイダーの値は、awsやalibaba-cloudなどの小文字で表示されます。




